/* IL GUERRIERO — data.js (pooled from 3 books) */
(function(){
"use strict";
window.GAME_DATA = {
  id: "guerr",
  modes: ["ring","trepunti","quiz","memoria"],
  rings: [
    {key:"morte",color:"#1a1326",ring:"#3a2f52",label:{it:"Immortalamento",en:"Immortalamento"}},
    {key:"cronos",color:"#10212a",ring:"#2f5d6b",label:{it:"Cronos",en:"Kronos"}},
    {key:"ring",color:"#2a1410",ring:"#7c3a2a",label:{it:"Il Ring",en:"The Ring"}},
    {key:"guerriero",color:"#3a2c10",ring:"#c9973a",label:{it:"Il Guerriero",en:"The Warrior"}}
  ],
  modeDefs: {
    ring: { type:"classify", roman:"I", glyph:"◐", optionKeys:[0,1], count:10,
      items: [
        {item:{it:"Desiderare ardentemente la vittoria per dimostrare di essere qualcuno",en:"Ardently desiring victory to prove one is someone"},belongs:0,note:{it:"Il desiderio di vincere è sinonimo di paura: non sei sicuro di te.",en:"The desire to win is synonymous with fear: you're not sure of yourself."}},
        {item:{it:"Fluire nel Qui-e-Ora senza aspettative sul risultato",en:"Flowing in the Here-and-Now without expectations"},belongs:1,note:{it:"Quando la vittoria perde importanza, la prestazione perfetta la fa verificare.",en:"When victory loses importance, perfect performance causes it to occur."}},
        {item:{it:"Sali sul ring pensando 'Devo distruggere il mio avversario'",en:"You step into the ring thinking 'I must destroy my opponent'"},belongs:0,note:{it:"Qualsiasi azione motivata dalla furia è un'azione votata al fallimento (Gengis Khan).",en:"Any action motivated by fury is an action doomed to failure (Genghis Khan)."}},
        {item:{it:"Corpo in 'rilassatezza attiva', come un felino prima del salto",en:"Body in 'active relaxation', like a cat before the leap"},belongs:1,note:{it:"Tensione fisica pura, non sporcata da tensione mentale ed emotiva.",en:"Pure physical tension, not dirtied by mental and emotional tension."}},
        {item:{it:"Colpire con rabbia e aggressività per schiacciare l'avversario",en:"Striking with rage and aggression to crush the opponent"},belongs:0,note:{it:"La rabbia è un combustibile che lascia intatta l'insoddisfazione.",en:"Rage is a fuel that when exhausted leaves dissatisfaction intact."}},
        {item:{it:"Combattere con la precisione di una coreografia di danza classica",en:"Fighting with the precision of a classical ballet choreography"},belongs:1,note:{it:"Il colpo si esegue come un brano musicale al violino.",en:"The blow is executed like a musical piece on the violin."}},
        {item:{it:"I muscoli contratti dalla tensione emotiva prima del match",en:"Muscles clenched with emotional tension before the match"},belongs:0,note:{it:"Le emozioni creano attrito psicologico che impatta l'efficienza.",en:"Emotions create psychological friction that impacts efficiency."}},
        {item:{it:"Il colpo parte da solo, come se la Vita lo sferrasse attraverso di te",en:"The blow goes out on its own, as if Life struck it through you"},belongs:1,note:{it:"Non ostacolare un colpo che sta già andando verso il suo destino.",en:"Don't hinder a blow already heading toward its destiny."}},
        {item:{it:"La prestazione come danza dove i due avversari sono complici",en:"Performance as a dance where opponents are accomplices"},belongs:1,note:{it:"I due avversari si sostengono a vicenda per ottenere il massimo.",en:"The two opponents support each other to achieve their best."}},
        {item:{it:"Anticipare con la mente ciò che sta per succedere, provando paura",en:"Mentally anticipating what's about to happen, feeling fear"},belongs:0,note:{it:"La paura è basata su un'immagine mentale, un'anticipazione… un'illusione.",en:"Fear is based on a mental image, an anticipation… an illusion."}},
        {item:{it:"Sperare che l'avversario perda per poter vincere tu",en:"Hoping the opponent loses so that you can win"},belongs:0,note:{it:"Io valgo se sono stato bravo, non perché un altro ha perso.",en:"I am worth something if I performed well, not because someone else lost."}},
        {item:{it:"Fra l'attacco dell'avversario e la tua reazione non passa alcun pensiero",en:"No thought comes between the opponent's attack and your reaction"},belongs:1,note:{it:"La mente non va fermata in alcun luogo e su alcun oggetto.",en:"The mind must not stop on any place or any object."}},
        {item:{it:"Mettere in gioco la propria serenità sul risultato dell'incontro",en:"Staking one's serenity on the outcome of the bout"},belongs:0,note:{it:"Un guerriero intelligente non porta la sua serenità sul campo di battaglia come posta in gioco: è una posta tremendamente alta.",en:"An intelligent warrior does not bring his serenity to the battlefield as a stake: it is a terribly high one."}},
        {item:{it:"Cercare il record personale più che la sconfitta dell'avversario",en:"Seeking a personal best rather than the opponent's defeat"},belongs:1,note:{it:"Il miglioramento della prestazione è l'autentica vittoria.",en:"Improving one's performance is the true victory."}},
        {item:{it:"Durante la Ram Muay pensare già all'incontro che sta per cominciare",en:"During the Ram Muay already thinking about the bout about to begin"},belongs:0,note:{it:"Avrà difficoltà a vincere, perché non ha ancora vinto se stesso.",en:"He will struggle to win, because he has not yet conquered himself."}},
        {item:{it:"Assaporare ogni singolo giorno di allenamento, senza vivere in funzione della vittoria futura",en:"Savouring every single day of training, without living for a future victory"},belongs:1,note:{it:"Vivere in funzione del giorno in cui vincerete significa non vivere pienamente né il presente né il futuro.",en:"Living for the day you will win means living fully neither the present nor the future."}}
      ]
    },
    trepunti: { type:"scenario", roman:"II", glyph:"△", optionKeys:[0,1,2], count:10,
      items: [
        {sit:{it:"Il capo ti umilia al lavoro. Ti chiudi in bagno e osservi la rabbia che sale.",en:"Your boss humiliates you. You lock in the bathroom and observe the rage rising."},correct:0,note:{it:"Punto primo — Auto-osservazione: osserva cosa accade dentro di te. È già guarigione.",en:"Point one — Self-observation: observe what's happening inside you. It's already healing."}},
        {sit:{it:"Ti lamenti della società per la tua condizione economica.",en:"You blame society for your economic condition."},correct:1,note:{it:"Punto secondo — Non incolpare: l'origine dei tuoi mali si trova dentro di te.",en:"Point two — Don't blame: the origin of all your ills lies within you."}},
        {sit:{it:"Metti le mani sul plesso solare e respiri mandando amore al dolore.",en:"You place hands on your solar plexus and breathe, sending love to the pain."},correct:2,note:{it:"Punto terzo — Ama e perdona ciò che stai provando dentro di te in questo momento.",en:"Point three — Love and forgive what you're feeling within you right now."}},
        {sit:{it:"Qualcuno ti taglia la strada. Noti il fastidio nel corpo senza giudicarlo.",en:"Someone cuts you off. You notice the annoyance in your body without judging."},correct:0,note:{it:"L'Osservatore non giudica, non critica, non ha fretta di cambiare… al limite sorride.",en:"The Observer doesn't judge, doesn't criticise, isn't in a hurry to change… at most smiles."}},
        {sit:{it:"Pensi: 'Se non ci fosse quel collega, non avrei problemi.'",en:"You think: 'If not for that colleague, I'd have no problems.'"},correct:1,note:{it:"Non soffri perché qualcuno ti ha fatto qualcosa, ma qualcuno lo ha fatto perché hai scelto la sofferenza.",en:"You don't suffer because someone did something, but someone did it because you chose suffering."}},
        {sit:{it:"Senti il dolore della solitudine e scegli di amarlo e perdonarlo.",en:"You feel the pain of loneliness and choose to love and forgive it."},correct:2,note:{it:"Ama e perdona la tua sofferenza, il tuo dolore, la tua ferita sanguinante.",en:"Love and forgive your suffering, your pain, your bleeding wound."}},
        {sit:{it:"La signora al telefono sul treno ti irrita. La tua irritazione ha creato la scena.",en:"The lady on the phone irritates you. Your irritation created the scene."},correct:1,note:{it:"Era la mia irritazione a creare e alimentare quell'episodio… e non viceversa.",en:"It was my irritation creating and feeding that episode… not the reverse."}},
        {sit:{it:"Espiri immaginando di mandare amore alle parti ferite del tuo essere.",en:"You exhale imagining sending love to the wounded parts of your being."},correct:2,note:{it:"Inspirando: più presente. Espirando: mando amore al mio dolore.",en:"Inhaling: more present. Exhaling: sending love to my pain."}},
        {sit:{it:"Senti il senso di ingiustizia e osservi la rabbia con distacco.",en:"You feel injustice and observe the rage with detachment."},correct:0,note:{it:"Trovavo la forza per osservare con neutralità la mia rabbia, la voglia di uccidere, di scappare, il senso di ingiustizia, il senso di costrizione… Li vedevo salire dal plesso solare.",en:"I found the strength to observe with neutrality my rage, the urge to kill, to run away, the sense of injustice, the sense of constriction… I saw them rising from the solar plexus."}},
        {sit:{it:"Vieni accusato di un errore. Prima di rispondere ti fermi e guardi che cosa accade dentro di te.",en:"You are accused of a mistake. Before answering you stop and look at what is happening inside you."},correct:0,note:{it:"L'autosservazione interrompe per un attimo l'azione ipnotica del mondo.",en:"Self-observation interrupts for a moment the hypnotic action of the world."}},
        {sit:{it:"Al lavoro si ripete da anni la stessa situazione con colleghi sempre diversi. Smetti di dare la colpa a loro.",en:"The same situation has repeated itself at work for years with ever-different colleagues. You stop blaming them."},correct:1,note:{it:"Il tuo essere crea il mondo, non viceversa.",en:"Your being creates the world, not the other way round."}},
        {sit:{it:"Pensi che il mondo ce l'abbia con te; poi ricordi che il mondo non può decidere nulla.",en:"You think the world is against you; then you remember the world cannot decide anything."},correct:1,note:{it:"«Il mondo non ha volontà propria. Non può decidere nulla.» (Draco Daatson)",en:"'The world has no will of its own. It cannot decide anything.' (Draco Daatson)"}},
        {sit:{it:"Qualcuno ti ha ferito. Invece di cercare di perdonare lui, rivolgi amore e perdono a ciò che provi dentro di te.",en:"Someone has hurt you. Instead of trying to forgive him, you turn love and forgiveness towards what you feel inside."},correct:2,note:{it:"Non c'è niente e nessuno da perdonare all'esterno di te.",en:"There is nothing and no one to forgive outside you."}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"Il 'colpo perfetto' è sferrato da…",en:"The 'perfect blow' is struck by…"},options:{it:["La Vita stessa attraverso il corpo dell'atleta","La pura forza muscolare","La rabbia","La tecnica meccanica"],en:["Life itself through the athlete's body","Pure muscular force","Rage","Mechanical technique"]},correct:0,note:{it:"La Vita sferra solo colpi perfetti. L'atleta deve evitare d'intervenire.",en:"Life only strikes perfect blows. The athlete must avoid intervening."}},
        {q:{it:"Lo stato ideale dell'atleta è…",en:"The athlete's ideal state is…"},options:{it:["Corpo rilassato, emozioni assenti, mente assente","Corpo teso, mente attiva","Rabbia controllata","Totale aggressività"],en:["Body relaxed, emotions absent, mind absent","Body tense, mind active","Controlled rage","Total aggression"]},correct:0,note:{it:"Rilassatezza attiva: tensione fisica pura, non sporcata da tensione mentale.",en:"Active relaxation: pure physical tension, not dirtied by mental tension."}},
        {q:{it:"I maestri prevedevano il vincitore osservando…",en:"Masters predicted the winner by observing…"},options:{it:["Come i fighter eseguivano la Ram Muay","Il peso dei combattenti","Il numero di allenamenti","L'età"],en:["How fighters performed the Ram Muay","Fighters' weight","Number of training sessions","Age"]},correct:0,note:{it:"Chi è concentrato nella danza — nel Qui-e-Ora — ha già vinto.",en:"He who is focused in the dance — in the Here-and-Now — has already won."}},
        {q:{it:"Il monaco-guerriero moderno deve…",en:"The modern monk-warrior must…"},options:{it:["Costituire una 'resistenza interiore' basata su solidi principi","Isolarsi dalla società","Combattere ogni giorno","Seguire solo tecniche orientali"],en:["Constitute an 'inner resistance' based on solid principles","Isolate from society","Fight every day","Follow only Eastern techniques"]},correct:0,note:{it:"Non piegarsi all'assenza di spirito dell'epoca moderna.",en:"Not bending to the spiritlessness of the modern age."}},
        {q:{it:"Draco Daatson ha fondato…",en:"Draco Daatson founded…"},options:{it:["La setta dei Senza Sonno","Un monastero","Una scuola di yoga","Un partito"],en:["The Sleepless sect","A monastery","A yoga school","A party"]},correct:0,note:{it:"Un manipolo di arditi disposti a tutto pur di svegliarsi, riunito secondo la tradizione nel IV secolo d.C.",en:"A band of daring people ready for anything in order to wake up, gathered according to tradition in the 4th century AD."}},
        {q:{it:"L''immortalamento' del guerriero avviene attraverso…",en:"The warrior's 'immortalamento' happens through…"},options:{it:["L'accettazione totale della morte","Una pozione magica","Evitare ogni pericolo","La tecnologia"],en:["Total acceptance of death","A magic potion","Avoiding every danger","Technology"]},correct:0,note:{it:"Chi trova il coraggio di affrontare la morte ha già fabbricato un'anima immortale.",en:"He who finds courage to face death has already fabricated an immortal soul."}},
        {q:{it:"Fare pace con la propria morte serve a…",en:"Making peace with one's death serves to…"},options:{it:["Percepire l'immortalità e raggiungere la serenità interiore","Diventare tristi","Rinunciare alla vita","Niente"],en:["Perceive immortality and reach inner serenity","Become sad","Renounce life","Nothing"]},correct:0,note:{it:"Il Fuoco interiore emerge solo quando la mente si sente vicina alla sua fine.",en:"The inner Fire emerges only when the mind feels close to its end."}},
        {q:{it:"Per la rinascita italica basterebbero…",en:"For Italian rebirth it would be enough to have…"},options:{it:["Dieci monaci-guerrieri centrati e integri","Un milione di manifestanti","Un nuovo governo","Dieci miliardi"],en:["Ten centred, whole monk-warriors","A million demonstrators","A new government","Ten billion"]},correct:0,note:{it:"Dieci persone di tal fatta sarebbero sufficienti per una rinascita spirituale.",en:"Ten such people would suffice for a spiritual rebirth."}},
        {q:{it:"L'addestramento del Guerriero è su…",en:"The Warrior's training is on…"},options:{it:["Tre livelli: fisico, emotivo e mentale","Solo spirituale","Solo arti marziali","Solo studio"],en:["Three levels: physical, emotional and mental","Only spiritual","Only martial arts","Only study"]},correct:0,note:{it:"Fisico: vita sana. Emotivo: non esprimere all'esterno le emozioni negative. Mentale: eliminare lamentela, critica e giudizio.",en:"Physical: healthy living. Emotional: not expressing negative emotions outwardly. Mental: eliminating complaint, criticism and judgment."}},
        {q:{it:"Per sconfiggere Cronos, il dio del tempo, basta…",en:"To defeat Kronos, the god of time, it is enough to…"},options:{it:["Vivere nell'istante presente","Imparare una tecnica di meditazione avanzata","Pianificare con cura il futuro","Rielaborare il passato"],en:["Live in the present instant","Learn an advanced meditation technique","Plan the future carefully","Work through the past"]},correct:0,note:{it:"Non esiste una tecnica elaborata per riuscirci.",en:"There is no elaborate technique for doing it."}},
        {q:{it:"Per Draco Daatson il desiderio di vincere è sinonimo di…",en:"For Draco Daatson the desire to win is synonymous with…"},options:{it:["Paura","Coraggio","Talento","Forza di volontà"],en:["Fear","Courage","Talent","Willpower"]},correct:0,note:{it:"Chi ha paura di perdere teme che la sconfitta metta in crisi la sua fragile identità.",en:"Whoever is afraid of losing fears that defeat will shake his fragile identity."}},
        {q:{it:"Che rapporto c'è fra serenità e vittoria?",en:"What is the relationship between serenity and victory?"},options:{it:["La serenità è la causa della vittoria","La vittoria porta la serenità","Nessun rapporto","Per vincere serve la rabbia"],en:["Serenity is the cause of victory","Victory brings serenity","None at all","To win you need rage"]},correct:0,note:{it:"«Non sono sereno se vincerò, ma vincerò se saprò restare sereno.»",en:"'I am not serene if I win, but I will win if I can remain serene.'"}},
        {q:{it:"Le lettere di FUOCO stanno per i valori…",en:"The letters of FUOCO (Fire) stand for the values…"},options:{it:["Fedeltà, Umiltà, Onestà, Coraggio, Onore","Forza, Unità, Ordine, Costanza, Obbedienza","Fede, Unione, Orgoglio, Calma, Ordine","Fermezza, Umiltà, Obbedienza, Carità, Onore"],en:["Fidelity, Humility, Honesty, Courage, Honour","Strength, Unity, Order, Constancy, Obedience","Faith, Union, Pride, Calm, Order","Firmness, Humility, Obedience, Charity, Honour"]},correct:0,note:{it:"Il Coraggio indica letteralmente l'abilità di agire con il Cuore.",en:"Courage literally means the ability to act from the Heart."}},
        {q:{it:"Un allenatore che non è anche maestro spirituale forma…",en:"A coach who is not also a spiritual master forms…"},options:{it:["Soldati anziché monaci-guerrieri","Campioni del mondo","Allenatori migliori di lui","Atleti più veloci"],en:["Soldiers instead of monk-warriors","World champions","Coaches better than himself","Faster athletes"]},correct:0,note:{it:"Il soldato si limita a eseguire ordini; il guerriero si disciplina per imparare a seguire il suo Cuore.",en:"The soldier merely follows orders; the warrior disciplines himself to learn to follow his Heart."}},
        {q:{it:"Come chiamano gli orientali l'«azione senza azione» del gesto perfetto?",en:"What do Easterners call the 'action without action' of the perfect gesture?"},options:{it:["Wu wei","Kata","Dojo","Bushido"],en:["Wu wei","Kata","Dojo","Bushido"]},correct:0,note:{it:"È la «trance agonistica», l'azione priva d'intenzionalità.",en:"It is the 'competitive trance', action without intention."}},
        {q:{it:"Approfittare dell'infortunio dell'avversario per vincere…",en:"Taking advantage of the opponent's injury to win…"},options:{it:["Non aggiunge nulla al nostro valore","È una strategia intelligente","Dimostra la nostra superiorità","Fa parte del codice del guerriero"],en:["Adds nothing to our worth","Is a smart strategy","Proves our superiority","Is part of the warrior's code"]},correct:0,note:{it:"La debolezza dell'avversario non ci rende più forti. I nostri avversari non sono nostri nemici.",en:"The opponent's weakness does not make us stronger. Our opponents are not our enemies."}},
        {q:{it:"Perché l'autentico guerriero non desidera vincere?",en:"Why does the authentic warrior not desire to win?"},options:{it:["Non ne ha più bisogno: non deve dimostrare di essere qualcuno","Ha paura di perdere","Preferisce non combattere","Pensa di non esserne capace"],en:["He no longer needs to: he has nothing to prove","He is afraid of losing","He prefers not to fight","He thinks he is not capable of it"]},correct:0,note:{it:"La vittoria dell'atleta ideale arriva come eventuale effetto collaterale d'una prestazione perfetta.",en:"The ideal athlete's victory comes as a possible side effect of a perfect performance."}},
        {q:{it:"Per Draco Daatson il guerriero che per un solo attimo spera in un aiuto esterno…",en:"For Draco Daatson the warrior who for a single moment hopes for outside help…"},options:{it:["È già vinto","Dimostra saggezza","Merita di essere aiutato","Sarà salvato dai compagni"],en:["Is already defeated","Shows wisdom","Deserves to be helped","Will be saved by his companions"]},correct:0,note:{it:"I Senza Sonno erano incapaci di provare paura, perché coscienti di essere l'origine della propria realtà.",en:"The Sleepless were unable to feel fear, being aware that they were the origin of their own reality."}},
        {q:{it:"I monaci Senza Sonno…",en:"The Sleepless monks…"},options:{it:["Dormivano tre-quattro ore per notte e facevano un solo pasto al giorno","Non dormivano mai","Vivevano isolati sui monti","Si nutrivano solo di erbe"],en:["Slept three or four hours a night and ate one meal a day","Never slept","Lived in isolation in the mountains","Ate only herbs"]},correct:0,note:{it:"La disciplina fisica permetteva loro di accedere alla disciplina emotiva e quindi a quella mentale.",en:"Physical discipline gave them access to emotional discipline and then to mental discipline."}},
        {q:{it:"Per Draco Daatson la libertà viene da…",en:"For Draco Daatson freedom comes from…"},options:{it:["La disciplina","Fare ciò che si vuole quando si vuole","Rifiutare ogni regola","La fortuna"],en:["Discipline","Doing whatever you want whenever you want","Rejecting every rule","Luck"]},correct:0,note:{it:"«In verità solo la disciplina dona la libertà.» L'autentica libertà si raggiunge disciplinando il corpo, le emozioni e la mente.",en:"'In truth only discipline gives freedom.' True freedom is reached by disciplining body, emotions and mind."}},
        {q:{it:"La parola odierna più vicina al Fuoco Fisso è…",en:"The modern word closest to the Fixed Fire is…"},options:{it:["Fede","Rabbia","Passione","Ambizione"],en:["Faith","Rage","Passion","Ambition"]},correct:0,note:{it:"È il sentire di essere accompagnati dalla Vita in ogni istante. Si chiama Fisso perché a un certo punto diviene stabile.",en:"It is the feeling of being accompanied by Life at every instant. It is called Fixed because at a certain point it becomes stable."}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✶",
      items: [
        {a:{it:"Il colpo perfetto",en:"The perfect blow"},b:{it:"Non ostacolare\nil destino",en:"Don't hinder\ndestiny"}},
        {a:{it:"Rilassatezza\nattiva",en:"Active\nrelaxation"},b:{it:"Corpo pronto\nmente assente",en:"Body ready\nmind absent"}},
        {a:{it:"I Tre Punti",en:"The Three Points"},b:{it:"Osserva, non incolpare\nama e perdona",en:"Observe, don't blame\nlove and forgive"}},
        {a:{it:"I Senza Sonno",en:"The Sleepless"},b:{it:"Guerrieri del\nrisveglio",en:"Warriors of\nawakening"}},
        {a:{it:"La Ram Muay",en:"The Ram Muay"},b:{it:"La danza rivela\nil vincitore",en:"The dance reveals\nthe winner"}},
        {a:{it:"Monaco-guerriero",en:"Monk-warrior"},b:{it:"Resistenza\ninteriore",en:"Inner\nresistance"}},
        {a:{it:"I Valori\ndel FUOCO",en:"The Values\nof FUOCO"},b:{it:"Fedeltà, Umiltà,\nOnestà, Coraggio, Onore",en:"Fidelity, Humility,\nHonesty, Courage, Honour"}},
        {a:{it:"Il Fuoco Fisso",en:"The Fixed Fire"},b:{it:"Una Fede\ndivenuta stabile",en:"A Faith\nmade stable"}},
        {a:{it:"Immortalamento",en:"Immortalamento"},b:{it:"Immortali attraverso\nla morte in battaglia",en:"Immortal through\ndeath in battle"}}
      ]
    }
  }
};
})();
