/* I CINQUE VEICOLI — data.js (dalle opere di Arthur E. Powell) */
(function(){
"use strict";
window.GAME_DATA = {
  id: "veicoli",
  modes: ["veicolo","colore","quiz","memoria"],
  rings: [
    {key:"causale",color:"#2a1a3a",ring:"#7a5ab0",label:{it:"Causale",en:"Causal"}},
    {key:"mentale",color:"#10212a",ring:"#3a6a9a",label:{it:"Mentale",en:"Mental"}},
    {key:"astrale",color:"#2a1410",ring:"#7c3a2a",label:{it:"Astrale",en:"Astral"}},
    {key:"eterico",color:"#1a2a1a",ring:"#6a9a7a",label:{it:"Eterico",en:"Etheric"}}
  ],
  modeDefs: {
    veicolo: { type:"scenario", roman:"I", glyph:"◎", optionKeys:[0,1,2,3],
      items: [
        {sit:{it:"Duplicato esatto del corpo denso: assorbe il pràna dal sole e lo distribuisce attraverso i centri di forza.",en:"An exact duplicate of the dense body: it absorbs prana from the sun and distributes it through the force centres."},correct:0,note:{it:"Il Doppio Eterico è il veicolo del pràna, ponte fra il corpo denso e l'astrale.",en:"The Etheric Double is the vehicle of prana, the bridge between the dense body and the astral."}},
        {sit:{it:"Un incessante gioco di colori vi esprime sentimenti, passioni ed emozioni.",en:"An incessant play of colours expresses feelings, passions and emotions in it."},correct:1,note:{it:"Per il chiaroveggente il gioco cromatico è la caratteristica principale del corpo astrale.",en:"For the clairvoyant the play of colours is the astral body's main characteristic."}},
        {sit:{it:"Veicolo del pensiero concreto: si disgrega quando termina il soggiorno nel Devachan inferiore.",en:"Vehicle of concrete thought: it disintegrates when the stay in the lower Devachan ends."},correct:2,note:{it:"Il corpo mentale vive i quattro cieli inferiori, poi si dissolve e la coscienza si ritira nell'ego.",en:"The mental body lives the four lower heavens, then dissolves and consciousness withdraws into the ego."}},
        {sit:{it:"Il veicolo permanente dell'ego: conserva l'essenza di tutte le esperienze tra una vita e l'altra.",en:"The ego's permanent vehicle: it preserves the essence of all experiences between lives."},correct:3,note:{it:"Il corpo causale nasce con l'individualizzazione e dura per l'intero ciclo delle incarnazioni.",en:"The causal body is born with individualisation and lasts the entire cycle of incarnations."}},
        {sit:{it:"Alla morte si ritira dal corpo denso, restando unito ad esso da un sottile cordone magnetico.",en:"At death it withdraws from the dense body, remaining joined to it by a thin magnetic cord."},correct:0,note:{it:"Il doppio si ritira lentamente: è lo 'spettro eterico' visibile presso i cimiteri.",en:"The double withdraws slowly: it is the 'etheric wraith' visible near graveyards."}},
        {sit:{it:"I suoi chakram sono vortici a quattro dimensioni.",en:"Its chakras are four-dimensional vortices."},correct:1,note:{it:"I chakram astrali si estendono in una dimensione sconosciuta al doppio eterico.",en:"Astral chakras extend into a dimension unknown to the etheric double."}},
        {sit:{it:"Dopo la morte vive nel kàmaloka, con i gusci più densi disposti all'esterno.",en:"After death it lives in kamaloka, with the densest shells arranged outside."},correct:1,note:{it:"L'elementale del desiderio ridispone la materia astrale in gusci concentrici — chi sa, può impedirlo.",en:"The desire-elemental rearranges astral matter into concentric shells — one who knows can prevent it."}},
        {sit:{it:"È composto di materia dei tre sotto-piani superiori del mondo mentale.",en:"It is composed of matter from the three higher sub-planes of the mental world."},correct:3,note:{it:"Il corpo causale appartiene al piano mentale superiore: il regno del pensiero astratto.",en:"The causal body belongs to the higher mental plane: the realm of abstract thought."}},
        {sit:{it:"In esso si vive il 'giorno' che segue la notte della vita terrestre: i quattro cieli inferiori.",en:"In it one lives the 'day' that follows the night of earthly life: the four lower heavens."},correct:2,note:{it:"Il Devachan inferiore si svolge nel corpo mentale, dove ogni aspirazione diventa facoltà.",en:"The lower Devachan unfolds in the mental body, where every aspiration becomes a faculty."}}
      ]
    },
    colore: { type:"quiz", roman:"II", glyph:"❖", count:10,
      items: [
        {q:{it:"Nuvole dense di nero nell'aura rivelano…",en:"Dense black clouds in the aura reveal…"},options:{it:["Odio e malizia","Depressione","Paura","Avarizia"],en:["Hatred and malice","Depression","Fear","Avarice"]},correct:0,note:{it:"Nero in nuvole dense: odio e malizia.",en:"Black in dense clouds: hatred and malice."}},
        {q:{it:"Lo scarlatto vivo sul fondo dell'aura indica…",en:"Vivid scarlet on the background of the aura indicates…"},options:{it:["Nobile indignazione","Collera","Sensualità","Orgoglio"],en:["Noble indignation","Anger","Sensuality","Pride"]},correct:0,note:{it:"La collera è in lampi rosso scuro su fondo nero; lo scarlatto vivo è 'nobile indignazione'.",en:"Anger shows as dark red flashes on black; vivid scarlet is 'noble indignation'."}},
        {q:{it:"Il colore più frequente nel corpo astrale dell'uomo medio è…",en:"The most frequent colour in the average man's astral body is…"},options:{it:["Grigio-bruno opaco: egoismo","Rosa: amore","Giallo: intelletto","Blu: devozione"],en:["Dull grey-brown: selfishness","Pink: love","Yellow: intellect","Blue: devotion"]},correct:0,note:{it:"Il grigio-bruno dell'egoismo è uno dei colori che più frequentemente si trovano nel corpo astrale.",en:"The grey-brown of selfishness is one of the most frequent colours in the astral body."}},
        {q:{it:"L'avarizia appare come…",en:"Avarice appears as…"},options:{it:["Linee parallele rosso-bruno color ruggine","Nuvole nere","Lampi scarlatti","Macchie verdi"],en:["Rust-coloured red-brown parallel lines","Black clouds","Scarlet flashes","Green patches"]},correct:0,note:{it:"Rosso-bruno cupo, simile al color ruggine, in linee parallele che striano il corpo astrale.",en:"Dull red-brown, rust-like, in parallel lines streaking the astral body."}},
        {q:{it:"Il bruno-verdastro illuminato da lampi scarlatti rivela…",en:"Greenish-brown lit by scarlet flashes reveals…"},options:{it:["Gelosia","Astuzia","Adattabilità","Invidia del bene altrui"],en:["Jealousy","Cunning","Adaptability","Envy of others' good"]},correct:0,note:{it:"Nell'uomo medio abbonda questo colore quando è 'innamorato'.",en:"In the average man this colour abounds when he is 'in love'."}},
        {q:{it:"La depressione si mostra come…",en:"Depression shows as…"},options:{it:["Grigio plumbeo in linee parallele, come una gabbia","Grigio livido","Nero uniforme","Blu fangoso"],en:["Leaden grey in parallel lines, like a cage","Livid grey","Uniform black","Muddy blue"]},correct:0,note:{it:"Come l'avarizia, anche la depressione si dispone in linee parallele che danno l'impressione di una gabbia.",en:"Like avarice, depression arranges itself in parallel lines giving the impression of a cage."}},
        {q:{it:"Il grigio livido, 'tinta orribilmente disgustante', esprime…",en:"Livid grey, a 'horribly disgusting hue', expresses…"},options:{it:["Paura","Odio","Egoismo","Malattia"],en:["Fear","Hatred","Selfishness","Illness"]},correct:0,note:{it:"Grigio livido: paura.",en:"Livid grey: fear."}},
        {q:{it:"Il rosa straordinariamente brillante con sfumature di lillà indica…",en:"Extraordinarily bright pink with lilac shades indicates…"},options:{it:["Amore spirituale per l'umanità","Amore egoista","Devozione religiosa","Gioia"],en:["Spiritual love for humanity","Selfish love","Religious devotion","Joy"]},correct:0,note:{it:"Il rosa è amore non egoista; brillante con lillà: amore spirituale per l'umanità. Il cremisi opaco è amore egoista.",en:"Pink is unselfish love; bright with lilac: spiritual love for humanity. Dull crimson is selfish love."}},
        {q:{it:"L'arancio nell'aura rivela…",en:"Orange in the aura reveals…"},options:{it:["Orgoglio o ambizione","Vitalità","Coraggio","Creatività"],en:["Pride or ambition","Vitality","Courage","Creativity"]},correct:0,note:{it:"Arancio: orgoglio o ambizione. Spesso è unito all'irritabilità.",en:"Orange: pride or ambition. Often joined with irritability."}},
        {q:{it:"Il giallo oro indica…",en:"Golden yellow indicates…"},options:{it:["Intelligenza pura applicata a filosofia o matematica","Ricchezza interiore","Intelletto a scopi egoistici","Spiritualità devozionale"],en:["Pure intelligence applied to philosophy or mathematics","Inner wealth","Intellect for selfish ends","Devotional spirituality"]},correct:0,note:{it:"L'ocra cupo è intelletto egoistico; il giallo primula è intelletto votato allo spirito; l'oro pura intelligenza filosofica.",en:"Dull ochre is selfish intellect; primrose yellow is intellect devoted to spirit; gold pure philosophical intelligence."}},
        {q:{it:"Il verde smeraldo esprime…",en:"Emerald green expresses…"},options:{it:["Versatilità e ingegnosità altruista","Astuzia e inganno","Gelosia","Forte vitalità"],en:["Versatility and unselfish resourcefulness","Cunning and deceit","Jealousy","Strong vitality"]},correct:0,note:{it:"Il grigio-verde fangoso è astuzia; lo smeraldo versatilità altruista; il verde sidro vitalità.",en:"Muddy grey-green is cunning; emerald unselfish versatility; cider green vitality."}},
        {q:{it:"Il blu chiaro come l'ultramarino o il cobalto rivela…",en:"Light blue like ultramarine or cobalt reveals…"},options:{it:["Devozione a un nobile ideale spirituale","Calma","Sentimento religioso generico","Tristezza"],en:["Devotion to a noble spiritual ideal","Calm","Generic religious feeling","Sadness"]},correct:0,note:{it:"Il blu cupo trasparente è sentimento religioso; il blu chiaro devozione a un nobile ideale.",en:"Dark transparent blue is religious feeling; light blue devotion to a noble ideal."}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"La parola sanscrita 'chakram' significa…",en:"The Sanskrit word 'chakram' means…"},options:{it:["Ruota o disco girante","Fiore di loto","Centro di luce","Porta sottile"],en:["Wheel or spinning disc","Lotus flower","Centre of light","Subtle gate"]},correct:0,note:{it:"I chakram sono i punti di congiunzione attraverso cui la forza si riversa da un veicolo nell'altro.",en:"Chakras are the junction points through which force pours from one vehicle into another."}},
        {q:{it:"Kundalini, il Fuoco Serpentino, risiede…",en:"Kundalini, the Serpent Fire, resides…"},options:{it:["Nel chakram della base della colonna vertebrale","Nel cuore","Nella sommità del capo","Nella milza"],en:["In the chakra at the base of the spine","In the heart","At the crown of the head","In the spleen"]},correct:0,note:{it:"Da lì si sposta vivificando gli altri centri: ombelico, milza, cuore, gola, fronte, sommità.",en:"From there it moves on, vivifying the other centres: navel, spleen, heart, throat, brow, crown."}},
        {q:{it:"Quale chakram assorbe il pràna e vitalizza tutto il corpo astrale?",en:"Which chakra absorbs prana and vitalises the whole astral body?"},options:{it:["La milza","Il cuore","La gola","L'ombelico"],en:["The spleen","The heart","The throat","The navel"]},correct:0,note:{it:"La sua vivificazione permette di viaggiare coscientemente in astrale, pur con ricordi vaghi.",en:"Its vivification allows conscious astral travel, though with vague recollections."}},
        {q:{it:"Il chakram del cuore astrale conferisce…",en:"The astral heart chakra confers…"},options:{it:["Comprensione istintiva dei sentimenti delle altre entità","Udito astrale","Vista astrale","Il potere di volare"],en:["Instinctive understanding of other entities' feelings","Astral hearing","Astral sight","The power of flight"]},correct:0,note:{it:"Gola = udito astrale; fronte = vista astrale; sommità = pienezza delle facoltà.",en:"Throat = astral hearing; brow = astral sight; crown = fullness of faculties."}},
        {q:{it:"Il siddhi di 'ingrandire o impicciolire a volontà' dipende dal chakram…",en:"The siddhi of 'enlarging or diminishing at will' depends on the chakra…"},options:{it:["Fra le sopracciglia","Della gola","Del cuore","Della milza"],en:["Between the eyebrows","Of the throat","Of the heart","Of the spleen"]},correct:0,note:{it:"Permette di percepire e studiare molecole e atomi, come con un microscopio.",en:"It allows one to perceive and study molecules and atoms, as with a microscope."}},
        {q:{it:"Oltre ai sette chakram principali, esistono tre chakram inferiori…",en:"Besides the seven main chakras, there are three lower chakras…"},options:{it:["Usati solo da certe scuole di magia nera","Attivi solo nei bambini","Ormai atrofizzati","Riservati ai Maestri"],en:["Used only by certain schools of black magic","Active only in children","Now atrophied","Reserved for Masters"]},correct:0,note:{it:"Powell li menziona e tralascia di occuparsene proprio per questo.",en:"Powell mentions them and sets them aside for precisely this reason."}},
        {q:{it:"'Devachan' significa…",en:"'Devachan' means…"},options:{it:["Il luogo dei deva: il mondo celeste","Il vuoto luminoso","La terra pura","Il sonno senza sogni"],en:["The place of the devas: the heaven world","The luminous void","The pure land","Dreamless sleep"]},correct:0,note:{it:"È il 'giorno' che succede alla notte della vita terrestre: assimilazione dell'esperienza.",en:"It is the 'day' following the night of earthly life: assimilation of experience."}},
        {q:{it:"Quanti 'cieli' compongono il mondo celeste?",en:"How many 'heavens' make up the heaven world?"},options:{it:["Sette: quattro inferiori e tre superiori","Tre","Nove","Dodici"],en:["Seven: four lower and three higher","Three","Nine","Twelve"]},correct:0,note:{it:"Quattro cieli sul piano mentale inferiore, tre sul piano causale — fino ai Maestri di Saggezza.",en:"Four heavens on the lower mental plane, three on the causal plane — up to the Masters of Wisdom."}},
        {q:{it:"L'individualizzazione avviene quando…",en:"Individualisation occurs when…"},options:{it:["Un animale rompe l'involucro dell'anima-gruppo e nasce il corpo causale","L'uomo impara a leggere","La monade si addormenta","Il corpo astrale si colora"],en:["An animal breaks the group-soul's envelope and the causal body is born","Man learns to read","The monad falls asleep","The astral body takes colour"]},correct:0,note:{it:"Prima dell'individualizzazione la vita evolve in anime-gruppo: minerali, vegetali, animali.",en:"Before individualisation life evolves in group-souls: mineral, vegetable, animal."}},
        {q:{it:"Le anime-gruppo minerali hanno…",en:"Mineral group-souls have…"},options:{it:["Tre strati nell'involucro","Un solo strato","Nessun involucro","Sette strati"],en:["Three layers in their envelope","A single layer","No envelope","Seven layers"]},correct:0,note:{it:"Minerali: tre strati. Vegetali: due. Animali: uno solo — prossimi all'individualizzazione.",en:"Mineral: three layers. Vegetable: two. Animal: just one — close to individualisation."}},
        {q:{it:"Gli atomi permanenti sono…",en:"The permanent atoms are…"},options:{it:["I 'semi' che conservano le vibrazioni di ogni esperienza tra le vite","Particelle indistruttibili del cervello","Gli atomi del DNA","I ricordi coscienti"],en:["The 'seeds' preserving the vibrations of every experience between lives","Indestructible brain particles","The atoms of DNA","Conscious memories"]},correct:0,note:{it:"Fisico, astrale e mentale: servono da nucleo per la costruzione dei nuovi veicoli.",en:"Physical, astral and mental: they serve as nuclei for building the new vehicles."}},
        {q:{it:"Kundalini è una delle tre forze emanate…",en:"Kundalini is one of the three forces emanating…"},options:{it:["Dal sole, con Fohat e Pràna","Dalla terra","Dalla luna","Dal cuore umano"],en:["From the sun, with Fohat and Prana","From the earth","From the moon","From the human heart"]},correct:0,note:{it:"Il Fuoco-serpentino è separato e distinto da Fohat e da Pràna.",en:"The Serpent Fire is separate and distinct from Fohat and Prana."}},
        {q:{it:"'Trishna', la causa della rincarnazione, è…",en:"'Trishna', the cause of reincarnation, is…"},options:{it:["La sete di esistenza","La paura della morte","Il debito karmico","La volontà divina"],en:["The thirst for existence","The fear of death","Karmic debt","Divine will"]},correct:0,note:{it:"È la sete di esperienza e di espressione che richiama l'ego verso una nuova vita.",en:"It is the thirst for experience and expression calling the ego towards a new life."}},
        {q:{it:"Passando dal kàmaloka al Devachan, l'uomo può portare con sé…",en:"Passing from kamaloka to Devachan, man can take with him…"},options:{it:["Solo i germi latenti nell'atomo astrale permanente","Tutte le sue passioni","I corpi astrali dei cari","Le forme-pensiero cattive"],en:["Only the latent germs in the permanent astral atom","All his passions","The astral bodies of loved ones","Evil thought-forms"]},correct:0,note:{it:"La materia devachanica non può rispondere alle vibrazioni grossolane delle passioni.",en:"Devachanic matter cannot respond to the coarse vibrations of the passions."}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✶",
      items: [
        {a:{it:"Base della colonna",en:"Base of the spine"},b:{it:"Kundalini",en:"Kundalini"}},
        {a:{it:"Milza",en:"Spleen"},b:{it:"Pràna",en:"Prana"}},
        {a:{it:"Cuore",en:"Heart"},b:{it:"Empatia astrale",en:"Astral empathy"}},
        {a:{it:"Gola",en:"Throat"},b:{it:"Udito astrale",en:"Astral hearing"}},
        {a:{it:"Fra le sopracciglia",en:"Between the eyebrows"},b:{it:"Vista astrale",en:"Astral sight"}},
        {a:{it:"Sommità del capo",en:"Crown of the head"},b:{it:"Pienezza delle\nfacoltà",en:"Fullness of\nfaculties"}}
      ]
    }
  }
};
})();
