/* Dati lezioni — Scuola ContattaTi (versione italiana) */
var L1=[
  {num:1,day:14,month:9,year:2025,titolo:'Siamo veramente liberi?',sottotitolo:"L'Addormentamento ed il Risveglio nella Scuola di Consapevolezza ed Alchimia",desc:'Gurdjieff descrive l\'essere umano come una <strong>carrozza senza padrone</strong>: il corpo fisico è la carrozza, trascinata senza controllo; le emozioni sono i cavalli, impulsivi e senza direzione; la mente è il cocchiere, spesso distratto; la coscienza è il passeggero, addormentato, che dovrebbe dare indicazioni. Senza consapevolezza si vive in uno stato di <strong>sonno</strong>: si agisce meccanicamente, si reagisce agli stimoli come un riflesso, ci si identifica con maschere e ruoli perdendo il contatto con la propria essenza autentica. Come nel <strong>Labirinto di Cnosso</strong>, la conoscenza di sé è il filo di Arianna che permette di sfuggire alla prigionia psicologica. Solo il risveglio della coscienza può renderci liberi.',temi:['La via del Conosci Te Stesso — Γνῶθι Σεαυτόν','La prigione dell\'Ego','La Scuola di Risveglio della Coscienza: valori e obiettivi','Opus Alchemicum — Lavoro su di Sé','Evoluzione Orizzontale e Verticale','Legge di Meccanicità','Influenze A-B-C','La Carrozza di Gurdjieff e la Casa senza padrone','La Macchina Biologica','La Quintessenza e la Pietra Filosofale','Legge di Molteplicità o Frammentazione dell\'Io','Il Processo di Solve et Coagula','Addormentamento della Coscienza','Arcani Evolutivi VII-XI','Regole di Pratica di Lavoro su di Sé','I 3 Veleni e i 3 Rimedi'],citazione:'"Esistono menti che si interrogano, che desiderano la verità del cuore. Se un uomo ragiona e pensa bene, deve inevitabilmente ritornare a se stesso."',autore:'Georges Ivanovitch Gurdjieff'},
  {num:2,day:26,month:10,year:2025,titolo:'Il Potere del Qui e Ora: liberarsi dal passato, vivere il presente',sottotitolo:'Le 96 Leggi Universali — 2ª Lezione, Anno 1',desc:'Chi comanda davvero la nostra vita? Sotto la superficie coesistono diversi strati dell\'<strong>Io</strong>, dai condizionamenti esterni al nucleo più autentico dell\'Anima, e riconoscerli è il primo passo per smettere di reagire e iniziare a scegliere. Le <strong>3 metamorfosi</strong> di Nietzsche offrono una mappa archetipica di questa trasformazione interiore: dal peso del dovere alla ribellione, alla pura creazione. Il percorso alchemico traduce tutto questo in un <strong>Opus</strong> pratico che conduce alla Pietra Filosofale: l\'incarnazione del divino nella vita quotidiana, più che una conquista intellettuale.',temi:['L\'Hic et Nunc — Kairos e Kronos','La Legge di Liberazione','Mindfulness e Sati — L\'Attenzione','L\'Anicca, la Dukka e l\'Anatta','Gli Schemi dell\'Ego','Il Dramma ed il Potere del Qui ed Ora','Il Dolore, la Sofferenza e l\'Autocommiserazione','La Tripartizione dell\'Io','Le 3 Metamorfosi, l\'Oltreuomo: Cammello-Leone-Fanciullo','Il Sale Filosofale e il Sole — L\'Oro','I Centri di Natura Superiore e i Centri di Natura Inferiore','Il Fuoco Alchemico: il Focus','Le Prove Iniziatiche','Legge di Accelerazione','Legge di Riparazione e Centro di Gravità Permanente','Gli Arcani Evolutivi XII-XIII'],citazione:'"Nulla è più pericoloso e mortale per l\'anima che occuparsi continuamente di sé stessi e della propria condizione, della propria insoddisfazione e debolezza solitaria."',autore:'Hermann Hesse'},
  {num:3,day:14,month:12,year:2025,titolo:'Oltre la Realtà Tangibile, l\'Armonia e la Perfezione della Vita. Come cambiare la realtà che non ci piace?',sottotitolo:'Le 96 Leggi Universali — 3ª Lezione, Anno 1',desc:'I <strong>Pendoli Mentali</strong> si inceppano quando ci allontaniamo dalla nostra verità interiore: restiamo imprigionati dentro credenze subliminali, invisibili e polarizzanti, come calamite che impediscono al pendolo di tornare al centro. Il comportamento che ne deriva non parla di noi, ma della posizione che occupiamo rispetto al pendolo. Solo avvicinandosi al centro l\'essere si rivela come presenza viva, autentica. Altro tema centrale è la <strong>Menzogna</strong> come tradimento della propria identità: ogni bugia crea distanza non solo dagli altri ma dal proprio cuore, il luogo dell\'unità dove si percepisce la verità e la comunione.',temi:['La Tetraktys Pitagorica','La Legge dell\'Uno','La Legge del Due','La Legge del Ritmo','La Legge del Pendolo','I Saṅkhāra e le Formazioni Mentali Condizionanti','L\'Idea di Sé e i Pendoli Mentali','La Legge dell\'Equilibrio','La Legge di Azione e Reazione','La Legge del Tre','La Legge del Boomerang','La Legge del Ritorno all\'Uno','Legge del Ciclo','Il Cerchio della Vita: l\'Uroboro','La Caduta dall\'Eden','Legge delle Infinite Possibilità: il Pi Greco — π — e la Trinità','Legge di Reciprocità: la Regola Aurea ed Argentea','Menzogna e Verità','Il Ciclo Dopaminergico di Gratificazione','La Mente e l\'Ego Spirituale','Tarocchi Evolutivi XIV e XV'],citazione:'"L\'uomo è la specie più folle: venera un Dio invisibile e distrugge una Natura visibile."',autore:'Hubert Reeves'},
  {num:4,day:1,month:2,year:2026,titolo:'"La Scienza Interiore della Creazione" — Prendi in mano la tua vita',sottotitolo:'Le 96 Leggi Universali — 4ª Lezione, Anno 1',desc:'La <strong>Legge di Causa ed Effetto</strong> rivela che nulla è casuale: il cosmo è un ordine nascosto dove ogni piccolo cambio di rotta genera enormi differenze nel destino. La <strong>Legge dello Specchio</strong> mostra che sulla terra non si riceve per merito ma per risonanza: ciò che reprimiamo ritorna per essere visto attraverso gli altri, invitandoci a guardare dentro anziché fuori. L\'<strong>Alchimia Emotiva</strong> insegna che le emozioni non elaborate diventano veleni che intossicano corpo, mente e relazioni. Solo attraversando il sentire con presenza si può trasformare l\'energia grezza in forza creativa e prendere in mano la propria vita.',temi:['Pratica di Lavoro su di Sé','La Legge di Causa Effetto','Responsabilità e Colpa: Stoicismo','La Legge di Attrazione e Risonanza','La Legge dello Specchio','La Legge di Precedenza','L\'Alchimia Emotiva','Le Emozioni — Sentimenti e Intelligenza Emotiva','La Legge di Creazione Intenzionale','La Legge dell\'Aspettativa e il Dubbio','Il Processo Creativo e la Costante di Creazione','Effetto Maharishi','I 2 Sistemi Biologici di Risposta: Cannabinoide ed Oppioide','La Pineale: DMT, Amandanide, Pinealina e Onde Gamma','Arcani Evolutivi La Torre e La Stella'],citazione:'"Tutto ciò che cerchi è già dentro di te. Sei già ciò che stai cercando. Non cercare fuori: ciò che è fuori è solo un riflesso."',autore:'Osho'},
  {num:5,day:15,month:3,year:2026,titolo:'Come superare i blocchi e raggiungere gli obiettivi nella vita',sottotitolo:'Le 96 Leggi Universali — 5ª Lezione, Anno 1',desc:'Perché ogni progetto, prima o poi, si inceppa? La <strong>Legge del 7 (dell\'Ottava)</strong> spiega che lungo la strada verso un obiettivo ci sono punti di stallo inevitabili: il primo è interiore, quando l\'energia iniziale si esaurisce e affiorano i dubbi; il secondo è esteriore, quando siamo quasi al traguardo e le resistenze si intensificano. <strong>L\'autosabotaggio</strong> e il <strong>vittimismo</strong> sono le deviazioni naturali che si attivano quando non siamo presenti a noi stessi: attribuendo la responsabilità al fuori, rinunciamo al potere di intervenire sulla nostra vita. Riconoscere questi meccanismi è già l\'inizio del loro scioglimento.',temi:['Il Seme Divino e l\'Imago Dei: la Legge Mistica','Legge del Karma e del Dharma','Il Nobile Ottuplice Sentiero','Tendenza Karmica, Loop Karmici e Controtendenza','Debito e Credito Karmico','Karma Positivo e Negativo','Legge del Qui ed Ora','Legge del Cambiamento','Esho Funi: Principio di Non Dualità','Leggi di Responsabilità e Legge dell\'Accettazione','Legge del Sette o dell\'Ottava','Obiettivi da Raggiungere, Shock Addizionali ed Ultima Sfida','Ansia di Anticipazione, Ansia da Prestazione e Ipersalienza','Autosabotaggi e Vittimismo','Il Dubbio Vuoto e il Dubbio Germinativo','La Devianza Spirituale e le Sincronicità','Legge di Abbondanza','Legge del Non Attaccamento','Legge del Servizio','Legge dell\'Impermanenza'],citazione:'"Non esiste vento favorevole per il marinaio che non sa dove andare."',autore:'Seneca'},
  {num:6,day:3,month:5,year:2026,titolo:'Come trasformare le emozioni negative in carburante per la propria evoluzione',sottotitolo:'Alchimia: Trasmutazione del Piombo in Oro — 6ª Lezione, Anno 1',desc:'Le <strong>Emozioni</strong> (dal latino <em>e/ex-movēre</em>) sono impulsi reattivi che salgono dalle profondità e ci muovono verso l\'esterno. I <strong>Sentimenti</strong> (dal latino <em>sentire</em>) sono percezioni interiori più stabili e profonde, il vero Sentire. Imparare a distinguerli è fondamentale per non essere in balia delle reazioni automatiche. Il percorso alchemico passa attraverso tre grandi fasi, <strong>Nigredo</strong>, <strong>Albedo</strong> e <strong>Rubedo</strong>: dissoluzione, purificazione e rinascita. Il primo strumento dell\'alchimista è il <strong>Fuoco Alchemico</strong>, generato dall\'attrito tra disagio interiore e osservazione cosciente: è il fuoco che accende la trasformazione.',temi:['Lo Studio a Spirale e la Scuola Iniziatica','L\'Illusione dei Sensi — Mundus Sensibilis','La Coscienza Extracerebrale — Mundus Imaginabilis','Osservatore e Testimone — Parsifal','Identificazione ed il Ricordo di Sé','Definizione e Caratterizzazione','Le 4 Menti','Le Emozioni Negative — Cavalcare la Tigre: la Padronanza di Sé','Immaginazione Negativa','Immaginazione Creativa','Legge Trasmutativa','Le 3 Fasi dell\'Alchimia Inferior: Nigredo, Albedo, Rubedo','Cauda Pavonis, Citrinitas, Iosis','La Rinascita: l\'Araba Fenice','Il Chrism','L\'Amor Fati','Arcani Evolutivi: La Luna, il Sole, il Giudizio, il Mondo','Il Sal-Nitro, Mercurio-Loquens e Zolfo-Ignis'],citazione:'"La vita inizia dove finisce la paura."',autore:'Osho'}
];

var L2=[
  {num:1,day:13,month:9,year:2026,titolo:'Il Tao: la scelta tra il Bene ed il Male ed il Libero Arbitrio',sottotitolo:'Le Leggi Universali \u2014 1\u00aa Lezione, 2\u00b0 Anno',temi:['La Legge di Polarit\u00e0','Yin e Yang: il Tao e l\'insegnamento del Bene e del Male','Bene e Perbenismo','La Via di Mezzo','Legge del Divenire o Mutamento','Karma, Destino e Libero Arbitrio','La Legge del Libero Arbitrio','I Triangoli Sacri','Legge della Scala','Il Transurfing','Il Bivio ed il Discernimento','La Legge dell\'8, o della Scelta'],citazione:'"Tutte le dualit\u00e0 devono essere abbandonate. La dualit\u00e0 in quanto tale dev\'essere abbandonata, perch\u00e9 tu esisti oltre la dualit\u00e0."',autore:'Osho'},
  {num:2,day:8,month:11,year:2026,titolo:"L'Enneagramma, la Geometria Sacra dell'Anima ed il Cammino della Personalit\u00e0",sottotitolo:'Le Leggi Universali \u2014 2\u00aa Lezione, 2\u00b0 Anno',temi:["L'identificazione con la Personalit\u00e0","L'addormentamento e la Caduta dall'Eden",'Carattere Destino nel Cerchio del Samsara',"La Legge del 9: l'Enneagramma come Cammino di Conoscenza Profonda","La Geometria Sacra dell'Anima: Legge dell'Unit\u00e0, del 3 e del 7",'Enneagramma: Karma e Dharma','Il Cammino nella Via della Virt\u00f9 ed il Ritorno a Casa','Personalit\u00e0 e Carattere','Passioni e Fissazioni Dominanti','Sottotipi Istintuali e Ali','Legge del Salmone o di Controtendenza','Scelte vs Decisioni','Legge del Lavoro su di S\u00e9'],citazione:'"Destino e carattere sono due nomi del medesimo concetto."',autore:'Hermann Hesse'},
  {num:3,day:13,month:12,year:2026,titolo:"Chi cerca trova... L'Enneagramma per ritrovare se stessi",sottotitolo:'Le 96 Leggi Universali \u2014 3\u00aa Lezione, 2\u00b0 Anno',temi:['Il Velo di Maya','Iside ed Osiride','I 4 Passi della Trasmutazione Iniziatica','Il Bambino Interiore','Fuoco Divino e Fuoco Prometeo','Enneatipo 9-8-1, il Centro Viscerale','Verit\u00e0 e Carisma','Archetipo Numerologico Guerriero/Ribelle (1)','Archetipo Numerologico Sovrano/Tiranno (8)','Archetipo Numerologico Liberatore/Angelo Caduto (9)','I 9 Volti di Dio'],citazione:'"Colui che cerca non desista dal cercare fino a quando non avr\u00e0 trovato; quando avr\u00e0 trovato si stupir\u00e0."',autore:'Vangelo di Tommaso'},
  {num:4,day:7,month:2,year:2027,titolo:"Il Ricordo di S\u00e9 attraverso l'Enneagramma",sottotitolo:'Le 96 Leggi Universali \u2014 4\u00aa Lezione, 2\u00b0 Anno',temi:['Legge di Compensazione','Ricordo di S\u00e9 e Buddheit\u00e0','Legge Mistica','Legge del Mistero','Giudizio e Discernimento','Il Non-Giudizio','Enneatipi del Centro Emotivo (2-3-4)','Archetipo Numerologico 2 Fanciullo/Orfano','Archetipo Numerologico 3 Giullare/Straniero','Archetipo Numerologico 4 Costruttore/Prigioniero'],citazione:'"Racchiudi la Verit\u00e0 nel tuo Cuore, e che essa parli attraverso le tue Opere. La Scienza sar\u00e0 la tua forza; la Fede la tua spada."',autore:'Ermete Trismegisto'},
  {num:5,day:7,month:3,year:2027,titolo:"Il Cambiamento \u2014 Superare le resistenze attraverso l'Enneagramma",sottotitolo:'Le 96 Leggi Universali \u2014 5\u00aa Lezione, 2\u00b0 Anno',temi:['La Tela di Penelope','Gli Auto-Sabotaggi ed il Procrastinare','Il Cambiamento e le Resistenze','Il Vaso di Pandora e la Legge del Vaso','Enneatipi del Centro Mentale (5-6-7)','Archetipo Numerologico il Creatore/il Girovago (5)',"Archetipo Numerologico l'Angelo Custode/il Martire (6)",'Archetipo Numerologico il Sovrano/Solitario (7)','La Conversione della Nevrosi','Le Idee Sante','Es, Ego e Super-Io','Gli Enneatipi e la loro Relazione con gli Altri'],citazione:'"Chi guarda s\u00e9 stesso rischia di incontrare s\u00e9 stesso. Lo specchio non lusinga, mostra quella faccia che non mostriamo mai al mondo."',autore:'Carl Gustav Jung'},
  {num:6,day:9,month:5,year:2027,titolo:"Legge dell'Amore \u2014 Autostima, Amore di S\u00e9 e Mission",sottotitolo:'Le 96 Leggi Universali \u2014 6\u00aa Lezione, 2\u00b0 Anno',temi:["I 9 Enneatipi nell'Amore",'Amore di S\u00e9: Autostima e Accettazione','I 3 Tipi di Cambiamento','Identit\u00e0: Valori e Mission','La Vision e la Vocazione','La Guida Interiore','Piramide dei Livelli Logici e dei Bisogni','Il Mito della Caverna di Platone',"Le 3 Forme dell'Amore: Eros, Agap\u00e8, Phil\u00eca",'Scelte di Testa, Pancia e Cuore','Pineale, Occhio di Horus e Occhio di Ra',"La Legge dell'Amore ed Apertura del Cuore",'I 4 Piani della Realt\u00e0','La Forza di Gravit\u00e0','La Maya di Krishna: Matrix e Realt\u00e0 Olografica'],citazione:'"Atto d\'amore \u00e8 accogliere in noi la nostra parte pi\u00f9 ferita e fragile."',autore:'Carl Gustav Jung'},
  {num:7,day:30,month:5,year:2027},
];

var L3=[
  {num:1,titolo:"L'Albero della Vita e la Risalita all'Eden",sottotitolo:'Le Leggi Universali \u2014 1\u00aa Lezione, 3\u00b0 Anno',temi:["Caduta e Risalita all'Eden","L'Adam Kadmon","L'Albero della Vita e i Frutti Immortali",'La Legge della Magia','Legge della Slatentizzazione o Attivazione','La Legge del 10','Principio della Decima e Legge dei Vasi Comunicanti','Registri Akashici','Emanazione e Conversione della Luce',"L'Albero Sephirotico e Qliphotico",'Significato delle Sephiroth','Legge di Differenza di Potenziale','Codice Binario e Quantistico: il Libero Arbitrio'],citazione:'"L\'Albero della Vita affonda le sue radici nel tuo stesso cuore."',autore:'Gialad-ad-din Rum\u00ec'},
  {num:2,titolo:'La Creazione attraverso le Geometrie Sacre',sottotitolo:'Le Leggi Universali \u2014 2\u00aa Lezione, 3\u00b0 Anno',temi:["L'importanza di un Pensiero Corretto","Dal Seme all'Albero della Vita",'Il Fiore della Vita \u2014 Il Frutto della Vita \u2014 Il Cubo di Metatron','La Merkaba e i Wormholes','La Vescica Piscis ed il Femminino Sacro','Il Pane Quotidiano: Chiedi e ti sar\u00e0 dato','I 3 Pilastri e le 3 Triadi','I 22 Sentieri Arcani','La Legge del 13, o del Ricordo di S\u00e9',"La Memoria dell'Acqua",'La Spirale Aurea e la Costante di Fidia \u03a6 (PHI)','La Coscienza Cristica o Cristallo','Il Potere Personale e la Crescita del Livello di Coscienza','Le 10 Dimensioni','Legge Naturale e Legge della Volont\u00e0 Superiore o Eterna','Temperanza e Lavoro su di S\u00e9'],citazione:'"Se potessimo vedere il miracolo di un singolo fiore, la nostra intera vita cambierebbe."',autore:'Buddha'},
  {num:3,titolo:'Il Mago, la Magia e le Parole di Potere',sottotitolo:'Le Leggi Universali \u2014 3\u00aa Lezione, 3\u00b0 Anno',temi:["I 3 Stati dell'Acqua e l'Albero della Vita",'Il Verbo Creativo: la Cimatica, il Suono si fa Forma',"L'Om-Aum, il Suono di Creazione",'Adamo ed il Potere di Nominare le Cose','La Forma e la Funzione','La Torre di Babele e la Parola Perduta','La Parola di Potere o Magica ed il Potere delle Parole','Parole Segno -Rombo- e Parole Singolo -Triangolo-','Esoterismo ed Essoterismo: il Religioso, il Mistico, il Mago','La Magia Naturale e la Magia Ermetica','Legge di Compensazione','La Legge dello Scambio Magico, i Sacrifici e i Re Magi','Legge del Focus, la Bacchetta Magica','Le Eggregore o Forme Pensiero','Le Subpersonalit\u00e0','Legge della Connessione',"L'Atteggiamento Interiore \u2014 lo Stato d'Animo",'Effetto Osservatore','Pensiero e Sguardo Magico'],citazione:'"Ci sono solo fatti?, io direi: no, proprio i fatti non ci sono, bens\u00ec solo interpretazioni."',autore:'Friedrich Nietzsche'},
  {num:4,titolo:"Raggiungere Da'at la Sephira Nascosta: la Conoscenza Unificante ed il Potere Divino celato nel DNA",sottotitolo:"Le Leggi dell'Universo \u2014 4\u00aa Lezione, 3\u00b0 Anno",temi:["Ho'oponopono e la Magia Ermetica",'Il Teatro Familiare','La Via Solare della Coscienza o Via del Cuore','Salire su Tiphareth-Geburah-Chesed',"L'importanza della Corretta Comunicazione",'Legge del 6 o Legge della Ricongiunzione degli Opposti o della Scelta','Legge di Liberazione','La Stella di David \u2014 il Sigillo Salomonico',"L'Esagono e la Legge di Efficienza",'Legge di Determinazione','Il Coraggio e Forza del Leone','Il Servizio e Agni Yoga',"Da'at la Sephira Nascosta \u2014 L'Akasha","L'Abisso e l'Antro della Sibilla",'Il Silenzio',"Il Vuoto Quantistico e l'Energia di Punto Zero",'Il Miracolo','Legge del Ribaltamento \u2014 Legge del Dono','Logos Divino celato nel DNA-GNA'],citazione:'"I due giorni pi\u00f9 importanti della vita sono quello in cui sei nato e quello in cui capisci perch\u00e9."',autore:'Mark Twain'},
  {num:5,titolo:'Shamballah il Regno della Luce: i 7 Raggi e le 7 Iniziazioni per tornare alla Casa del Padre',sottotitolo:'Le Leggi Universali \u2014 5\u00aa Lezione, 3\u00b0 Anno',temi:["Come Ritornare all'Uno",'I 7 Raggi','I 3 Veli che Conducono alla Verit\u00e0','La Via Iniziatica','Le 7 Iniziazioni','I Maestri Ascesi e Shamballah','Legge della Necessit\u00e0','Legge della Volont\u00e0 Libera','Legge della Provvidenza Divina','Teorema di Pitagora','Legge del Perdono','Le 7 Richieste del Padre Nostro \u2014 7 Peccati Capitali \u2014 7 Doni dello Spirito Santo','La Magia: il Sentiero della Mano Destra e della Mano Sinistra','La Vita Iniziatica di Ges\u00f9 e la Sua Missione: il Cristo'],citazione:'"Tu non sei separato dalla globalit\u00e0. Sei una cosa sola con il sole, la terra, l\'aria. Tu non hai una vita. Tu sei la vita."',autore:'Eckhart Tolle'},
  {num:6,titolo:'La Compassione \u2014 Trascendere la Dualit\u00e0, al di l\u00e0 del Sogno della Coscienza',sottotitolo:'Le Leggi Universali \u2014 6\u00aa Lezione, 3\u00b0 Anno',temi:["L'Importanza della Carne, Malkuth",'Il Discernimento','La Legge del Potere Personale','La Via della Freccia e la Via del Serpente','Il Sentiero Probatorio e quello Propriamente Detto',"L'Ansia-Angoscia e Giusto Distacco nello Zen",'La Legge della Messa a Fuoco',"L'Uovo Cosmico ed il Rebis",'Il Sogno della Coscienza e la Matrix','Io Sono il Supremo: Essere in Congruenza con la Natura Superiore','Il Ricordo di S\u00e9 ed il Testimone Silenzioso',"L'Io Sono e la Fiamma Violetta di Saint Germain",'La Vera Libert\u00e0','Trascendere la Dualit\u00e0 del Pendolo',"La Compassione, l'Amorevole Gentilezza e la Gratitudine",'Paradossi Taoisti ed Evangelici, la Via della Saggezza'],citazione:'"Chi percepisce contemporaneamente la propria ombra e la propria luce vede s\u00e9 stesso da due lati e, in tal modo, raggiunge il centro."',autore:'C.G. Jung'}
];

var L4=[
  {num:1,titolo:"L'Antica Sapienza e la Via che conduce a manifestare la Divinit\u00e0",sottotitolo:'Scuola di Consapevolezza ed Alchimia \u2014 1\u00aa Lezione, 4\u00b0 Anno',desc:'L\u2019evoluzione non \u00e8 un concetto astratto: \u00e8 il dispiegamento concreto della vita divina all\u2019interno di noi. La <strong>monade</strong>, scintilla dal triangolo supremo, attraversa quattro regni (minerale, vegetale, animale, umano) per portare a manifestazione ci\u00f2 che \u00e8 latente come in un seme. L\u2019uomo \u00e8 l\u2019unico essere capace di farlo consapevolmente. La <strong>legge di creazione</strong> \u00e8 Dio che si fa carne; la <strong>legge di evoluzione</strong> \u00e8 la carne che si fa Dio. Attraverso i <strong>sette corpi</strong> (fisico, eterico, astrale, mentale, causale, buddhico, atmico) l\u2019anima evolve: prima dominando la macchina biologica, poi attivando i poteri dell\u2019anima. I pensieri coltivati con intensit\u00e0 diventano forze interiori nella vita successiva; le tendenze karmiche si ripetono identiche; i desideri insoddisfatti ritornano come compulsioni, quelli soddisfatti e dolorosi si ribaltano in ombra.',temi:['La Preghiera del Padre Nostro','La Via che conduce a manifestare la Divinit\u00e0',"L'Antica Sapienza e la Creazione dell'Uomo",'La Legge di Creazione','Legge di Evoluzione \u2014 Il Sentiero della Mano Destra',"La Legge dell'Analogia",'Lo Spirito-Materia, gli Atomi e gli Elementali','La Settemplice Natura Umana: la Triade Superiore ed il Quaternario Inferiore','I 7 Piani: Fisico, Eterico, Astrale, Mentale, Causale, Buddhico, Atmico',"Il Corpo, l'Anima e lo Spirito",'Lilith, Samael, Gamaliel \u2014 Il Sentiero della Mano Sinistra','Metamorfosi dei Pensieri tra una vita e l\u2019altra','Tendenze karmiche e controtendenze','Ombre karmiche e desideri invertiti','Sofferenza e Sacrificio','La Sophia e i 5 punti dell\u2019Antica Sapienza','Legge d\u2019Attrazione come legge del corpo astrale','Impulso emotivo vs Istinto'],citazione:'"Si deve cercare non di essere senza peccato, ma di essere un Dio. Colui che agisce secondo le virt\u00f9 teoretiche, \u00e8 un Dio. Ma colui che agisce secondo le virt\u00f9 paradigmatiche \u00e8 il Padre degli Dei."',autore:'Plotino'},
  {num:2,titolo:"La Vita dopo la Morte, l'Aldil\u00e0 e la Reincarnazione",sottotitolo:'Le Leggi Universali \u2014 2\u00aa Lezione, 4\u00b0 Anno',desc:'Cosa accade ai nostri sette corpi dopo la morte? Il <strong>quadro mnemonico</strong> ci mostra l\u2019intera vita appena conclusa come uno specchio karmico, senza coinvolgimento emotivo. Poi l\u2019anima attraversa i sette piani del <strong>Kamaloka</strong>, il luogo del desiderio: dagli inferni ai purgatori, fino ai paradisi terrestri, purificando ogni attaccamento. Infine entra nel <strong>Devachan</strong>, il regno celeste, dove incontra solo le anime che ha amato e raccoglie i frutti di tutto ci\u00f2 che di buono ha compiuto in vita. Ogni qualit\u00e0 viene amplificata e trasformata in facolt\u00e0 per la vita successiva. La lezione si chiude con il momento di <strong>chiara visione</strong>: all\u2019anima vengono mostrate le linee generali della prossima incarnazione.',temi:['Il Biocentrismo',"La Vita dopo la Morte e l'Aldil\u00e0",'Legge del Merito','Legge di Corrispondenza','I 3 Gunas: Tamasico, Rajasico, Sattvico','Il Kamaloka e la Purificazione: i 7 piani',"La Legge dell'Eco e del Riverbero",'Legge del Contrappasso per analogia e per contrasto','Il Devachan con forma e senza forma: i 7 Cieli','La Trasformazione da Abilit\u00e0 in Facolt\u00e0',"La Legge della Simpatia o dell'Affinit\u00e0",'La Famiglia Animica','I 4 tipi di Attaccamento e il destino karmico',"L'Evoluzione dei 4 Regni","La Personalit\u00e0 e Individualizzazione",'Legge della Misura','Legge Generale della Reincarnazione','Il Sigillo Mnemonico delle Vite Precedenti','I 49 giorni del Bardo e la Pentecoste','Larve astrali e fantasmi','Legge del Riciclo Naturale'],citazione:'"Nessun uomo mortale pu\u00f2 divenire immortale solo morendo; egli deve essersi guadagnato la vita eterna durante la sua esistenza terrena. Vi \u00e8 nell\'uomo qualcosa di incorruttibile ed eterno e qualcosa di corruttibile e temporale."',autore:'Paracelso'},
  {num:3,titolo:"La Formazione del Destino, il Karma e l'Ascesa dell'Uomo",sottotitolo:'Leggi Universali \u2014 3\u00aa Lezione, 4\u00b0 Anno',desc:'La <strong>monade</strong>, scintilla divina, scende attraverso i regni minerale, vegetale, animale e umano, portando in ogni regno una nuova qualit\u00e0: forma, crescita, movimento, autocoscienza. Solo nell\u2019uomo si forma il <strong>sutratma</strong>, il filo di memoria che vita dopo vita porta a manifestazione un progetto animico unico e irripetibile. Il <strong>karma</strong> non \u00e8 una punizione ma una legge di maturazione: karma di carattere, di legame, riflesso, di saturazione, ognuno con la sua via di scioglimento. Al centro di tutto: i tre veleni dell\u2019esistenza (ignoranza, avversione, attaccamento), i tre dojo di trasformazione (famiglia, coppia, lavoro) e la <strong>Fiamma Violetta</strong> di Saint Germain come strumento alchemico di purificazione. La lezione si conclude con una visione cosmica: dall\u2019illuminazione del singolo alla formazione di una stella, fino alla supernova come ultimo sacrificio del logos solare.',temi:['La Monade e i 4 Regni','Il Sutratma: il filo di memoria monadico','L\u2019et\u00e0 dell\u2019Anima: giovane, matura, antica','Karma e formazione del destino','Karma di carattere, di legame, riflesso, di saturazione','I 3 veleni: ignoranza, avversione, attaccamento','I 4 Lipika: i Signori del Karma','Il DNA come libro karmico','Karma maturo e karma in formazione','Il debito di gratitudine','I 3 dojo di trasformazione: famiglia, coppia, lavoro','Legge di Connessione','Legge del Sacrificio e Sacrum Facere','Legge del Comune Trogo-Auto-Egocratico-Cosmico','La Fiamma Violetta di Saint Germain: Solve et Coagula',"L'IO SONO e la coscienza cristica",'Formazione ed Evoluzione di un Cosmo','Le 7 Razze-Radice: dalla Polare alla Paradisiaca','Spiriti Luciferi e Arimanici','L\u2019Asura e l\u2019Anticristo','La Via della Freccia e la Via del Serpente','Legge della messa a fuoco','Legge Akashica','Le Sale di Amenti'],citazione:'"Nel sacrificio l\'ego si inginocchia e l\'anima si eleva. Quello che appare inizialmente come sofferenza si trasforma in un nobile atto di offerta per un bene superiore."',autore:'Corrado Debiasi'},
];

var L5=[
  {num:1,day:11,month:10,year:2026,titolo:"Dall'Alchimia alla Magia",sottotitolo:'Le Leggi Universali \u2014 1\u00aa Lezione, 5\u00b0 Anno',temi:['La Scala di Giacobbe: la Gerarchia Spirituale e i 7 Stadi di Coscienza secondo Gurdjieff','Maghi Bianchi, Maghi Neri e Aspiranti Maghi','La Magia Ermetica','Le Ombre',"Arte dell'Attenzione","La Volont\u00e0",'La Filosofia Ermetica','Ermete Trismegisto: Thod l\'Atlantideo','Come accedere alla Sapienza delle Tavole di Smeraldo','La Triade Ermetica','Frattalit\u00e0'],citazione:'"Dentro di te, O uomo, ho messo la mia Conoscenza. Dentro di te ho messo la Luce. Ascoltami adesso e ricevi la mia Saggezza, che ho portato dai livelli dello Spazio che sono al di Sopra ed Oltre."',autore:'VIII Tavola di Smeraldo \u2014 Ermete Trismegisto'},
  {num:2,day:10,month:1,year:2027,titolo:'I 7 Sommi Principi Ermetici',sottotitolo:'Le Leggi Universali \u2014 2\u00aa Lezione, 5\u00b0 Anno',temi:['I 7 Principi Ermetici \u2014 Il Kybalion','Legge del Mentalismo','Legge di Corrispondenza','Legge della Vibrazione','Legge del Ritmo','Legge della Neutralizzazione','Legge del Genere','Legge di Causalit\u00e0','Legge del Compenso o del Prezzo',"Legge dell'Uso",'Legge di Assunzione o Responsabilit\u00e0','La Trasmutazione Mentale','Legge del Divino Paradosso','Legge del Tutto','Il Tutto e lo Spirito','Il Genere Mentale: Femminino e Mascolino Sacro e Dissacrato','Camera 101: l\'Audacia di affrontare i propri Demoni','Come funziona la Mente nella Magia','La Suggestione Mentale'],citazione:'"Allorch\u00e9 si ode il rumore dei passi del Maestro, si aprono le orecchie di coloro che sono pronti a riceverne l\'Insegnamento. Le labbra della Saggezza sono solo aperte alle orecchie della Comprensione."',autore:'Il Kybalion \u2014 Insegnamenti ermetici'},
  {num:3,day:4,month:4,year:2027,titolo:'La Magia Ermetica attraverso i 5 Elementi',sottotitolo:'Le Leggi Universali \u2014 3\u00aa Lezione, 5\u00b0 Anno',temi:['La Magia del Cuore Puro: Tiphareth, Chokmah','La Preghiera e la Fede','Credenze e Rappresentazioni Mentali','Come nascono le Credenze Limitanti','Come Trasmutare le nostre Convinzioni e Credenze che bloccano il nostro Potenziale','Autosugestione: Subconscio \u2014 Qui ed Ora','Logos-Verbo-Parola-Informazione: DNA',"13 Desideri di Al\u00e0' Ad-D\u012bn",'15 Elementi nella Magia Ermetica','La Legge del Ciclo Vitale','Lapis Philosophorum \u2014 Pietra Filosofale','Dal Credere al Percepire','Legge del Nome'],citazione:'"Se non ti fai simile a Dio, non potrai capire Dio. Innalzati a una grandezza al di l\u00e0 di ogni misura, fatti Eternit\u00e0: allora capirai Dio."',autore:'Ermete Trismegisto, Corpus Hermeticum'},
];

var L6=[
  {num:1,titolo:'Le Tavole Smeraldine e le Ferite Astrali',sottotitolo:'Le Leggi dell\'Universo \u2014 1\u00aa Lezione, 6\u00b0 Anno',temi:['Classificazione della Magia','Legge della Somiglianza e Legge del Contatto','La Fabbricazione della Pietra Filosofale','Filtri Percetivi: i 7 Principi','Le Ferite Astrali','Prima Proposizione Tavole di Smeraldo','Le 3 Sostanze: Mercurio, Zolfo, Sale','Seconda Proposizione Tavole di Smeraldo','Il Caos','Ferite Astrali e Talenti Spirituali',"L'Alchimia delle Ferite Astrali",'Le Ferite Agenti Trasformanti','Via Positiva e Via Negativa','Caos Deterministico',"L'Emozione Maestra di Vita",'Terza Proposizione Tavole di Smeraldo','Raggio di Creazione e Tavola degli Idrogeni','La Nostra Natura di Luce'],citazione:'"Conoscere l\'Essenza divina \u00e8 la destinazione spirituale della nostra Anima, che \u00e8 stata mandata sulla terra dal Creatore dell\'universo."',autore:'Pitagora'},
  {num:2,titolo:'La Formazione delle Ferite Astrali ed il Processo Incarnatorio',sottotitolo:'Le Leggi Universali \u2014 2\u00aa Lezione, 6\u00b0 Anno',temi:['Movimento ed Evitamento','Le 4 Forze Intrinseche','I Plasmi \u2014 OB ed OR','Quarta Proposizione \u2014 Tavole di Smeraldo','Il Telesma \u2014 OD','Memoria, Informazione ed Impregnamento','Processo e Tunnel Incarnatorio','Nascita della Ferita Astrale','Lo Zodiaco e le 12 Costellazioni','I 6 Assi e le 3 Croci',"L'incontro con i Corpi Celesti: la Genesi della Ferita",'Quinta Proposizione \u2014 Tavole di Smeraldo',"L'Acqua degli Ermetisti",'Legge della Misura','Maschere e Ferite'],citazione:'"Di tutto il creato, l\'uomo \u00e8 l\'unico essere duplice: mortale secondo la sua corporeit\u00e0, immortale secondo la sua Essenza."',autore:'Ermete Trismegisto'},
  {num:3,titolo:'Le 7 Chiavi della Realizzazione Interiore: la Magia Archetipica',sottotitolo:'Dalle Ferite Astrali ai Talenti Spirituali \u2014 3\u00aa Lezione, 6\u00b0 Anno',temi:['Sesta Proposizione delle Tavole di Smeraldo','Pentacolo-Adam Kadmon-Gloria','Il Corpo di Dolore','Fatti vs Esperienze','Settima Proposizione delle Tavole di Smeraldo','I Pianeti come Nuclei Concentrici dell\'Io','Ottava Proposizione delle Tavole di Smeraldo','Le 7 Ferite Astrali e le 7 Maschere','Guarire le Ferite con la Consapevolezza','I 7 Talenti Spirituali','Le 7 Chiavi della Realizzazione Interiore','Il Magnete Tetrapolare, la Matrice Astrale e l\'Aura','Gli Archetipi Astrologici','Nona Proposizione delle Tavole di Smeraldo','Sutratma \u2014 Antahkarana \u2014 Attivit\u00e0 Creativa','Decima Proposizione delle Tavole di Smeraldo'],citazione:'"La conoscenza \u00e8 Magia ed \u00e8 la sola Legge. Non abbiate paura del potere dentro di voi poich\u00e9 esso segue la LEGGE, come le stelle nel cielo. Segui ed impara la mia Magia. Sappi che tutta la Forza \u00e8 tua se lo vorrai."',autore:'Toth l\'Atlantideo'},
];

var LESP=[
  {titolo:'Seminario esperienziale \u2014 Gli Specchi Esseni & l\'Enneagramma',sottotitolo:'Masseria Chinunno, Foresta Mercadante',temi:['Guardarsi attraverso i 7 Specchi Esseni','Ritrovarsi attraverso la Geometria dell\'Anima','Gli Specchi Esseni e l\'Enneagramma','Giornata 29: seminario teorico-pratico','Giornata 30: pratica ed esercizi di gruppo in natura','Con la collaborazione di Eleonora Digregorio'],citazione:'"La vita di ogni uomo \u00e8 una via verso s\u00e9 stesso."',autore:'Hermann Hesse'},
  {titolo:'Residenziale in presenza \u2014 Accendi il tuo Fuoco Alchemico',sottotitolo:'Residenziale intensivo',temi:['Esperienza condivisa utile ad uscire dalla propria zona di comfort','Portare la Presenza nel QUI-e-ORA all\'interno della vita quotidiana','Allenamento alla PRESENZA ed al DOMINIO DI SE\'','Esperienze in natura condivise','Convivenza: restare in costante OSSERVAZIONE dei propri meccanismi','Con la collaborazione di Eleonora Digregorio e Paolo Michele Colella'],citazione:'"La vera scoperta di s\u00e9 inizia dove finisce la propria zona di comfort."',autore:'Adam Braun'},
  {titolo:'La Magia dei 4 Elementi e la Quintessenza',sottotitolo:'Seminario Esperienziale in Natura per Aspiranti Maghi',temi:['I 4 Elementi: Fuoco-Aria-Acqua-Terra','Amore e Discordia','Ogni Elemento ha un Messaggio','I 4 Elementi vediamoli singolarmente','La Virt\u00f9 Ritrovata','Quando manca un Elemento?','Spiriti della Natura e la loro Magia: Salamandre, Silfidi, Ondine e Gnomi','Aspetti Magici','Come gestire la Magia dei 4 Elementi nel quotidiano e la Pozione Magica Perfetta'],citazione:'"L\'armonia tra i ritmi interni di una persona e i ritmi esterni della natura \u00e8 il fondamento del proprio senso di identificazione con il cosmo."',autore:'Alexander Lowen'},
  {titolo:'Ricchezza, Abbondanza e Mission \u2014 Le Chiavi della Realizzazione Interiore',sottotitolo:'Masseria Chinunno, Foresta Mercadante',temi:['Abbondanza e Mission: perch\u00e9 e come sono collegate?','Quali sono le Leggi che le regolano?','I simboli archetipici: Urano, Nettuno, Plutone'],citazione:'"L\'Abbondanza non \u00e8 qualcosa che acquisisci, ma \u00e8 qualcosa con cui sintonizzarti."',autore:'Wayne Dyer'},
  {titolo:"Il Tao nell'Alchimia di Coppia",sottotitolo:'Seminario in Natura \u2014 Corso teorico-pratico esperienziale',temi:['La coppia come strumento alchemico per raggiungere il Tao del Sacro Incontro degli Opposti',"L'incontro divino del Maschile e Femminile dentro e fuori di s\u00e9",'Come sublimare il proprio rapporto di coppia o accogliere l\'Anima Gemella','Spazi dedicati a Meditazione, Biodanza, Tantrayoga e Musica Sacra Indiana'],citazione:'"Gli amanti sono specchi tra loro. L\'amore ti rende consapevole del tuo volto originale."',autore:'Osho'},
  {titolo:"Il Viaggio Archetipico dell'Anima attraverso i 22 Arcani Evolutivi",sottotitolo:'Seminario teorico-pratico',temi:['Lavoro su di s\u00e9 attraverso gli Arcani Maggiori, passando per i 22 campi di esperienza','I passi che la nostra Anima compie in ogni vita'],citazione:'"Conosci ci\u00f2 che ti sta davanti, e ci\u00f2 che ti \u00e8 nascosto ti verr\u00e0 rivelato."',autore:'Ges\u00f9 di Nazareth'},
  {titolo:'I 7 Chakra \u2014 Amare S\u00e9 Stessi',sottotitolo:'Masseria Chinunno, Cassano (BA)',temi:['I 7 Chakra','Le Ferite ed Emozioni dei Chakra','La Guarigione dei 7 Chakra',"L'Attivazione dei 7 Portali",'I Diritti dei Chakra','Attivare le Leggi Universali attraverso il Riequilibrio dei 7 Chakra','Imparare ad Amarsi','Le Relazioni Affettive e i 7 Chakra','Attivare il nostro Magnetismo','Esercizi e Meditazioni in Natura'],citazione:'"Nessuna grazia esteriore \u00e8 completa se non \u00e8 compenetrata e vivificata dalla bellezza interiore."',autore:'Victor Hugo'}
];

var L7=[
  {num:1,titolo:'Il Velo di Mem: Iniziazione Sciamanica al Mistero del Passato',sottotitolo:'Magia Ermetica Operativa per la Trasmutazione del Passato \u2014 1\u00aa Lezione, 7\u00b0 Anno',temi:['Introduzione alla Magia Operativa Ermetica','Il Campo di Coscienza Unificato','Magia Ermetica e Sciamanesimo: un Percorso di Trasformazione','Sciamanesimo: Tecniche e Pratiche','Tonal e Nagual: i Tre Mondi del Nagual','Il Tamburo Sciamanico: Risonanza con la Terra e Stato di Coscienza Alterato o Trance Sciamnica','Kronos, Kairos e Aion il Tempo di Dio','Multidimensionalit\u00e0: il Tempo come Spirale e l\'Io come Frattale','Portali Energetici: le Lettere Ebraiche','Riscrittura del Passato Energetico: Guarigione attraverso la Memoria','Il Viaggio Sciamanico: Attraversare il Velo del Tempo'],citazione:'"Conosci il mondo in te stesso. Non cercare mai te stesso nel mondo, perch\u00e9 questo significherebbe proiettare la tua illusione."',autore:'Antico Proverbio Egizio'},
  {num:2,titolo:'Il Respiro di Alef: Iniziazione Sciamanica al Mistero del Presente Vivente',sottotitolo:'Magia Ermetica Operativa per la Trasformazione del Presente \u2014 2\u00aa Lezione, 7\u00b0 Anno',temi:['Il Viaggio Sciamanico di Recupero dei Frammenti di Anima','Alef \u2014 il Portale del Presente',"L'Informazione e il Principio Olografico",'Multiverso e Multidimensionalit\u00e0','La Ruota di Medicina e gli Uomini Medicina','Alfa a \u2014 la Costante di Struttura Fine e la Legge di Manifestazione','La Crisi come Portale','I Guardiani della Soglia: Arconti, Demoni Interiori ed Elementi Collegati','Trasformazione dei Demoni Interiori: Nutrire, Nominare, Reintegrare','Assunzione dell\'Archetipo e Creazione del Golem','Legge dell\'Intenzione Autentica: Ichinen Sanzen','Legge di Coerenza','Codex Cognitivi e Codex Inconsci','Il Lavoro con i Simboli','Archetipi degli Organi e Guarigione Energetica'],citazione:'"Ci\u00f2 che abbiamo occultato in un luogo, l\'abbiamo manifestato in un altro, affinch\u00e9 possa essere compreso dalla vostra saggezza."',autore:'Heinrich Cornelius Agrippa di Nettesheim'},
  {num:3,titolo:'Shin \u2014 La Tripla Fiamma che Traccia il Destino: Il Risveglio della Kundalini e l\u2019Attivazione del Terzo Occhio',sottotitolo:'Magia Ermetica Operativa per la Trasformazione del Futuro \u2014 3\u00aa Lezione, 7\u00b0 Anno',temi:['Creativit\u00e0 come Atto Divino','Shin la Triplice Fiamma e il Codice \u03c0','L\u2019Impulso Creativo, il Desiderio e l\u2019Energia Sessuale','Eros, Centro Sessuale e Magnetismo Bianco','Il Risveglio della Kundalini','Le Energie della Fonte: Fohat, Prana, Kundalini','L\u2019Antahkarana: il Filo della Coscienza','DNA e la Parola Latente','I 12 Strati del DNA','L\u2019Ankh \u2625: la Chiave della Vita','Luz: il Seme Immortale','Legge di Sincronicit\u00e0 e Legge di Unit\u00e0','La Fortuna e il Sincronismo Divino','Teurgia Bianca','La Protezione delle Entit\u00e0 di Luce','Decreti, Mantra e Icaro','Le 22 Lettere Ebraiche e la Ghematria','I Talismani','Focus: la Bacchetta Magica del Mago','Il Proposito: la Chiamata','Il S\u00e9 Futuro','La Struttura 64 e 72','64 Chiavi Genetiche','I 72 Nomi di Dio','Attivazione del Terzo Occhio','Gli Specchi Ermetici Bianchi e Neri'],citazione:'\u201cColui che conosce il fuoco che \u00e8 dentro di lui ascender\u00e0 al fuoco eterno e vivr\u00e0 eternamente in esso. Fuoco, il fuoco interiore, \u00e8 il pi\u00f9 potente di tutte le forze, da esso derivano tutte le cose e penetra tutte le cose della Terra.\u201d',autore:'Thot l\u2019Atlantideo \u2014 Tavola III, La Chiave della Saggezza'}
];

/* ═══════════════════════════════════════════════════
   TRADUZIONI INGLESI DELLE LEZIONI
   Stanno in fondo a questo file e non in un file a parte: Anna Carla manda
   gli aggiornamenti in italiano e chi li riporta deve vedere subito che
   esiste anche una versione inglese da aggiornare. Un secondo file
   resterebbe indietro in silenzio, come e' gia' successo col design system.
   Il ciclo in coda le innesta come campo .en su ogni lezione, quindi i dati
   italiani sopra non vengono toccati: se una traduzione manca, la pagina
   inglese mostra l'italiano invece di rompersi.
   Le citazioni di autori antichi usano la versione inglese consolidata dove
   esiste (Ermete, Vangelo di Tommaso, Seneca, Rumi, Buddha); quelle degli
   autori moderni sono tradotte dall'italiano.
   ═══════════════════════════════════════════════════ */
var L_EN = {
L1: [
 {titolo:'Are we truly free?',
  sottotitolo:'Sleep and Awakening in the School of Consciousness and Alchemy',
  desc:'Gurdjieff describes the human being as a <strong>carriage without a master</strong>: the physical body is the carriage, dragged along without control; the emotions are the horses, impulsive and without direction; the mind is the coachman, often distracted; consciousness is the passenger, asleep, who ought to be giving directions. Without awareness we live in a state of <strong>sleep</strong>: we act mechanically, we react to stimuli by reflex, we identify with masks and roles and lose touch with our authentic essence. As in the <strong>Labyrinth of Knossos</strong>, self-knowledge is the thread of Ariadne that lets us escape our psychological imprisonment. Only the awakening of consciousness can make us free.',
  temi:['The way of Know Thyself — Γνῶθι Σεαυτόν','The prison of the Ego','The School of Awakening: values and aims','Opus Alchemicum — Work on Oneself','Horizontal and Vertical Evolution','The Law of Mechanicalness','A-B-C Influences','Gurdjieff’s Carriage and the House without a master','The Biological Machine','The Quintessence and the Philosopher’s Stone','The Law of Multiplicity, or Fragmentation of the I','The Process of Solve et Coagula','The Falling Asleep of Consciousness','Evolutionary Arcana VII-XI','Rules of Practice for Work on Oneself','The 3 Poisons and the 3 Remedies'],
  citazione:'"There are minds that question, that long for the truth of the heart. If a man reasons and thinks soundly, he must inevitably return to himself."',
  autore:'Georges Ivanovitch Gurdjieff'},

 {titolo:'The Power of Here and Now: freeing yourself from the past, living the present',
  sottotitolo:'The 96 Universal Laws — Lesson 2, Year 1',
  desc:'Who is really in charge of our life? Beneath the surface several layers of the <strong>I</strong> coexist, from outward conditioning to the most authentic core of the Soul, and recognising them is the first step towards choosing instead of reacting. Nietzsche’s <strong>three metamorphoses</strong> offer an archetypal map of this inner transformation: from the weight of duty to rebellion, to pure creation. The alchemical path turns all of this into a practical <strong>Opus</strong> leading to the Philosopher’s Stone: the incarnation of the divine in everyday life, rather than an intellectual conquest.',
  temi:['Hic et Nunc — Kairos and Kronos','The Law of Liberation','Mindfulness and Sati — Attention','Anicca, Dukkha and Anatta','The patterns of the Ego','The Drama and the Power of Here and Now','Pain, Suffering and Self-pity','The Threefold Division of the I','The 3 Metamorphoses, the Overman: Camel-Lion-Child','Philosophical Salt and the Sun — Gold','Higher Centres and Lower Centres','The Alchemical Fire: Focus','The Initiatory Trials','The Law of Acceleration','The Law of Reparation and the Permanent Centre of Gravity','Evolutionary Arcana XII-XIII'],
  citazione:'"Nothing is more dangerous and deadly for the soul than to be endlessly occupied with oneself and one’s own condition, one’s dissatisfaction and solitary weakness."',
  autore:'Hermann Hesse'},

 {titolo:'Beyond Tangible Reality: the Harmony and Perfection of Life. How do we change a reality we do not like?',
  sottotitolo:'The 96 Universal Laws — Lesson 3, Year 1',
  desc:'<strong>Mental Pendulums</strong> jam when we drift away from our inner truth: we stay imprisoned within subliminal beliefs, invisible and polarising, like magnets that stop the pendulum returning to the centre. The behaviour that follows says nothing about us, only about the position we occupy in relation to the pendulum. Only by moving towards the centre does the being reveal itself as a living, authentic presence. The other central theme is the <strong>Lie</strong> as a betrayal of one’s own identity: every lie creates distance not only from others but from one’s own heart, the place of unity where truth and communion are felt.',
  temi:['The Pythagorean Tetractys','The Law of the One','The Law of the Two','The Law of Rhythm','The Law of the Pendulum','Saṅkhāra and Conditioning Mental Formations','The Idea of Self and Mental Pendulums','The Law of Balance','The Law of Action and Reaction','The Law of the Three','The Law of the Boomerang','The Law of Return to the One','The Law of the Cycle','The Circle of Life: the Ouroboros','The Fall from Eden','The Law of Infinite Possibilities: Pi — π — and the Trinity','The Law of Reciprocity: the Golden and Silver Rules','Falsehood and Truth','The Dopamine Reward Cycle','The Mind and the Spiritual Ego','Evolutionary Tarot XIV and XV'],
  citazione:'"Man is the maddest species: he worships an invisible God and destroys a visible Nature."',
  autore:'Hubert Reeves'},

 {titolo:'"The Inner Science of Creation" — Take your life into your own hands',
  sottotitolo:'The 96 Universal Laws — Lesson 4, Year 1',
  desc:'The <strong>Law of Cause and Effect</strong> reveals that nothing is accidental: the cosmos is a hidden order where every small change of course produces enormous differences in destiny. The <strong>Law of the Mirror</strong> shows that on this earth we do not receive by merit but by resonance: what we repress returns to be seen through others, inviting us to look inward rather than outward. <strong>Emotional Alchemy</strong> teaches that unprocessed emotions become poisons that intoxicate body, mind and relationships. Only by passing through feeling with presence can raw energy be transformed into creative force, and life taken into one’s own hands.',
  temi:['Practice of Work on Oneself','The Law of Cause and Effect','Responsibility and Guilt: Stoicism','The Law of Attraction and Resonance','The Law of the Mirror','The Law of Precedence','Emotional Alchemy','Emotions — Feelings and Emotional Intelligence','The Law of Intentional Creation','The Law of Expectation and Doubt','The Creative Process and the Constant of Creation','The Maharishi Effect','The 2 Biological Response Systems: Cannabinoid and Opioid','The Pineal Gland: DMT, Anandamide, Pinealin and Gamma Waves','Evolutionary Arcana The Tower and The Star'],
  citazione:'"Everything you are looking for is already within you. You are already what you are seeking. Do not look outside: what is outside is only a reflection."',
  autore:'Osho'},

 {titolo:'How to overcome blocks and reach your goals in life',
  sottotitolo:'The 96 Universal Laws — Lesson 5, Year 1',
  desc:'Why does every project sooner or later jam? The <strong>Law of Seven (of the Octave)</strong> explains that along the road to a goal there are unavoidable points of stagnation: the first is inward, when the initial energy runs out and doubts surface; the second is outward, when we are almost at the finish and resistance intensifies. <strong>Self-sabotage</strong> and <strong>victimhood</strong> are the natural deviations that switch on when we are not present to ourselves: by placing responsibility outside, we give up the power to act on our own life. Recognising these mechanisms is already the beginning of their dissolution.',
  temi:['The Divine Seed and the Imago Dei: the Mystical Law','The Law of Karma and Dharma','The Noble Eightfold Path','Karmic Tendency, Karmic Loops and Counter-tendency','Karmic Debt and Credit','Positive and Negative Karma','The Law of Here and Now','The Law of Change','Esho Funi: the Principle of Non-Duality','The Laws of Responsibility and Acceptance','The Law of Seven, or of the Octave','Goals to Reach, Additional Shocks and the Final Challenge','Anticipatory Anxiety, Performance Anxiety and Hypersalience','Self-sabotage and Victimhood','Empty Doubt and Germinative Doubt','Spiritual Deviance and Synchronicities','The Law of Abundance','The Law of Non-attachment','The Law of Service','The Law of Impermanence'],
  citazione:'"There is no favourable wind for the sailor who does not know where he is going."',
  autore:'Seneca'},

 {titolo:'How to turn negative emotions into fuel for your own evolution',
  sottotitolo:'Alchemy: Transmuting Lead into Gold — Lesson 6, Year 1',
  desc:'<strong>Emotions</strong> (from the Latin <em>e/ex-movēre</em>) are reactive impulses that rise from the depths and move us outwards. <strong>Feelings</strong> (from the Latin <em>sentire</em>) are inner perceptions, more stable and deeper: true Feeling. Learning to tell them apart is essential if we are not to be at the mercy of automatic reactions. The alchemical path passes through three great phases, <strong>Nigredo</strong>, <strong>Albedo</strong> and <strong>Rubedo</strong>: dissolution, purification and rebirth. The alchemist’s first instrument is the <strong>Alchemical Fire</strong>, born of the friction between inner discomfort and conscious observation: it is the fire that kindles transformation.',
  temi:['Spiral Study and the Initiatory School','The Illusion of the Senses — Mundus Sensibilis','Extracerebral Consciousness — Mundus Imaginabilis','Observer and Witness — Parsifal','Identification and Self-Remembering','Definition and Characterisation','The 4 Minds','Negative Emotions — Riding the Tiger: Self-Mastery','Negative Imagination','Creative Imagination','The Law of Transmutation','The 3 Phases of Lower Alchemy: Nigredo, Albedo, Rubedo','Cauda Pavonis, Citrinitas, Iosis','Rebirth: the Phoenix','The Chrism','Amor Fati','Evolutionary Arcana: The Moon, The Sun, Judgement, The World','Sal-Nitre, Mercurius-Loquens and Sulphur-Ignis'],
  citazione:'"Life begins where fear ends."',
  autore:'Osho'}
],
L2: [
 {titolo:'The Tao: the choice between Good and Evil, and Free Will',
  sottotitolo:'The Universal Laws — Lesson 1, Year 2',
  temi:['The Law of Polarity','Yin and Yang: the Tao and the teaching of Good and Evil','Goodness and Respectability','The Middle Way','The Law of Becoming, or Change','Karma, Destiny and Free Will','The Law of Free Will','The Sacred Triangles','The Law of the Ladder','Transurfing','The Crossroads and Discernment','The Law of the 8, or of Choice'],
  citazione:'"All dualities must be abandoned. Duality as such must be abandoned, because you exist beyond duality."',
  autore:'Osho'},

 {titolo:'The Enneagram, the Sacred Geometry of the Soul and the Path of Personality',
  sottotitolo:'The Universal Laws — Lesson 2, Year 2',
  temi:['Identification with the Personality','Falling asleep and the Fall from Eden','Character as Destiny in the Circle of Samsara','The Law of the 9: the Enneagram as a Path of Deep Knowledge','The Sacred Geometry of the Soul: the Law of Unity, of 3 and of 7','Enneagram: Karma and Dharma','The Journey along the Way of Virtue and the Return Home','Personality and Character','Dominant Passions and Fixations','Instinctual Subtypes and Wings','The Law of the Salmon, or of Counter-tendency','Choices vs Decisions','The Law of Work on Oneself'],
  citazione:'"Destiny and character are two names for the same concept."',
  autore:'Hermann Hesse'},

 {titolo:'Seek and you shall find… The Enneagram as a way back to yourself',
  sottotitolo:'The 96 Universal Laws — Lesson 3, Year 2',
  temi:['The Veil of Maya','Isis and Osiris','The 4 Steps of Initiatory Transmutation','The Inner Child','Divine Fire and Promethean Fire','Enneatype 9-8-1, the Gut Centre','Truth and Charisma','Numerological Archetype Warrior/Rebel (1)','Numerological Archetype Sovereign/Tyrant (8)','Numerological Archetype Liberator/Fallen Angel (9)','The 9 Faces of God'],
  citazione:'"Let him who seeks not cease seeking until he finds; and when he finds he will be troubled, and when he is troubled he will marvel."',
  autore:'Gospel of Thomas'},

 {titolo:'Self-Remembering through the Enneagram',
  sottotitolo:'The 96 Universal Laws — Lesson 4, Year 2',
  temi:['The Law of Compensation','Self-Remembering and Buddhahood','The Mystical Law','The Law of Mystery','Judgement and Discernment','Non-Judgement','Enneatypes of the Emotional Centre (2-3-4)','Numerological Archetype 2 Child/Orphan','Numerological Archetype 3 Jester/Stranger','Numerological Archetype 4 Builder/Prisoner'],
  citazione:'"Keep the Truth locked in your Heart, and let it speak through your Works. Science shall be your strength; Faith your sword."',
  autore:'Hermes Trismegistus'},

 {titolo:'Change — Overcoming resistance through the Enneagram',
  sottotitolo:'The 96 Universal Laws — Lesson 5, Year 2',
  temi:['Penelope’s Web','Self-sabotage and Procrastination','Change and Resistance','Pandora’s Jar and the Law of the Vessel','Enneatypes of the Mental Centre (5-6-7)','Numerological Archetype the Creator/the Wanderer (5)','Numerological Archetype the Guardian Angel/the Martyr (6)','Numerological Archetype the Sovereign/the Solitary (7)','The Conversion of Neurosis','The Holy Ideas','Id, Ego and Super-Ego','The Enneatypes and their Relationship with Others'],
  citazione:'"Whoever looks at himself risks meeting himself. The mirror does not flatter; it shows the face we never show the world."',
  autore:'Carl Gustav Jung'},

 {titolo:'The Law of Love — Self-esteem, Self-love and Mission',
  sottotitolo:'The 96 Universal Laws — Lesson 6, Year 2',
  temi:['The 9 Enneatypes in Love','Self-love: Self-esteem and Acceptance','The 3 Types of Change','Identity: Values and Mission','Vision and Vocation','The Inner Guide','The Pyramid of Logical Levels and of Needs','Plato’s Myth of the Cave','The 3 Forms of Love: Eros, Agape, Philia','Choices of the Head, the Gut and the Heart','Pineal Gland, Eye of Horus and Eye of Ra','The Law of Love and the Opening of the Heart','The 4 Planes of Reality','The Force of Gravity','Krishna’s Maya: the Matrix and Holographic Reality'],
  citazione:'"An act of love is to welcome within ourselves our most wounded and fragile part."',
  autore:'Carl Gustav Jung'}
],
L4: [
 {titolo:'The Ancient Wisdom and the Way that leads to manifesting Divinity',
  sottotitolo:'School of Consciousness and Alchemy — Lesson 1, Year 4',
  desc:'Evolution is not an abstract idea: it is the concrete unfolding of divine life within us. The <strong>monad</strong>, a spark from the supreme triangle, passes through four kingdoms (mineral, vegetable, animal, human) to bring into manifestation what lies latent in it as in a seed. Human beings are the only ones able to do this consciously. The <strong>law of creation</strong> is God becoming flesh; the <strong>law of evolution</strong> is flesh becoming God. Through the <strong>seven bodies</strong> (physical, etheric, astral, mental, causal, buddhic, atmic) the soul evolves: first by mastering the biological machine, then by activating the powers of the soul. Thoughts cultivated with intensity become inner forces in the next life; karmic tendencies repeat themselves unchanged; unsatisfied desires return as compulsions, while those satisfied and painful turn over into shadow.',
  temi:['The Lord’s Prayer','The Way that leads to manifesting Divinity','The Ancient Wisdom and the Creation of Man','The Law of Creation','The Law of Evolution — The Path of the Right Hand','The Law of Analogy','Spirit-Matter, Atoms and Elementals','The Sevenfold Human Nature: the Higher Triad and the Lower Quaternary','The 7 Planes: Physical, Etheric, Astral, Mental, Causal, Buddhic, Atmic','Body, Soul and Spirit','Lilith, Samael, Gamaliel — The Path of the Left Hand','The Metamorphosis of Thoughts between one life and the next','Karmic tendencies and counter-tendencies','Karmic shadows and inverted desires','Suffering and Sacrifice','Sophia and the 5 points of the Ancient Wisdom','The Law of Attraction as a law of the astral body','Emotional impulse vs Instinct'],
  citazione:'"One must seek not to be without sin, but to be a God. He who acts according to the theoretical virtues is a God. But he who acts according to the paradigmatic virtues is the Father of the Gods."',
  autore:'Plotinus'},

 {titolo:'Life after Death, the Afterlife and Reincarnation',
  sottotitolo:'The Universal Laws — Lesson 2, Year 4',
  desc:'What happens to our seven bodies after death? The <strong>mnemonic tableau</strong> shows us the whole life just ended as a karmic mirror, without emotional involvement. The soul then passes through the seven planes of <strong>Kamaloka</strong>, the place of desire: from the hells to the purgatories and on to the earthly paradises, purifying every attachment. At last it enters <strong>Devachan</strong>, the celestial realm, where it meets only the souls it has loved and gathers the fruits of all the good it accomplished in life. Every quality is amplified and turned into a faculty for the life to come. The lesson closes with the moment of <strong>clear vision</strong>: the soul is shown the broad lines of its next incarnation.',
  temi:['Biocentrism','Life after Death and the Afterlife','The Law of Merit','The Law of Correspondence','The 3 Gunas: Tamasic, Rajasic, Sattvic','Kamaloka and Purification: the 7 planes','The Law of the Echo and of Reverberation','The Law of Retribution by analogy and by contrast','Devachan with form and without form: the 7 Heavens','The Transformation of Ability into Faculty','The Law of Sympathy, or of Affinity','The Soul Family','The 4 types of Attachment and karmic destiny','The Evolution of the 4 Kingdoms','Personality and Individualisation','The Law of Measure','The General Law of Reincarnation','The Mnemonic Seal of Previous Lives','The 49 days of the Bardo and Pentecost','Astral larvae and ghosts','The Law of Natural Recycling'],
  citazione:'"No mortal man can become immortal merely by dying; he must have earned eternal life during his earthly existence. There is in man something incorruptible and eternal, and something corruptible and temporal."',
  autore:'Paracelsus'},

 {titolo:'The Shaping of Destiny, Karma and the Ascent of Man',
  sottotitolo:'Universal Laws — Lesson 3, Year 4',
  desc:'The <strong>monad</strong>, a divine spark, descends through the mineral, vegetable, animal and human kingdoms, bringing a new quality to each: form, growth, movement, self-awareness. Only in the human being does the <strong>sutratma</strong> form, the thread of memory that, life after life, brings to manifestation a soul project that is unique and unrepeatable. <strong>Karma</strong> is not a punishment but a law of ripening: karma of character, of bond, reflected karma, karma of saturation, each with its own way of dissolving. At the centre of it all: the three poisons of existence (ignorance, aversion, attachment), the three dojos of transformation (family, couple, work) and Saint Germain’s <strong>Violet Flame</strong> as an alchemical instrument of purification. The lesson closes with a cosmic vision: from the enlightenment of one person to the formation of a star, and on to the supernova as the last sacrifice of the solar logos.',
  temi:['The Monad and the 4 Kingdoms','The Sutratma: the monadic thread of memory','The age of the Soul: young, mature, ancient','Karma and the shaping of destiny','Karma of character, of bond, reflected, of saturation','The 3 poisons: ignorance, aversion, attachment','The 4 Lipika: the Lords of Karma','DNA as a karmic book','Ripe karma and karma in formation','The debt of gratitude','The 3 dojos of transformation: family, couple, work','The Law of Connection','The Law of Sacrifice and Sacrum Facere','The Law of the Common Trogo-Auto-Egocratic-Cosmic Process','Saint Germain’s Violet Flame: Solve et Coagula','The I AM and Christ consciousness','The Formation and Evolution of a Cosmos','The 7 Root Races: from the Polarian to the Paradisiacal','Luciferic and Ahrimanic Spirits','The Asura and the Antichrist','The Way of the Arrow and the Way of the Serpent','The Law of Focusing','The Akashic Law','The Halls of Amenti'],
  citazione:'"In sacrifice the ego kneels and the soul rises. What at first appears as suffering is transformed into a noble act of offering for a higher good."',
  autore:'Corrado Debiasi'}
],
L3: [
 {titolo:'The Tree of Life and the Ascent back to Eden',
  sottotitolo:'The Universal Laws — Lesson 1, Year 3',
  temi:['The Fall and the Ascent back to Eden','Adam Kadmon','The Tree of Life and the Immortal Fruits','The Law of Magic','The Law of Unlatching, or Activation','The Law of the 10','The Principle of the Tithe and the Law of Communicating Vessels','The Akashic Records','Emanation and Conversion of Light','The Sephirotic and Qliphotic Tree','The Meaning of the Sephiroth','The Law of Potential Difference','Binary and Quantum Code: Free Will'],
  citazione:'"The Tree of Life sinks its roots in your own heart."',
  autore:'Jalal ad-Din Rumi'},

 {titolo:'Creation through Sacred Geometry',
  sottotitolo:'The Universal Laws — Lesson 2, Year 3',
  temi:['The importance of Right Thinking','From the Seed to the Tree of Life','The Flower of Life — The Fruit of Life — Metatron’s Cube','The Merkaba and Wormholes','The Vesica Piscis and the Sacred Feminine','Daily Bread: Ask and it shall be given you','The 3 Pillars and the 3 Triads','The 22 Arcane Paths','The Law of the 13, or of Self-Remembering','The Memory of Water','The Golden Spiral and Phidias’ Constant Φ (PHI)','Christ, or Crystal, Consciousness','Personal Power and the Growth of the Level of Consciousness','The 10 Dimensions','Natural Law and the Law of the Higher, or Eternal, Will','Temperance and Work on Oneself'],
  citazione:'"If we could see the miracle of a single flower, our whole life would change."',
  autore:'Buddha'},

 {titolo:'The Magician, Magic and the Words of Power',
  sottotitolo:'The Universal Laws — Lesson 3, Year 3',
  temi:['The 3 States of Water and the Tree of Life','The Creative Word: Cymatics, Sound becoming Form','Om-Aum, the Sound of Creation','Adam and the Power of Naming Things','Form and Function','The Tower of Babel and the Lost Word','The Word of Power, or Magic Word, and the Power of Words','Sign Words -Rhombus- and Single Words -Triangle-','Esotericism and Exotericism: the Religious, the Mystic, the Magician','Natural Magic and Hermetic Magic','The Law of Compensation','The Law of Magical Exchange, Sacrifices and the Magi','The Law of Focus, the Magic Wand','Egregores, or Thought-Forms','Subpersonalities','The Law of Connection','Inner Attitude — the State of Mind','The Observer Effect','Thought and the Magical Gaze'],
  citazione:'"Are there only facts? I would say: no, facts is precisely what there is not, only interpretations."',
  autore:'Friedrich Nietzsche'},

 {titolo:'Reaching Da’at, the Hidden Sephira: unifying Knowledge and the Divine Power concealed in DNA',
  sottotitolo:'The Laws of the Universe — Lesson 4, Year 3',
  temi:['Ho’oponopono and Hermetic Magic','The Family Theatre','The Solar Way of Consciousness, or Way of the Heart','Rising through Tiphareth-Geburah-Chesed','The importance of Right Communication','The Law of the 6, or Law of the Reunion of Opposites, or of Choice','The Law of Liberation','The Star of David — the Seal of Solomon','The Hexagon and the Law of Efficiency','The Law of Determination','The Courage and Strength of the Lion','Service and Agni Yoga','Da’at, the Hidden Sephira — Akasha','The Abyss and the Sibyl’s Cave','Silence','The Quantum Vacuum and Zero-Point Energy','The Miracle','The Law of Reversal — The Law of the Gift','The Divine Logos concealed in DNA-GNA'],
  citazione:'"The two most important days in your life are the day you are born and the day you find out why."',
  autore:'Mark Twain'},

 {titolo:'Shamballa, the Kingdom of Light: the 7 Rays and the 7 Initiations for the return to the Father’s House',
  sottotitolo:'The Universal Laws — Lesson 5, Year 3',
  temi:['How to Return to the One','The 7 Rays','The 3 Veils that Lead to Truth','The Initiatory Way','The 7 Initiations','The Ascended Masters and Shamballa','The Law of Necessity','The Law of Free Will','The Law of Divine Providence','Pythagoras’ Theorem','The Law of Forgiveness','The 7 Petitions of the Lord’s Prayer — 7 Deadly Sins — 7 Gifts of the Holy Spirit','Magic: the Path of the Right Hand and of the Left Hand','The Initiatory Life of Jesus and His Mission: the Christ'],
  citazione:'"You are not separate from the whole. You are one with the sun, the earth, the air. You do not have a life. You are life."',
  autore:'Eckhart Tolle'},

 {titolo:'Compassion — Transcending Duality, beyond the Dream of Consciousness',
  sottotitolo:'The Universal Laws — Lesson 6, Year 3',
  temi:['The Importance of the Flesh, Malkuth','Discernment','The Law of Personal Power','The Way of the Arrow and the Way of the Serpent','The Probationary Path and the Path Proper','Anxiety-Anguish and Right Detachment in Zen','The Law of Focus','The Cosmic Egg and the Rebis','The Dream of Consciousness and the Matrix','I Am the Supreme: Being in Congruence with the Higher Nature','Self-Remembering and the Silent Witness','The I Am and Saint Germain’s Violet Flame','True Freedom','Transcending the Duality of the Pendulum','Compassion, Loving Kindness and Gratitude','Taoist and Gospel Paradoxes, the Way of Wisdom'],
  citazione:'"Whoever perceives at once his own shadow and his own light sees himself from two sides and so reaches the centre."',
  autore:'C.G. Jung'}
],

L5: [
 {titolo:'From Alchemy to Magic',
  sottotitolo:'The Universal Laws — Lesson 1, Year 5',
  temi:['Jacob’s Ladder: the Spiritual Hierarchy and Gurdjieff’s 7 States of Consciousness','White Magicians, Black Magicians and Aspiring Magicians','Hermetic Magic','The Shadows','The Art of Attention','The Will','Hermetic Philosophy','Hermes Trismegistus: Thoth the Atlantean','How to reach the Wisdom of the Emerald Tablets','The Hermetic Triad','Fractality'],
  citazione:'"Within thee, O man, I have placed my Knowledge. Within thee I have placed my Light. Hear me now and receive my Wisdom, which I have brought from the planes of Space that are Above and Beyond."',
  autore:'Emerald Tablet VIII — Hermes Trismegistus'},

 {titolo:'The 7 Great Hermetic Principles',
  sottotitolo:'The Universal Laws — Lesson 2, Year 5',
  temi:['The 7 Hermetic Principles — The Kybalion','The Law of Mentalism','The Law of Correspondence','The Law of Vibration','The Law of Rhythm','The Law of Neutralisation','The Law of Gender','The Law of Causality','The Law of Compensation, or of the Price','The Law of Use','The Law of Assumption, or Responsibility','Mental Transmutation','The Law of the Divine Paradox','The Law of the All','The All and the Spirit','Mental Gender: the Sacred and Desecrated Feminine and Masculine','Room 101: the Daring to Face One’s Own Demons','How the Mind Works in Magic','Mental Suggestion'],
  citazione:'"When the ears of the pupil are ready to hear, then cometh the lips to fill them with wisdom. The lips of Wisdom are closed, except to the ears of Understanding."',
  autore:'The Kybalion — Hermetic Teachings'},

 {titolo:'Hermetic Magic through the 5 Elements',
  sottotitolo:'The Universal Laws — Lesson 3, Year 5',
  temi:['The Magic of the Pure Heart: Tiphareth, Chokmah','Prayer and Faith','Beliefs and Mental Representations','How Limiting Beliefs are Born','How to Transmute the Convictions and Beliefs that Block our Potential','Autosuggestion: the Subconscious — Here and Now','Logos-Word-Speech-Information: DNA','The 13 Wishes of Alā’ ad-Dīn','The 15 Elements in Hermetic Magic','The Law of the Life Cycle','Lapis Philosophorum — the Philosopher’s Stone','From Believing to Perceiving','The Law of the Name'],
  citazione:'"Unless you make yourself equal to God, you cannot understand God. Grow to a greatness beyond all measure, make yourself Eternity: then you will understand God."',
  autore:'Hermes Trismegistus, Corpus Hermeticum'}
],

L6: [
 {titolo:'The Emerald Tablets and the Astral Wounds',
  sottotitolo:'The Laws of the Universe — Lesson 1, Year 6',
  temi:['A Classification of Magic','The Law of Similarity and the Law of Contact','The Making of the Philosopher’s Stone','Perceptual Filters: the 7 Principles','The Astral Wounds','First Proposition of the Emerald Tablets','The 3 Substances: Mercury, Sulphur, Salt','Second Proposition of the Emerald Tablets','Chaos','Astral Wounds and Spiritual Talents','The Alchemy of the Astral Wounds','Wounds as Transforming Agents','The Positive Way and the Negative Way','Deterministic Chaos','Emotion as a Teacher of Life','Third Proposition of the Emerald Tablets','The Ray of Creation and the Table of Hydrogens','Our Nature of Light'],
  citazione:'"To know the divine Essence is the spiritual destination of our Soul, which was sent to earth by the Creator of the universe."',
  autore:'Pythagoras'},

 {titolo:'The Formation of the Astral Wounds and the Process of Incarnation',
  sottotitolo:'The Universal Laws — Lesson 2, Year 6',
  temi:['Movement and Avoidance','The 4 Intrinsic Forces','The Plasmas — OB and OR','Fourth Proposition — Emerald Tablets','The Telesma — OD','Memory, Information and Impregnation','The Process and Tunnel of Incarnation','The Birth of the Astral Wound','The Zodiac and the 12 Constellations','The 6 Axes and the 3 Crosses','The Encounter with the Celestial Bodies: the Genesis of the Wound','Fifth Proposition — Emerald Tablets','The Water of the Hermetists','The Law of Measure','Masks and Wounds'],
  citazione:'"Of all creation, man is the only twofold being: mortal in his body, immortal in his Essence."',
  autore:'Hermes Trismegistus'},

 {titolo:'The 7 Keys of Inner Realisation: Archetypal Magic',
  sottotitolo:'From the Astral Wounds to the Spiritual Talents — Lesson 3, Year 6',
  temi:['Sixth Proposition of the Emerald Tablets','Pentacle-Adam Kadmon-Glory','The Pain Body','Facts vs Experiences','Seventh Proposition of the Emerald Tablets','The Planets as Concentric Nuclei of the I','Eighth Proposition of the Emerald Tablets','The 7 Astral Wounds and the 7 Masks','Healing the Wounds with Awareness','The 7 Spiritual Talents','The 7 Keys of Inner Realisation','The Tetrapolar Magnet, the Astral Matrix and the Aura','The Astrological Archetypes','Ninth Proposition of the Emerald Tablets','Sutratma — Antahkarana — Creative Activity','Tenth Proposition of the Emerald Tablets'],
  citazione:'"Knowledge is Magic and is the only Law. Fear not the power within thee, for it follows the LAW, as do the stars in the sky. Follow and learn my Magic. Know that all Force is thine if thou wilt it."',
  autore:'Thoth the Atlantean'}
],

L7: [
 {titolo:'The Veil of Mem: Shamanic Initiation into the Mystery of the Past',
  sottotitolo:'Operative Hermetic Magic for the Transmutation of the Past — Lesson 1, Year 7',
  temi:['Introduction to Operative Hermetic Magic','The Unified Field of Consciousness','Hermetic Magic and Shamanism: a Path of Transformation','Shamanism: Techniques and Practices','Tonal and Nagual: the Three Worlds of the Nagual','The Shamanic Drum: Resonance with the Earth and the Altered State, or Shamanic Trance','Kronos, Kairos and Aion, the Time of God','Multidimensionality: Time as a Spiral and the I as a Fractal','Energy Portals: the Hebrew Letters','Rewriting the Energetic Past: Healing through Memory','The Shamanic Journey: Crossing the Veil of Time'],
  citazione:'"Know the world in yourself. Never look for yourself in the world, for this would be to project your illusion."',
  autore:'Ancient Egyptian Proverb'},

 {titolo:'The Breath of Aleph: Shamanic Initiation into the Mystery of the Living Present',
  sottotitolo:'Operative Hermetic Magic for the Transformation of the Present — Lesson 2, Year 7',
  temi:['The Shamanic Journey to Recover Soul Fragments','Aleph — the Portal of the Present','Information and the Holographic Principle','Multiverse and Multidimensionality','The Medicine Wheel and the Medicine People','Alpha a — the Fine-Structure Constant and the Law of Manifestation','Crisis as a Portal','The Guardians of the Threshold: Archons, Inner Demons and Related Elements','Transforming the Inner Demons: Feeding, Naming, Reintegrating','Assuming the Archetype and Creating the Golem','The Law of Authentic Intention: Ichinen Sanzen','The Law of Coherence','Cognitive Codices and Unconscious Codices','Working with Symbols','Archetypes of the Organs and Energetic Healing'],
  citazione:'"What we have concealed in one place, we have revealed in another, that it may be understood by your wisdom."',
  autore:'Heinrich Cornelius Agrippa von Nettesheim'},

 {titolo:'Shin — The Triple Flame that Traces Destiny: the Awakening of Kundalini and the Activation of the Third Eye',
  sottotitolo:'Operative Hermetic Magic for the Transformation of the Future — Lesson 3, Year 7',
  temi:['Creativity as a Divine Act','Shin, the Triple Flame, and the π Code','The Creative Impulse, Desire and Sexual Energy','Eros, the Sexual Centre and White Magnetism','The Awakening of Kundalini','The Energies of the Source: Fohat, Prana, Kundalini','The Antahkarana: the Thread of Consciousness','DNA and the Latent Word','The 12 Layers of DNA','The Ankh ☥: the Key of Life','Luz: the Immortal Seed','The Law of Synchronicity and the Law of Unity','Fortune and Divine Synchronism','White Theurgy','The Protection of the Beings of Light','Decrees, Mantras and Icaros','The 22 Hebrew Letters and Gematria','Talismans','Focus: the Magician’s Wand','Purpose: the Calling','The Future Self','The Structure of 64 and 72','The 64 Gene Keys','The 72 Names of God','Activation of the Third Eye','The White and Black Hermetic Mirrors'],
  citazione:'"He who knows the fire that is within himself shall ascend unto the eternal fire and dwell in it eternally. Fire, the inner fire, is the mightiest of all forces, for all things come from it and it penetrates all things of Earth."',
  autore:'Thoth the Atlantean — Tablet III, The Key of Wisdom'}
],

LESP: [
 {titolo:'Experiential seminar — The Essene Mirrors & the Enneagram',
  sottotitolo:'Masseria Chinunno, Foresta Mercadante',
  temi:['Seeing yourself through the 7 Essene Mirrors','Finding yourself again through the Geometry of the Soul','The Essene Mirrors and the Enneagram','Day 29: theory and practice seminar','Day 30: group practice and exercises in nature','In collaboration with Eleonora Digregorio'],
  citazione:'"Every man’s life is a road towards himself."',
  autore:'Hermann Hesse'},

 {titolo:'Residential retreat — Kindle your Alchemical Fire',
  sottotitolo:'Intensive residential',
  temi:['A shared experience for stepping out of your comfort zone','Bringing Presence into the HERE-and-NOW of everyday life','Training in PRESENCE and SELF-MASTERY','Shared experiences in nature','Living together: staying in constant OBSERVATION of your own mechanisms','In collaboration with Eleonora Digregorio and Paolo Michele Colella'],
  citazione:'"True self-discovery begins where your comfort zone ends."',
  autore:'Adam Braun'},

 {titolo:'The Magic of the 4 Elements and the Quintessence',
  sottotitolo:'Experiential seminar in nature for Aspiring Magicians',
  temi:['The 4 Elements: Fire-Air-Water-Earth','Love and Strife','Every Element carries a Message','The 4 Elements, one by one','Virtue Regained','What happens when an Element is missing?','Nature Spirits and their Magic: Salamanders, Sylphs, Undines and Gnomes','Magical Aspects','Handling the Magic of the 4 Elements in daily life, and the Perfect Magic Potion'],
  citazione:'"The harmony between a person’s inner rhythms and the outer rhythms of nature is the foundation of one’s sense of identification with the cosmos."',
  autore:'Alexander Lowen'},

 {titolo:'Wealth, Abundance and Mission — The Keys of Inner Realisation',
  sottotitolo:'Masseria Chinunno, Foresta Mercadante',
  temi:['Abundance and Mission: why and how are they connected?','Which Laws govern them?','The archetypal symbols: Uranus, Neptune, Pluto'],
  citazione:'"Abundance is not something you acquire. It is something you tune in to."',
  autore:'Wayne Dyer'},

 {titolo:'The Tao in the Alchemy of the Couple',
  sottotitolo:'Seminar in nature — experiential course, theory and practice',
  temi:['The couple as an alchemical instrument for reaching the Tao of the Sacred Meeting of Opposites','The divine meeting of Masculine and Feminine within and without','How to sublimate your relationship, or welcome your Soul Mate','Sessions of Meditation, Biodanza, Tantra Yoga and Indian Sacred Music'],
  citazione:'"Lovers are mirrors to each other. Love makes you aware of your original face."',
  autore:'Osho'},

 {titolo:'The Archetypal Journey of the Soul through the 22 Evolutionary Arcana',
  sottotitolo:'Seminar, theory and practice',
  temi:['Work on oneself through the Major Arcana, across the 22 fields of experience','The steps our Soul takes in every life'],
  citazione:'"Know what is before your face, and what is hidden from you will be revealed to you."',
  autore:'Jesus of Nazareth'},

 {titolo:'The 7 Chakras — Loving Yourself',
  sottotitolo:'Masseria Chinunno, Cassano (BA)',
  temi:['The 7 Chakras','The Wounds and Emotions of the Chakras','Healing the 7 Chakras','Activating the 7 Portals','The Rights of the Chakras','Activating the Universal Laws by rebalancing the 7 Chakras','Learning to love yourself','Relationships and the 7 Chakras','Activating our Magnetism','Exercises and Meditations in Nature'],
  citazione:'"No outward grace is complete unless it is interpenetrated and quickened by inner beauty."',
  autore:'Victor Hugo'}
]
};

/* Innesto: ogni traduzione diventa il campo .en della lezione corrispondente,
   per posizione nell'array. I dati italiani sopra non vengono toccati, e una
   lezione senza traduzione mostra l'italiano invece di rompere la pagina. */
(function(){
  var mappa = {L1:L1, L2:L2, L3:L3, L4:L4, L5:L5, L6:L6, L7:L7, LESP:LESP};
  Object.keys(L_EN).forEach(function(k){
    if(!mappa[k]) return;
    L_EN[k].forEach(function(t,i){ if(mappa[k][i]) mappa[k][i].en = t; });
  });
})();
