/* LA RESPONSABILITÀ — data.js (pooled from 5 books) */
(function(){
"use strict";
window.GAME_DATA = {
  id: "resp",
  modes: ["servo","dentro","quiz","memoria"],
  rings: [
    {key:"servizio",color:"#1a1326",ring:"#3a2f52",label:{it:"Servizio",en:"Service"}},
    {key:"preghiera",color:"#10212a",ring:"#2f5d6b",label:{it:"Preghiera",en:"Prayer"}},
    {key:"responsabilita",color:"#2a1410",ring:"#7c3a2a",label:{it:"Responsabilità",en:"Responsibility"}},
    {key:"potere",color:"#3a2c10",ring:"#c9973a",label:{it:"Potere",en:"Power"}}
  ],
  modeDefs: {
    servo: { type:"classify", roman:"I", glyph:"♔", count:10, optionKeys:[0,1],
      items: [
        {item:{it:"Incolpare lo Stato, la società o la sfortuna per i propri fallimenti",en:"Blaming the State, society or bad luck for one's failures"},belongs:0,note:{it:"«Non trovare giustificazioni alla tua povertà in un mondo esterno che tu stesso stai plasmando.»",en:"'Don't find justifications for your poverty in an outside world you yourself are shaping.'"}},
        {item:{it:"Sentire che tutto ciò che accade lo si è attirato dall'interno",en:"Feeling that everything that happens has been attracted from within"},belongs:1,note:{it:"«Chi è divenuto un re nell'anima, crea intorno a sé il proprio regno.»",en:"'He who has become a king in the soul creates his own kingdom around him.'"}},
        {item:{it:"Vivere senza uno scopo, in attesa della pensione",en:"Living without a purpose, waiting for retirement"},belongs:0,note:{it:"«Non sei povero perché hai pochi soldi in banca, ma perché non hai uno scopo.»",en:"'You're not poor because you have little money in the bank, but because you have no purpose.'"}},
        {item:{it:"Avere una visione e diventare magnetici, attirando collaboratori",en:"Having a vision and becoming magnetic, attracting collaborators"},belongs:1,note:{it:"«Chi ha un'idea, chi ha una visione, non dipende, ma crea. Chi ha uno scopo, diventa per questo solo fatto MAGNETICO.»",en:"'He who has an idea, who has a vision, does not depend: he creates. He who has a purpose becomes, by that fact alone, MAGNETIC.'"}},
        {item:{it:"Accusare il Sistema: gli stai assegnando i poteri di un Dio",en:"Blaming the System: you are assigning it the powers of a God"},belongs:0,note:{it:"«Nell'accusare il Sistema del tuo fallimento lo stai idolatrando, gli stai assegnando i poteri di un Dio, ti inginocchi ai suoi piedi.»",en:"'In blaming the System for your failure you are idolising it, assigning it the powers of a God, kneeling at its feet.'"}},
        {item:{it:"«Divieni Re e un regno ti sarà dato»: la regalità dell'essere precede il regno",en:"'Become King and a kingdom shall be given': regality of being precedes the kingdom"},belongs:1,note:{it:"La regalità interiore precede, non segue, l'attribuzione di un regno.",en:"Inner regality precedes, not follows, the attribution of a kingdom."}},
        {item:{it:"La lamentela come preghiera quotidiana rivolta al Sistema",en:"Complaint as a daily prayer addressed to the System"},belongs:0,note:{it:"«Nel lamentarti lo stai pregando come si prega un idolo.»",en:"'In complaining you are praying to it like an idol.'"}},
        {item:{it:"Resistere al desiderio di approvazione: accumulare Forza e Magnetismo",en:"Resisting the desire for approval: accumulating Force and Magnetism"},belongs:1,note:{it:"«Ciò che non viene espulso diventa come una calamita che attira l'attenzione dall'esterno.»",en:"'What is not expelled becomes like a magnet that attracts attention from outside.'"}},
        {item:{it:"Giudicare gli altri e poi avere paura del loro giudizio",en:"Judging others and then fearing their judgment"},belongs:0,note:{it:"«Il timido sembra una vittima invece è un carnefice, cioè qualcuno che giudica il mondo e, come conseguenza, ha paura di essere giudicato dal mondo.»",en:"'The shy person seems a victim but is a perpetrator: someone who judges the world and, as a consequence, is afraid of being judged by it.'"}},
        {item:{it:"Il massimo della sottomissione all'Altissimo = massimo del Potere",en:"The utmost submission to the Most High = utmost Power"},belongs:1,note:{it:"«Abbassandoci ci innalziamo, umiliandoci ci eleviamo.»",en:"'By lowering ourselves we rise, by humbling ourselves we elevate.'"}},
        {item:{it:"Pensare di essere schiavi perché qualcuno ci domina",en:"Thinking we are slaves because someone dominates us"},belongs:0,note:{it:"«Non sei uno schiavo perché qualcuno ti domina, ma qualcuno ti domina perché sei uno schiavo.»",en:"'You are not a slave because someone dominates you; someone dominates you because you are a slave.'"}},
        {item:{it:"Inseguire un SOGNO più grande della paura di morire di fame",en:"Pursuing a DREAM greater than the fear of starving"},belongs:1,note:{it:"«Quando il sogno è più grande della paura di morire di fame, allora il guerriero si butta nella vita, rischia… e se il suo ardore è autentico la vita lo premia… sempre.»",en:"'When the dream is greater than the fear of starving, the warrior throws himself into life, takes risks… and if his ardour is genuine, life rewards him… always.'"}},
        {item:{it:"Chiedersi al mattino: «Quali parti di me emergeranno oggi in ufficio?»",en:"Asking in the morning: 'Which parts of me will emerge at the office today?'"},belongs:1,note:{it:"Colleghi e clienti sono frammenti del suo inconscio che emergono.",en:"Colleagues and clients are fragments of his unconscious emerging."}},
        {item:{it:"Creare il proprio lavoro invece di chiederlo",en:"Creating one's own work instead of asking for it"},belongs:1,note:{it:"«Il monaco guerriero non chiede il lavoro... lo crea!»",en:"'The warrior monk doesn't ask for work... he creates it!'"}},
        {item:{it:"Buttarsi in un progetto tenendo pronta la ritirata «nel caso non andasse bene»",en:"Launching a project while keeping a retreat ready 'in case it goes badly'"},belongs:0,note:{it:"«Come può vincere il guerriero che prepara già la ritirata?»",en:"'How can a warrior who is already preparing his retreat win?'"}},
        {item:{it:"Delegare a un maestro la responsabilità della propria felicità",en:"Delegating responsibility for one's happiness to a master"},belongs:0,note:{it:"È più comodo: se falliamo, avremo qualcuno da cui andare a lamentarci.",en:"It's more comfortable: if we fail, we'll have someone to complain to."}},
        {item:{it:"Non esprimere all'esterno un'emozione negativa, senza reprimerla",en:"Not expressing a negative emotion outwardly, without repressing it"},belongs:1,note:{it:"«Ciò fa sì che si accumuli energia all'interno.»",en:"'This allows energy to accumulate within.'"}}
      ]
    },
    dentro: { type:"classify", roman:"II", glyph:"◇", count:10, optionKeys:[0,1],
      items: [
        {item:{it:"«Non sono ricco perché la società è ingiusta»",en:"'I'm not rich because society is unjust'"},belongs:0,note:{it:"«Il mondo è un tuo riflesso. […] Non trovare giustificazioni alla tua povertà in un mondo esterno che tu stesso stai plasmando a ogni istante.»",en:"'The world is your reflection. […] Don't find justifications for your poverty in an outside world you yourself are shaping at every instant.'"}},
        {item:{it:"«Faccio quel lavoro perché dentro di me sono ancora uno schiavo»",en:"'I do that job because inside myself I'm still a slave'"},belongs:1,note:{it:"«Non sei uno schiavo perché fai quel lavoro, ma fai quel lavoro perché dentro di te sei uno schiavo.»",en:"'You are not a slave because you do that job; you do that job because inside you are a slave.'"}},
        {item:{it:"Sul treno, una signora al telefono mi irrita: è colpa sua",en:"On the train, a lady on the phone irritates me: it's her fault"},belongs:0,note:{it:"«Era la mia irritazione, quella che mi portavo dentro da sempre, a creare e alimentare quell'episodio… e non viceversa.»",en:"'It was my irritation, the one I had always carried inside me, that created and fed that episode… and not the reverse.'"}},
        {item:{it:"Comprendo che la mia aggressività repressa ha attirato la scena",en:"I understand that my repressed aggression attracted the scene"},belongs:1,note:{it:"«Le emozioni presenti nel tuo inconscio creano la scena e poi tu reagisci alla scena provando coscientemente l'emozione negativa.»",en:"'The emotions present in your unconscious create the scene, and then you react to the scene by consciously feeling the negative emotion.'"}},
        {item:{it:"Sperare che le restrizioni diminuiscano per sentirsi finalmente liberi",en:"Hoping restrictions decrease in order to finally feel free"},belongs:0,note:{it:"«Nessuno può farmi sentire più libero di quanto io non sia già adesso.»",en:"'No one can make me feel freer than I already am now.'"}},
        {item:{it:"Utilizzare la tensione sociale come occasione per approfondire il lavoro su di sé",en:"Using social tension as an occasion to deepen the work on oneself"},belongs:1,note:{it:"«Tempi favorevoli per chi vuole svegliarsi»: la crisi è il momento migliore.",en:"'Favourable times for those who want to awaken': crisis is the best moment."}},
        {item:{it:"Qualcuno ti dona denaro quando sei in povertà: dormi ancora un po'",en:"Someone donates money when you're poor: sleep a little longer"},belongs:0,note:{it:"Victoria Ignis: «Spesso è solo un sedativo, qualcosa che ti consente di dormire ancora per un po' di tempo.»",en:"Victoria Ignis: 'Often just a sedative, something that lets you sleep a while longer.'"}},
        {item:{it:"Il maestro ti impone di dare il 10% del tuo stipendio da 500 euro in beneficenza",en:"The master forces you to give 10% of your €500 salary to charity"},belongs:1,note:{it:"«Questo è Aiuto.» Fa contorcere nel dolore, ma scioglie i blocchi.",en:"'This is Help.' It makes you writhe in pain, but dissolves the blocks."}},
        {item:{it:"«La colpa della mia situazione è dei banchieri e del Governo Occulto»",en:"'My situation is the fault of bankers and the Hidden Government'"},belongs:0,note:{it:"Si combattono le proprie ombre credendo che esistano indipendentemente da noi.",en:"One fights one's own shadows believing they exist independently of us."}},
        {item:{it:"«Mi sono licenziato io: ho usato il mondo per far emergere queste emozioni»",en:"'I fired myself: I used the world to bring up these emotions'"},belongs:1,note:{it:"«Vi ho appena dato una chiave magica, usatela in ogni circostanza.»",en:"'I have just given you a magic key, use it in every circumstance.'"}},
        {item:{it:"Riconoscere nel partner che ci tradisce un riflesso del tradimento che abbiamo dentro",en:"Recognising in a cheating partner a reflection of the betrayal we carry inside"},belongs:1,note:{it:"Un RIFLESSO rappresenta un condizionamento emotivo che vuole emergere alla coscienza.",en:"A REFLECTION represents an emotional conditioning that wants to surface into consciousness."}},
        {item:{it:"Chiedersi se ci irrita chi ha tanti soldi perché vorremmo essere come lui",en:"Asking whether rich people irritate us because we'd like to be like them"},belongs:1,note:{it:"Legge dello Specchio: ci dà fastidio ciò che vorremmo essere.",en:"Law of the Mirror: we're annoyed by what we'd like to be."}},
        {item:{it:"Pretendere pace dal mondo restando in conflitto dentro di sé",en:"Demanding peace from the world while staying in conflict within"},belongs:0,note:{it:"«Un uomo in conflitto all'interno di sé, alimenta il conflitto nel mondo.»",en:"'A man in conflict within himself feeds conflict in the world.'"}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"Responsabilità e ricchezza sono…",en:"Responsibility and wealth are…"},options:{it:["Sempre commisurate l'una all'altra","Completamente indipendenti","Inversamente proporzionali","Riservate a pochi"],en:["Always commensurate with each other","Completely independent","Inversely proportional","Reserved for a few"]},correct:0,note:{it:"«Solo chi riesce a portare sulle sue spalle un ben definito grado di responsabilità, ottiene un grado corrispondente di ricchezza.»",en:"'Only he who can carry on his shoulders a well-defined degree of responsibility obtains a corresponding degree of wealth.'"}},
        {q:{it:"Vincere alla lotteria senza maturità interiore è paragonato a…",en:"Winning the lottery without inner maturity is compared to…"},options:{it:["Mettere le dita bagnate nella presa di corrente","Trovare un tesoro","Un premio meritato","Piantare un seme"],en:["Putting wet fingers into an electrical socket","Finding a treasure","A deserved prize","Planting a seed"]},correct:0,note:{it:"«Il tuo sistema nervoso salta»: il voltaggio della ricchezza è troppo elevato.",en:"'Your nervous system blows': the voltage of wealth is too high."}},
        {q:{it:"«Desiderare ciò che accade» significa…",en:"'Desiring what happens' means…"},options:{it:["Sentire che sei tu a far accadere tutto e quindi lo vuoi","Rassegnarsi passivamente","Non avere più desideri","Reprimere la volontà"],en:["Feeling that you make everything happen and therefore want it","Passively resigning","Having no more desires","Repressing the will"]},correct:0,note:{it:"Quando REALIZZI che tutto è stato da te voluto, ciò che vuoi e ciò che è… coincidono.",en:"When you REALISE everything was willed by you, what you want and what is… coincide."}},
        {q:{it:"La prima vittima del tuo giudizio sei…",en:"The first victim of your judgment is…"},options:{it:["Tu stesso","La persona giudicata","La società","Nessuno"],en:["Yourself","The person judged","Society","Nobody"]},correct:0,note:{it:"Il giudizio rovina la vita di chi lo prova, non di chi lo subisce.",en:"Judgment ruins the life of the one who feels it, not the one who suffers it."}},
        {q:{it:"Le tecniche (mantra, meditazione) da sole…",en:"Techniques (mantras, meditation) alone…"},options:{it:["Non risvegliano, possono addormentare di più","Garantiscono il risveglio","Sono l'unica via","Funzionano per tutti uguale"],en:["Don't awaken, they can deepen sleep","Guarantee awakening","Are the only way","Work for everyone the same"]},correct:0,note:{it:"Victoria Ignis: «In tutti questi anni non ho mai visto nessun occidentale risvegliarsi utilizzando tecniche di meditazione!»",en:"Victoria Ignis: 'In all these years I have never seen a single Westerner awaken by using meditation techniques!'"}},
        {q:{it:"Il vero Re si pone…",en:"The true King places himself…"},options:{it:["Alla base della struttura e la serve","In cima alla piramide","Lontano dagli altri","Al centro dell'attenzione"],en:["At the base of the structure and serves it","At the top of the pyramid","Far from others","At the centre of attention"]},correct:0,note:{it:"«Il reggitore è colui [che] si pone alla base della struttura e da questa posizione la regge, e per reggerla la deve servire.»",en:"'The ruler is he who places himself at the base of the structure and from that position upholds it, and to uphold it he must serve it.'"}},
        {q:{it:"La Preghiera dell'Esicasmo è…",en:"The Hesychast Prayer is…"},options:{it:["«Signore Gesù Cristo, figlio di Dio, abbi pietà di me, peccatore»","«Ave Maria piena di grazia»","«Om mani padme hum»","«Padre Nostro»"],en:["'Lord Jesus Christ, Son of God, have mercy on me, a sinner'","'Hail Mary full of grace'","'Om mani padme hum'","'Our Father'"]},correct:0,note:{it:"Praticata incessantemente dai Padri del Deserto dal IV secolo. Il 'peccatore' è chi si è allontanato da Dio.",en:"Practised incessantly by the Desert Fathers since the 4th century. The 'sinner' is one who has moved away from God."}},
        {q:{it:"Le paure della macchina biologica sono…",en:"The fears of the biological machine are…"},options:{it:["Distorsioni del campo elettrico che, riparate, diventano Potere","Difetti permanenti","Punizioni divine","Reazioni normali"],en:["Electric field distortions that, once repaired, become Power","Permanent defects","Divine punishments","Normal reactions"]},correct:0,note:{it:"Ciò che prima era difetto si trasforma in Potere. Il mago fabbrica la bacchetta un pezzo alla volta.",en:"What was once a defect transforms into Power. The mage builds his wand one piece at a time."}},
        {q:{it:"Usare la volontà per realizzare desideri dell'io è…",en:"Using will to realise ego desires is…"},options:{it:["Magia nera","Magia bianca","Il segreto alchemico","L'auto-osservazione"],en:["Black magic","White magic","The alchemical secret","Self-observation"]},correct:0,note:{it:"La magia bianca segue la 'vera volontà' dell'anima, non i desideri della personalità.",en:"White magic follows the 'true will' of the soul, not the personality's desires."}},
        {q:{it:"«Il Sistema è perfetto così com'è» significa…",en:"'The System is perfect as it is' means…"},options:{it:["L'unico che deve cambiare sei tu","Non bisogna fare nulla","Va adorato","È stato creato da Dio"],en:["The only one who must change is you","Nothing needs to be done","It must be adored","It was created by God"]},correct:0,note:{it:"Se il Sistema è più forte di te non puoi vincerlo. Devi cambiare te stesso.",en:"If the System is stronger than you, you can't defeat it. You must change yourself."}},
        {q:{it:"La democrazia, secondo Brizzi, è…",en:"Democracy, per Brizzi, is…"},options:{it:["Una maschera dell'oligarchia: il popolo non può autogovernarsi","Il miglior sistema possibile","L'unica via per la libertà","Un'invenzione moderna perfetta"],en:["A mask of oligarchy: the people cannot self-govern","The best possible system","The only way to freedom","A perfect modern invention"]},correct:0,note:{it:"La democrazia «semplicemente non esiste, o meglio, […] può esistere solo come maschera dell'oligarchia».",en:"Democracy 'simply does not exist, or rather, […] can exist only as a mask of oligarchy'."}},
        {q:{it:"Solo se siamo liberi interiormente…",en:"Only if we are free inwardly…"},options:{it:["La libertà, la pace e la giustizia si irradieranno da noi verso l'esterno","Possiamo votare meglio","Possiamo cambiare partito","Diventiamo ricchi"],en:["Freedom, peace and justice will radiate from us outward","We can vote better","We can change party","We become rich"]},correct:0,note:{it:"Un uomo in conflitto interiore irradia disarmonia anche quando appare pacato.",en:"A man in inner conflict radiates disharmony even when he appears calm."}},
        {q:{it:"La sofferenza, secondo il libro, è…",en:"Suffering, per the book, is…"},options:{it:["Un portale: se resti presente, la coscienza si apre","Un errore da eliminare","Una punizione divina","Qualcosa di evitabile"],en:["A portal: if you stay present, consciousness opens","A mistake to eliminate","A divine punishment","Something avoidable"]},correct:0,note:{it:"«In ciò che ti dà più fastidio è nascosto il segreto della tua liberazione.»",en:"'In what annoys you most is hidden the secret of your liberation.'"}},
        {q:{it:"Secondo Brizzi, ogni vittima…",en:"According to Brizzi, every victim…"},options:{it:["Crea il suo carnefice","È innocente per definizione","Va sempre difesa dal Sistema","Prima o poi si ribella"],en:["Creates its own executioner","Is innocent by definition","Must always be protected by the System","Sooner or later rebels"]},correct:0,note:{it:"«Uno schiavo richiama un padrone e ogni vittima crea il suo carnefice.»",en:"'A slave attracts a master and every victim creates its executioner.'"}},
        {q:{it:"Che cosa succede se ci assumiamo la responsabilità totale per quanto ci accade?",en:"What happens if we take total responsibility for what happens to us?"},options:{it:["Ci liberiamo dall'attesa che cambino il mondo e i governi","Ci sentiamo in colpa per tutto","Dobbiamo cambiare il mondo da soli","Diventiamo indifferenti agli altri"],en:["We are freed from waiting for the world and governments to change","We feel guilty about everything","We must change the world alone","We become indifferent to others"]},correct:0,note:{it:"L'attesa che il mondo cambi rende infelici e frustrati un po' tutti.",en:"Waiting for the world to change makes almost everyone unhappy and frustrated."}},
        {q:{it:"Come si acquisiscono libero arbitrio e responsabilità?",en:"How are free will and responsibility acquired?"},options:{it:["Con gli sforzi per fabbricare un vero Io al proprio interno","Con il compimento della maggiore età","Con il voto e la partecipazione politica","Sono innati in ogni essere umano"],en:["Through efforts to build a real I within","By coming of age","Through voting and political participation","They are innate in every human"]},correct:0,note:{it:"Senza un vero Io, tutto avviene secondo leggi meccaniche.",en:"Without a real I, everything happens by mechanical laws."}},
        {q:{it:"Perché delegare a un maestro la responsabilità della propria felicità è una tentazione?",en:"Why is delegating responsibility for one's happiness to a master tempting?"},options:{it:["È comodo: se falliamo, avremo qualcuno da cui andare a lamentarci","Perché il maestro sa sempre tutto","Perché è l'unica via tradizionale","Perché accelera il risveglio"],en:["It's comfortable: if we fail, we'll have someone to complain to","Because the master always knows everything","Because it's the only traditional way","Because it speeds up awakening"]},correct:0,note:{it:"Nel percorso alchemico «i tempi di attuazione dipendono interamente da noi».",en:"On the alchemical path 'the timing depends entirely on us'."}},
        {q:{it:"Fra le motivazioni per intraprendere il risveglio, quale è «vincente»?",en:"Among the motives for undertaking awakening, which one 'wins'?"},options:{it:["Amo l'umanità e lavorando su di me ne trarranno beneficio tutti","Così sarò più potente dei comuni mortali","Così risolverò in un colpo solo i miei problemi","Così otterrò dei superpoteri"],en:["I love humanity, and working on myself will benefit everyone","That way I'll be more powerful than ordinary mortals","That way I'll solve all my problems at once","That way I'll gain superpowers"]},correct:0,note:{it:"«Si accede a una volontà superiore solo desiderando il bene degli altri, anziché il proprio.»",en:"'One reaches a higher will only by wishing for the good of others rather than one's own.'"}},
        {q:{it:"Nell'immagine di Victoria Ignis, perché si mettono gli ostacoli davanti ai cavalli?",en:"In Victoria Ignis's image, why are obstacles placed before horses?"},options:{it:["Perché sviluppino nuove capacità e superino sé stessi","Per farli cadere","Per selezionare i più forti","Per spaventarli"],en:["So they develop new abilities and surpass themselves","To make them fall","To select the strongest","To frighten them"]},correct:0,note:{it:"«L'ostacolo crea una difficoltà, la quale è evolutiva.»",en:"'The obstacle creates a difficulty, which is evolutionary.'"}},
        {q:{it:"Davanti a un licenziamento, qual è la «chiave magica» del monaco guerriero?",en:"Faced with being fired, what is the warrior monk's 'magic key'?"},options:{it:["Pensare: «IO mi sono licenziato, ho usato il mondo per licenziarmi»","Fare causa all'azienda","Cercare subito un altro impiego uguale","Accusare la crisi economica"],en:["Thinking: 'I fired myself, I used the world to fire myself'","Suing the company","Immediately looking for the same job elsewhere","Blaming the economic crisis"]},correct:0,note:{it:"«Sono le nostre emozioni a plasmare il mondo, e non viceversa.»",en:"'It is our emotions that shape the world, and not the other way round.'"}},
        {q:{it:"Perché le azioni dettate dalla paura non hanno Forza?",en:"Why do actions dictated by fear lack Force?"},options:{it:["Sono re-azioni totalmente meccaniche, non azioni","Perché sono troppo lente","Perché nessuno le approva","Perché nascono dal Cuore"],en:["They are wholly mechanical re-actions, not actions","Because they are too slow","Because nobody approves of them","Because they come from the Heart"]},correct:0,note:{it:"Il monaco guerriero ha smesso di aver paura del Mondo: sa che il mondo è suo.",en:"The warrior monk has stopped fearing the World: he knows the world is his."}},
        {q:{it:"In che cosa consiste all'inizio la disciplina emotiva del monaco guerriero?",en:"What does the warrior monk's emotional discipline consist of at first?"},options:{it:["Non esprimere all'esterno le emozioni negative, senza reprimerle","Non provare più rabbia o gelosia","Sfogare ogni emozione appena nasce","Evitare le persone che ci irritano"],en:["Not expressing negative emotions outwardly, without repressing them","No longer feeling anger or jealousy","Venting every emotion as soon as it arises","Avoiding people who irritate us"]},correct:0,note:{it:"«Ciò fa sì che si accumuli energia all'interno.»",en:"'This allows energy to accumulate within.'"}},
        {q:{it:"Se da qualche parte dei bambini sono costretti a lavorare dodici ore al giorno, chi ne è responsabile secondo «Officina Alkemica»?",en:"If somewhere children are forced to work twelve hours a day, who is responsible according to 'Officina Alkemica'?"},options:{it:["Noi, con le emozioni negative che emettiamo","Solo le multinazionali","Solo i governi","Nessuno: è il destino"],en:["We are, through the negative emotions we emit","Only multinationals","Only governments","No one: it's fate"]},correct:0,note:{it:"«Guerra, sfruttamento e prevaricazione, che sono dentro di noi, causano gli stessi fenomeni a livello planetario.»",en:"'War, exploitation and oppression, which are within us, cause the same phenomena on a planetary scale.'"}},
        {q:{it:"Secondo la Legge dello Specchio, perché può darci fastidio chi ha tanti soldi?",en:"According to the Law of the Mirror, why might a wealthy person annoy us?"},options:{it:["Perché magari vorremmo essere come lui","Perché i soldi sono sempre frutto di disonestà","Perché la ricchezza è un peccato","Perché ci ha fatto un torto"],en:["Because perhaps we would like to be like him","Because money always comes from dishonesty","Because wealth is a sin","Because he wronged us"]},correct:0,note:{it:"Ci dà fastidio ciò che siamo, ciò che vorremmo essere e ciò a cui abbiamo rinunciato.",en:"We are annoyed by what we are, what we'd like to be and what we've given up."}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✶",
      items: [
        {a:{it:"Responsabilità\n100%",en:"100%\nResponsibility"},b:{it:"Il mantra\ndel mago",en:"The mage's\nmantra"}},
        {a:{it:"Servo",en:"Servant"},b:{it:"Corre lungo\nla circonferenza",en:"Runs along\nthe circumference"}},
        {a:{it:"Re",en:"King"},b:{it:"Sta al Centro\ne crea",en:"Stands at the Centre\nand creates"}},
        {a:{it:"La lamentela",en:"Complaint"},b:{it:"Preghiera rivolta\nal Sistema",en:"Prayer addressed\nto the System"}},
        {a:{it:"Il vero Aiuto",en:"True Help"},b:{it:"Fa contorcere\nma trasforma",en:"Makes you writhe\nbut transforms"}},
        {a:{it:"Il Magnetismo",en:"Magnetism"},b:{it:"Forza trattenuta\nall'interno",en:"Force held\nwithin"}},
        {a:{it:"La vittima",en:"The victim"},b:{it:"Crea il suo\ncarnefice",en:"Creates its\nexecutioner"}},
        {a:{it:"L'Avere",en:"Having"},b:{it:"Conseguenza\ndell'Essere",en:"Consequence\nof Being"}},
        {a:{it:"L'ostacolo",en:"The obstacle"},b:{it:"Difficoltà\nevolutiva",en:"Evolutionary\ndifficulty"}}
      ]
    }
  }
};
})();
