/* LA RESPONSABILITÀ — data.js (pooled from 5 books) */
(function(){
"use strict";
window.GAME_DATA = {
  id: "resp",
  modes: ["servo","dentro","quiz","memoria"],
  rings: [
    {key:"servizio",color:"#1a1326",ring:"#3a2f52",label:{it:"Servizio",en:"Service"}},
    {key:"preghiera",color:"#10212a",ring:"#2f5d6b",label:{it:"Preghiera",en:"Prayer"}},
    {key:"responsabilita",color:"#2a1410",ring:"#7c3a2a",label:{it:"Responsabilità",en:"Responsibility"}},
    {key:"potere",color:"#3a2c10",ring:"#c9973a",label:{it:"Potere",en:"Power"}}
  ],
  modeDefs: {
    servo: { type:"classify", roman:"I", glyph:"♔", optionKeys:[0,1],
      items: [
        {item:{it:"Incolpare lo Stato, la società o la sfortuna per i propri fallimenti",en:"Blaming the State, society or bad luck for one's failures"},belongs:0,note:{it:"«Non trovare giustificazioni alla tua povertà in un mondo esterno che tu stesso stai plasmando.»",en:"'Don't find justifications for your poverty in an outside world you yourself are shaping.'"}},
        {item:{it:"Sentire che tutto ciò che accade lo si è attirato dall'interno",en:"Feeling that everything that happens has been attracted from within"},belongs:1,note:{it:"«Chi è divenuto un re nell'anima, crea intorno a sé il proprio regno.»",en:"'He who has become a king in the soul creates his own kingdom around him.'"}},
        {item:{it:"Vivere senza uno scopo, in attesa della pensione",en:"Living without a purpose, waiting for retirement"},belongs:0,note:{it:"«Non sei povero perché hai pochi soldi, ma perché non hai uno scopo.»",en:"'You're not poor because you have little money, but because you have no purpose.'"}},
        {item:{it:"Avere una visione e diventare magnetici, attirando collaboratori",en:"Having a vision and becoming magnetic, attracting collaborators"},belongs:1,note:{it:"«Chi ha un'idea, una visione, non dipende, ma crea. Diventa MAGNETICO.»",en:"'He who has an idea, a vision, doesn't depend — he creates. He becomes MAGNETIC.'"}},
        {item:{it:"Accusare il Sistema: gli stai assegnando i poteri di un Dio",en:"Blaming the System: you are assigning it the powers of a God"},belongs:0,note:{it:"«Nell'accusare il Sistema ti stai inginocchiando ai suoi piedi.»",en:"'In blaming the System you are kneeling at its feet.'"}},
        {item:{it:"«Divieni Re e un regno ti sarà dato»: la regalità dell'essere precede il regno",en:"'Become King and a kingdom shall be given': regality of being precedes the kingdom"},belongs:1,note:{it:"La regalità interiore precede, non segue, l'attribuzione di un regno.",en:"Inner regality precedes, not follows, the attribution of a kingdom."}},
        {item:{it:"La lamentela come preghiera quotidiana rivolta al Sistema",en:"Complaint as a daily prayer addressed to the System"},belongs:0,note:{it:"«Nel lamentarti lo stai pregando come si prega un idolo.»",en:"'In complaining you are praying to it like an idol.'"}},
        {item:{it:"Resistere al desiderio di approvazione: accumulare Forza e Magnetismo",en:"Resisting the desire for approval: accumulating Force and Magnetism"},belongs:1,note:{it:"«Ciò che non viene espulso diventa come una calamita che attira l'attenzione dall'esterno.»",en:"'What is not expelled becomes like a magnet that attracts attention from outside.'"}},
        {item:{it:"Giudicare gli altri e poi avere paura del loro giudizio",en:"Judging others and then fearing their judgment"},belongs:0,note:{it:"«Il timido sembra una vittima, invece è un carnefice: giudica il mondo.»",en:"'The shy person seems a victim but is a perpetrator: he judges the world.'"}},
        {item:{it:"Il massimo della sottomissione all'Altissimo = massimo del Potere",en:"The utmost submission to the Most High = utmost Power"},belongs:1,note:{it:"«Abbassandoci ci innalziamo, umiliandoci ci eleviamo.»",en:"'By lowering ourselves we rise, by humbling ourselves we elevate.'"}},
        {item:{it:"Non sei uno schiavo perché qualcuno ti domina, ma qualcuno ti domina perché sei uno schiavo",en:"You're not a slave because someone dominates you, but someone dominates you because you're a slave"},belongs:0,note:{it:"La schiavitù è interiore, non esteriore.",en:"Slavery is inner, not outer."}},
        {item:{it:"Inseguire un SOGNO più grande della paura di morire di fame",en:"Pursuing a DREAM greater than the fear of starving"},belongs:1,note:{it:"«Se il sogno è più grande della paura, il guerriero si butta nella vita e la vita lo premia… sempre.»",en:"'If the dream is greater than the fear, the warrior throws himself into life and life rewards him… always.'"}}
      ]
    },
    dentro: { type:"classify", roman:"II", glyph:"◇", optionKeys:[0,1],
      items: [
        {item:{it:"«Non sono ricco perché la società è ingiusta»",en:"'I'm not rich because society is unjust'"},belongs:0,note:{it:"«Il mondo è un tuo riflesso. Non trovare giustificazioni in un mondo esterno.»",en:"'The world is your reflection. Don't find justifications in an outside world.'"}},
        {item:{it:"«Faccio quel lavoro perché dentro di me sono ancora uno schiavo»",en:"'I do that job because inside myself I'm still a slave'"},belongs:1,note:{it:"«Non sei schiavo perché fai quel lavoro, ma fai quel lavoro perché dentro di te sei uno schiavo.»",en:"'You're not a slave because of your job, but you do that job because inside you are a slave.'"}},
        {item:{it:"Sul treno, una signora al telefono mi irrita: è colpa sua",en:"On the train, a lady on the phone irritates me: it's her fault"},belongs:0,note:{it:"«È la mia irritazione a creare e alimentare quell'episodio… e non viceversa.»",en:"'It is my irritation that creates and feeds that episode… not the reverse.'"}},
        {item:{it:"Comprendo che la mia aggressività repressa ha attirato la scena",en:"I understand that my repressed aggression attracted the scene"},belongs:1,note:{it:"«Le emozioni nel tuo inconscio creano la scena e poi tu reagisci provando l'emozione negativa.»",en:"'The emotions in your unconscious create the scene and then you react feeling the negative emotion.'"}},
        {item:{it:"Sperare che le restrizioni diminuiscano per sentirsi finalmente liberi",en:"Hoping restrictions decrease in order to finally feel free"},belongs:0,note:{it:"«Nessuno può farmi sentire più libero di quanto io non sia già.»",en:"'No one can make me feel freer than I already am.'"}},
        {item:{it:"Utilizzare la tensione sociale come occasione per approfondire il lavoro su di sé",en:"Using social tension as an occasion to deepen the work on oneself"},belongs:1,note:{it:"«Tempi favorevoli per chi vuole svegliarsi»: la crisi è il momento migliore.",en:"'Favourable times for those who want to awaken': crisis is the best moment."}},
        {item:{it:"Qualcuno ti dona denaro quando sei in povertà: dormi ancora un po'",en:"Someone donates money when you're poor: sleep a little longer"},belongs:0,note:{it:"Victoria Ignis: «Spesso è solo un sedativo, qualcosa che ti consente di dormire ancora.»",en:"Victoria Ignis: 'Often just a sedative, something that lets you sleep a while longer.'"}},
        {item:{it:"Il maestro ti impone di dare il 10% del tuo stipendio da 500 euro in beneficenza",en:"The master forces you to give 10% of your €500 salary to charity"},belongs:1,note:{it:"«Questo è Aiuto.» Fa contorcere nel dolore, ma scioglie i blocchi.",en:"'This is Help.' It makes you writhe in pain, but dissolves the blocks."}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"Responsabilità e ricchezza sono…",en:"Responsibility and wealth are…"},options:{it:["Sempre commisurate l'una all'altra","Completamente indipendenti","Inversamente proporzionali","Riservate a pochi"],en:["Always commensurate with each other","Completely independent","Inversely proportional","Reserved for a few"]},correct:0,note:{it:"«Solo chi regge un certo grado di responsabilità ottiene il corrispondente grado di ricchezza.»",en:"'Only he who bears a certain degree of responsibility obtains the corresponding degree of wealth.'"}},
        {q:{it:"Vincere alla lotteria senza maturità interiore è paragonato a…",en:"Winning the lottery without inner maturity is compared to…"},options:{it:["Mettere le dita bagnate nella presa di corrente","Trovare un tesoro","Un premio meritato","Piantare un seme"],en:["Putting wet fingers into an electrical socket","Finding a treasure","A deserved prize","Planting a seed"]},correct:0,note:{it:"«Il tuo sistema nervoso salta»: il voltaggio della ricchezza è troppo elevato.",en:"'Your nervous system blows': the voltage of wealth is too high.'"}},
        {q:{it:"«Desiderare ciò che accade» significa…",en:"'Desiring what happens' means…"},options:{it:["Sentire che sei tu a far accadere tutto e quindi lo vuoi","Rassegnarsi passivamente","Non avere più desideri","Reprimere la volontà"],en:["Feeling that you make everything happen and therefore want it","Passively resigning","Having no more desires","Repressing the will"]},correct:0,note:{it:"Quando REALIZZI che tutto è stato da te voluto, ciò che vuoi e ciò che è… coincidono.",en:"When you REALISE everything was willed by you, what you want and what is… coincide."}},
        {q:{it:"La prima vittima del tuo giudizio sei…",en:"The first victim of your judgment is…"},options:{it:["Tu stesso","La persona giudicata","La società","Nessuno"],en:["Yourself","The person judged","Society","Nobody"]},correct:0,note:{it:"Il giudizio rovina la vita di chi lo prova, non di chi lo subisce.",en:"Judgment ruins the life of the one who feels it, not the one who suffers it."}},
        {q:{it:"Le tecniche (mantra, meditazione) da sole…",en:"Techniques (mantras, meditation) alone…"},options:{it:["Non risvegliano, possono addormentare di più","Garantiscono il risveglio","Sono l'unica via","Funzionano per tutti uguale"],en:["Don't awaken, they can deepen sleep","Guarantee awakening","Are the only way","Work for everyone the same"]},correct:0,note:{it:"Victoria Ignis: «Non ho mai visto nessun occidentale risvegliarsi utilizzando tecniche di meditazione!»",en:"Victoria Ignis: 'I have never seen any Westerner awaken through meditation techniques!'"}},
        {q:{it:"Il vero Re si pone…",en:"The true King places himself…"},options:{it:["Alla base della struttura e la serve","In cima alla piramide","Lontano dagli altri","Al centro dell'attenzione"],en:["At the base of the structure and serves it","At the top of the pyramid","Far from others","At the centre of attention"]},correct:0,note:{it:"«Il reggitore è colui che si pone alla base e da lì la regge, e per reggerla la deve servire.»",en:"'The ruler places himself at the base and from there upholds it, and to uphold it he must serve it.'"}},
        {q:{it:"La Preghiera dell'Esicasmo è…",en:"The Hesychast Prayer is…"},options:{it:["«Signore Gesù Cristo, figlio di Dio, abbi pietà di me, peccatore»","«Ave Maria piena di grazia»","«Om mani padme hum»","«Padre Nostro»"],en:["'Lord Jesus Christ, Son of God, have mercy on me, a sinner'","'Hail Mary full of grace'","'Om mani padme hum'","'Our Father'"]},correct:0,note:{it:"Praticata incessantemente dai Padri del Deserto dal IV secolo. Il 'peccatore' è chi si è allontanato da Dio.",en:"Practised incessantly by the Desert Fathers since the 4th century."}},
        {q:{it:"Le paure della macchina biologica sono…",en:"The fears of the biological machine are…"},options:{it:["Distorsioni del campo elettrico che, riparate, diventano Potere","Difetti permanenti","Punizioni divine","Reazioni normali"],en:["Electric field distortions that, once repaired, become Power","Permanent defects","Divine punishments","Normal reactions"]},correct:0,note:{it:"Ciò che prima era difetto si trasforma in Potere. Il mago fabbrica la bacchetta un pezzo alla volta.",en:"What was once a defect transforms into Power. The mage builds his wand one piece at a time."}},
        {q:{it:"Usare la volontà per realizzare desideri dell'io è…",en:"Using will to realise ego desires is…"},options:{it:["Magia nera","Magia bianca","Il segreto alchemico","L'auto-osservazione"],en:["Black magic","White magic","The alchemical secret","Self-observation"]},correct:0,note:{it:"La magia bianca segue la 'vera volontà' dell'anima, non i desideri della personalità.",en:"White magic follows the 'true will' of the soul, not the personality's desires."}},
        {q:{it:"«Il Sistema è perfetto così com'è» significa…",en:"'The System is perfect as it is' means…"},options:{it:["L'unico che deve cambiare sei tu","Non bisogna fare nulla","Va adorato","È stato creato da Dio"],en:["The only one who must change is you","Nothing needs to be done","It must be adored","It was created by God"]},correct:0,note:{it:"Se il Sistema è più forte di te non puoi vincerlo. Devi cambiare te stesso.",en:"If the System is stronger than you, you can't defeat it. You must change yourself."}},
        {q:{it:"La sofferenza, secondo il libro, è…",en:"Suffering, per the book, is…"},options:{it:["Un portale: se resti presente, la coscienza si apre","Un errore da eliminare","Una punizione divina","Qualcosa di evitabile"],en:["A portal: if you stay present, consciousness opens","A mistake to eliminate","A divine punishment","Something avoidable"]},correct:0,note:{it:"«In ciò che ti dà più fastidio è nascosto il segreto della tua liberazione.»",en:"'In what annoys you most is hidden the secret of your liberation.'"}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✶",
      items: [
        {a:{it:"Responsabilità\n100%",en:"100%\nResponsibility"},b:{it:"Il mantra\ndel mago",en:"The mage's\nmantra"}},
        {a:{it:"Servo",en:"Servant"},b:{it:"Corre lungo\nla circonferenza",en:"Runs along\nthe circumference"}},
        {a:{it:"Re",en:"King"},b:{it:"Sta al Centro\ne crea",en:"Stands at the Centre\nand creates"}},
        {a:{it:"La lamentela",en:"Complaint"},b:{it:"Preghiera rivolta\nal Sistema",en:"Prayer addressed\nto the System"}},
        {a:{it:"Il vero Aiuto",en:"True Help"},b:{it:"Fa contorcere\nma trasforma",en:"Makes you writhe\nbut transforms"}},
        {a:{it:"Il Magnetismo",en:"Magnetism"},b:{it:"Forza trattenuta\nall'interno",en:"Force held\nwithin"}}
      ]
    }
  }
};
})();
