/* I CINQUE VEICOLI — data.js (dalle opere di Arthur E. Powell) */
(function(){
"use strict";
window.GAME_DATA = {
  id: "veicoli",
  modes: ["veicolo","colore","quiz","memoria"],
  rings: [
    {key:"causale",color:"#2a1a3a",ring:"#7a5ab0",label:{it:"Causale",en:"Causal"}},
    {key:"mentale",color:"#10212a",ring:"#3a6a9a",label:{it:"Mentale",en:"Mental"}},
    {key:"astrale",color:"#2a1410",ring:"#7c3a2a",label:{it:"Astrale",en:"Astral"}},
    {key:"eterico",color:"#1a2a1a",ring:"#6a9a7a",label:{it:"Eterico",en:"Etheric"}}
  ],
  modeDefs: {
    veicolo: { type:"scenario", roman:"I", glyph:"◎", optionKeys:[0,1,2,3], count:10,
      items: [
        {sit:{it:"Duplicato esatto del corpo denso: assorbe il pràna dal sole e lo distribuisce attraverso i centri di forza.",en:"An exact duplicate of the dense body: it absorbs prana from the sun and distributes it through the force centres."},correct:0,note:{it:"Il Doppio Eterico è il veicolo del pràna, ponte fra il corpo denso e l'astrale.",en:"The Etheric Double is the vehicle of prana, the bridge between the dense body and the astral."}},
        {sit:{it:"Un incessante gioco di colori vi esprime sentimenti, passioni ed emozioni.",en:"An incessant play of colours expresses feelings, passions and emotions in it."},correct:1,note:{it:"Per il chiaroveggente il gioco cromatico è la caratteristica principale del corpo astrale.",en:"For the clairvoyant the play of colours is the astral body's main characteristic."}},
        {sit:{it:"Veicolo del pensiero concreto: si disgrega quando termina il soggiorno nel Devachan inferiore.",en:"Vehicle of concrete thought: it disintegrates when the stay in the lower Devachan ends."},correct:2,note:{it:"Il corpo mentale vive i quattro cieli inferiori, poi si dissolve e la coscienza si ritira nell'ego.",en:"The mental body lives the four lower heavens, then dissolves and consciousness withdraws into the ego."}},
        {sit:{it:"Il veicolo permanente dell'ego: conserva l'essenza di tutte le esperienze tra una vita e l'altra.",en:"The ego's permanent vehicle: it preserves the essence of all experiences between lives."},correct:3,note:{it:"Il corpo causale nasce con l'individualizzazione e dura per l'intero ciclo delle incarnazioni.",en:"The causal body is born with individualisation and lasts the entire cycle of incarnations."}},
        {sit:{it:"Al momento della morte si ritira dal corpo denso: il filo lucente che ancora lo univa ad esso si rompe.",en:"At the moment of death it withdraws from the dense body: the shining thread that still joined it to the body breaks."},correct:0,note:{it:"Dopo la morte il doppio resta fluttuante sopra il corpo; col tempo diventa un cadavere eterico, e questi spettri eterici si vedono spesso nei cimiteri.",en:"After death the double floats above the body; in time it becomes an etheric corpse, and such etheric wraiths are often seen in graveyards."}},
        {sit:{it:"I suoi chakram sono vortici a quattro dimensioni.",en:"Its chakras are four-dimensional vortices."},correct:1,note:{it:"I chakram astrali si estendono in una dimensione sconosciuta al doppio eterico.",en:"Astral chakras extend into a dimension unknown to the etheric double."}},
        {sit:{it:"Dopo la morte vive nel kàmaloka, con i gusci più densi disposti all'esterno.",en:"After death it lives in kamaloka, with the densest shells arranged outside."},correct:1,note:{it:"L'elementale del desiderio ridispone la materia astrale in gusci concentrici — chi sa, può impedirlo.",en:"The desire-elemental rearranges astral matter into concentric shells — one who knows can prevent it."}},
        {sit:{it:"È composto di materia dei tre sotto-piani superiori del mondo mentale.",en:"It is composed of matter from the three higher sub-planes of the mental world."},correct:3,note:{it:"Il corpo causale appartiene al piano mentale superiore: il regno del pensiero astratto.",en:"The causal body belongs to the higher mental plane: the realm of abstract thought."}},
        {sit:{it:"In esso si vive il 'giorno' che segue la notte della vita terrestre: i quattro cieli inferiori.",en:"In it one lives the 'day' that follows the night of earthly life: the four lower heavens."},correct:2,note:{it:"Il Devachan inferiore si svolge nel corpo mentale, dove ogni aspirazione diventa facoltà.",en:"The lower Devachan unfolds in the mental body, where every aspiration becomes a faculty."}},
        {sit:{it:"Nel Ràja Yoga, insieme al corpo denso, forma lo 'Stulopadhi', il più basso Upadhi di Atma.",en:"In Raja Yoga, together with the dense body, it forms the 'Sthulopadhi', the lowest Upadhi of Atma."},correct:0,note:{it:"È il doppio eterico: in tedesco è il 'Doppelganger', e dopo la morte è chiamato anche 'spettro dei cimiteri'.",en:"It is the etheric double: in German it is the 'Doppelganger', and after death it is also called the 'graveyard wraith'."}},
        {sit:{it:"Il suo abbandono dopo la vita nel kàmaloka è chiamato 'seconda morte'.",en:"Leaving it after life in kamaloka is called the 'second death'."},correct:1,note:{it:"Il corpo astrale si disgrega e i suoi materiali ritornano al mondo astrale, come quelli del corpo fisico ritornano al mondo fisico.",en:"The astral body disintegrates and its materials return to the astral world, as those of the physical body return to the physical world."}},
        {sit:{it:"Il suo centro stabile è una singola molecola del quarto sottopiano, che resta con l'uomo in tutte le incarnazioni.",en:"Its stable centre is a single molecule of the fourth sub-plane, which stays with man through all his incarnations."},correct:2,note:{it:"È l'unità mentale del corpo mentale: la sua materia viene sparpagliata e raccolta più volte, vita dopo vita, e l'unità resta.",en:"It is the mental unit of the mental body: its matter is scattered and gathered many times, life after life, and the unit remains."}},
        {sit:{it:"Nell'individualizzazione, è ciò in cui si converte l'involucro dell'anima-gruppo.",en:"At individualisation, it is what the group-soul's envelope is converted into."},correct:3,note:{it:"Il corpo causale diventa il veicolo animato dalla scintilla divina discesa dal mondo superiore.",en:"The causal body becomes the vehicle animated by the divine spark descended from the higher world."}}
      ]
    },
    colore: { type:"quiz", roman:"II", glyph:"❖", count:10,
      items: [
        {q:{it:"Nuvole dense di nero nell'aura rivelano…",en:"Dense black clouds in the aura reveal…"},options:{it:["Odio e malizia","Depressione","Paura","Avarizia"],en:["Hatred and malice","Depression","Fear","Avarice"]},correct:0,note:{it:"Nero in nuvole dense: odio e malizia.",en:"Black in dense clouds: hatred and malice."}},
        {q:{it:"Lo scarlatto vivo sul fondo dell'aura indica…",en:"Vivid scarlet on the background of the aura indicates…"},options:{it:["Nobile indignazione","Collera","Sensualità","Orgoglio"],en:["Noble indignation","Anger","Sensuality","Pride"]},correct:0,note:{it:"La collera è in lampi rosso scuro su fondo nero; lo scarlatto vivo è 'nobile indignazione'.",en:"Anger shows as dark red flashes on black; vivid scarlet is 'noble indignation'."}},
        {q:{it:"Quale colore, uno dei più frequenti nel corpo astrale, esprime l'egoismo?",en:"Which colour, one of the most frequent in the astral body, expresses selfishness?"},options:{it:["Grigio-bruno opaco","Rosa","Giallo","Blu"],en:["Dull grey-brown","Pink","Yellow","Blue"]},correct:0,note:{it:"Il grigio-bruno dell'egoismo è uno dei colori che più frequentemente si trovano nel corpo astrale.",en:"The grey-brown of selfishness is one of the most frequent colours in the astral body."}},
        {q:{it:"L'avarizia appare come…",en:"Avarice appears as…"},options:{it:["Linee parallele rosso-bruno color ruggine","Nuvole nere","Lampi scarlatti","Macchie verdi"],en:["Rust-coloured red-brown parallel lines","Black clouds","Scarlet flashes","Green patches"]},correct:0,note:{it:"Rosso-bruno cupo, simile al color ruggine, in linee parallele che striano il corpo astrale.",en:"Dull red-brown, rust-like, in parallel lines streaking the astral body."}},
        {q:{it:"Il bruno-verdastro illuminato da lampi scarlatti rivela…",en:"Greenish-brown lit by scarlet flashes reveals…"},options:{it:["Gelosia","Astuzia","Adattabilità","Invidia del bene altrui"],en:["Jealousy","Cunning","Adaptability","Envy of others' good"]},correct:0,note:{it:"Nell'uomo medio abbonda questo colore quando è 'innamorato'.",en:"In the average man this colour abounds when he is 'in love'."}},
        {q:{it:"La depressione si mostra come…",en:"Depression shows as…"},options:{it:["Grigio plumbeo in linee parallele, come una gabbia","Grigio livido","Nero uniforme","Blu fangoso"],en:["Leaden grey in parallel lines, like a cage","Livid grey","Uniform black","Muddy blue"]},correct:0,note:{it:"Come l'avarizia, anche la depressione si dispone in linee parallele che danno l'impressione di una gabbia.",en:"Like avarice, depression arranges itself in parallel lines giving the impression of a cage."}},
        {q:{it:"Il grigio livido, 'tinta orribilmente disgustante', esprime…",en:"Livid grey, a 'horribly disgusting hue', expresses…"},options:{it:["Paura","Odio","Egoismo","Malattia"],en:["Fear","Hatred","Selfishness","Illness"]},correct:0,note:{it:"Grigio livido: paura.",en:"Livid grey: fear."}},
        {q:{it:"Il rosa straordinariamente brillante con sfumature di lillà indica…",en:"Extraordinarily bright pink with lilac shades indicates…"},options:{it:["Amore spirituale per l'umanità","Amore egoista","Devozione religiosa","Gioia"],en:["Spiritual love for humanity","Selfish love","Religious devotion","Joy"]},correct:0,note:{it:"Il rosa è amore non egoista; brillante con lillà: amore spirituale per l'umanità. Il cremisi opaco è amore egoista.",en:"Pink is unselfish love; bright with lilac: spiritual love for humanity. Dull crimson is selfish love."}},
        {q:{it:"L'arancio nell'aura rivela…",en:"Orange in the aura reveals…"},options:{it:["Orgoglio o ambizione","Vitalità","Coraggio","Creatività"],en:["Pride or ambition","Vitality","Courage","Creativity"]},correct:0,note:{it:"Arancio: orgoglio o ambizione. Spesso è unito all'irritabilità.",en:"Orange: pride or ambition. Often joined with irritability."}},
        {q:{it:"Il giallo oro indica…",en:"Golden yellow indicates…"},options:{it:["Intelligenza pura applicata a filosofia o matematica","Ricchezza interiore","Intelletto a scopi egoistici","Spiritualità devozionale"],en:["Pure intelligence applied to philosophy or mathematics","Inner wealth","Intellect for selfish ends","Devotional spirituality"]},correct:0,note:{it:"L'ocra cupo è intelletto egoistico; il giallo primula è intelletto votato allo spirito; l'oro pura intelligenza filosofica.",en:"Dull ochre is selfish intellect; primrose yellow is intellect devoted to spirit; gold pure philosophical intelligence."}},
        {q:{it:"Il verde smeraldo esprime…",en:"Emerald green expresses…"},options:{it:["Versatilità e ingegnosità altruista","Astuzia e inganno","Gelosia","Forte vitalità"],en:["Versatility and unselfish resourcefulness","Cunning and deceit","Jealousy","Strong vitality"]},correct:0,note:{it:"Il grigio-verde fangoso è astuzia; lo smeraldo versatilità altruista; il verde sidro vitalità.",en:"Muddy grey-green is cunning; emerald unselfish versatility; cider green vitality."}},
        {q:{it:"Il blu chiaro come l'ultramarino o il cobalto rivela…",en:"Light blue like ultramarine or cobalt reveals…"},options:{it:["Devozione a un nobile ideale spirituale","Calma","Sentimento religioso generico","Tristezza"],en:["Devotion to a noble spiritual ideal","Calm","Generic religious feeling","Sadness"]},correct:0,note:{it:"Il blu cupo trasparente è sentimento religioso; il blu chiaro devozione a un nobile ideale.",en:"Dark transparent blue is religious feeling; light blue devotion to a noble ideal."}},
        {q:{it:"Una nube scarlatta nel corpo astrale indica…",en:"A scarlet cloud in the astral body indicates…"},options:{it:["Irritabilità","Nobile indignazione","Collera","Sensualità"],en:["Irritability","Noble indignation","Anger","Sensuality"]},correct:0,note:{it:"Nube scarlatta: irritabilità. Lo scarlatto vivo sul fondo dell'aura è 'nobile indignazione', i lampi rosso scuro su fondo nero sono collera.",en:"Scarlet cloud: irritability. Vivid scarlet on the aura's background is 'noble indignation', dark red flashes on black are anger."}},
        {q:{it:"Il rosso sangue e il rosso cupo, colore 'difficile a descriversi, ma facilmente riconoscibile', esprimono…",en:"Blood red and dull red, a colour 'hard to describe, but easily recognised', express…"},options:{it:["Sensualità","Collera","Coraggio","Vitalità"],en:["Sensuality","Anger","Courage","Vitality"]},correct:0,note:{it:"La massa della sensualità fluttua di solito fra la parte superiore e quella inferiore del corpo astrale.",en:"The mass of sensuality usually floats between the upper and lower parts of the astral body."}},
        {q:{it:"Una tinta violetta nel corpo astrale indica…",en:"A violet tint in the astral body indicates…"},options:{it:["Affetto e devozione mescolati","Paura","Orgoglio spirituale","Basse facoltà psichiche"],en:["Affection and devotion mingled","Fear","Spiritual pride","Low psychic faculties"]},correct:0,note:{it:"Il rosa è affetto, il blu devozione: la tinta violetta ne indica la mescolanza. Le basse facoltà psichiche sono l'infra-rosso.",en:"Pink is affection, blue devotion: the violet tint shows them mingled. Low psychic faculties are infra-red."}},
        {q:{it:"Il blu-lilla brillante, accompagnato da scintillanti stelle dorate, rivela…",en:"Brilliant lilac-blue, accompanied by sparkling golden stars, reveals…"},options:{it:["La più alta spiritualità","Intelligenza filosofica","Amore egoista","Adattabilità"],en:["The highest spirituality","Philosophical intelligence","Selfish love","Adaptability"]},correct:0,note:{it:"Blu-lilla brillante con stelle dorate: la più alta spiritualità con aspirazioni nobilissime.",en:"Brilliant lilac-blue with golden stars: the highest spirituality with the noblest aspirations."}},
        {q:{it:"Il verde-blu pallido e luminoso esprime…",en:"Pale luminous blue-green expresses…"},options:{it:["Profonda simpatia e comprensione","Astuzia","Gelosia","Depressione"],en:["Deep sympathy and understanding","Cunning","Jealousy","Depression"]},correct:0,note:{it:"Il verde in generale designa adattabilità; nel verde-blu pallido è l'adattabilità che nasce dalla simpatia.",en:"Green in general denotes adaptability; in pale blue-green it is the adaptability born of sympathy."}},
        {q:{it:"Dove si trovano il giallo dell'intelletto, il rosa dell'affetto e l'azzurro della devozione?",en:"Where are the yellow of intellect, the pink of affection and the blue of devotion found?"},options:{it:["Sempre nella parte superiore del corpo astrale","Nella parte inferiore","Al centro, attorno al cuore","Sparsi in modo casuale"],en:["Always in the upper part of the astral body","In the lower part","In the centre, around the heart","Scattered at random"]},correct:0,note:{it:"I colori dell'egoismo, dell'avarizia, dell'inganno e dell'odio stanno nella parte inferiore; la sensualità fluttua fra le due.",en:"The colours of selfishness, avarice, deceit and hatred lie in the lower part; sensuality floats between the two."}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"La parola sanscrita 'chakram' significa…",en:"The Sanskrit word 'chakram' means…"},options:{it:["Ruota o disco girante","Fiore di loto","Centro di luce","Porta sottile"],en:["Wheel or spinning disc","Lotus flower","Centre of light","Subtle gate"]},correct:0,note:{it:"I chakram sono i punti di congiunzione attraverso cui la forza si riversa da un veicolo nell'altro.",en:"Chakras are the junction points through which force pours from one vehicle into another."}},
        {q:{it:"Kundalini, il Fuoco Serpentino, risiede…",en:"Kundalini, the Serpent Fire, resides…"},options:{it:["Nel chakram della base della colonna vertebrale","Nel cuore","Nella sommità del capo","Nella milza"],en:["In the chakra at the base of the spine","In the heart","At the crown of the head","In the spleen"]},correct:0,note:{it:"Da lì si sposta vivificando gli altri centri: ombelico, milza, cuore, gola, fronte, sommità.",en:"From there it moves on, vivifying the other centres: navel, spleen, heart, throat, brow, crown."}},
        {q:{it:"Quale chakram assorbe il pràna e vitalizza tutto il corpo astrale?",en:"Which chakra absorbs prana and vitalises the whole astral body?"},options:{it:["La milza","Il cuore","La gola","L'ombelico"],en:["The spleen","The heart","The throat","The navel"]},correct:0,note:{it:"La sua vivificazione permette di viaggiare coscientemente in astrale, pur con ricordi vaghi.",en:"Its vivification allows conscious astral travel, though with vague recollections."}},
        {q:{it:"Il chakram del cuore astrale conferisce…",en:"The astral heart chakra confers…"},options:{it:["Comprensione istintiva dei sentimenti delle altre entità","Udito astrale","Vista astrale","Il potere di volare"],en:["Instinctive understanding of other entities' feelings","Astral hearing","Astral sight","The power of flight"]},correct:0,note:{it:"Gola = udito astrale; fronte = vista astrale; sommità = pienezza delle facoltà.",en:"Throat = astral hearing; brow = astral sight; crown = fullness of faculties."}},
        {q:{it:"Il siddhi descritto come il potere 'di ingrandire o di impicciolire a volontà' dipende dal chakram…",en:"The siddhi described as the power 'of enlarging or diminishing at will' depends on the chakra…"},options:{it:["Fra le sopracciglia","Della gola","Del cuore","Della milza"],en:["Between the eyebrows","Of the throat","Of the heart","Of the spleen"]},correct:0,note:{it:"Permette di percepire e studiare molecole e atomi, come con un microscopio.",en:"It allows one to perceive and study molecules and atoms, as with a microscope."}},
        {q:{it:"Oltre ai sette chakram principali, esistono tre chakram inferiori…",en:"Besides the seven main chakras, there are three lower chakras…"},options:{it:["Usati solo da certe scuole di magia nera","Attivi solo nei bambini","Ormai atrofizzati","Riservati ai Maestri"],en:["Used only by certain schools of black magic","Active only in children","Now atrophied","Reserved for Masters"]},correct:0,note:{it:"Powell li menziona e tralascia di occuparsene proprio per questo.",en:"Powell mentions them and sets them aside for precisely this reason."}},
        {q:{it:"Secondo Il Corpo Mentale, 'devachan' letteralmente significa…",en:"According to The Mental Body, 'devachan' literally means…"},options:{it:["La terra risplendente","Il sonno senza sogni","Il vuoto luminoso","La terra pura"],en:["The shining land","Dreamless sleep","The luminous void","The pure land"]},correct:0,note:{it:"In sanscrito è anche detto devasthan, terra degli Dei: è il 'giorno' che succede alla notte della vita terrestre.",en:"In Sanskrit it is also called devasthan, land of the Gods: it is the 'day' following the night of earthly life."}},
        {q:{it:"Quanti 'cieli' compongono il mondo celeste?",en:"How many 'heavens' make up the heaven world?"},options:{it:["Sette: quattro inferiori e tre superiori","Tre","Nove","Dodici"],en:["Seven: four lower and three higher","Three","Nine","Twelve"]},correct:0,note:{it:"Quattro cieli sul piano mentale inferiore, tre sul piano causale — fino ai Maestri di Saggezza.",en:"Four heavens on the lower mental plane, three on the causal plane — up to the Masters of Wisdom."}},
        {q:{it:"L'individualizzazione avviene quando…",en:"Individualisation occurs when…"},options:{it:["Un animale rompe l'involucro dell'anima-gruppo e nasce il corpo causale","L'uomo impara a leggere","La monade si addormenta","Il corpo astrale si colora"],en:["An animal breaks the group-soul's envelope and the causal body is born","Man learns to read","The monad falls asleep","The astral body takes colour"]},correct:0,note:{it:"Prima dell'individualizzazione la vita evolve in anime-gruppo: minerali, vegetali, animali.",en:"Before individualisation life evolves in group-souls: mineral, vegetable, animal."}},
        {q:{it:"Le anime-gruppo minerali hanno…",en:"Mineral group-souls have…"},options:{it:["Tre strati nell'involucro","Un solo strato","Nessun involucro","Sette strati"],en:["Three layers in their envelope","A single layer","No envelope","Seven layers"]},correct:0,note:{it:"Minerali: tre strati. Vegetali: due. Animali: uno solo — prossimi all'individualizzazione.",en:"Mineral: three layers. Vegetable: two. Animal: just one — close to individualisation."}},
        {q:{it:"Gli atomi permanenti sono…",en:"The permanent atoms are…"},options:{it:["I 'semi' che conservano le vibrazioni di ogni esperienza tra le vite","Particelle indistruttibili del cervello","Gli atomi del DNA","I ricordi coscienti"],en:["The 'seeds' preserving the vibrations of every experience between lives","Indestructible brain particles","The atoms of DNA","Conscious memories"]},correct:0,note:{it:"Fisico, astrale e mentale: servono da nucleo per la costruzione dei nuovi veicoli.",en:"Physical, astral and mental: they serve as nuclei for building the new vehicles."}},
        {q:{it:"Kundalini è una delle tre forze emanate…",en:"Kundalini is one of the three forces emanating…"},options:{it:["Dal sole, con Fohat e Pràna","Dalla terra","Dalla luna","Dal cuore umano"],en:["From the sun, with Fohat and Prana","From the earth","From the moon","From the human heart"]},correct:0,note:{it:"Il Fuoco-serpentino è separato e distinto da Fohat e da Pràna.",en:"The Serpent Fire is separate and distinct from Fohat and Prana."}},
        {q:{it:"'Trishna', la causa della rincarnazione, è…",en:"'Trishna', the cause of reincarnation, is…"},options:{it:["La sete di esistenza","La paura della morte","Il debito karmico","La volontà divina"],en:["The thirst for existence","The fear of death","Karmic debt","Divine will"]},correct:0,note:{it:"È la sete di esperienza e di espressione che richiama l'ego verso una nuova vita.",en:"It is the thirst for experience and expression calling the ego towards a new life."}},
        {q:{it:"Passando dal kàmaloka al Devachan, l'uomo può portare con sé…",en:"Passing from kamaloka to Devachan, man can take with him…"},options:{it:["Solo i germi latenti nell'atomo astrale permanente","Tutte le sue passioni","I corpi astrali dei cari","Le forme-pensiero cattive"],en:["Only the latent germs in the permanent astral atom","All his passions","The astral bodies of loved ones","Evil thought-forms"]},correct:0,note:{it:"La materia devachanica non può rispondere alle vibrazioni grossolane delle passioni.",en:"Devachanic matter cannot respond to the coarse vibrations of the passions."}},
        {q:{it:"Il doppio eterico si estende oltre la superficie della pelle per circa…",en:"The etheric double extends beyond the surface of the skin by about…"},options:{it:["Mezzo centimetro","Parecchi centimetri","Un metro","Non la oltrepassa"],en:["Half a centimetre","Several centimetres","A metre","It does not go beyond it"]},correct:0,note:{it:"Parecchi centimetri è invece l'estensione dell'aura eterica, o aura della salute.",en:"Several centimetres is instead the extent of the etheric aura, or health aura."}},
        {q:{it:"Quando si producono in maggior quantità i globuli di vitalità?",en:"When are vitality globules produced in the greatest quantity?"},options:{it:["Quando il sole risplende","Di notte","Col tempo nuvoloso","Nelle notti di luna piena"],en:["When the sun shines","At night","In cloudy weather","On full-moon nights"]},correct:0,note:{it:"Durante la notte la produzione sembra cessare: viviamo della riserva prodotta il giorno prima.",en:"At night production seems to stop: we live on the reserve produced the day before."}},
        {q:{it:"Il corpo astrale riordinato in gusci dall'elementale del desiderio è detto…",en:"The astral body rearranged into shells by the desire-elemental is called…"},options:{it:["Yàtanà, o corpo della sofferenza","Mayavirupa","Stulopadhi","Pràmamayakosha"],en:["Yatana, or body of suffering","Mayavirupa","Sthulopadhi","Pranamayakosha"]},correct:0,note:{it:"In un uomo estremamente cattivo, con un corpo astrale di materia in gran parte grossolana, è detto Dhruvam, o corpo forte.",en:"In an extremely evil man, whose astral body is mostly of coarse matter, it is called Dhruvam, or strong body."}},
        {q:{it:"'Sùtratmà' significa letteralmente…",en:"'Sutratma' literally means…"},options:{it:["Il Filo dell'Io","Organo interno","Terra degli Dei","Ruota girante"],en:["The Thread of the Self","Inner organ","Land of the Gods","Spinning wheel"]},correct:0,note:{it:"Le particelle permanenti vi saranno infilate come perle su un cordone.",en:"The permanent particles will be strung on it like pearls on a cord."}},
        {q:{it:"Secondo Powell, qual è uno dei grandi vantaggi della cremazione?",en:"According to Powell, what is one of the great advantages of cremation?"},options:{it:["Toglie al corpo eterico il suo centro di attrazione e ne assicura una rapida decomposizione","Purifica il corpo astrale","Evita la seconda morte","Rende inutile il kàmaloka"],en:["It removes the etheric body's centre of attraction and ensures its rapid decomposition","It purifies the astral body","It avoids the second death","It makes kamaloka unnecessary"]},correct:0,note:{it:"La cremazione impedisce anche qualsiasi tentativo di anormale ricomposizione dei principi.",en:"Cremation also prevents any attempt at an abnormal recomposition of the principles."}},
        {q:{it:"Il quinto cielo, il più basso dei livelli senza forma, è…",en:"The fifth heaven, the lowest of the formless levels, is…"},options:{it:["La regione più popolosa di tutte","Abitato solo dai Maestri e dai loro allievi","Il cielo della devozione religiosa antropomorfica","Il cielo degli affetti famigliari"],en:["The most populous region of all","Inhabited only by the Masters and their pupils","The heaven of anthropomorphic religious devotion","The heaven of family affections"]},correct:0,note:{it:"Vi si trovano tutte le anime capaci di funzionare nel corpo causale. Il primo cielo è quello degli affetti famigliari, il secondo della devozione antropomorfica, il settimo dei Maestri.",en:"All souls able to function in the causal body are found there. The first heaven is that of family affections, the second of anthropomorphic devotion, the seventh of the Masters."}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✶",
      items: [
        {a:{it:"Base della colonna",en:"Base of the spine"},b:{it:"Kundalini",en:"Kundalini"}},
        {a:{it:"Milza",en:"Spleen"},b:{it:"Pràna",en:"Prana"}},
        {a:{it:"Cuore",en:"Heart"},b:{it:"Empatia astrale",en:"Astral empathy"}},
        {a:{it:"Gola",en:"Throat"},b:{it:"Udito astrale",en:"Astral hearing"}},
        {a:{it:"Fra le sopracciglia",en:"Between the eyebrows"},b:{it:"Vista astrale",en:"Astral sight"}},
        {a:{it:"Sommità del capo",en:"Crown of the head"},b:{it:"Pienezza delle\nfacoltà",en:"Fullness of\nfaculties"}},
        {a:{it:"Ombelico",en:"Navel"},b:{it:"Sensibilità\ngenerale",en:"General\nsensitivity"}},
        {a:{it:"Loto dai mille petali",en:"Thousand-petalled lotus"},b:{it:"960 raggi",en:"960 spokes"}}
      ]
    }
  }
};
})();
