/* LE LEGGI COSMICHE — data.js */
(function(){
"use strict";
window.GAME_DATA = {
  id: "leggi",
  modes: ["legge","specchio","quiz","memoria"],
  rings: [
    {key:"ottava",color:"#1a1326",ring:"#3a2f52",label:{it:"L'Ottava",en:"The Octave"}},
    {key:"risonanza",color:"#10212a",ring:"#2f5d6b",label:{it:"Risonanza",en:"Resonance"}},
    {key:"specchio",color:"#2a1410",ring:"#7c3a2a",label:{it:"Lo Specchio",en:"The Mirror"}},
    {key:"attrazione",color:"#3a2c10",ring:"#c9973a",label:{it:"Attrazione",en:"Attraction"}}
  ],
  modeDefs: {
    legge: { type:"scenario", roman:"I", glyph:"☉", optionKeys:[0,1,2,3], count:10,
      items: [
        {sit:{it:"Inizi un progetto con entusiasmo, ma dopo qualche settimana l'energia cala.",en:"You start a project with enthusiasm, but after a few weeks the energy drops."},correct:0,note:{it:"Legge dell'Ottava: fra MI e FA c'è un intervallo. Serve uno 'shock' per proseguire.",en:"Law of the Octave: between MI and FA there is an interval. A 'shock' is needed to continue."}},
        {sit:{it:"Ti lamenti del tuo posto di lavoro, ma non riesci mai a cambiarlo.",en:"You complain about your job, but never manage to change it."},correct:1,note:{it:"Legge di Risonanza: attiriamo la realtà più utile alla nostra evoluzione.",en:"Law of Resonance: we attract the reality most useful to our evolution."}},
        {sit:{it:"La mancanza di rispetto di un collega ti irrita, e ti chiedi in quali occasioni sei tu a non avere rispetto.",en:"A colleague's lack of respect irritates you, and you ask yourself on which occasions it is you who lack respect."},correct:2,note:{it:"Legge dello Specchio: «se la mancanza di rispetto non fosse già dentro di noi, non ci darebbe fastidio all'esterno».",en:"Law of the Mirror: 'if the lack of respect were not already within us, it would not bother us outside'."}},
        {sit:{it:"Critichi il modo di vestire di qualcuno e poi ti senti giudicato.",en:"You criticise someone's dressing and then feel judged yourself."},correct:3,note:{it:"Non-giudizio: giudizio verso altri e verso noi stessi sono due facce della stessa medaglia.",en:"Non-judgment: judgment toward others and toward ourselves are two sides of the same coin."}},
        {sit:{it:"Provi pietà per un disabile; il Cuore aperto proverebbe compassione.",en:"You feel pity for a disabled person; the open Heart would feel compassion."},correct:0,note:{it:"Legge dell'Ottava: pietà e compassione sono la stessa nota su due ottave diverse.",en:"Law of the Octave: pity and compassion are the same note on two different octaves."}},
        {sit:{it:"Dopo aver cambiato interiormente, le persone intorno cambiano.",en:"After changing inwardly, the people around you change too."},correct:1,note:{it:"Legge di Risonanza: nella misura in cui cambiamo, cambiano persone e luoghi che attiriamo.",en:"Law of Resonance: to the degree we change, the people and places we attract change too."}},
        {sit:{it:"Vedi un difetto 'oggettivo' nel mondo, ma stai osservando qualcosa dentro di te.",en:"You see an 'objective' flaw in the world, but you're observing something within yourself."},correct:2,note:{it:"Legge dello Specchio: la realtà ci fa da specchio. Vediamo solo ciò che siamo.",en:"Law of the Mirror: reality mirrors us. We see only what we are."}},
        {sit:{it:"Giudichi 'ricco' qualcuno e crei dentro di te il polo della povertà.",en:"You judge someone 'rich' and create within yourself the pole of poverty."},correct:3,note:{it:"Non-giudizio: il positivo crea il negativo. Nella dualità non c'è via d'uscita.",en:"Non-judgment: the positive creates the negative. In duality there is no way out."}},
        {sit:{it:"Due bulli ti prendono di mira. Più hai paura, più tornano.",en:"Two bullies single you out. The more you fear them, the more they come back."},correct:1,note:{it:"Attrazione/Risonanza: la paura emana dal corpo come un odore e attira ciò che temi.",en:"Attraction/Resonance: fear emanates from the body and attracts what you fear."}},
        {sit:{it:"Decidi di smettere di fumare, ma poco dopo l'inizio stai per ricominciare.",en:"You decide to quit smoking, but shortly after starting you're about to relapse."},correct:0,note:{it:"Legge dell'Ottava: è il primo punto di possibile interruzione, fra MI e FA.",en:"Law of the Octave: it is the first point of possible interruption, between MI and FA."}},
        {sit:{it:"Una coppia entra in crisi al settimo anno.",en:"A couple hits a crisis in the seventh year."},correct:0,note:{it:"Legge dell'Ottava, detta anche Legge del Sette: le interruzioni naturali dell'energia.",en:"Law of the Octave, also called the Law of Seven: the natural interruptions of energy."}},
        {sit:{it:"La domenica preferisci discutere di filosofia piuttosto che andare allo stadio.",en:"On Sundays you'd rather discuss philosophy than go to the stadium."},correct:1,note:{it:"Legge di Risonanza: il simile attrae il simile.",en:"Law of Resonance: like attracts like."}},
        {sit:{it:"Cambi partner, ma dopo un po' provi con quello nuovo gli stessi fastidi.",en:"You change partner, but after a while you feel the same irritations with the new one."},correct:2,note:{it:"Legge dello Specchio: la causa del nostro fastidio non può mai essere un evento oggettivo esterno.",en:"Law of the Mirror: the cause of our irritation can never be an objective external event."}},
        {sit:{it:"Non hai mai rubato, eppure i ladri ti danno molto fastidio.",en:"You've never stolen, yet thieves annoy you greatly."},correct:2,note:{it:"Legge dello Specchio: i ladri rispecchiano il nostro attaccamento alle cose materiali.",en:"Law of the Mirror: thieves mirror our attachment to material things."}},
        {sit:{it:"Ridi di chi scivola per le scale, e poi ti senti deriso quando sei tu a essere maldestro.",en:"You laugh at someone slipping on the stairs, then feel mocked when you are clumsy yourself."},correct:3,note:{it:"Non-giudizio: «Con l'intensità con la quale giudichiamo, ci sentiamo giudicati dal mondo circostante.»",en:"Non-judgment: 'With the intensity with which we judge, we feel judged by the world around us.'"}}
      ]
    },
    specchio: { type:"classify", roman:"II", glyph:"◇", optionKeys:[0,1], count:10,
      items: [
        {item:{it:"Cerchi di evitare l'interrogazione sperando che la maestra cambi idea",en:"You try to avoid the exam hoping the teacher will change her mind"},belongs:0,note:{it:"Pettini lo specchio: la paura del giudizio resta dentro di te.",en:"Combing the mirror: the fear of judgment remains inside you."}},
        {item:{it:"Osservi la sensazione di paura quando vedi i bulli arrivare",en:"You observe the sensation of fear when you see the bullies coming"},belongs:1,note:{it:"Lavori dall'interno: osservi il Piombo interiore senza rifiutarlo.",en:"Working from within: you observe the inner Lead without rejecting it."}},
        {item:{it:"Ti lamenti del mondo e aspetti che gli altri cambino",en:"You complain about the world and wait for others to change"},belongs:0,note:{it:"Solo indagando te stesso puoi cambiare il mondo.",en:"Only by examining yourself can you change the world."}},
        {item:{it:"Mandi amore alle parti del tuo corpo che vengono prese in giro",en:"You send love to the parts of your body that are made fun of"},belongs:1,note:{it:"Ami il modo in cui è fatto il tuo corpo. Altrimenti incontrerai sempre qualcuno a cui non piace.",en:"You love the way your body is made. Otherwise you'll always meet someone who doesn't like it."}},
        {item:{it:"Incolpi qualcun altro per ciò che ti è successo",en:"You blame someone else for what happened to you"},belongs:0,note:{it:"Nella Magia agisci all'interno per modificare l'esterno.",en:"In Magic you act within to change the outside."}},
        {item:{it:"Quando qualcosa ti dà disagio, pensi: 'Che parte di me sta emergendo?'",en:"When something makes you uneasy, you think: 'What part of me is emerging?'"},belongs:1,note:{it:"Dovresti essere contento: hai la possibilità di osservare un aspetto nascosto.",en:"You should be happy: you have the chance to observe a hidden aspect."}},
        {item:{it:"Ti concentri sulla frase 'Adesso sono presente' passando attraverso una porta",en:"You focus on 'Now I am present' while passing through a door"},belongs:1,note:{it:"Esercizio fondamentale di Presenza per renderti più sveglio nella vita quotidiana.",en:"Fundamental Presence exercise to make you more awake in daily life."}},
        {item:{it:"Speri che la sfortuna passi da sola, senza cambiare nulla di te",en:"You hope bad luck will pass on its own, without changing anything about yourself"},belongs:0,note:{it:"Non puoi sfuggire a una parte di te: ti seguirà ovunque andrai.",en:"You can't escape a part of yourself: it will follow you wherever you go."}},
        {item:{it:"Cambi lavoro per sfuggire a un collega che non sopporti, senza guardarti dentro",en:"You change job to escape a colleague you can't stand, without looking within"},belongs:0,note:{it:"Se il problema è dentro di te, nel nuovo lavoro incontrerai gli stessi impedimenti.",en:"If the problem is within you, you'll meet the same obstacles in the new job."}},
        {item:{it:"Cerchi di togliere le macchie dal viso pulendo lo specchio",en:"You try to remove the spots on your face by cleaning the mirror"},belongs:0,note:{it:"Le esperienze che ci accadono nel mondo sono l'effetto di quanto proviamo interiormente.",en:"The experiences that happen to us in the world are the effect of what we feel inside."}},
        {item:{it:"Non sopporti la mancanza di rispetto e ti chiedi quando sei tu a non rispettare gli altri",en:"You can't stand disrespect and ask yourself when you fail to respect others"},belongs:1,note:{it:"Seconda fase: cercare in noi stessi la caratteristica che ci disturba all'esterno.",en:"Second phase: looking in ourselves for the trait that bothers us outside."}},
        {item:{it:"Davanti a una notizia che ti irrita, osservi che cosa esattamente ti procura fastidio",en:"Faced with irritating news, you observe exactly what bothers you"},belongs:1,note:{it:"Prima fase della Legge dello Specchio, al posto di giudicare e condannare.",en:"First phase of the Law of the Mirror, instead of judging and condemning."}},
        {item:{it:"Consideri un 'nemico' come chi ti mostra un aspetto di te su cui lavorare",en:"You regard an 'enemy' as one who shows you an aspect of yourself to work on"},belongs:1,note:{it:"Applicata su vasta scala, la Legge dello Specchio basterebbe da sola a mutare la nostra civiltà.",en:"Applied on a wide scale, the Law of the Mirror alone would transform our civilisation."}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"Nella Legge dell'Ottava, gli intervalli si trovano fra…",en:"In the Law of the Octave, the intervals are between…"},options:{it:["MI–FA e SI–DO","DO–RE e FA–SOL","RE–MI e LA–SI","SOL–LA e DO–RE"],en:["MI–FA and SI–DO","DO–RE and FA–SOL","RE–MI and LA–SI","SOL–LA and DO–RE"]},correct:0,note:{it:"Come sulla tastiera: fra MI-FA e SI-DO non c'è il tasto nero.",en:"As on the keyboard: between MI-FA and SI-DO there is no black key."}},
        {q:{it:"Il 'pensiero verticale' è…",en:"'Vertical thinking' is…"},options:{it:["La capacità di cogliere il significato simbolico oltre l'apparenza","Il pensiero logico","Il dialogo interno","L'immaginazione negativa"],en:["The ability to grasp symbolic meaning beyond appearance","Logical thinking","Inner dialogue","Negative imagination"]},correct:0,note:{it:"La realtà parla per simboli: il pensiero simbolico coglie la Verità nascosta.",en:"Reality speaks through symbols: symbolic thinking grasps the hidden Truth."}},
        {q:{it:"Secondo la Legge di Risonanza, siamo sempre…",en:"According to the Law of Resonance, we are always…"},options:{it:["Nel posto migliore per la nostra evoluzione","Nel posto sbagliato","Dove il destino ci ha messo","Dove vogliono gli altri"],en:["In the best place for our evolution","In the wrong place","Where destiny put us","Where others want us"]},correct:0,note:{it:"Chi si lamenta del pianeta è chi ne ha più bisogno per la propria evoluzione.",en:"Whoever complains about the planet is the one who most needs it for evolution."}},
        {q:{it:"Secondo la Legge dello Specchio, la realtà esterna è…",en:"According to the Law of the Mirror, outer reality is…"},options:{it:["Una proiezione che riflette ciò che siamo","Indipendente da noi","Un caso senza senso","Creata dagli altri"],en:["A projection mirroring what we are","Independent of us","A meaningless accident","Created by others"]},correct:0,note:{it:"Vediamo solo ciò che siamo: il mondo è costruito a nostra immagine.",en:"We see only what we are: the world is built in our image."}},
        {q:{it:"La mente funziona in maniera…",en:"The mind works in a…"},options:{it:["Duale: come un processo binario","Unitaria e sintetica","Casuale","Sempre intuitiva"],en:["Dual way, like a binary process","Unitary and synthetic way","Random","Always intuitive"]},correct:0,note:{it:"Buono/cattivo, caldo/freddo: la mente conosce solo attraverso gli opposti.",en:"Good/bad, hot/cold: the mind knows only through opposites."}},
        {q:{it:"Per uscire dalla dualità bisogna…",en:"To exit duality one must…"},options:{it:["Identificarsi con l'anima e guardare dal Cuore","Pensare più forte","Scegliere sempre il polo positivo","Eliminare la mente"],en:["Identify with the soul and look from the Heart","Think harder","Always choose the positive pole","Eliminate the mind"]},correct:0,note:{it:"Il Cuore sintetizza e intuisce la perfezione di tutto ciò che accade.",en:"The Heart synthesises and intuits the perfection of all that happens."}},
        {q:{it:"«Un uomo non attrae ciò che vuole, bensì…» (Il bambino e il mago)",en:"'A man doesn't attract what he wants, but…' (The child and the magus)"},options:{it:["Ciò che è","Ciò che odia","Ciò che gli altri vogliono","Il caso"],en:["What he is","What he hates","What others want","Chance"]},correct:0,note:{it:"La causa è dentro, l'effetto è fuori. Il mondo riflette ciò che sei.",en:"The cause is inside, the effect is outside. The world reflects what you are."}},
        {q:{it:"La Gratitudine agisce come…",en:"Gratitude acts as…"},options:{it:["Un magnete: più ne hai, più attiri motivi per essere grato","Un sedativo","Un'illusione","Un obbligo morale"],en:["A magnet: the more you feel, the more reasons to be grateful you attract","A sedative","An illusion","A moral obligation"]},correct:0,note:{it:"Secondo segreto del Mago: la Gratitudine è una forza attrattiva.",en:"Second secret of the Magus: Gratitude is an attractive force."}},
        {q:{it:"Brizzi spiega la Legge di Risonanza con l'immagine…",en:"Brizzi explains the Law of Resonance with the image of…"},options:{it:["Del diapason che fa vibrare solo le corde accordate sulla stessa nota","Di uno specchio","Di una sinusoide","Di un computer binario"],en:["A tuning fork that makes only the strings tuned to the same note vibrate","A mirror","A sine wave","A binary computer"]},correct:0,note:{it:"Così, fra tutti i possibili posti di lavoro, solo uno ha risuonato con noi.",en:"Likewise, of all possible jobs, only one resonated with us."}},
        {q:{it:"La Legge dello Specchio può essere applicata…",en:"The Law of the Mirror can be applied…"},options:{it:["Solo a se stessi, non agli altri","Soprattutto a chi ci critica","A chiunque sbagli","Solo ai nemici"],en:["Only to oneself, not to others","Above all to those who criticise us","To anyone who errs","Only to enemies"]},correct:0,note:{it:"Non possiamo servircene per farci scudo dalle critiche degli altri.",en:"We cannot use it as a shield against others' criticism."}},
        {q:{it:"Ghiaccio, acqua e vapore sono…",en:"Ice, water and steam are…"},options:{it:["Tre ottave differenti della stessa sostanza","Tre sostanze diverse","Tre intervalli dell'ottava","Tre deviazioni dell'ottava"],en:["Three different octaves of the same substance","Three different substances","Three intervals of the octave","Three deviations of the octave"]},correct:0,note:{it:"A ogni passaggio la vibrazione raddoppia. Allo stesso modo Discepolo, Iniziato e Maestro sono tre ottave della stessa persona.",en:"At each step the vibration doubles. In the same way Disciple, Initiate and Master are three octaves of the same person."}},
        {q:{it:"Per passare dal MI al FA in un progetto serve…",en:"To pass from MI to FA in a project you need…"},options:{it:["Uno «shock addizionale» che porti nuova energia","Aspettare che l'energia torni da sola","Ricominciare da capo","Cambiare obiettivo"],en:["An 'additional shock' that brings new energy","Waiting for the energy to return by itself","Starting over","Changing goal"]},correct:0,note:{it:"Possiamo darlo a noi stessi o a chi vediamo in una fase di calo dell'energia.",en:"We can give it to ourselves or to someone we see in a slump."}},
        {q:{it:"In un progetto, i due punti di possibile interruzione cadono…",en:"In a project, the two points of possible interruption fall…"},options:{it:["Poco dopo l'inizio e poco prima della fine","Esattamente a metà","Solo alla fine","Solo all'inizio"],en:["Shortly after the start and shortly before the end","Exactly halfway","Only at the end","Only at the start"]},correct:0,note:{it:"Per questo un progetto che va a buon fine è l'eccezione.",en:"That is why a project that reaches completion is the exception."}},
        {q:{it:"«Il Cristianesimo che devia e diventa Inquisizione» è un esempio di…",en:"'Christianity that deviates and becomes the Inquisition' is an example of…"},options:{it:["Deviazione dell'ottava","Legge dello Specchio","Legge di Risonanza","Pensiero verticale"],en:["Deviation of the octave","Law of the Mirror","Law of Resonance","Vertical thinking"]},correct:0,note:{it:"Accumulando deviazioni, l'energia gira su se stessa fino a prendere la direzione opposta.",en:"As deviations accumulate, energy turns on itself until it takes the opposite direction."}},
        {q:{it:"Perché i ladri ci infastidiscono, anche se non abbiamo mai rubato?",en:"Why do thieves annoy us, even if we have never stolen?"},options:{it:["Perché rispecchiano il nostro identico attaccamento alle cose materiali","Perché siamo onesti","Perché la legge li condanna","Perché in questo caso la Legge dello Specchio non vale"],en:["Because they mirror our identical attachment to material things","Because we are honest","Because the law condemns them","Because in this case the Law of the Mirror doesn't apply"]},correct:0,note:{it:"«La Legge dello Specchio vale SEMPRE.»",en:"'The Law of the Mirror ALWAYS applies.'"}},
        {q:{it:"Secondo la Legge di Compensazione, a una certa quantità di felicità della personalità…",en:"According to the Law of Compensation, a given amount of the personality's happiness…"},options:{it:["Deve corrispondere un'identica quantità di infelicità","Segue sempre altra felicità","Non segue nulla","Segue il doppio di infelicità"],en:["Must be matched by an identical amount of unhappiness","Is always followed by more happiness","Is followed by nothing","Is followed by twice as much unhappiness"]},correct:0,note:{it:"Si può rappresentare con una sinusoide. Vale finché restiamo identificati con la personalità.",en:"It can be drawn as a sine wave. It holds as long as we remain identified with the personality."}},
        {q:{it:"La Legge di Compensazione riguarda…",en:"The Law of Compensation concerns…"},options:{it:["L'intensità del sentimento","La sua durata","Solo il denaro","Solo il corpo fisico"],en:["The intensity of the feeling","Its duration","Only money","Only the physical body"]},correct:0,note:{it:"Il rapporto è sempre di 1 a 1: una vita di euforia può compensarsi con una settimana di terribili sofferenze.",en:"The ratio is always 1 to 1: a life of euphoria can be compensated by a week of terrible suffering."}},
        {q:{it:"Non giudicare significa…",en:"Not judging means…"},options:{it:["Restare capaci di discriminare e di fare delle scelte","Accettare passivamente tutto","Frequentare chiunque","Non combattere mai per nulla"],en:["Remaining able to discern and to make choices","Passively accepting everything","Spending time with anyone","Never fighting for anything"]},correct:0,note:{it:"«Possiamo combattere per la libertà di un popolo, pur senza giudicare sbagliato il popolo oppressore.»",en:"'We can fight for a people's freedom without judging the oppressor people wrong.'"}},
        {q:{it:"«Gli uomini muscolosi sono belli.» Secondo Brizzi, questa frase…",en:"'Muscular men are beautiful.' According to Brizzi, this sentence…"},options:{it:["È anch'essa un giudizio: crea automaticamente il polo opposto","È una semplice constatazione neutra","È un'emozione superiore","È pensiero verticale"],en:["Is a judgment too: it automatically creates the opposite pole","Is a simple neutral observation","Is a higher emotion","Is vertical thinking"]},correct:0,note:{it:"Anche il giudizio positivo alimenta la dualità e il senso di separazione.",en:"Positive judgment too feeds duality and the sense of separation."}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✶",
      items: [
        {a:{it:"Legge dell'Ottava",en:"Law of the Octave"},b:{it:"Intervalli MI-FA\ne SI-DO",en:"Intervals MI-FA\nand SI-DO"}},
        {a:{it:"Legge di Risonanza",en:"Law of Resonance"},b:{it:"Il simile attrae\nil simile",en:"Like attracts\nlike"}},
        {a:{it:"Legge dello Specchio",en:"Law of the Mirror"},b:{it:"Vediamo solo\nciò che siamo",en:"We see only\nwhat we are"}},
        {a:{it:"Il Non-giudizio",en:"Non-judgment"},b:{it:"Uscire dalla\ndualità",en:"Exiting\nduality"}},
        {a:{it:"L'Attrazione",en:"Attraction"},b:{it:"La causa è dentro\nl'effetto è fuori",en:"Cause inside\neffect outside"}},
        {a:{it:"Il pensiero\nverticale",en:"Vertical\nthinking"},b:{it:"Cogliere il simbolo\noltre l'apparenza",en:"Grasping the symbol\nbeyond appearance"}},
        {a:{it:"Legge di\nCompensazione",en:"Law of\nCompensation"},b:{it:"La\nsinusoide",en:"The\nsine wave"}},
        {a:{it:"Shock\naddizionale",en:"Additional\nshock"},b:{it:"Passare\ndal MI al FA",en:"Passing\nfrom MI to FA"}},
        {a:{it:"Deviazione\ndell'ottava",en:"Octave\ndeviation"},b:{it:"Cristianesimo\n→ Inquisizione",en:"Christianity\n→ Inquisition"}}
      ]
    }
  }
};
})();
