/* ============================================================
   LA SACRA SESSUALITÀ — dati bilingue (IT / EN)
   Fonte: S. Brizzi, "La sacra sessualità" (Antipodi, 2017)
   Esposto come window.SS_DATA.
   ============================================================ */
(function () {
  "use strict";

  /* ---------- I. SACRO O PROFANO? ---------- */
  // belongs: 0 = Profano (possesso, meccanicità, paura), 1 = Sacro (Cuore, rituale, evoluzione)
  const SACRO = [
    { item: { it: "Fare sesso per sfregare organi e provare il brivido dell'orgasmo", en: "Having sex to rub organs and feel the thrill of orgasm" }, belongs: 0,
      note: { it: "«Il sesso è legato alla trasmissione dell'amore e non ha niente a che fare con lo sfregamento di due parti anatomiche e con il piacere fisico che ne deriva.»", en: "'Sex is linked to the transmission of love and has nothing to do with the rubbing of two anatomical parts and with the physical pleasure that derives from it.'" } },
    { item: { it: "Unirsi con l'intenzione di svolgere un rituale che avvicina a Dio", en: "Uniting with the intention of performing a ritual that draws one closer to God" }, belongs: 1,
      note: { it: "«Si prendeva la decisione di fare sesso come noi oggi prenderemmo la decisione di andare a messa.»", en: "'The decision to have sex was taken as we today would take the decision to go to mass.'" } },
    { item: { it: "Possedere il partner con tentacoli magnetici: la 'conquista'", en: "Possessing the partner with magnetic tentacles: the 'conquest'" }, belongs: 0,
      note: { it: "«Quella che oggi consideriamo la normalità di coppia, cioè un rapporto di coppia normale, una volta (ai tempi di cui vi sto parlando) era considerata magia nera, o meglio, magia rossa.»", en: "'What we today consider normality in a couple, that is, a normal couple relationship, was once (in the times I am telling you about) considered black magic, or rather, red magic.'" } },
    { item: { it: "Far salire l'energia sessuale nel Cuore come conseguenza dell'amore per i nemici", en: "Raising sexual energy into the Heart as a consequence of loving one's enemies" }, belongs: 1,
      note: { it: "«Una sessualità per così dire “iniziatica” giunge come conseguenza dell'apertura del proprio Cuore e non può esserne la causa.»", en: "'A so-called 'initiatic' sexuality comes as a consequence of the opening of one's own Heart and cannot be its cause.'" } },
    { item: { it: "Dipendere dal sesso come da una droga: cercare sensazioni sempre più estreme", en: "Depending on sex like a drug: seeking ever more extreme sensations" }, belongs: 0,
      note: { it: "«Fino a quando giungo a un punto tale che se non provo il brivido del sesso estremo o del sesso clandestino, non sento più nulla.»", en: "'Until I reach a point where if I don't feel the thrill of extreme or clandestine sex, I feel nothing anymore.'" } },
    { item: { it: "Commuoversi durante l'atto sessuale grazie alla totale Presenza", en: "Being moved during the sexual act thanks to total Presence" }, belongs: 1,
      note: { it: "«Mi è capitato più volte di sentire il Cuore infiammarsi e di commuovermi durante l'atto sessuale, semplicemente grazie al fatto di essere totalmente presente a me stesso.»", en: "'Several times I have felt my Heart catch fire and been moved during the sexual act, simply because I was totally present to myself.'" } },
    { item: { it: "Usare il sesso per 'segnare' il partner come un territorio", en: "Using sex to 'mark' the partner like a territory" }, belongs: 0,
      note: { it: "«Nella maggior parte dei casi [...] si fa l'amore per possedere un altro essere umano magicamente, cioè magneticamente.»", en: "'In most cases [...] one makes love to possess another human being magically, that is, magnetically.'" } },
    { item: { it: "Il Cuore come valore aggiunto che fa la differenza fra vecchia e nuova sessualità", en: "The Heart as the added value that makes the difference between old and new sexuality" }, belongs: 1,
      note: { it: "«In passato si conosceva la sessualità sacra nel senso che se ne conoscevano bene le applicazioni energetiche, ma mancava il Cuore, ed è questa assenza che ha potuto condurre alle deviazioni.»", en: "'In the past sacred sexuality was known in the sense that its energetic applications were well known, but the Heart was missing, and it is this absence that led to the deviations.'" } },
    { item: { it: "Imparare il sesso dai video pornografici come unico riferimento", en: "Learning about sex from pornographic videos as the only reference" }, belongs: 0,
      note: { it: "«In quei video il sesso è ancora più degradato rispetto alla realtà [...]. Tutto viene percepito nell'ottica della “prestazione”, come in un qualunque sport.»", en: "'In those videos sex is even more degraded than in reality [...]. Everything is perceived in terms of 'performance', as in any sport.'" } },
    { item: { it: "Lacrimare mentre si fa l'amore: qualcosa che ancora mancava ad Atlantide", en: "Weeping while making love: something that was still missing in Atlantis" }, belongs: 1,
      note: { it: "«Possiamo tornare a pensare e praticare il sesso in un altro modo, molto più elevato, con il Cuore aperto e la capacità di vedere la Bellezza ovunque, lacrimando mentre facciamo l'amore, qualcosa che ancora mancava ai tempi di Atlantide.»", en: "'We can go back to thinking of and practising sex in another, much higher way, with an open Heart and the ability to see Beauty everywhere, weeping as we make love, something that was still missing in the days of Atlantis.'" } },
    { item: { it: "Unirsi solo per uno scopo che precede l'atto e ne è la causa", en: "Uniting only for a purpose that precedes the act and is its cause" }, belongs: 1,
      note: { it: "«L'atto sessuale aveva sempre uno scopo che lo precedeva e ne era la causa, altrimenti non ci si univa.»", en: "'The sexual act always had a purpose that preceded it and was its cause; otherwise people did not unite.'" } },
    { item: { it: "Tenere il partner sotto controllo per dimostrargli che ci si tiene a lui", en: "Keeping the partner under control to show how much one cares" }, belongs: 0,
      note: { it: "«“Ti sto possedendo perché ti amo”, è esattamente il contrario dell'amore; invece viene confuso per l'amore.»", en: "''I am possessing you because I love you' is exactly the opposite of love; yet it is mistaken for love.'" } },
    { item: { it: "Essere fedeli per un riconoscimento fra anime, senza viverlo come un obbligo morale", en: "Being faithful out of a recognition between souls, without living it as a moral obligation" }, belongs: 1,
      note: { it: "È l'appartenenza: la fedeltà non è vissuta come una costrizione morale, ma come «la naturale conseguenza d'un riconoscimento animico».", en: "This is belonging: faithfulness is not lived as a moral constraint, but as 'the natural consequence of a recognition between souls'." } },
    { item: { it: "Cercare l'illuminazione con esercizi energetici forzati, pur di non perdonare un parente", en: "Seeking enlightenment through forced energy exercises, rather than forgiving a relative" }, belongs: 0,
      note: { it: "Spera di farlo a casa sua, nella sua cameretta, «senza dover amare i propri nemici, che si trovano nel mondo reale».", en: "He hopes to do it at home, in his little room, 'without having to love his enemies, who are in the real world'." } },
    { item: { it: "Continuare ad amare e conservare nel Cuore anche chi ci ha detto di no", en: "Continuing to love, and keeping in one's Heart, even someone who said no to us" }, belongs: 1,
      note: { it: "«Imparare ad amare e conservare nel vostro Cuore anche chi vi dice di no.»", en: "'Learning to love, and to keep in your Heart, even those who say no to you.'" } },
    { item: { it: "Mostrare il partner agli amici come un bel manichino da sfoggiare", en: "Showing the partner off to friends like a fine mannequin" }, belongs: 0,
      note: { it: "«Chiediti se l'altro lo consideri davvero più importante di te.»", en: "'Ask yourself whether you really consider the other more important than yourself.'" } }
  ];

  /* ---------- II. LE TRE FASI DELLA COPPIA (scenari — 3 opzioni) ---------- */
  // correct: 0 = Euforia (maschere), 1 = Crisi (emersione ombre), 2 = Intimità autentica
  const FASI = [
    { sit: { it: "Entrambi indossano maschere e puntano sull'apparenza e sulla performance sessuale.",
        en: "Both wear masks and focus on appearance and sexual performance." },
      correct: 0,
      note: { it: "Prima fase — Euforia: «Utilizziamo delle “maschere sessuali” [...] per nascondere le paure più profonde: la paura di non valere niente.»", en: "First phase — Euphoria: 'We use 'sexual masks' [...] to hide the deepest fears: the fear of being worthless.'" } },
    { sit: { it: "Emergono paure, insicurezze e disfunzioni fisiche: più l'intimità cresce, più ci si sente vulnerabili.",
        en: "Fears, insecurities and physical dysfunctions emerge: the more intimacy grows, the more vulnerable one feels." },
      correct: 1,
      note: { it: "Seconda fase — Crisi: «Più diventiamo intimi con qualcuno, più diventiamo vulnerabili, e questo fa anche sì che crescano le paure, le insicurezze... oppure la noia.»", en: "Second phase — Crisis: 'The more intimate we become with someone, the more vulnerable we become, and this also makes fears and insecurities grow... or boredom.'" } },
    { sit: { it: "I partner si mettono a nudo (fisicamente e psicologicamente) senza più maschere.",
        en: "The partners bare themselves (physically and psychologically) without masks." },
      correct: 2,
      note: { it: "Terza fase — Intimità autentica: «O si è disposti a 'morire' alla propria vecchia immagine, oppure non si creerà mai una coppia reale.»", en: "Third phase — Authentic intimacy: 'Either you are willing to 'die' to your old image, or you will never create a real couple.'" } },
    { sit: { it: "Lei decide di separarsi perché 'non è più innamorata', dopo che l'eccitazione è svanita.",
        en: "She decides to separate because she's 'no longer in love', after the excitement faded." },
      correct: 1,
      note: { it: "Strategia di evitamento della seconda fase: «Uno o entrambi i partner [...] giungono alla conclusione che non sono più innamorati o che non sono caratterialmente compatibili e abbandonano il rapporto di coppia.»", en: "Avoidance strategy of the second phase: 'One or both partners [...] come to the conclusion that they are no longer in love or are not compatible in character, and abandon the couple relationship.'" } },
    { sit: { it: "Davanti alle paure emerse nella coppia, lui cerca di nascosto con un'altra l'eccitazione dell'inizio.",
        en: "Faced with the fears that have surfaced in the couple, he secretly seeks the excitement of the beginning with someone else." },
      correct: 1,
      note: { it: "Terza strategia di evitamento: «uno o entrambi tornano a rivivere clandestinamente la prima fase euforica della sessualità di coppia, ma adesso con altri partner».", en: "Third avoidance strategy: 'one or both go back to secretly reliving the first euphoric phase of the couple's sexuality, but now with other partners'." } },
    { sit: { it: "Ammettere un'insicurezza, condividerla: questo fa crescere l'intimità.",
        en: "Admitting an insecurity, sharing it: this grows intimacy." },
      correct: 2,
      note: { it: "Terza fase: «Nessuna insicurezza deve essere fonte di vergogna, anzi, ammettere un'insicurezza, condividendola, fa crescere l'intimità; proprio quell'intimità che si è cercato di evitare nella prima fase.»", en: "Third phase: 'No insecurity should be a source of shame; on the contrary, admitting an insecurity, sharing it, makes intimacy grow; precisely the intimacy one tried to avoid in the first phase.'" } },
    { sit: { it: "Passione ed eccitazione al massimo: ma non c'è ancora un contatto profondo.",
        en: "Passion and excitement at their peak: but there is no deep contact yet." },
      correct: 0,
      note: { it: "Prima fase — Euforia sessuale: «Per quanto possa sembrare una bella fase, in realtà non c'è ancora un contatto profondo e intimo fra i due partner.»", en: "First phase — Sexual euphoria: 'However beautiful this phase may seem, in reality there is no deep and intimate contact between the two partners yet.'" } },
    { sit: { it: "Il rapporto di coppia serve a far emergere le nostre ferite, non a farci sentire bene.",
        en: "The couple relationship serves to bring our wounds to the surface, not to make us feel good." },
      correct: 2,
      note: { it: "Terza fase: «il suo ruolo è quello di far emergere le nostre ferite [...]. Il partner non è il tappabuchi per i nostri vuoti interiori.»", en: "Third phase: 'his role is to bring our wounds to the surface [...]. The partner is not a stopgap for our inner voids.'" } },
    { sit: { it: "Due partner vivono insieme da anni, fanno l'amore regolarmente, ma restano distanti nel profondo.",
        en: "Two partners live together for years, make love regularly, but remain distant deep down." },
      correct: 1,
      note: { it: "Seconda strategia di evitamento: «Si stipula un tacito accordo nel quale si decide di non conoscersi mai al cento per cento.»", en: "Second avoidance strategy: 'A tacit agreement is reached to never fully know each other.'" } },
    { sit: { it: "Nei primi mesi lei ha da lui un'attenzione costante e si sente al centro del suo mondo.",
        en: "In the first months she gets his constant attention and feels at the centre of his world." },
      correct: 0,
      note: { it: "Prima fase — Euforia: «Se nella prima fase, quella euforica, avevamo la sua costante attenzione, nella seconda questa verrà a mancare.»", en: "First phase — Euphoria: 'If in the first, euphoric phase we had his constant attention, in the second it will be lacking.'" } },
    { sit: { it: "Col passare del tempo quell'attenzione costante viene a mancare e lei se ne sente privata.",
        en: "As time goes by that constant attention fades and she feels deprived of it." },
      correct: 1,
      note: { it: "Seconda fase — Crisi: dell'attenzione avuta nella fase euforica, «nella seconda questa verrà a mancare».", en: "Second phase — Crisis: of the attention received in the euphoric phase, 'in the second it will be lacking'." } },
    { sit: { it: "Lei sente la mancanza di attenzione, ma resta e la guarda in faccia invece di fuggire.",
        en: "She feels the lack of attention, but stays and faces it instead of running away." },
      correct: 2,
      note: { it: "Terza fase: «Nella terza fase dovremo quindi fare i conti con questa mancanza, resistendo alla tentazione di fuggire.»", en: "Third phase: 'In the third phase we will therefore have to come to terms with this lack, resisting the temptation to flee.'" } },
    { sit: { it: "Una coppia salta quasi del tutto l'entusiasmo iniziale: le difficoltà compaiono fin dall'inizio.",
        en: "A couple almost skips the initial enthusiasm: difficulties appear right from the start." },
      correct: 1,
      note: { it: "Alcune coppie passano direttamente alla seconda fase: i partner «hanno ereditato delle difficoltà dalle incarnazioni precedenti, a causa del karma sessuale accumulato».", en: "Some couples go straight to the second phase: the partners 'have inherited difficulties from previous incarnations, because of accumulated sexual karma'." } },
    { sit: { it: "Lui ammette che il suo bisogno di dimostrarsi all'altezza nasce da qualcosa che deve ancora provare a suo padre.",
        en: "He admits that his need to prove himself comes from something he still has to prove to his father." },
      correct: 2,
      note: { it: "Terza fase: riconoscere la paura dietro la maschera è «l'inizio di una trasformazione che porterà al vero amore».", en: "Third phase: recognising the fear behind the mask is 'the beginning of a transformation that will lead to true love'." } },
    { sit: { it: "Lei scopre che la sua chiusura verso di lui nasce dalla paura di arrendersi e perdere il controllo.",
        en: "She discovers that her closing off towards him comes from the fear of surrendering and losing control." },
      correct: 2,
      note: { it: "Terza fase: riconoscere «la paura di essere invasa, perdendo il controllo del territorio» è l'inizio della trasformazione.", en: "Third phase: recognising 'the fear of being invaded, losing control of the territory' is the beginning of transformation." } }
  ];

  /* ---------- III. QUIZ DELLA SACRA SESSUALITÀ ---------- */
  const QUIZ = [
    { q: { it: "La «ierà porneusis» (prostituzione sacra) nell'antichità era…", en: "The 'hierà porneusis' (sacred prostitution) in antiquity was…" },
      options: { it: ["Un rituale sacro d'avvicinamento a Dio", "Un mercato del piacere", "Un crimine", "Una forma di schiavitù"], en: ["A sacred ritual of approach to God", "A pleasure market", "A crime", "A form of slavery"] }, correct: 0,
      note: { it: "«Non poteva esserci sesso se non all'interno della sfera del sacro.» Le sacerdotesse istruivano alla sessualità i giovani uomini e le giovani donne.", en: "'There could be no sex except within the sphere of the sacred.' Priestesses instructed young men and young women in sexuality." } },
    { q: { it: "La Confessione originariamente era…", en: "Confession originally was…" },
      options: { it: ["Un atto terapeutico del sacerdote-guaritore", "Un elenco di peccati morali", "Un rituale di punizione", "Una formalità burocratica"], en: ["A therapeutic act of the priest-healer", "A list of moral sins", "A punishment ritual", "A bureaucratic formality"] }, correct: 0,
      note: { it: "«Il sacerdote era un terapeuta, un guaritore che ti permetteva di compiere un tuo percorso, ti dava delle indicazioni, degli esercizi, che potevano essere delle preghiere oppure no.»", en: "'The priest was a therapist, a healer who allowed you to walk your own path; he gave you guidance and exercises, which might or might not be prayers.'" } },
    { q: { it: "Fare sesso 'solo per procreare' originariamente significava…", en: "'Having sex only to procreate' originally meant…" },
      options: { it: ["Far incarnare consapevolmente anime di alta levatura spirituale", "Reprimere il piacere per motivi morali", "Limitare la popolazione", "Obbedire a un dogma senza significato"], en: ["Consciously letting souls of high spiritual stature incarnate", "Repressing pleasure for moral reasons", "Limiting population", "Obeying a meaningless dogma"] }, correct: 0,
      note: { it: "«A seconda della levatura spirituale delle due persone che si univano sessualmente, poteva nascere un'anima d'un tipo piuttosto che d'un altro.»", en: "'Depending on the spiritual stature of the two people uniting sexually, a soul of one kind rather than another could be born.'" } },
    { q: { it: "Il 'karma sessuale' di chi ha difficoltà sessuali indica…", en: "The 'sexual karma' of those with sexual difficulties indicates…" },
      options: { it: ["Un potenziale sessuale maggiore, mal utilizzato in vite passate", "Una punizione divina", "Mancanza di energia sessuale", "Cattiva sorte"], en: ["A greater sexual potential, misused in past lives", "A divine punishment", "Lack of sexual energy", "Bad luck"] }, correct: 0,
      note: { it: "«Le difficoltà sessuali si associano sempre a un grande potenziale sessuale.»", en: "'Sexual difficulties are always associated with a great sexual potential.'" } },
    { q: { it: "La vera libertà sessuale è…", en: "True sexual freedom is…" },
      options: { it: ["Libertà dai meccanismi psicologici di prestazione e giudizio", "Poter fare qualunque cosa si desideri", "Assenza di regole", "Libertinaggio sfrenato"], en: ["Freedom from the psychological mechanisms of performance and judgment", "Being able to do anything one wants", "The absence of rules", "Unbridled libertinage"] }, correct: 0,
      note: { it: "«La mia sessualità è libera non quando posso utilizzare tutte le posizioni che voglio [...], ma quando non sono più costretto a pensare alle mie dimensioni e alla mia prestazione.»", en: "'My sexuality is free not when I can use all the positions I want [...], but when I am no longer forced to think about my size and my performance.'" } },
    { q: { it: "Il giudizio sessuale è…", en: "Sexual judgment is…" },
      options: { it: ["La vera malattia psichica dei nostri tempi, all'origine di ogni paura sessuale", "Un difetto minore", "Una protezione naturale", "Irrilevante per la sessualità"], en: ["The true psychic disease of our times, at the root of every sexual fear", "A minor flaw", "A natural protection", "Irrelevant to sexuality"] }, correct: 0,
      note: { it: "«Uscire dal giudizio è una strada — decisamente sottovalutata e poco praticata — per giungere al risveglio spirituale.»", en: "'Getting out of judgment is a path (decidedly underrated and little practised) to spiritual awakening.'" } },
    { q: { it: "Le sacerdotesse torneranno perché…", en: "Priestesses will return because…" },
      options: { it: ["Stiamo entrando in un'era femminile: restaurazione dei Misteri", "La storia si ripete identica", "Lo dice la scienza", "Lo decidono i governi"], en: ["We are entering a feminine era: restoration of the Mysteries", "History repeats itself identically", "Science says so", "Governments decide it"] }, correct: 0,
      note: { it: "«Tutto ciò che in passato possedeva una sacralità, la recupererà di nuovo in futuro, ma su un piano superiore.»", en: "'Everything that once possessed sacredness will recover it in the future, but on a higher plane.'" } },
    { q: { it: "Nella sessualità sacra, la penetrazione diventa…", en: "In sacred sexuality, penetration becomes…" },
      options: { it: ["L'aspetto meno importante rispetto a ciò che c'è intorno", "L'unico scopo del rapporto", "Un atto meccanico da perfezionare", "Irrilevante"], en: ["The least important aspect compared to what surrounds it", "The sole purpose of the relationship", "A mechanical act to perfect", "Irrelevant"] }, correct: 0,
      note: { it: "«Alla fine non ti ricordi neanche più cosa è successo [...]. L'abbiamo fatto, ma abbiamo vissuto tante di quelle esperienze che il momento dello sfregamento degli organi sessuali è passato in secondo piano.»", en: "'In the end you don't even remember what happened [...]. We did it, but we lived so many experiences that the moment of the rubbing of the sexual organs faded into the background.'" } },
    { q: { it: "Il rapporto fra magia sessuale e apertura del Cuore è…", en: "The relationship between sexual magic and the opening of the Heart is…" },
      options: { it: ["Il Cuore si apre prima; la sessualità sacra ne è la conseguenza", "La sessualità sacra apre il Cuore", "Non hanno alcun rapporto", "Sono la stessa cosa"], en: ["The Heart opens first; sacred sexuality is the consequence", "Sacred sexuality opens the Heart", "They have no relationship", "They are the same thing"] }, correct: 0,
      note: { it: "«Non è mai possibile mettere il carro davanti ai buoi.» Chi lavora su di sé con «la Presenza nel qui-e-ora, il non-giudizio, la capacità di amare i propri nemici» giunge naturalmente a indirizzare l'energia verso l'alto.", en: "'You can never put the cart before the horse.' Whoever works on himself with 'Presence in the here-and-now, non-judgment, the ability to love one's enemies' naturally comes to direct the energy upward." } },
    { q: { it: "Secondo il «karma sessuale», le difficoltà sessuali di oggi nascono da…", en: "According to 'sexual karma', today's sexual difficulties arise from…" },
      options: { it: ["L'abuso dell'energia sessuale per fini personali in vite passate", "Il caso", "Una punizione divina", "Una scarsa energia sessuale"], en: ["The abuse of sexual energy for personal ends in past lives", "Chance", "A divine punishment", "Weak sexual energy"] }, correct: 0,
      note: { it: "«Non si hanno problemi sessuali “a caso”.» E non è una punizione: «ti viene data ancora una volta la possibilità di lavorare sulla tua sessualità».", en: "'One does not have sexual problems by chance.' Nor is it a punishment: 'you are given once again the chance to work on your sexuality'." } },
    { q: { it: "Che cosa è «sacro», secondo Brizzi?", en: "What is 'sacred', according to Brizzi?" },
      options: { it: ["Tutto ciò che permette una crescita interiore e avvicina all'Uno", "Ciò che una religione dichiara tale", "Ciò che è molto antico", "Ciò che è proibito"], en: ["Everything that allows inner growth and brings one closer to the One", "Whatever a religion declares to be so", "Whatever is very old", "Whatever is forbidden"] }, correct: 0,
      note: { it: "«Sto parlando di sacro, non di religioso, e sono due cose diverse.» Erano sacri il mangiare, l'abitare, il respirare.", en: "'I am speaking of the sacred, not the religious, and they are two different things.' Eating, dwelling and breathing were sacred." } },
    { q: { it: "Che cosa intende il libro per «società tradizionale»?", en: "What does the book mean by a 'traditional society'?" },
      options: { it: ["Una comunità in cui ogni ambito della vita sociale ha come scopo l'evoluzione interiore", "Una società contadina", "Una società che rifiuta la tecnologia", "Una società governata dai sacerdoti"], en: ["A community in which every area of social life aims at inner evolution", "A farming society", "A society that rejects technology", "A society ruled by priests"] }, correct: 0,
      note: { it: "Economia, politica, scienza, arte ed educazione avevano tutte lo scopo di mantenere vivo il rapporto fra l'uomo e Dio.", en: "Economy, politics, science, art and education all aimed at keeping alive the relationship between man and God." } },
    { q: { it: "Il karma, secondo il libro, è…", en: "Karma, according to the book, is…" },
      options: { it: ["Cause che producono effetti, senza punizione né moralità", "Una punizione per le azioni sbagliate", "Un giudizio morale di Dio", "Il destino già scritto"], en: ["Causes producing effects, with no punishment and no morality", "A punishment for wrong actions", "God's moral judgment", "A fate already written"] }, correct: 0,
      note: { it: "«Se mi butto dal balcone mi spiaccico al suolo. È una legge karmica. Questo non significa che Dio mi ha punito perché ho fatto qualcosa di sbagliato.»", en: "'If I throw myself off the balcony I hit the ground. It is a karmic law. This does not mean that God has punished me because I did something wrong.'" } },
    { q: { it: "Perché cerchiamo di possedere qualcuno?", en: "Why do we try to possess someone?" },
      options: { it: ["Perché ci sentiamo separati da lui", "Perché lo amiamo più degli altri", "Per proteggerlo", "Per istinto di sopravvivenza"], en: ["Because we feel separate from them", "Because we love them more than others", "To protect them", "Out of survival instinct"] }, correct: 0,
      note: { it: "«Tutte le volte che cerchiamo di possedere qualcuno o qualcosa è solo perché ci sentiamo separati da esso.» E ancora: «Se ti possiedo, a ben guardare, è perché non ti amo.»", en: "'Whenever we try to possess someone or something it is only because we feel separate from it.' And again: 'If I possess you, on closer inspection, it is because I do not love you.'" } },
    { q: { it: "Qual è l'ottava alta del possesso?", en: "What is the higher octave of possession?" },
      options: { it: ["L'appartenenza, che nasce dal Cuore", "La gelosia", "Il matrimonio", "L'indifferenza"], en: ["Belonging, which arises from the Heart", "Jealousy", "Marriage", "Indifference"] }, correct: 0,
      note: { it: "«Nel possesso è sempre implicata l'energia sessuale. [...] Nell'appartenenza invece è implicata l'energia del Cuore.»", en: "'Possession always involves sexual energy. [...] Belonging instead involves the energy of the Heart.'" } },
    { q: { it: "Su Atlantide il senso del possesso…", en: "In Atlantis the sense of possession…" },
      options: { it: ["Era radicato e serviva a entrare meglio nella materia", "Era del tutto sconosciuto", "Era punito dalla legge", "Era riservato ai re"], en: ["Was deep-rooted and served to enter matter more fully", "Was completely unknown", "Was punished by law", "Was reserved for kings"] }, correct: 0,
      note: { it: "Oggi è il contrario: «Il possesso è esattamente il contrario dell'evoluzione spirituale, in questo periodo storico.»", en: "Today it is the opposite: 'Possession is exactly the opposite of spiritual evolution, in this historical period.'" } },
    { q: { it: "Se nella coppia uno dei due manifesta una difficoltà, la responsabilità è…", en: "If one partner in a couple shows a difficulty, the responsibility is…" },
      options: { it: ["Sempre al 50%: il lavoro interiore si fa insieme", "Tutta di chi ha la difficoltà", "Del medico che deve curarla", "Di nessuno"], en: ["Always 50%: inner work is done together", "Entirely that of the one with the difficulty", "The doctor's, who must treat it", "Nobody's"] }, correct: 0,
      note: { it: "«Sei tu che l'hai incontrato, sei tu che lo stai richiamando, sei tu che hai bisogno di questa esperienza.»", en: "'You are the one who met him, you are the one calling him, you are the one who needs this experience.'" } },
    { q: { it: "Secondo la Legge dello Specchio, il giudizio che leggo negli occhi dell'altro…", en: "According to the Law of the Mirror, the judgment I read in the other's eyes…" },
      options: { it: ["Lo sento solo nella misura in cui io stesso mi giudico", "È sempre reale", "Dipende da quanto l'altro mi conosce", "Si supera cambiando partner"], en: ["I feel it only insofar as I judge myself", "Is always real", "Depends on how well the other knows me", "Is overcome by changing partner"] }, correct: 0,
      note: { it: "«Il giudizio che avverto non è oggettivo, non esiste fuori di me, perché è letteralmente creato da me, dal mio modo di vedere la vita.»", en: "'The judgment I sense is not objective, it does not exist outside me, because it is literally created by me, by my way of seeing life.'" } },
    { q: { it: "Qual è la chiave per uscire dal giudizio?", en: "What is the key to getting out of judgment?" },
      options: { it: ["La Presenza nel qui-e-ora, applicata a lungo", "Imporsi da domani di non giudicare nessuno", "Evitare le persone che giudicano", "Leggere testi sacri"], en: ["Presence in the here-and-now, applied over time", "Resolving from tomorrow to judge nobody", "Avoiding people who judge", "Reading sacred texts"] }, correct: 0,
      note: { it: "«Giudichiamo noi stessi, quindi giudichiamo gli altri e di conseguenza ci sentiamo giudicati dagli altri. Sono le tre facce d'una stessa medaglia.»", en: "'We judge ourselves, so we judge others and consequently we feel judged by others. They are three faces of the same coin.'" } },
    { q: { it: "La «restaurazione dei Misteri» non sarà un ritorno al passato perché…", en: "The 'restoration of the Mysteries' will not be a return to the past because…" },
      options: { it: ["L'evoluzione è ciclica ma sale a spirale", "Il passato non è mai esistito", "Mancano i testi antichi", "Le leggi lo vietano"], en: ["Evolution is cyclical but rises in a spiral", "The past never existed", "The ancient texts are missing", "The law forbids it"] }, correct: 0,
      note: { it: "«Non torneremo a ciò che è stato nel passato, in quanto niente torna come prima, ma vivremo una nuova sacralità, più elevata rispetto a quella che abbiamo perduto.»", en: "'We will not return to what was in the past, since nothing returns as before, but we will live a new sacredness, higher than the one we have lost.'" } },
    { q: { it: "Nella restaurazione dei Misteri, il mistero più grande sarà la Pietra Filosofale, cioè…", en: "In the restoration of the Mysteries, the greatest mystery will be the Philosophers' Stone, that is…" },
      options: { it: ["La capacità di cogliere una commovente Bellezza nel mondo", "Una tecnica energetica segreta", "La trasformazione dei metalli", "Un testo antico ritrovato"], en: ["The ability to perceive a moving Beauty in the world", "A secret energy technique", "The transformation of metals", "A rediscovered ancient text"] }, correct: 0,
      note: { it: "È «una diretta conseguenza dell'apertura del Cuore».", en: "It is 'a direct consequence of the opening of the Heart'." } },
    { q: { it: "Come si impara a vivere con il Cuore aperto, secondo l'ultimo capitolo?", en: "How does one learn to live with an open Heart, according to the last chapter?" },
      options: { it: ["Stando accanto a qualcuno il cui Cuore è già aperto", "Leggendo molti libri", "Con un seminario di un fine settimana", "Da soli, senza nessuno"], en: ["By staying close to someone whose Heart is already open", "By reading many books", "Through a weekend seminar", "Alone, with nobody"] }, correct: 0,
      note: { it: "È la trasmissione fra maestro e allievo: una vibrazione cardiaca «non può essere imparata autonomamente, perché non si tratta d'una nozione intellettuale».", en: "It is the transmission between master and pupil: a vibration of the heart 'cannot be learned on one's own, because it is not an intellectual notion'." } }
  ];

  /* ---------- IV. MEMORIA: SACRO ↔ DEGENERAZIONE ---------- */
  const MEMORY = [
    { a: { it: "Prostituzione\nsacra", en: "Sacred\nprostitution" }, b: { it: "Iniziazione\nsessuale", en: "Sexual\ninitiation" } },
    { a: { it: "Confessione", en: "Confession" }, b: { it: "Terapia del\nsacerdote-guaritore", en: "Therapy of the\npriest-healer" } },
    { a: { it: "Fare sesso\nper procreare", en: "Sex for\nprocreation" }, b: { it: "Far incarnare\nanime elevate", en: "Letting elevated\nsouls incarnate" } },
    { a: { it: "Il pos-sesso", en: "Pos-session" }, b: { it: "Magia rossa:\nlegatura d'amore", en: "Red magic:\nlove binding" } },
    { a: { it: "La vera libertà\nsessuale", en: "True sexual\nfreedom" }, b: { it: "Libertà dal giudizio\ne dalla prestazione", en: "Freedom from judgment\nand performance" } },
    { a: { it: "La messa\nautentica", en: "The authentic\nmass" }, b: { it: "Trasmissione\neucaristica", en: "Eucharistic\ntransmission" } },
    { a: { it: "Sacer-dote", en: "Sacer-dos\n(priest)" }, b: { it: "Dispensare\nil sacro", en: "Dispensing\nthe sacred" } },
    { a: { it: "Magnetismo\nlunare", en: "Lunar\nmagnetism" }, b: { it: "Viene dalla\npersonalità", en: "Comes from the\npersonality" } },
    { a: { it: "Magnetismo\nsolare", en: "Solar\nmagnetism" }, b: { it: "Viene\ndall'anima", en: "Comes from\nthe soul" } }
  ];

  const RINGS = [
    { key: "misteri", color: "#1a1326", ring: "#3a2f52", label: { it: "I Misteri", en: "The Mysteries" } },
    { key: "cuore", color: "#2a1410", ring: "#7c3a2a", label: { it: "Il Cuore", en: "The Heart" } },
    { key: "coppia", color: "#10212a", ring: "#2f5d6b", label: { it: "La Coppia", en: "The Couple" } },
    { key: "sacro", color: "#3a2c10", ring: "#c9973a", label: { it: "Il Sacro", en: "The Sacred" } }
  ];

  window.GAME_DATA = {
  id: "sess",
  modes: ["sacro","fasi","quiz","memoria"],
  rings: RINGS,
  modeDefs: {
    sacro: { type:"classify", roman:"I", glyph:"☉", optionKeys:[0,1], count:10, items: SACRO },
    fasi: { type:"scenario", roman:"II", glyph:"◐", optionKeys:[0,1,2], count:10, items: FASI },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10, items: QUIZ },
    memoria: { type:"memory", roman:"IV", glyph:"✶", items: MEMORY }
  }
};
})();
