/* LA MAGIA BIANCA — data.js (dalle opere di Alice A. Bailey) */
(function(){
"use strict";
window.GAME_DATA = {
  id: "magia",
  modes: ["aspetto","regole","quiz","memoria"],
  rings: [
    {key:"monade",color:"#1a1326",ring:"#7a5ab0",label:{it:"Monade",en:"Monad"}},
    {key:"anima",color:"#10212a",ring:"#3a7c9a",label:{it:"Anima",en:"Soul"}},
    {key:"personalita",color:"#2a1410",ring:"#c9973a",label:{it:"Personalità",en:"Personality"}}
  ],
  modeDefs: {
    aspetto: { type:"scenario", roman:"I", glyph:"△", optionKeys:[0,1,2], count:10,
      items: [
        {sit:{it:"Lo Spirito universale in te: il settimo principio, la scintilla divina che dimora nei piani più alti.",en:"The universal Spirit in you: the seventh principle, the divine spark dwelling on the highest planes."},correct:0,note:{it:"Atma: «Lo Spirito universale; la Monade divina; il settimo Principio» (glossario di Iniziazione umana e solare).",en:"Atma: 'The universal Spirit; the divine Monad; the seventh Principle' (glossary of Initiation, Human and Solar)."}},
        {sit:{it:"L'Angelo Solare che si raccoglie e, in profonda meditazione, comunica con il suo riflesso.",en:"The Solar Angel that recollects itself and, in deep meditation, communes with its reflection."},correct:1,note:{it:"È la Regola Uno: l'Angelo Solare è l'anima, il cui 'riflesso' è la personalità nei tre mondi.",en:"This is Rule One: the Solar Angel is the soul, whose 'reflection' is the personality in the three worlds."}},
        {sit:{it:"Il riflesso inferiore: il triplice veicolo fatto di corpo fisico, emozioni e mente concreta.",en:"The lower reflection: the threefold vehicle made of physical body, emotions and concrete mind."},correct:2,note:{it:"È la 'triplice personalità' che la luce maggiore dell'anima illumina (Regola Due): i veicoli con cui l'anima opera nei tre mondi.",en:"It is the 'threefold personality' illumined by the greater light of the soul (Rule Two): the vehicles through which the soul works in the three worlds."}},
        {sit:{it:"La 'luce maggiore' che illumina i tre e rende possibile il lavoro dei quattro.",en:"The 'greater light' that illumines the three and makes the work of the four possible."},correct:1,note:{it:"Regola Due: la luce maggiore è quella dell'anima, che illumina la triplice personalità.",en:"Rule Two: the greater light is that of the soul, illumining the threefold personality."}},
        {sit:{it:"La 'luce inferiore' nascosta sul piano fisico, che dev'essere proiettata verso l'alto.",en:"The 'lesser light' hidden on the physical plane, which must be thrown upward."},correct:2,note:{it:"Regola Due: la luce latente nell'uomo fisico sale per fondersi con la luce dell'anima.",en:"Rule Two: the light latent in physical man rises to merge with the soul's light."}},
        {sit:{it:"Il sé illusorio, da cui l'aspirante deve imparare a distinguersi per lavorare con intelligenza.",en:"The illusory self, from which the aspirant must learn to distinguish himself in order to work intelligently."},correct:2,note:{it:"Solo chi distingue fra sé reale e sé illusorio può lavorare con intelligenza (Regola Uno).",en:"Only one who distinguishes the real self from the illusory self can work intelligently (Rule One)."}},
        {sit:{it:"Il Pensatore che usa i tre mondi come campo d'esperienza e di servizio.",en:"The Thinker who uses the three worlds as a field of experience and service."},correct:1,note:{it:"L'anima è il vero uomo, il Pensatore: i corpi sono i suoi strumenti.",en:"The soul is the real man, the Thinker: the bodies are its instruments."}},
        {sit:{it:"Ciò con cui l'uomo si unifica alla quinta iniziazione, per intervento del Signore del Mondo.",en:"That with which man is unified at the fifth initiation, through the intervention of the Lord of the World."},correct:0,note:{it:"«L'uomo si unifica con la Monade alla quinta iniziazione per intervento del Signore del Mondo, l'Osservatore Solitario, il Grande Sacrificio.»",en:"'Man is unified with the Monad at the fifth initiation through the intervention of the Lord of the World, the Silent Watcher, the Great Sacrifice.'"}},
        {sit:{it:"Colui che si ribella alla trasmutazione quando il discepolo trasferisce la coscienza dal personale all'impersonale.",en:"That which rebels against transmutation when the disciple shifts consciousness from the personal to the impersonal."},correct:2,note:{it:"Il sé inferiore del discepolo si ribella: è una delle cause della sofferenza sul Sentiero.",en:"The disciple's lower self rebels: one of the causes of suffering on the Path."}},
        {sit:{it:"Ciò da cui emana la luce stessa dell'anima.",en:"That from which the very light of the soul emanates."},correct:0,note:{it:"Commento alla Regola Due: «è vero che la luce dell'anima emana dalla Monade».",en:"Commentary on Rule Two: 'it is true that the light of the soul emanates from the Monad'."}},
        {sit:{it:"Ciò che, dalla terza iniziazione in poi, guida l'Ego in modo definitivo.",en:"That which, from the third initiation onward, definitely guides the Ego."},correct:0,note:{it:"Alla Trasfigurazione la Monade comincia a riversare sempre di più la sua vita divina nel canale preparato e purificato.",en:"At the Transfiguration the Monad begins to pour its divine life ever more into the prepared and purified channel."}},
        {sit:{it:"Il Karana Sarira, intermediario fra Spirito e materia, fra Monade e personalità.",en:"The Karana Sarira, intermediary between Spirit and matter, between Monad and personality."},correct:1,note:{it:"È il corpo causale, «il corpo spirituale dell'anima»: per il discepolo avanzato e l'iniziato è il punto intermedio della Regola Otto.",en:"It is the causal body, 'the spiritual body of the soul': for the advanced disciple and the initiate it is the midway point of Rule Eight."}},
        {sit:{it:"Colui che dimora nella forma: quando l'impulso all'azione emana da lui, l'azione è pura entro i limiti del gruppo.",en:"The One who dwells in the form: when the impulse to act comes from him, the action is pure within the limits of the group."},correct:1,note:{it:"Regola Nove: «L'anima ha coscienza di gruppo».",en:"Rule Nine: 'The soul is group conscious'."}},
        {sit:{it:"Il corpo kama-manasico, desiderio-mente: per l'uomo nei tre mondi, sotto molti aspetti il corpo più importante dell'attuale sistema solare.",en:"The kama-manasic body, desire-mind: for man in the three worlds, in many respects the most important body of the present solar system."},correct:2,note:{it:"Il discepolo deve studiarlo: è uno dei veicoli con cui l'uomo vive nei tre mondi.",en:"The disciple must study it: it is one of the vehicles through which man lives in the three worlds."}}
      ]
    },
    regole: { type:"quiz", roman:"II", glyph:"✶", count:10,
      items: [
        {q:{it:"Regola Uno: l'Angelo Solare…",en:"Rule One: the Solar Angel…"},options:{it:["Si raccoglie e comunica con il suo riflesso in meditazione","Disperde la sua forza nei tre mondi","Combatte l'ombra","Dorme fino all'iniziazione"],en:["Recollects itself and communes with its reflection in meditation","Scatters its force in the three worlds","Fights the shadow","Sleeps until initiation"]},correct:0,note:{it:"«L'Angelo Solare si raccoglie, non disperde la sua forza, ma in profonda meditazione comunica con il suo riflesso.»",en:"'The Solar Angel collects himself, scatters not his force, but in meditation deep communicates with his reflection.'"}},
        {q:{it:"La 'luce maggiore' della Regola Due è…",en:"The 'greater light' of Rule Two is…"},options:{it:["La luce dell'anima","La luce del sole fisico","La kundalini","La luce della mente"],en:["The light of the soul","The light of the physical sun","Kundalini","The light of the mind"]},correct:0,note:{it:"La luce maggiore illumina i tre; la luce inferiore, nascosta nell'uomo fisico, è proiettata verso l'alto.",en:"The greater light illumines the three; the lesser light, hidden in physical man, is thrown upward."}},
        {q:{it:"La chiave del lavoro magico nella Regola Sei è…",en:"The key to magical work in Rule Six is…"},options:{it:["La contemplazione: visione ferma verso un unico obiettivo","La recitazione di mantra","Il digiuno","Il sacrificio rituale"],en:["Contemplation: steady vision toward a single objective","Reciting mantras","Fasting","Ritual sacrifice"]},correct:0,note:{it:"«I deva dei quattro inferiori sentono la forza quando l'occhio si apre […]». L'occhio si apre nella contemplazione.",en:"'The devas of the lower four feel the force when the eye opens […]'. The eye opens in contemplation."}},
        {q:{it:"Il 'campo di battaglia' dove il mago rischia di annegare (Regola Otto) è…",en:"The 'battleground' where the magician risks drowning (Rule Eight) is…"},options:{it:["Il piano astrale","Il piano fisico","Il piano mentale","Il corpo causale"],en:["The astral plane","The physical plane","The mental plane","The causal body"]},correct:0,note:{it:"Il piano astrale è il campo di battaglia dei sensi e il luogo da cui si opera la magia.",en:"The astral plane is the battleground of the senses and the place from which magic is wrought."}},
        {q:{it:"Il mago deve poggiare i piedi nel punto 'né secco né umido' (Regola Otto). Per chi è sul Sentiero della Prova, quel punto intermedio è…",en:"The magician must stand where it is 'neither dry nor wet' (Rule Eight). For one on the Probationary Path, that midway point is…"},options:{it:["Il piano emotivo, dove terra (natura fisica) e acqua (natura emotiva) s'incontrano","La riva del mare","Il piano buddhico","Il silenzio assoluto"],en:["The emotional plane, where earth (physical nature) and water (emotional nature) meet","The seashore","The buddhic plane","Absolute silence"]},correct:0,note:{it:"Per il discepolo il punto intermedio è il piano mentale; per il discepolo avanzato e l'iniziato, il corpo causale. L'aria è il simbolo del piano buddhico; la mente corrisponde al fuoco.",en:"For the disciple the midway point is the mental plane; for the advanced disciple and the initiate, the causal body. Air is the symbol of the buddhic plane; the mind corresponds to fire."}},
        {q:{it:"La purezza richiesta dalla Regola Nove dipende soprattutto…",en:"The purity required by Rule Nine depends above all…"},options:{it:["Dal movente","Dalla dieta","Dalle parole pronunciate","Dal raggio dell'aspirante"],en:["On motive","On diet","On the words spoken","On the aspirant's ray"]},correct:0,note:{it:"Se l'incentivo scaturisce da un desiderio personale e l'azione è compiuta applicando la mente, la sua caratteristica è l'impurità.",en:"If the incentive springs from a personal desire and the action is carried out by applying the mind, its characteristic is impurity."}},
        {q:{it:"Regola Dieci: quando la forma pensiero è abbastanza potente…",en:"Rule Ten: when the thought-form is potent enough…"},options:{it:["Cessano i costruttori esterni e subentrano i lavoratori interiori","Il mago la distrugge","Va consegnata al Maestro","Si dissolve da sola"],en:["The outer builders cease and the inner workers take over","The magician destroys it","It must be handed to the Master","It dissolves by itself"]},correct:0,note:{it:"«Cessi allora l'opera dei costruttori esterni e subentri il ciclo dei lavoratori interiori.»",en:"'Then let the outer builders cease their labors and the inner workers enter on their cycle.'"}},
        {q:{it:"La 'frase mistica' della Regola Undici serve a…",en:"The 'mystic phrase' of Rule Eleven serves to…"},options:{it:["Salvaguardare il mago dall'operato delle vite che ha vincolato","Aprire i piani superiori","Chiamare l'Angelo Solare","Benedire la forma creata"],en:["Safeguard the magician from the action of the lives he has bound","Open the higher planes","Call the Solar Angel","Bless the created form"]},correct:0,note:{it:"Terza ingiunzione della Regola: pronunciare la frase mistica che lo salvaguarderà dal loro operare.",en:"The Rule's third injunction: utter the mystic phrase that will save him from their work."}},
        {q:{it:"Nella Regola Dodici il mago, posto nel punto di mezzo, libera…",en:"In Rule Twelve the magician, standing at the midway point, releases…"},options:{it:["I 'prigionieri del pianeta'","Le anime dei morti","I deva del fuoco","Le forme-pensiero altrui"],en:["The 'prisoners of the planet'","The souls of the dead","The fire devas","Others' thought-forms"]},correct:0,note:{it:"«Che il mago si ponga nel punto di mezzo e liberi così i \"prigionieri del pianeta\" la cui nota corrisponde ed è correttamente intonata a ciò che deve essere compiuto.»",en:"'Let the magician place himself at the midway point and thus release the \"prisoners of the planet\" whose note is right and justly tuned to that which must be made.'"}},
        {q:{it:"Le prime sei regole riguardano il lavoro…",en:"The first six rules concern the work…"},options:{it:["Sul piano mentale","Sul piano fisico","Sul piano astrale","Sul piano buddhico"],en:["On the mental plane","On the physical plane","On the astral plane","On the buddhic plane"]},correct:0,note:{it:"Regole 1-6: piano mentale; 7-11: piano astrale; 12-15: piano fisico.",en:"Rules 1-6: mental plane; 7-11: astral plane; 12-15: physical plane."}},
        {q:{it:"Le ultime quattro regole (12-15) riguardano il lavoro…",en:"The last four rules (12-15) concern the work…"},options:{it:["Sul piano fisico","Sul piano mentale","Nel Devachan","Sui sette raggi"],en:["On the physical plane","On the mental plane","In Devachan","On the seven rays"]},correct:0,note:{it:"Attuare le idee soggettive nella manifestazione fisica è la parte più difficile del lavoro magico.",en:"Bringing subjective ideas into physical manifestation is the hardest part of magical work."}},
        {q:{it:"Secondo la Regola Quattro, mentre l'amore attrae, la mente…",en:"According to Rule Four, while love attracts, the mind…"},options:{it:["Attrae, respinge e coordina: è il fattore creativo per eccellenza","Solo respinge","Divide e separa","Riposa nell'unità"],en:["Attracts, repels and co-ordinates: the creative factor par excellence","Only repels","Divides and separates","Rests in unity"]},correct:0,note:{it:"L'amore è il grande unificatore; la mente è l'utilizzatore delle energie del cosmo.",en:"Love is the great unifier; the mind is the wielder of the energies of the cosmos."}},
        {q:{it:"Regola Tre: quando la luce recede e il fuoco del punto di luce impallidisce…",en:"Rule Three: when the light recedes and the fire of the point of light grows dim…"},options:{it:["Viene emesso il secondo suono","Il lavoro si arresta","Il mago abbandona la forma","L'Angelo Solare si ritira"],en:["The second sound is uttered","The work stops","The magician abandons the form","The Solar Angel withdraws"]},correct:0,note:{it:"«Le miriadi si raccolgono attorno al suo ardente calore fintanto che la luce non recede. Il suo fuoco impallidisce. Viene allora emesso il secondo suono.»",en:"'The myriads gather round its fiery warmth until the light recedes. Its fire grows dim. Then the second sound is uttered.'"}},
        {q:{it:"Regola Cinque: quali tre cose impegnano l'Angelo Solare prima che l'involucro creato discenda?",en:"Rule Five: which three things engage the Solar Angel before the created sheath descends?"},options:{it:["La condizione delle acque, l'immunità di colui che crea, la contemplazione stabile","Il suono, la luce, la forma","Il digiuno, il silenzio, la preghiera","I tre corpi della personalità"],en:["The condition of the waters, the immunity of the one who creates, steady contemplation","Sound, light, form","Fasting, silence, prayer","The three bodies of the personality"]},correct:0,note:{it:"La regola si chiude così: «Così cuore, gola, occhio sono uniti nel triplice servizio.»",en:"The rule ends: 'Thus heart, throat and eye are united in the threefold service.'"}},
        {q:{it:"Nella Regola Cinque, la «condizione delle acque» è…",en:"In Rule Five, the 'condition of the waters' is…"},options:{it:["Lo stato della sostanza emotiva in cui la forma pensiero deve immergersi","Il livello dei mari nel mondo","La purezza del corpo fisico","Il flusso del prana"],en:["The state of the emotional substance into which the thought-form must be immersed","The level of the world's seas","The purity of the physical body","The flow of prana"]},correct:0,note:{it:"«Pace, sicurezza e retta aspirazione!» Queste tre parole, vissute ogni giorno, determinano la giusta «condizione delle acque».",en:"'Peace, assurance and right aspiration!' These three words, lived every day, determine the right 'condition of the waters'."}},
        {q:{it:"L'«immunità di colui che così crea» (Regola Cinque) è necessaria perché…",en:"The 'immunity of the one who thus creates' (Rule Five) is needed because…"},options:{it:["Le persone sono spesso uccise, in senso occulto, dalle loro stesse forme pensiero","I deva sono ostili all'uomo","Il piano fisico è impuro","Il Maestro punisce gli errori"],en:["People are often killed, in the occult sense, by their own thought-forms","The devas are hostile to man","The physical plane is impure","The Master punishes mistakes"]},correct:0,note:{it:"«La creazione del pensiero, mediante la concentrazione e la meditazione, è un'opera estremamente pericolosa.»",en:"'The creation of thought, through concentration and meditation, is an extremely dangerous work.'"}},
        {q:{it:"Il «piano dove il potere vitale deve essere cercato» (Regola Sette) è…",en:"The 'plane where the vital power must be sought' (Rule Seven) is…"},options:{it:["Il piano astrale","Il piano mentale","Il piano fisico denso","Il piano buddhico"],en:["The astral plane","The mental plane","The dense physical plane","The buddhic plane"]},correct:0,note:{it:"La regola descrive il piano astrale: il piano delle forze duplici, dei due sentieri, dei poli che vibrano, dove si fa una scelta.",en:"The rule describes the astral plane: the plane of dual forces, of the two paths, of vibrating poles, where a choice is made."}},
        {q:{it:"Regola Sette, «colui che medita deve fare la sua scelta»: per l'aspirante la scelta è fra…",en:"Rule Seven, 'he who meditates must make his choice': for the aspirant the choice is between…"},options:{it:["Progresso rapido o lento","I sette Sentieri","Due Maestri","Magia bianca e magia nera"],en:["Rapid or slow progress","The seven Paths","Two Masters","White and black magic"]},correct:0,note:{it:"Per il discepolo è la scelta dei metodi di servizio; per il Maestro, la scelta fra i sette Sentieri.",en:"For the disciple it is the choice of methods of service; for the Master, the choice among the seven Paths."}},
        {q:{it:"Quale regola è detta «la più importante contenuta nel libro» per lo studente medio?",en:"Which rule is called 'the most important contained in the book' for the average student?"},options:{it:["La Regola Otto","La Regola Uno","La Regola Quindici","La Regola Dieci"],en:["Rule Eight","Rule One","Rule Fifteen","Rule Ten"]},correct:0,note:{it:"Tratta del lavoro e dell'attività dell'aspirante intelligente in questo momento.",en:"It deals with the work and activity of the intelligent aspirant at this time."}},
        {q:{it:"Commentando la Regola Nove, al posto dell'ingiunzione «uccidi il desiderio» si suggerisce…",en:"Commenting on Rule Nine, in place of the injunction 'kill out desire' it is suggested…"},options:{it:["«Riorientare» o «ridirigere» il desiderio","Ignorare il desiderio","Soddisfare ogni desiderio","Reprimere le emozioni"],en:["To 'reorient' or 'redirect' desire","To ignore desire","To satisfy every desire","To repress the emotions"]},correct:0,note:{it:"Il riorientamento costante di tutta la natura del desiderio è la chiave d'ogni processo di trasmutazione e di un efficace lavoro magico.",en:"The constant reorientation of the whole desire nature is the key to every process of transmutation and to effective magical work."}},
        {q:{it:"Chi sono i «prigionieri del pianeta» della Regola Dodici?",en:"Who are the 'prisoners of the planet' of Rule Twelve?"},options:{it:["Tutte le forme di vita subumane, le vite incorporate in una forma","Le anime dei defunti","I maghi neri","Gli uomini non ancora individualizzati"],en:["All subhuman forms of life, the lives embodied in a form","The souls of the dead","Black magicians","Men not yet individualised"]},correct:0,note:{it:"Liberarli, usando gli intervalli fra l'espirare e l'inspirare, è l'obiettivo di tutta l'opera magica in questo periodo mondiale.",en:"Releasing them, by using the intervals between outbreathing and inbreathing, is the goal of all magical work in this world period."}},
        {q:{it:"Regola Tredici: «il mago deve riconoscere i quattro». I quattro sono…",en:"Rule Thirteen: 'the magician must recognise the four'. The four are…"},options:{it:["I quattro gradi di sostanza eterica","I quattro elementi","I quattro Maestri","I quattro raggi minori"],en:["The four grades of etheric substance","The four elements","The four Masters","The four minor rays"]},correct:0,note:{it:"Costituiscono l'involucro eterico di tutte le forme della natura, «dalla montagna alla formica, dalla pianta all'atomo».",en:"They make up the etheric sheath of all forms in nature, 'from the mountain to the ant, from the plant to the atom'."}},
        {q:{it:"L'«ora del pericolo per l'anima coraggiosa» (Regola Quattordici) riguarda…",en:"The 'hour of danger for the soul courageous' (Rule Fourteen) concerns…"},options:{it:["Il lavoro con i fuochi o i prana dell'universo","L'annegamento nelle acque astrali","La morte fisica del mago","L'incontro con il Maestro"],en:["Work with the fires or pranas of the universe","Drowning in the astral waters","The magician's physical death","Meeting the Master"]},correct:0,note:{it:"«Le acque non hanno nuociuto al creatore bianco e nulla potrebbe annegarlo e nemmeno bagnarlo. Ora il pericolo del fuoco e della fiamma minaccia».",en:"'The waters have not harmed the white creator and nothing could drown him or even wet him. Now the danger of fire and flame threatens'."}},
        {q:{it:"Il «senso esoterico», di cui si parla nel commento alla Regola Quindici, è…",en:"The 'esoteric sense', discussed in the commentary on Rule Fifteen, is…"},options:{it:["Il potere di vivere e agire soggettivamente, in costante contatto interiore con l'anima","La chiaroveggenza","La conoscenza dei simboli","Un sesto senso fisico"],en:["The power to live and act subjectively, in constant inner contact with the soul","Clairvoyance","Knowledge of symbols","A physical sixth sense"]},correct:0,note:{it:"«Il senso esoterico è il principale requisito necessario dell'aspirante in questo periodo della storia mondiale.»",en:"'The esoteric sense is the chief requirement of the aspirant in this period of world history.'"}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"'Iniziazione' deriva dal latino in + ire e significa…",en:"'Initiation' derives from Latin in + ire and means…"},options:{it:["Entrare dentro: l'ingresso in un nuovo stadio della vita spirituale","Essere eletti","Ricevere un segreto","Morire al mondo"],en:["To go into: entry upon a new stage of the spiritual life","To be chosen","To receive a secret","To die to the world"]},correct:0,note:{it:"Indica l'ingresso nella vita spirituale o in un suo nuovo stadio.",en:"It indicates entry into the spiritual life or into a new stage of it."}},
        {q:{it:"Il Sentiero della Prova corrisponde…",en:"The Path of Probation corresponds…"},options:{it:["All'ultimo periodo della gestazione: il Cristo bambino si forma nel cuore","Alla vecchiaia dell'anima","Alla morte","Al battesimo"],en:["To the last period of gestation: the Christ-child forms in the heart","To the soul's old age","To death","To baptism"]},correct:0,note:{it:"Concezione = individualizzazione; gestazione = ruota della vita; prima iniziazione = nascita.",en:"Conception = individualisation; gestation = the wheel of life; first initiation = birth."}},
        {q:{it:"Sul Sentiero della Prova l'uomo…",en:"On the Path of Probation man…"},options:{it:["'Si prende in mano' e coltiva le qualità che gli mancano","Riceve i poteri","Incontra il Maestro faccia a faccia","Abbandona il mondo"],en:["'Takes himself in hand' and cultivates the qualities he lacks","Receives the powers","Meets the Master face to face","Abandons the world"]},correct:0,note:{it:"Si dedica alla formazione del carattere e cerca di dominare la personalità.",en:"He devotes himself to character-building and seeks to master the personality."}},
        {q:{it:"Alla prima iniziazione si dimostra il dominio…",en:"At the first initiation one demonstrates control…"},options:{it:["Sul corpo fisico","Sul corpo astrale","Sulla mente","Sul karma"],en:["Over the physical body","Over the astral body","Over the mind","Over karma"]},correct:0,note:{it:"I 'peccati della carne' devono essere dominati; di solito viene vivificato il centro del cuore.",en:"The 'sins of the flesh' must be mastered; usually the heart centre is vivified."}},
        {q:{it:"La seconda iniziazione, il Battesimo, è la crisi del dominio…",en:"The second initiation, the Baptism, is the crisis of control…"},options:{it:["Sul corpo astrale: la morte del desiderio","Sul corpo fisico","Sul corpo causale","Sul respiro"],en:["Over the astral body: the death of desire","Over the physical body","Over the causal body","Over the breath"]},correct:0,note:{it:"Fra la prima e la seconda possono trascorrere molte vite; dopo, il progresso è rapido.",en:"Many lives may pass between the first and second; afterwards progress is rapid."}},
        {q:{it:"Nel Catechismo esoterico, la Croce che fa attraversare l'abisso è formata…",en:"In the esoteric catechism, the Cross that carries one across the abyss is formed…"},options:{it:["Dalle aspirazioni che recidono i desideri mondani","Da legno e chiodi","Dalle quattro direzioni","Dal karma passato"],en:["By aspirations that cut athwart worldly desires","Of wood and nails","By the four directions","By past karma"]},correct:0,note:{it:"«La Croce è formata dalle aspirazioni mosse dall'impulso divino, le quali recidono trasversalmente i desideri mondani alimentati dalla vita che procede dal basso.»",en:"'The Cross is formed by aspirations, instilled by the divine urge, which cut athwart the worldly desires fed by the life that proceeds from below.'"}},
        {q:{it:"Chi siede sul 'Seggio possente' al termine della quinta parte della scala?",en:"Who sits on the 'mighty Seat' at the end of the fifth portion of the ladder?"},options:{it:["Il Giovane dalle innumerevoli Estati, il Signore dell'Amore","Un angelo senza nome","Il primo uomo","Il Buddha"],en:["The Youth of Endless Summers, the Lord of Love","A nameless angel","The first man","The Buddha"]},correct:0,note:{it:"«Il grande Kumara con la Spada Fiammeggiante, la Pace di tutta la Terra» — Sanat Kumara.",en:"'The mighty Kumara with the Flaming Sword, the Peace of all the Earth' — Sanat Kumara."}},
        {q:{it:"Discepolo è colui che…",en:"A disciple is one who…"},options:{it:["Trasferisce il centro d'attività da se stesso al gruppo","Obbedisce ciecamente al Maestro","Rinuncia alla famiglia","Studia i testi sacri"],en:["Shifts his centre of activity from himself to the group","Blindly obeys the Master","Renounces his family","Studies the sacred texts"]},correct:0,note:{it:"Si è consacrato a servire l'umanità, cooperare col Piano e seguire il sé superiore.",en:"He is pledged to serve humanity, co-operate with the Plan and follow the higher self."}},
        {q:{it:"Alla Porta dell'Iniziazione si giunge 'con i piedi lavati…'",en:"One reaches the Gate of Initiation 'with feet washed…'"},options:{it:["Nel sangue del cuore","Nell'acqua del Gange","Nella rugiada del mattino","Nelle lacrime"],en:["In the blood of the heart","In the waters of the Ganges","In morning dew","In tears"]},correct:0,note:{it:"Ogni passo avanti è frutto del sacrificio volontario di ciò che è più caro al cuore.",en:"Every step forward is the fruit of the willing sacrifice of what is dearest to the heart."}},
        {q:{it:"Quanti Sentieri si aprono davanti a chi giunge alla quinta iniziazione?",en:"How many Paths open before one who reaches the fifth initiation?"},options:{it:["Sette","Tre","Uno","Dodici"],en:["Seven","Three","One","Twelve"]},correct:0,note:{it:"Prima di percorrerli l'uomo dev'essere un Maestro di Saggezza, un Fratello di Compassione.",en:"Before treading them man must be a Master of Wisdom, a Brother of Compassion."}},
        {q:{it:"L'Adepto è chi ha conseguito…",en:"An Adept is one who has taken…"},options:{it:["Cinque iniziazioni","Due iniziazioni","Sette iniziazioni","Nessuna: è nato adepto"],en:["Five initiations","Two initiations","Seven initiations","None: he is born an adept"]},correct:0,note:{it:"È entrato nel quinto regno, quello spirituale: gli restano solo le ultime due iniziazioni.",en:"He has entered the fifth, spiritual kingdom: only the last two initiations remain."}},
        {q:{it:"L'Antahkarana è…",en:"The Antahkarana is…"},options:{it:["Il ponte fra mente superiore e inferiore, costruito dall'aspirante","Un mantra segreto","Il corpo di luce","Il filo della memoria"],en:["The bridge between higher and lower mind, built by the aspirant","A secret mantra","The body of light","The thread of memory"]},correct:0,note:{it:"Viene costruito dall'aspirante stesso con sostanza mentale.",en:"It is built by the aspirant himself out of mental substance."}},
        {q:{it:"Chi è lo Ierofante delle prime due iniziazioni?",en:"Who is the Hierophant of the first two initiations?"},options:{it:["Il Cristo, l'Istruttore del Mondo","Il Signore del Mondo","Il Mahachohan","Il Manu"],en:["The Christ, the World Teacher","The Lord of the World","The Mahachohan","The Manu"]},correct:0,note:{it:"Solo alla terza iniziazione officia il grande Ierofante, il Signore del Mondo: è il suo primo contatto con l'iniziato.",en:"Only at the third initiation does the great Hierophant, the Lord of the World, officiate: it is his first contact with the initiate."}},
        {q:{it:"Alla terza iniziazione, la Trasfigurazione…",en:"At the third initiation, the Transfiguration…"},options:{it:["L'intera personalità è inondata dalla luce che fluisce dall'alto","Si vivifica il centro del cuore","Il corpo causale si dissolve","Si sceglie uno dei sette Sentieri"],en:["The whole personality is flooded with the light streaming from above","The heart centre is vivified","The causal body dissolves","One of the seven Paths is chosen"]},correct:0,note:{it:"Il centro del cuore si vivifica di solito alla prima iniziazione; il corpo causale si dissolve dopo la quarta.",en:"The heart centre is usually vivified at the first initiation; the causal body dissolves after the fourth."}},
        {q:{it:"La quarta iniziazione, o Crocifissione, è la vita in cui l'uomo…",en:"The fourth initiation, or Crucifixion, is the life in which man…"},options:{it:["Fa la Grande Rinuncia","Riceve il primo insegnamento","Si individualizza","Vivifica il centro della gola"],en:["Makes the Great Renunciation","Receives his first teaching","Individualises","Vivifies the throat centre"]},correct:0,note:{it:"«A tutto si è rinunciato: amici, denaro, reputazione, qualità personali, posizione nel mondo, famiglia e persino la vita stessa.»",en:"'Everything has been renounced: friends, money, reputation, personal qualities, position in the world, family and even life itself.'"}},
        {q:{it:"Quando si dissolve il corpo causale?",en:"When does the causal body dissolve?"},options:{it:["Dopo la quarta iniziazione","Alla morte fisica","Alla prima iniziazione","Mai"],en:["After the fourth initiation","At physical death","At the first initiation","Never"]},correct:0,note:{it:"Perdura per tutto il lungo ciclo delle incarnazioni; dopo la quarta iniziazione un'ulteriore incarnazione non è più necessaria.",en:"It lasts through the long cycle of incarnations; after the fourth initiation no further incarnation is needed."}},
        {q:{it:"La prima iniziazione trasferisce il discepolo…",en:"The first initiation transfers the disciple…"},options:{it:["Dall'Aula dell'Apprendimento all'Aula della Saggezza","Dal piano fisico a quello buddhico","Dal regno animale a quello umano","Dall'ashram al mondo"],en:["From the Hall of Learning to the Hall of Wisdom","From the physical to the buddhic plane","From the animal to the human kingdom","From the ashram to the world"]},correct:0,note:{it:"Dopo quest'iniziazione l'iniziato verrà istruito principalmente sui fatti del piano astrale.",en:"After this initiation the initiate is taught chiefly about the facts of the astral plane."}},
        {q:{it:"In «Iniziazione umana e solare», il termine Chohan indica…",en:"In 'Initiation, Human and Solar', the term Chohan denotes…"},options:{it:["Gli Adepti della sesta iniziazione","I discepoli accettati","Gli iniziati di primo grado","I deva del fuoco"],en:["The Adepts of the sixth initiation","Accepted disciples","First-degree initiates","The fire devas"]},correct:0,note:{it:"Chohan significa Signore, Maestro, Capo.",en:"Chohan means Lord, Master, Chief."}},
        {q:{it:"Per il discepolo moderno l'ostacolo maggiore, più della mancanza di discernimento, è la mancanza di…",en:"For the modern disciple the greater obstacle, more than lack of discrimination, is lack of…"},options:{it:["Distacco","Studio","Devozione","Poteri psichici"],en:["Detachment","Study","Devotion","Psychic powers"]},correct:0,note:{it:"«Distacco significa aver conseguito uno stato di coscienza in cui è realizzato l'equilibrio e in cui non domina né il piacere né il dolore, sostituiti dalla gioia e dalla beatitudine.»",en:"'Detachment means having attained a state of consciousness in which balance is achieved and in which neither pleasure nor pain dominates, replaced by joy and bliss.'"}},
        {q:{it:"Quale mezzo di preparazione all'iniziazione è definito «la più occulta manifestazione esistente»?",en:"Which means of preparation for initiation is called 'the most occult manifestation in existence'?"},options:{it:["La parola","Il respiro","Il digiuno","Il sogno"],en:["Speech","The breath","Fasting","Dreams"]},correct:0,note:{it:"Chi sorveglia le proprie parole e parla soltanto con propositi altruistici supera rapidamente i passi iniziali necessari per prepararsi all'iniziazione.",en:"One who guards his words and speaks only with unselfish purpose quickly passes the initial steps needed to prepare for initiation."}},
        {q:{it:"Il Catechismo esoterico veniva recitato…",en:"The esoteric catechism was recited…"},options:{it:["Dai partecipanti ai misteri minori, prima di passare ai maggiori","Dai Maestri alla quinta iniziazione","Ogni mattina nell'ashram","Solo dai Chohan"],en:["By participants in the lesser mysteries, before passing to the greater","By the Masters at the fifth initiation","Every morning in the ashram","Only by the Chohans"]},correct:0,note:{it:"È estratto dal XIII Archivio dei Maestri e contiene un messaggio per coloro che intendono percorrere il Sentiero.",en:"It is taken from the XIIIth Archive of the Masters and contains a message for those who intend to tread the Path."}},
        {q:{it:"Nel Catechismo, il braccio orizzontale della Croce è…",en:"In the catechism, the horizontal arm of the Cross is…"},options:{it:["La grande linea che separa l'inferiore dal superiore","Il ponte sull'abisso","La scala stessa","Il seggio del Kumara"],en:["The great line that separates the lower from the higher","The bridge over the abyss","The ladder itself","The seat of the Kumara"]},correct:0,note:{it:"Vi sono inchiodate le mani che afferrano e trattengono; quando non possono più afferrare, la vita interiore sale sul braccio verticale.",en:"On it are nailed the hands that grasp and hold; when they can grasp no longer, the inner life rises on the vertical arm."}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✧",
      items: [
        {a:{it:"Antahkarana",en:"Antahkarana"},b:{it:"Ponte fra le menti",en:"Bridge of minds"}},
        {a:{it:"Atma",en:"Atma"},b:{it:"Spirito universale",en:"Universal Spirit"}},
        {a:{it:"Buddhi",en:"Buddhi"},b:{it:"Anima spirituale",en:"Spiritual soul"}},
        {a:{it:"Ashram",en:"Ashram"},b:{it:"Cerchia del Maestro",en:"Master's circle"}},
        {a:{it:"Adepto",en:"Adept"},b:{it:"Cinque iniziazioni",en:"Five initiations"}},
        {a:{it:"Bodhisattva",en:"Bodhisattva"},b:{it:"Istruttore del Mondo",en:"World Teacher"}},
        {a:{it:"Kurukshetra\ndell'aspirante",en:"The aspirant's\nKurukshetra"},b:{it:"Piano astrale",en:"Astral plane"}},
        {a:{it:"Agnisurya",en:"Agnisuryas"},b:{it:"Elementali astrali",en:"Astral elementals"}}
      ]
    }
  }
};
})();
