/* LA MAGIA BIANCA — data.js (dalle opere di Alice A. Bailey) */
(function(){
"use strict";
window.GAME_DATA = {
  id: "magia",
  modes: ["aspetto","regole","quiz","memoria"],
  rings: [
    {key:"monade",color:"#1a1326",ring:"#7a5ab0",label:{it:"Monade",en:"Monad"}},
    {key:"anima",color:"#10212a",ring:"#3a7c9a",label:{it:"Anima",en:"Soul"}},
    {key:"personalita",color:"#2a1410",ring:"#c9973a",label:{it:"Personalità",en:"Personality"}}
  ],
  modeDefs: {
    aspetto: { type:"scenario", roman:"I", glyph:"△", optionKeys:[0,1,2],
      items: [
        {sit:{it:"Lo Spirito universale in te: il settimo principio, la scintilla divina che dimora nei piani più alti.",en:"The universal Spirit in you: the seventh principle, the divine spark dwelling on the highest planes."},correct:0,note:{it:"La Monade (Atma): lo Spirito, uno con il Padre. Non si incarna mai pienamente.",en:"The Monad (Atma): Spirit, one with the Father. It never fully incarnates."}},
        {sit:{it:"L'Angelo Solare che si raccoglie e, in profonda meditazione, comunica con il suo riflesso.",en:"The Solar Angel that recollects itself and, in deep meditation, communes with its reflection."},correct:1,note:{it:"È la Regola Uno: l'Angelo Solare è l'anima, il cui 'riflesso' è la personalità nei tre mondi.",en:"This is Rule One: the Solar Angel is the soul, whose 'reflection' is the personality in the three worlds."}},
        {sit:{it:"Il riflesso inferiore: il triplice veicolo fatto di corpo fisico, emozioni e mente concreta.",en:"The lower reflection: the threefold vehicle made of physical body, emotions and concrete mind."},correct:2,note:{it:"La personalità è 'tre in uno': i veicoli con cui l'anima opera nei tre mondi.",en:"The personality is 'three in one': the vehicles through which the soul works in the three worlds."}},
        {sit:{it:"La 'luce maggiore' che illumina i tre e rende possibile il lavoro dei quattro.",en:"The 'greater light' that illumines the three and makes the work of the four possible."},correct:1,note:{it:"Regola Due: la luce maggiore è quella dell'anima, che illumina la triplice personalità.",en:"Rule Two: the greater light is that of the soul, illumining the threefold personality."}},
        {sit:{it:"La 'luce inferiore' nascosta sul piano fisico, che dev'essere proiettata verso l'alto.",en:"The 'lesser light' hidden on the physical plane, which must be thrown upward."},correct:2,note:{it:"Regola Due: la luce latente nell'uomo fisico sale per fondersi con la luce dell'anima.",en:"Rule Two: the light latent in physical man rises to merge with the soul's light."}},
        {sit:{it:"Il sé illusorio, da cui l'aspirante deve imparare a distinguersi per lavorare con intelligenza.",en:"The illusory self, from which the aspirant must learn to distinguish himself in order to work intelligently."},correct:2,note:{it:"Solo chi distingue fra sé reale e sé illusorio può lavorare con intelligenza (Regola Uno).",en:"Only one who distinguishes the real self from the illusory self can work intelligently (Rule One)."}},
        {sit:{it:"Il Pensatore che usa i tre mondi come campo d'esperienza e di servizio.",en:"The Thinker who uses the three worlds as a field of experience and service."},correct:1,note:{it:"L'anima è il vero uomo, il Pensatore: i corpi sono i suoi strumenti.",en:"The soul is the real man, the Thinker: the bodies are its instruments."}},
        {sit:{it:"Ciò che alla quinta iniziazione rivela la sua unità con il Tutto: il punto più alto della triade.",en:"That which at the fifth initiation reveals its unity with the All: the highest point of the triad."},correct:0,note:{it:"Alla quinta iniziazione l'adepto realizza l'unione con la Monade, lo Spirito puro.",en:"At the fifth initiation the adept realises union with the Monad, pure Spirit."}},
        {sit:{it:"Colui che si ribella alla trasmutazione quando il discepolo trasferisce la coscienza dal personale all'impersonale.",en:"That which rebels against transmutation when the disciple shifts consciousness from the personal to the impersonal."},correct:2,note:{it:"Il sé inferiore del discepolo si ribella: è una delle cause della sofferenza sul Sentiero.",en:"The disciple's lower self rebels: one of the causes of suffering on the Path."}}
      ]
    },
    regole: { type:"quiz", roman:"II", glyph:"✶", count:10,
      items: [
        {q:{it:"Regola Uno: l'Angelo Solare…",en:"Rule One: the Solar Angel…"},options:{it:["Si raccoglie e comunica con il suo riflesso in meditazione","Disperde la sua forza nei tre mondi","Combatte l'ombra","Dorme fino all'iniziazione"],en:["Recollects itself and communes with its reflection in meditation","Scatters its force in the three worlds","Fights the shadow","Sleeps until initiation"]},correct:0,note:{it:"«L'Angelo Solare si raccoglie, non disperde la sua forza, ma in profonda meditazione comunica con il suo riflesso.»",en:"'The Solar Angel collects himself, scatters not his force, but in meditation deep communicates with his reflection.'"}},
        {q:{it:"La 'luce maggiore' della Regola Due è…",en:"The 'greater light' of Rule Two is…"},options:{it:["La luce dell'anima","La luce del sole fisico","La kundalini","La luce della mente"],en:["The light of the soul","The light of the physical sun","Kundalini","The light of the mind"]},correct:0,note:{it:"La luce maggiore illumina i tre; la luce inferiore, nascosta nell'uomo fisico, è proiettata verso l'alto.",en:"The greater light illumines the three; the lesser light, hidden in physical man, is thrown upward."}},
        {q:{it:"La chiave del lavoro magico nella Regola Sei è…",en:"The key to magical work in Rule Six is…"},options:{it:["La contemplazione: visione ferma verso un unico obiettivo","La recitazione di mantra","Il digiuno","Il sacrificio rituale"],en:["Contemplation: steady vision toward a single objective","Reciting mantras","Fasting","Ritual sacrifice"]},correct:0,note:{it:"«I deva dei quattro inferiori sentono la forza quando l'occhio si apre.» L'occhio si apre nella contemplazione.",en:"'The devas of the lower four feel the force when the eye opens.' The eye opens in contemplation."}},
        {q:{it:"Il 'campo di battaglia' dove il mago rischia di annegare (Regola Otto) è…",en:"The 'battleground' where the magician risks drowning (Rule Eight) is…"},options:{it:["Il piano astrale","Il piano fisico","Il piano mentale","Il corpo causale"],en:["The astral plane","The physical plane","The mental plane","The causal body"]},correct:0,note:{it:"Il piano astrale è il campo di battaglia dei sensi e il luogo da cui si opera la magia.",en:"The astral plane is the battleground of the senses and the place from which magic is wrought."}},
        {q:{it:"Il mago deve poggiare i piedi nel punto 'né secco né umido' (Regola Otto), cioè…",en:"The magician must stand where it is 'neither dry nor wet' (Rule Eight), that is…"},options:{it:["Nell'equilibrio fra mente ed emozione","Sulla riva del mare","Nel corpo eterico","Nel silenzio assoluto"],en:["In the balance between mind and emotion","On the seashore","In the etheric body","In absolute silence"]},correct:0,note:{it:"Dove acqua (emozione), terra (fisico) e aria (mente) s'incontrano, l'opera magica può compiersi.",en:"Where water (emotion), earth (physical) and air (mind) meet, the magical work can be wrought."}},
        {q:{it:"La purezza richiesta dalla Regola Nove dipende soprattutto…",en:"The purity required by Rule Nine depends above all…"},options:{it:["Dal movente","Dalla dieta","Dalle parole pronunciate","Dal raggio dell'aspirante"],en:["On motive","On diet","On the words spoken","On the aspirant's ray"]},correct:0,note:{it:"Se l'incentivo scaturisce da desiderio personale, l'azione è impura — anche se compiuta con la mente.",en:"If the incentive springs from personal desire, the action is impure — even when performed with the mind."}},
        {q:{it:"Regola Dieci: quando la forma pensiero è abbastanza potente…",en:"Rule Ten: when the thought-form is potent enough…"},options:{it:["Cessano i costruttori esterni e subentrano i lavoratori interiori","Il mago la distrugge","Va consegnata al Maestro","Si dissolve da sola"],en:["The outer builders cease and the inner workers take over","The magician destroys it","It must be handed to the Master","It dissolves by itself"]},correct:0,note:{it:"«Cessi allora l'opera dei costruttori esterni e subentri il ciclo dei lavoratori interiori.»",en:"'Then let the outer builders cease their labors and the inner workers enter on their cycle.'"}},
        {q:{it:"La 'frase mistica' della Regola Undici serve a…",en:"The 'mystic phrase' of Rule Eleven serves to…"},options:{it:["Salvaguardare il mago dall'operato delle vite che ha vincolato","Aprire i piani superiori","Chiamare l'Angelo Solare","Benedire la forma creata"],en:["Safeguard the magician from the action of the lives he has bound","Open the higher planes","Call the Solar Angel","Bless the created form"]},correct:0,note:{it:"Terza ingiunzione della Regola: pronunciare la frase mistica che lo salvaguarderà dal loro operare.",en:"The Rule's third injunction: utter the mystic phrase that will save him from their work."}},
        {q:{it:"Nella Regola Dodici il mago, posto nel punto di mezzo, libera…",en:"In Rule Twelve the magician, standing at the midway point, releases…"},options:{it:["I 'prigionieri del pianeta'","Le anime dei morti","I deva del fuoco","Le forme-pensiero altrui"],en:["The 'prisoners of the planet'","The souls of the dead","The fire devas","Others' thought-forms"]},correct:0,note:{it:"«Liberi quei prigionieri del pianeta la cui nota corrisponde ed è correttamente intonata a ciò che deve essere compiuto.»",en:"'Release those prisoners of the planet whose note is right and justly tuned to that which must be made.'"}},
        {q:{it:"Le prime sei regole riguardano il lavoro…",en:"The first six rules concern the work…"},options:{it:["Sul piano mentale","Sul piano fisico","Sul piano astrale","Sul piano buddhico"],en:["On the mental plane","On the physical plane","On the astral plane","On the buddhic plane"]},correct:0,note:{it:"Regole 1-6: piano mentale; 7-11: piano astrale; 12-15: piano fisico.",en:"Rules 1-6: mental plane; 7-11: astral plane; 12-15: physical plane."}},
        {q:{it:"Le ultime quattro regole (12-15) riguardano il lavoro…",en:"The last four rules (12-15) concern the work…"},options:{it:["Sul piano fisico","Sul piano mentale","Nel Devachan","Sui sette raggi"],en:["On the physical plane","On the mental plane","In Devachan","On the seven rays"]},correct:0,note:{it:"Attuare le idee soggettive nella manifestazione fisica è la parte più difficile del lavoro magico.",en:"Bringing subjective ideas into physical manifestation is the hardest part of magical work."}},
        {q:{it:"Secondo la Regola Quattro, mentre l'amore attrae, la mente…",en:"According to Rule Four, while love attracts, the mind…"},options:{it:["Attrae, respinge e coordina: è il fattore creativo per eccellenza","Solo respinge","Divide e separa","Riposa nell'unità"],en:["Attracts, repels and co-ordinates: the creative factor par excellence","Only repels","Divides and separates","Rests in unity"]},correct:0,note:{it:"L'amore è il grande unificatore; la mente è l'utilizzatore delle energie del cosmo.",en:"Love is the great unifier; the mind is the wielder of the energies of the cosmos."}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"'Iniziazione' deriva dal latino in + ire e significa…",en:"'Initiation' derives from Latin in + ire and means…"},options:{it:["Entrare dentro: l'ingresso in un nuovo stadio della vita spirituale","Essere eletti","Ricevere un segreto","Morire al mondo"],en:["To go into: entry upon a new stage of the spiritual life","To be chosen","To receive a secret","To die to the world"]},correct:0,note:{it:"Indica l'ingresso nella vita spirituale o in un suo nuovo stadio.",en:"It indicates entry into the spiritual life or into a new stage of it."}},
        {q:{it:"Il Sentiero della Prova corrisponde…",en:"The Path of Probation corresponds…"},options:{it:["All'ultimo periodo della gestazione: il Cristo bambino si forma nel cuore","Alla vecchiaia dell'anima","Alla morte","Al battesimo"],en:["To the last period of gestation: the Christ-child forms in the heart","To the soul's old age","To death","To baptism"]},correct:0,note:{it:"Concezione = individualizzazione; gestazione = ruota della vita; prima iniziazione = nascita.",en:"Conception = individualisation; gestation = the wheel of life; first initiation = birth."}},
        {q:{it:"Sul Sentiero della Prova l'uomo…",en:"On the Path of Probation man…"},options:{it:["'Si prende in mano' e coltiva le qualità che gli mancano","Riceve i poteri","Incontra il Maestro faccia a faccia","Abbandona il mondo"],en:["'Takes himself in hand' and cultivates the qualities he lacks","Receives the powers","Meets the Master face to face","Abandons the world"]},correct:0,note:{it:"Si dedica alla formazione del carattere e cerca di dominare la personalità.",en:"He devotes himself to character-building and seeks to master the personality."}},
        {q:{it:"Alla prima iniziazione si dimostra il dominio…",en:"At the first initiation one demonstrates control…"},options:{it:["Sul corpo fisico","Sul corpo astrale","Sulla mente","Sul karma"],en:["Over the physical body","Over the astral body","Over the mind","Over karma"]},correct:0,note:{it:"I 'peccati della carne' devono essere dominati; di solito viene vivificato il centro del cuore.",en:"The 'sins of the flesh' must be mastered; usually the heart centre is vivified."}},
        {q:{it:"La seconda iniziazione, il Battesimo, è la crisi del dominio…",en:"The second initiation, the Baptism, is the crisis of control…"},options:{it:["Sul corpo astrale: la morte del desiderio","Sul corpo fisico","Sul corpo causale","Sul respiro"],en:["Over the astral body: the death of desire","Over the physical body","Over the causal body","Over the breath"]},correct:0,note:{it:"Fra la prima e la seconda possono trascorrere molte vite; dopo, il progresso è rapido.",en:"Many lives may pass between the first and second; afterwards progress is rapid."}},
        {q:{it:"Nel Catechismo esoterico, la Croce che fa attraversare l'abisso è formata…",en:"In the esoteric catechism, the Cross that carries one across the abyss is formed…"},options:{it:["Dalle aspirazioni che recidono i desideri mondani","Da legno e chiodi","Dalle quattro direzioni","Dal karma passato"],en:["By aspirations that cut athwart worldly desires","Of wood and nails","By the four directions","By past karma"]},correct:0,note:{it:"«La Croce è formata dalle aspirazioni mosse dall'impulso divino, le quali recidono i desideri mondani.»",en:"'The Cross is formed by aspirations, instilled by the divine urge, which cut athwart worldly desires.'"}},
        {q:{it:"Chi siede sul 'Seggio possente' al termine della quinta parte della scala?",en:"Who sits on the 'mighty Seat' at the end of the fifth portion of the ladder?"},options:{it:["Il Giovane dalle innumerevoli Estati, il Signore dell'Amore","Un angelo senza nome","Il primo uomo","Il Buddha"],en:["The Youth of Endless Summers, the Lord of Love","A nameless angel","The first man","The Buddha"]},correct:0,note:{it:"«Il grande Kumara con la Spada Fiammeggiante, la Pace di tutta la Terra» — Sanat Kumara.",en:"'The mighty Kumara with the Flaming Sword, the Peace of all the Earth' — Sanat Kumara."}},
        {q:{it:"Discepolo è colui che…",en:"A disciple is one who…"},options:{it:["Trasferisce il centro d'attività da se stesso al gruppo","Obbedisce ciecamente al Maestro","Rinuncia alla famiglia","Studia i testi sacri"],en:["Shifts his centre of activity from himself to the group","Blindly obeys the Master","Renounces his family","Studies the sacred texts"]},correct:0,note:{it:"Si è consacrato a servire l'umanità, cooperare col Piano e seguire il sé superiore.",en:"He is pledged to serve humanity, co-operate with the Plan and follow the higher self."}},
        {q:{it:"Alla Porta dell'Iniziazione si giunge 'con i piedi lavati…'",en:"One reaches the Gate of Initiation 'with feet washed…'"},options:{it:["Nel sangue del cuore","Nell'acqua del Gange","Nella rugiada del mattino","Nelle lacrime"],en:["In the blood of the heart","In the waters of the Ganges","In morning dew","In tears"]},correct:0,note:{it:"Ogni passo avanti è frutto del sacrificio volontario di ciò che è più caro al cuore.",en:"Every step forward is the fruit of the willing sacrifice of what is dearest to the heart."}},
        {q:{it:"Quanti Sentieri si aprono davanti a chi giunge alla quinta iniziazione?",en:"How many Paths open before one who reaches the fifth initiation?"},options:{it:["Sette","Tre","Uno","Dodici"],en:["Seven","Three","One","Twelve"]},correct:0,note:{it:"Prima di percorrerli l'uomo dev'essere un Maestro di Saggezza, un Fratello di Compassione.",en:"Before treading them man must be a Master of Wisdom, a Brother of Compassion."}},
        {q:{it:"L'Adepto è chi ha conseguito…",en:"An Adept is one who has taken…"},options:{it:["Cinque iniziazioni","Due iniziazioni","Sette iniziazioni","Nessuna: è nato adepto"],en:["Five initiations","Two initiations","Seven initiations","None: he is born an adept"]},correct:0,note:{it:"È entrato nel quinto regno, quello spirituale: gli restano solo le ultime due iniziazioni.",en:"He has entered the fifth, spiritual kingdom: only the last two initiations remain."}},
        {q:{it:"L'Antahkarana è…",en:"The Antahkarana is…"},options:{it:["Il ponte fra mente superiore e inferiore, costruito dall'aspirante","Un mantra segreto","Il corpo di luce","Il filo della memoria"],en:["The bridge between higher and lower mind, built by the aspirant","A secret mantra","The body of light","The thread of memory"]},correct:0,note:{it:"Viene costruito dall'aspirante stesso con sostanza mentale.",en:"It is built by the aspirant himself out of mental substance."}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✧",
      items: [
        {a:{it:"Antahkarana",en:"Antahkarana"},b:{it:"Ponte fra le menti",en:"Bridge of minds"}},
        {a:{it:"Atma",en:"Atma"},b:{it:"Spirito universale",en:"Universal Spirit"}},
        {a:{it:"Buddhi",en:"Buddhi"},b:{it:"Anima spirituale",en:"Spiritual soul"}},
        {a:{it:"Ashram",en:"Ashram"},b:{it:"Cerchia del Maestro",en:"Master's circle"}},
        {a:{it:"Adepto",en:"Adept"},b:{it:"Cinque iniziazioni",en:"Five initiations"}},
        {a:{it:"Bodhisattva",en:"Bodhisattva"},b:{it:"Istruttore del Mondo",en:"World Teacher"}}
      ]
    }
  }
};
})();
