/* I MONDI INVISIBILI — data.js (from Mondi Spirituali + Risveglio + Porta del Mago) */
(function(){
"use strict";
window.GAME_DATA = {
  id: "mondi",
  modes: ["corpo","abitante","quiz","memoria"],
  rings: [
    {key:"adi",color:"#1a1326",ring:"#3a2f52",label:{it:"Adi",en:"Adi"}},
    {key:"mentale",color:"#10212a",ring:"#2f5d6b",label:{it:"Mentale",en:"Mental"}},
    {key:"astrale",color:"#2a1410",ring:"#7c3a2a",label:{it:"Astrale",en:"Astral"}},
    {key:"fisico",color:"#3a2c10",ring:"#c9973a",label:{it:"Fisico",en:"Physical"}}
  ],
  modeDefs: {
    corpo: { type:"scenario", roman:"I", glyph:"◐", optionKeys:[0,1,2], count:10,
      items: [
        {sit:{it:"Un corpo trasparente fatto di materia luminosa, dove non c'è notte né ombre.",en:"A transparent body made of luminous matter, where there is no night or shadows."},correct:1,note:{it:"Corpo astrale: sul piano astrale non c'è mai la notte, i corpi sono trasparenti e tutta la materia è luminosa.",en:"Astral body: on the astral plane there is never night, bodies are transparent and all matter is luminous."}},
        {sit:{it:"Un veicolo che si stacca nel sonno e vaga senza controllo, trascinato da desideri e paure.",en:"A vehicle that detaches in sleep and wanders without control, driven by desires and fears."},correct:1,note:{it:"Corpo astrale: tutti viaggiano così durante il sonno, ma mancando consapevolezza i viaggi sono confusi.",en:"Astral body: everyone travels this way in sleep, but lacking awareness the journeys are confused."}},
        {sit:{it:"Un doppio energetico, perfetto duplicato del corpo denso, che si estende per circa mezzo centimetro oltre la pelle.",en:"An energetic double, a perfect duplicate of the dense body, extending about half a centimetre beyond the skin."},correct:0,note:{it:"Corpo eterico (fisico): il 'doppio eterico' è la controparte energetica del corpo denso.",en:"Etheric body (physical): the 'etheric double' is the energetic counterpart of the dense body."}},
        {sit:{it:"La sede dei pensieri e delle immagini mentali; viene abbandonata con la terza morte.",en:"The seat of thoughts and mental images; it is abandoned at the third death."},correct:2,note:{it:"Corpo mentale: nella fase paradisiaca l'uomo si libera del guscio formato dai pensieri, lo abbandona e muore una terza volta.",en:"Mental body: in the paradise phase one frees oneself from the shell formed by thoughts, abandons it and dies a third time."}},
        {sit:{it:"Un campo di forza dove si percepiscono gli oggetti da tutti i lati contemporaneamente.",en:"A field of force where objects are perceived from all sides simultaneously."},correct:1,note:{it:"Corpo astrale: la vista astrale è quadridimensionale — ogni particella interna è visibile come l'esterno.",en:"Astral body: astral sight is four-dimensional — every inner particle is as visible as the outside."}},
        {sit:{it:"Il veicolo denso di carne e ossa che si abbandona alla prima morte.",en:"The dense vehicle of flesh and bone that is left at the first death."},correct:0,note:{it:"Corpo fisico: è il piano più grossolano, abbandonato al momento della morte.",en:"Physical body: the coarsest plane, left behind at the moment of death."}},
        {sit:{it:"Il corpo dove risiedono le forme-pensiero e i condizionamenti intellettuali.",en:"The body where thought-forms and intellectual conditioning reside."},correct:2,note:{it:"Corpo mentale: sede delle convinzioni e dei ragionamenti — l'alto e il basso della mente.",en:"Mental body: seat of beliefs and reasoning — the high and low of the mind."}},
        {sit:{it:"Un incessante gioco di colori che riflette ogni emozione provata in tempo reale.",en:"An incessant play of colours reflecting every emotion felt in real time."},correct:1,note:{it:"Corpo astrale/mercuriale: i colori dell'aura astrale cambiano istantaneamente con le emozioni.",en:"Astral/mercurial body: the colours of the astral aura change instantly with emotions."}},
        {sit:{it:"Il corpo che, una volta trasmutato, diventa il corpo Atmico: la resurrezione nella carne.",en:"The body that, once transmuted, becomes the Atmic body: the resurrection in the flesh."},correct:0,note:{it:"Corpo fisico trasmutato: la 'risurrezione nella carne' avviene quando il fisico sale di livello.",en:"Transmuted physical body: the 'resurrection in the flesh' occurs when the physical rises in level."}},
        {sit:{it:"Una griglia di linee energetiche, paralleli e meridiani, attorno a cui il corpo si forma già nell'utero.",en:"A grid of energy lines, parallels and meridians, around which the body forms already in the womb."},correct:0,note:{it:"Doppio eterico: vi si vedono i blocchi che impediscono al prana di fluire, per questo conta nell'agopuntura e nella pranoterapia.",en:"Etheric double: the blocks that stop prana flowing can be seen there, which is why it matters in acupuncture and pranotherapy."}},
        {sit:{it:"Un'aura che va da 30/60 cm a diversi metri, secondo l'evoluzione emotiva della persona.",en:"An aura ranging from 30/60 cm to several metres, according to the person's emotional evolution."},correct:1,note:{it:"Corpo astrale o emotivo: i chiaroveggenti riscontrano differenze anche notevoli fra un individuo e l'altro.",en:"Astral or emotional body: clairvoyants find even considerable differences between one individual and another."}},
        {sit:{it:"Un'aura che in un iniziato può coprire un'intera sala da conferenze.",en:"An aura that in an initiate can cover an entire conference hall."},correct:2,note:{it:"Corpo mentale: la sua aura è più estesa di quella del corpo astrale e dipende dal grado di sviluppo dell'individuo.",en:"Mental body: its aura is wider than that of the astral body and depends on the individual's degree of development."}},
        {sit:{it:"Ogni emozione vi scava un solco, e ripeterla diventa sempre più facile.",en:"Every emotion carves a groove in it, and repeating it becomes ever easier."},correct:1,note:{it:"Corpo astrale: l'energia segue sempre le linee di minor resistenza, così la sua materia diventa sempre più responsiva a quel tipo di emozione.",en:"Astral body: energy always follows the lines of least resistance, so its matter becomes ever more responsive to that kind of emotion."}},
        {sit:{it:"Vi nasce l'onda-pensiero, che si irradia in tutte le direzioni e ricrea un pensiero simile in chi ci sta accanto.",en:"The thought-wave arises there, radiating in all directions and recreating a similar thought in those near us."},correct:2,note:{it:"Corpo mentale: l'onda-pensiero va a risvegliare negli altri lo stesso tipo di sostanza mentale.",en:"Mental body: the thought-wave awakens the same kind of mental substance in others."}}
      ]
    },
    abitante: { type:"scenario", roman:"II", glyph:"◇", optionKeys:[0,1,2], count:10,
      items: [
        {sit:{it:"Massa informe che reagisce in una frazione di secondo a ogni pensiero umano, plasmandosi in un essere temporaneo.",en:"A formless mass reacting in a fraction of a second to every human thought, shaping itself into a temporary being."},correct:2,note:{it:"Essenza elementale: diffusa in tutto l'astrale, viene plasmata dai pensieri e dalle emozioni umane.",en:"Elemental essence: spread throughout the astral, it is shaped by human thoughts and emotions."}},
        {sit:{it:"Cadavere astrale che conserva l'apparenza e la memoria del defunto, ingannando i medium.",en:"An astral corpse keeping the appearance and memory of the deceased, deceiving mediums."},correct:1,note:{it:"Ombre: il cadavere astrale lasciato quando l'uomo muore sul piano astrale.",en:"Shades: the astral corpse left behind when one dies on the astral plane."}},
        {sit:{it:"Gnomi, ondine, silfidi, salamandre: amano il gioco e lo scherzo, rifuggono l'uomo.",en:"Gnomes, undines, sylphs, salamanders: they love play and pranks, they shun humankind."},correct:2,note:{it:"Spiriti di natura: gnomi (terra), ondine (acqua), silfidi (aria), salamandre (etere).",en:"Nature spirits: gnomes (earth), undines (water), sylphs (air), salamanders (ether)."}},
        {sit:{it:"Esseri potentissimi che si nutrono dei pensieri separativi e delle emozioni negative dell'umanità.",en:"Very powerful beings that feed on humanity's separative thoughts and negative emotions."},correct:2,note:{it:"Demoni: entità astrali che agiscono per egoismo. I più noti sono i 'rettiliani'.",en:"Demons: astral entities acting out of selfishness. The best known are the 'reptilians'."}},
        {sit:{it:"Persone comuni che ogni notte, durante il sonno, vagano in astrale senza consapevolezza.",en:"Ordinary people who every night, during sleep, wander the astral without awareness."},correct:0,note:{it:"Tutti viaggiano così durante il sonno: mancando controllo, tali viaggi sono confusi e poco utili.",en:"Everyone travels this way in sleep: lacking control, such journeys are confused and of little use."}},
        {sit:{it:"Individui trapassati in circostanze traumatiche che cercano di restare vicino al piano fisico.",en:"Individuals who died in traumatic circumstances, trying to stay near the physical plane."},correct:1,note:{it:"Suicidi e vittime di morte improvvisa: non accettano la nuova condizione.",en:"Suicides and victims of sudden death: they don't accept their new condition."}},
        {sit:{it:"Detti angeli o 'figli di Dio': appartengono a un'evoluzione superiore all'umanità.",en:"Called angels or 'sons of God': they belong to an evolution above humanity."},correct:2,note:{it:"Deva: tutto ciò che è cattivo è stato eliminato dal loro essere.",en:"Devas: all that is evil has been removed from their being."}},
        {sit:{it:"Maghi che usano il corpo astrale come primo veicolo di esplorazione cosciente.",en:"Magi who use the astral body as their first vehicle for conscious exploration."},correct:0,note:{it:"Maghi e loro allievi: ancora vivi nel corpo fisico, viaggiano coscientemente in astrale.",en:"Magi and their pupils: still alive in the physical body, they travel consciously in the astral."}},
        {sit:{it:"Anime che, pur di non sparire, restano nel sottopiano vicino alla materia nutrendosi dei vizi e delle emozioni più basse degli uomini.",en:"Souls who, rather than disappear, stay in the subplane near matter, feeding on people's vices and lowest emotions."},correct:1,note:{it:"Vampiri: molti preferiscono sopravvivere in forma di «vampiri» piuttosto che sparire per sempre.",en:"Vampires: many prefer to survive in the form of 'vampires' rather than disappear forever."}},
        {sit:{it:"Persone con poteri psichici che viaggiano coscienti in astrale senza la guida di un iniziato.",en:"People with psychic powers who travel consciously in the astral without an initiate's guidance."},correct:0,note:{it:"Psichici: se non sono seguiti e istruiti da un iniziato, spesso interpretano ciò che vedono in modo frammentario ed errato.",en:"Psychics: if not guided and taught by an initiate, they often interpret what they see in a fragmentary, mistaken way."}},
        {sit:{it:"Resti astrali all'ultimo stadio di disintegrazione, che riti Voodoo possono rianimare.",en:"Astral remains in the last stage of disintegration, which Voodoo rites can revive."},correct:1,note:{it:"Gusci: ombre all'ultimo stadio prima di scomparire, che la magia nera o i riti Voodoo e Obeah possono vitalizzare.",en:"Shells: shades in the last stage before vanishing, which black magic or Voodoo and Obeah rites can revitalise."}},
        {sit:{it:"Allievi di iniziati che dopo la morte rinunciano a salire per reincarnarsi presto, e intanto assistono altre anime.",en:"Pupils of initiates who after death forgo rising in order to reincarnate soon, meanwhile assisting other souls."},correct:1,note:{it:"Allievi: così continuano a svolgere il loro lavoro a favore dell'umanità.",en:"Pupils: in this way they continue their work for humanity."}},
        {sit:{it:"Maghi neri defunti, disposti a qualunque nefandezza pur di restare in astrale e rubare energia ai viventi.",en:"Deceased black magi, ready for any atrocity to remain in the astral and steal energy from the living."},correct:1,note:{it:"Maghi neri dopo la morte: le loro azioni vengono spesso scambiate per attività di demoni.",en:"Black magi after death: their actions are often mistaken for the activity of demons."}},
        {sit:{it:"Maghi ancora incarnati che acquisiscono poteri astrali per soggiogare l'umanità.",en:"Magi still incarnate who acquire astral powers to subjugate humanity."},correct:0,note:{it:"Maghi neri viventi: la stessa preparazione dei maghi bianchi, ma con poteri acquisiti per scopi egoistici.",en:"Living black magi: the same training as white magi, but with powers acquired for selfish ends."}},
        {sit:{it:"Mostri dai colori cupi nati da pensieri di disprezzo, che si ritirano davanti alla volontà del Mago.",en:"Dark-coloured monsters born of thoughts of contempt, which retreat before the Magus's will."},correct:2,note:{it:"Entità elementali: prendono forma dai pensieri e dalle emozioni pesanti delle persone.",en:"Elemental entities: they take shape from people's thoughts and heavy emotions."}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"Quanti sono i piani dell'universo manifesto?",en:"How many planes does the manifest universe have?"},options:{it:["Sette","Tre","Dodici","Quattro"],en:["Seven","Three","Twelve","Four"]},correct:0,note:{it:"Fisico, Astrale, Mentale, Buddhico, Atmico, Anupadaka, Adi.",en:"Physical, Astral, Mental, Buddhic, Atmic, Anupadaka, Adi."}},
        {q:{it:"In alchimia il corpo astrale è detto…",en:"In alchemy the astral body is called…"},options:{it:["Fluidico o Mercuriale","Atmico","Causale","Buddhico"],en:["Fluidic or Mercurial","Atmic","Causal","Buddhic"]},correct:0,note:{it:"Il corpo emotivo è detto Fluidico o Mercuriale per il gioco incessante dei colori.",en:"The emotional body is called Fluidic or Mercurial for the incessant play of colours."}},
        {q:{it:"Quante 'morti' descrivono gli scritti esoterici?",en:"How many 'deaths' do esoteric writings describe?"},options:{it:["Tre: una per ogni corpo","Una soltanto","Sette","Nessuna"],en:["Three: one for each body","Only one","Seven","None"]},correct:0,note:{it:"Una morte per ciascun corpo: fisico, emotivo e mentale.",en:"One death for each body: physical, emotional and mental."}},
        {q:{it:"Quando l'uomo sogna, si trova nel…",en:"When a person dreams, they are in the…"},options:{it:["Corpo astrale","Corpo causale","Corpo atmico","Nessun corpo"],en:["Astral body","Causal body","Atmic body","No body"]},correct:0,note:{it:"Nel sogno siamo nel corpo astrale: la lucidità dei sogni rivela quella che avremo da disincarnati.",en:"In dreams we are in the astral body: the lucidity of dreams reveals what we'll have once disincarnate."}},
        {q:{it:"L'esperienza dell''inferno' nel piano astrale serve a…",en:"The 'hell' experience on the astral plane serves to…"},options:{it:["Bruciare le emozioni inferiori e gli attaccamenti","Punire per l'eternità","Cancellare la memoria","Premiare i giusti"],en:["Burn lower emotions and attachments","Punish for eternity","Erase memory","Reward the righteous"]},correct:0,note:{it:"Non c'è punizione: è un processo di disgregazione dei condizionamenti emotivi.",en:"There is no punishment: it is a process of disintegrating emotional conditioning."}},
        {q:{it:"Cosa accade nel primo periodo dopo la morte?",en:"What happens in the first period after death?"},options:{it:["Si rivede tutta la vita 'all'indietro'","Si dimentica tutto","Si rinasce subito","Si incontra un giudice"],en:["One reviews all of life 'backwards'","One forgets everything","One is reborn at once","One meets a judge"]},correct:0,note:{it:"Rivedendo la vita al contrario si perde la connessione causa/effetto, e il comune giudizio sugli eventi viene sospeso.",en:"Reviewing life backwards, the cause/effect connection is lost and ordinary judgment of events is suspended."}},
        {q:{it:"Gli spiriti della terra, acqua, aria ed etere sono…",en:"The spirits of earth, water, air and ether are…"},options:{it:["Gnomi, ondine, silfidi, salamandre","Deva, ombre, gusci, vampiri","Gnomi, sirene, fate, draghi","Folletti, fate, elfi, troll"],en:["Gnomes, undines, sylphs, salamanders","Devas, shades, shells, vampires","Gnomes, sirens, fairies, dragons","Goblins, fairies, elves, trolls"]},correct:0,note:{it:"Gnomi = terra, ondine = acqua, silfidi = aria, salamandre = etere.",en:"Gnomes = earth, undines = water, sylphs = air, salamanders = ether."}},
        {q:{it:"Una forma-pensiero di gelosia, se alimentata, può…",en:"A thought-form of jealousy, if fed, can…"},options:{it:["'Attaccarsi' a un uomo per tutta la vita","Dissolversi subito","Trasformarsi in un Deva","Diventare un corpo fisico"],en:["'Attach' itself to a person for life","Dissolve at once","Turn into a Deva","Become a physical body"]},correct:0,note:{it:"L'elementale cerca di sopravvivere e spinge a ripetere il pensiero che lo alimenta.",en:"The elemental seeks to survive and pushes one to repeat the thought that feeds it."}},
        {q:{it:"Il 'corpo di gloria' corrisponde a…",en:"The 'body of glory' corresponds to…"},options:{it:["I tre corpi superiori: causale, buddhico, atmico","Solo il corpo astrale","Solo il corpo mentale","Il corpo eterico"],en:["The three higher bodies: causal, buddhic, atmic","Only the astral body","Only the mental body","The etheric body"]},correct:0,note:{it:"Il percorso alchemico porta alla costruzione dei tre corpi superiori al contempo.",en:"The alchemical path leads to building the three higher bodies at once."}},
        {q:{it:"Il 'mago nero' cerca l'immortalità…",en:"The 'black magus' seeks immortality…"},options:{it:["Fissando e abitando il corpo astrale","Aprendo il Cuore","Dissolvendosi nell'Uno","Rinunciando a ogni potere"],en:["By fixing and inhabiting the astral body","By opening the Heart","By dissolving into the One","By renouncing all power"]},correct:0,note:{it:"Chi si separa dall'anima può solo sopravvivere in astrale: le Logge Nere cercano allievi disciplinati.",en:"One severed from the soul can only survive in the astral: Black Lodges seek disciplined pupils."}},
        {q:{it:"Secondo La porta del mago, durante i discorsi in pubblico Hitler…",en:"According to La porta del mago, during his public speeches Hitler…"},options:{it:["Canalizzava una potente entità diabolica che lo possedeva","Parlava come un mago bianco","Era in uno stato di illuminazione","Recitava un testo scritto da altri"],en:["Channelled a powerful diabolical entity that possessed him","Spoke as a white magus","Was in a state of enlightenment","Recited a text written by others"]},correct:0,note:{it:"Brizzi lo definisce un «avatar nero», cioè l'incarnazione più perfetta delle forze duali che vogliono soggiogare il pianeta.",en:"Brizzi calls him a 'black avatar', that is, the most perfect incarnation of the dual forces that want to subjugate the planet."}},
        {q:{it:"Nell'aura astrale la gelosia appare come…",en:"In the astral aura jealousy appears as…"},options:{it:["Bruno-verdastro con lampi scarlatti","Rosa","Giallo primula","Blu chiaro"],en:["Greenish-brown with scarlet flashes","Pink","Primrose yellow","Light blue"]},correct:0,note:{it:"Ogni emozione ha un colore nell'aura: rosa è l'amore non egoista, giallo primula l'intelletto votato a scopi spirituali, blu chiaro la devozione a un nobile ideale.",en:"Every emotion has a colour in the aura: pink is unselfish love, primrose yellow the intellect devoted to spiritual aims, light blue devotion to a noble ideal."}},
        {q:{it:"Sul piano astrale, venendo a contatto con un oggetto, si percepisce…",en:"On the astral plane, touching an object, one perceives…"},options:{it:["Un grado vibratorio diverso","Se è caldo o freddo","Se è ruvido o liscio","Il suo peso"],en:["A different vibratory degree","Whether it is hot or cold","Whether it is rough or smooth","Its weight"]},correct:0,note:{it:"Non si sentono superfici dure o morbide, ruvide o lisce, calde o fredde: il contatto può risultare piacevole o spiacevole, stimolante o deprimente.",en:"One does not feel hard or soft, rough or smooth, hot or cold surfaces: the contact may feel pleasant or unpleasant, stimulating or depressing."}},
        {q:{it:"Il settimo sottopiano astrale è…",en:"The seventh astral subplane is…"},options:{it:["Il più denso, come un fluido nero e vischioso","Il più luminoso","Quello dei religiosi","Quello dei ricercatori"],en:["The densest, like a black viscous fluid","The brightest","That of the religious","That of researchers"]},correct:0,note:{it:"Vi dimorano a lungo gli assassini, i pervertiti e gli schiavi dei loro vizi, prima di iniziare la loro ascesa.",en:"Murderers, perverts and slaves of their vices dwell there a long time before starting their ascent."}},
        {q:{it:"Chi abita soprattutto il secondo sottopiano astrale?",en:"Who chiefly inhabits the second astral subplane?"},options:{it:["Religiosi egoisti che costruiscono templi immaginari","Assassini e criminali","Deva","Spiriti di natura"],en:["Selfish religious people building imaginary temples","Murderers and criminals","Devas","Nature spirits"]},correct:0,note:{it:"Vi adorano una riproduzione della divinità che già adoravano nel mondo fisico.",en:"There they worship a copy of the deity they already worshipped in the physical world."}},
        {q:{it:"Perché bisognerebbe attendere tre giorni prima della cremazione?",en:"Why should one wait three days before cremation?"},options:{it:["Perché il cordone argenteo fra eterico e fisico possa recidersi","Per rispetto della tradizione","Per motivi igienici","Per permettere ai parenti di salutare"],en:["So the silver cord between etheric and physical can sever","Out of respect for tradition","For hygienic reasons","To let relatives say goodbye"]},correct:0,note:{it:"Il cordone argenteo lega il corpo eterico al corpo fisico e deve avere il tempo di recidersi.",en:"The silver cord binds the etheric body to the physical body and needs time to sever."}},
        {q:{it:"La disperazione dei parenti inconsolabili, per il defunto, è…",en:"The despair of inconsolable relatives, for the deceased, is…"},options:{it:["Nociva: lo trattiene in basso","Un aiuto a salire","Indifferente","Necessaria per il distacco"],en:["Harmful: it holds him down","A help to rise","Irrelevant","Necessary for detachment"]},correct:0,note:{it:"Aiutano invece i pensieri di stima, di amore e di incoraggiamento a procedere nel cammino.",en:"Thoughts of esteem, love and encouragement to go on along the path help instead."}},
        {q:{it:"Secondo I mondi spirituali, la pena di morte…",en:"According to I mondi spirituali, the death penalty…"},options:{it:["Libera il criminale sul piano astrale, dove può nuocere di più","Elimina il criminale per sempre","Purifica la sua anima","Non ha alcuna conseguenza sottile"],en:["Frees the criminal onto the astral plane, where he can do more harm","Eliminates the criminal forever","Purifies his soul","Has no subtle consequence"]},correct:0,note:{it:"Nel corpo fisico può nuocere a una persona per volta; dall'astrale immette forme-pensiero di odio e violenza negli altri abitanti e, da lì, in quelli del piano fisico.",en:"In the physical body he can harm one person at a time; from the astral he injects thought-forms of hatred and violence into its other inhabitants and, from there, into those of the physical plane."}},
        {q:{it:"Il 'fuoco dell'Inferno' è…",en:"The 'fire of Hell' is…"},options:{it:["La sensazione dolorosa del distaccarsi degli atomi astrali","Un fuoco fisico sottoterra","Una punizione divina eterna","Un simbolo senza realtà"],en:["The painful sensation of astral atoms detaching","A physical fire underground","An eternal divine punishment","A symbol without reality"]},correct:0,note:{it:"Il dolore è sempre proporzionale ai nostri attaccamenti e alla nostra incapacità di amare.",en:"The pain is always proportional to our attachments and our inability to love."}},
        {q:{it:"Dopo la morte il corpo astrale si 'riorganizza'…",en:"After death the astral body 'reorganises' itself…"},options:{it:["Disponendo gli atomi più pesanti all'esterno, come una corazza","Dissolvendosi subito","Trasformandosi in corpo causale","Tornando nel corpo fisico"],en:["Placing its heaviest atoms outside, like armour","Dissolving at once","Turning into the causal body","Returning to the physical body"]},correct:0,note:{it:"Lo si può evitare con la Presenza e con l'uso di Volontà e Amore al momento del trapasso.",en:"It can be avoided through Presence and the use of Will and Love at the moment of passing."}},
        {q:{it:"Dal punto di vista dell'anima, le incarnazioni…",en:"From the soul's point of view, incarnations…"},options:{it:["Avvengono tutte contemporaneamente","Si susseguono una dopo l'altra","Sono solo una","Si ripetono identiche"],en:["All happen simultaneously","Follow one after another","Are only one","Repeat identically"]},correct:0,note:{it:"La successione è un'invenzione della personalità: le esistenze di un'anima si svolgono simultaneamente e si inviano messaggi di continuo.",en:"Succession is an invention of the personality: a soul's lives unfold simultaneously and constantly send each other messages."}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✶",
      items: [
        {a:{it:"Gnomi",en:"Gnomes"},b:{it:"Terra",en:"Earth"}},
        {a:{it:"Ondine",en:"Undines"},b:{it:"Acqua",en:"Water"}},
        {a:{it:"Silfidi",en:"Sylphs"},b:{it:"Aria",en:"Air"}},
        {a:{it:"Salamandre",en:"Salamanders"},b:{it:"Etere",en:"Ether"}},
        {a:{it:"Corpo astrale",en:"Astral body"},b:{it:"Mercuriale",en:"Mercurial"}},
        {a:{it:"Corpo di gloria",en:"Body of glory"},b:{it:"Causale + Buddhico\n+ Atmico",en:"Causal + Buddhic\n+ Atmic"}},
        {a:{it:"Rosa",en:"Pink"},b:{it:"Amore\nnon egoista",en:"Unselfish\nlove"}},
        {a:{it:"Grigio livido",en:"Livid grey"},b:{it:"Paura",en:"Fear"}},
        {a:{it:"Kamaloka",en:"Kamaloka"},b:{it:"Inferno e\nPurgatorio",en:"Hell and\nPurgatory"}}
      ]
    }
  }
};
})();
