/* LE EMOZIONI — data.js (pooled from 5 books) */
(function(){
"use strict";
window.GAME_DATA = {
  id: "emoz",
  modes: ["ottava","cuore","quiz","memoria"],
  rings: [
    {key:"perdono",color:"#1a1326",ring:"#3a2f52",label:{it:"Il Perdono",en:"Forgiveness"}},
    {key:"trasmut",color:"#10212a",ring:"#2f5d6b",label:{it:"Trasmutazione",en:"Transmutation"}},
    {key:"giudizio",color:"#2a1410",ring:"#7c3a2a",label:{it:"Non-giudizio",en:"Non-judgment"}},
    {key:"cuore",color:"#3a2c10",ring:"#c9973a",label:{it:"Il Cuore",en:"The Heart"}}
  ],
  modeDefs: {
    ottava: { type:"classify", roman:"I", glyph:"◐", count:10, optionKeys:[0,1],
      items: [
        {item:{it:"Compassione: gioia nel vedere un'anima che impara attraverso la sofferenza",en:"Compassion: joy seeing a soul learning through suffering"},belongs:1,note:{it:"L'ottava alta della pietà. Nella compassione c'è il senso della perfezione del creato.",en:"The high octave of pity. In compassion there is the sense of creation's perfection."}},
        {item:{it:"Pietà: considerare l'altro un povero sfortunato",en:"Pity: considering the other a poor unfortunate"},belongs:0,note:{it:"Nella pietà è presente il senso dell'ingiustizia, della sfortuna e dell'inferiorità.",en:"In pity there is the sense of injustice, misfortune and inferiority."}},
        {item:{it:"Innocuità: avere la possibilità di intervenire, ma decidere di non farlo",en:"Harmlessness: having the ability to intervene, but deciding not to"},belongs:1,note:{it:"Le autentiche arti marziali: la forza di non usare la forza.",en:"Authentic martial arts: the strength not to use strength."}},
        {item:{it:"Impotenza: non avere la capacità di intervenire",en:"Impotence: not having the ability to intervene"},belongs:0,note:{it:"Non è una scelta cosciente ma un'incapacità: l'ottava bassa dell'innocuità.",en:"Not a conscious choice but an incapacity: the low octave of harmlessness."}},
        {item:{it:"Solitudine: capire di non essere mai soli, uniti a tutti gli altri",en:"Solitude: understanding one is never alone, united with all others"},belongs:1,note:{it:"La solitudine è una conquista dell'anima: sento l'unità con il Tutto.",en:"Solitude is a conquest of the soul: I feel unity with the All."}},
        {item:{it:"Sentirsi soli: credere di essere separati dagli altri e soffrirne",en:"Feeling lonely: believing oneself separate from others and suffering"},belongs:0,note:{it:"L'ottava bassa della solitudine: la separazione come sofferenza.",en:"The low octave of solitude: separation as suffering."}},
        {item:{it:"Devozione: riconoscere liberamente la grandezza dell'altro",en:"Devotion: freely recognising the other's greatness"},belongs:1,note:{it:"Nella devozione si riconosce la grandezza senza servilismo.",en:"In devotion one recognises greatness without servility."}},
        {item:{it:"Servilismo: servire sperando in un tornaconto",en:"Servility: serving hoping for a gain"},belongs:0,note:{it:"L'ottava bassa della devozione: si serve per ottenere qualcosa.",en:"The low octave of devotion: one serves to obtain something."}},
        {item:{it:"Autostima: stimare le proprie qualità riconoscendo che ci sono state donate",en:"Self-esteem: esteeming qualities while recognising they were given"},belongs:1,note:{it:"L'autostima vera non compete: riconosce il valore ricevuto.",en:"True self-esteem doesn't compete: it recognises received value."}},
        {item:{it:"Orgoglio: credere che le qualità siano nostre ed entrare in competizione",en:"Pride: believing qualities are ours and entering competition"},belongs:0,note:{it:"L'ottava bassa dell'autostima: si attribuisce il merito a sé.",en:"The low octave of self-esteem: one credits oneself."}},
        {item:{it:"Umiltà: sicurezza che nasce dalla comprensione della propria forza",en:"Humility: confidence born from understanding one's own strength"},belongs:1,note:{it:"Non si ha più bisogno di dimostrare il proprio valore.",en:"One no longer needs to prove one's worth."}},
        {item:{it:"Disistima: incapacità di riconoscere le proprie qualità",en:"Low self-esteem: inability to recognise one's qualities"},belongs:0,note:{it:"L'ottava bassa dell'umiltà: non riconoscere ciò che si è.",en:"The low octave of humility: not recognising what one is."}},
        {item:{it:"Neutralità: vedere dietro le apparenze e capire che è meglio non schierarsi",en:"Neutrality: seeing behind appearances and understanding it's better not to take sides"},belongs:1,note:{it:"L'ottava alta del non prendere posizione.",en:"The high octave of not taking a position."}},
        {item:{it:"Menefreghismo: non mi importa niente di un fenomeno, quindi non prendo posizione",en:"Not caring: I don't care about something, so I take no position"},belongs:0,note:{it:"Stesso comportamento esterno della neutralità, ma nasce dall'indifferenza.",en:"Same outward behaviour as neutrality, but born of indifference."}},
        {item:{it:"Appartenenza: sento che l'altro è parte di me e io di lui, in un progetto animico condiviso",en:"Belonging: I feel the other is part of me and I of them, in a shared soul project"},belongs:1,note:{it:"Insieme apparteniamo a un progetto animico che condividiamo.",en:"Together we belong to a soul project that we share."}},
        {item:{it:"Possesso: credo che il partner sia mio e lo difendo dalle «insidie» degli altri",en:"Possession: I believe my partner is mine and defend them from others' 'snares'"},belongs:0,note:{it:"L'ottava bassa dell'appartenenza.",en:"The low octave of belonging."}},
        {item:{it:"Amore incondizionato: amo l'altro perché esiste, anche se decide di andarsene",en:"Unconditional love: I love the other because they exist, even if they decide to leave"},belongs:1,note:{it:"È l'agápe, il vero Amore: amiamo l'altro senza possesso.",en:"It is agápe, true Love: we love the other without possession."}},
        {item:{it:"Amore possessivo: amo solo nella misura in cui vengo ricambiato come mi aspetto",en:"Possessive love: I love only to the extent I am loved back as I expect"},belongs:0,note:{it:"Le sue conseguenze sono delusione, rancore, gelosia, desiderio di vendetta.",en:"Its consequences are disappointment, resentment, jealousy, desire for revenge."}}
      ]
    },
    cuore: { type:"scenario", roman:"II", glyph:"◇", count:10, optionKeys:[0,1],
      items: [
        {sit:{it:"Qualcuno ti ferisce con parole dure: sposti l'attenzione dal suo comportamento alla rabbia che provi tu.",en:"Someone wounds you with harsh words: you shift your attention from their behaviour to the anger you feel."},correct:1,note:{it:"L'attenzione va sull'emozione che provo, non sul comportamento dell'altro.",en:"Attention goes to the emotion I feel, not to the other's behaviour."}},
        {sit:{it:"Ti hanno fatto un torto; in un lampo vedi che l'altro non ti ha mai fatto nulla.",en:"You were wronged; in a flash you see that the other never did anything to you."},correct:1,note:{it:"Vero perdono: realizzare che l'altro non mi ha mai fatto nulla. Sono le mie emozioni a creare gli eventi.",en:"True forgiveness: realising the other never did anything to me. My emotions create events."}},
        {sit:{it:"Un difetto altrui ti irrita, e cerchi in te stesso quella stessa caratteristica.",en:"Someone else's flaw irritates you, and you look for that same trait in yourself."},correct:1,note:{it:"Attraverso gli altri sto giudicando una parte di me che ancora rifiuto.",en:"Through others I am judging a part of myself I still reject."}},
        {sit:{it:"Provi un'emozione negativa intensa: la accogli e la porti nel Cuore invece di scacciarla.",en:"You feel an intense negative emotion: you welcome it and bring it into the Heart instead of driving it away."},correct:1,note:{it:"La accolgo e la sciolgo nel Fuoco del Cuore: il demone diventa angelo.",en:"I welcome it and dissolve it in the Heart's Fire: the demon becomes an angel."}},
        {sit:{it:"Il mondo dovrebbe essere diverso da com'è: sono gli altri che devono cambiare.",en:"The world should be different from how it is: it's the others who must change."},correct:0,note:{it:"Ogni schema su come dovrebbe essere il mondo nasconde un giudizio. Solo indagando noi stessi possiamo cambiare il mondo.",en:"Every pattern of how the world should be hides a judgment. Only by examining ourselves can we change the world."}},
        {sit:{it:"Devo restituire l'offesa colpo su colpo per difendere il mio onore.",en:"I must return the offence blow for blow to defend my honour."},correct:0,note:{it:"Ogni re-azione è perfetta per quel grado di coscienza: il punto è l'emozione che provo io.",en:"Every re-action is perfect for that degree of consciousness: the point is the emotion I feel."}},
        {sit:{it:"Il perdono è da deboli: perdonerò solo dopo le scuse.",en:"Forgiveness is for the weak: I'll forgive only after an apology."},correct:0,note:{it:"Il perdono è una facoltà sovrumana, lo strumento del vero Guerriero, non da debosciati.",en:"Forgiveness is a superhuman faculty, the weapon of the true Warrior, not for the dissolute."}},
        {sit:{it:"Quella persona è semplicemente sbagliata, il problema è solo suo.",en:"That person is simply wrong, the problem is theirs alone."},correct:0,note:{it:"Più consideriamo sbagliata la materia, più ci allontaniamo dallo spirito.",en:"The more we deem matter wrong, the further we drift from spirit."}},
        {sit:{it:"Vedi un uomo rubare un portafogli: provi compassione per lui e intervieni per fermarlo.",en:"You see a man stealing a wallet: you feel compassion for him and step in to stop him."},correct:1,note:{it:"Le emozioni superiori «implicano azione, non passività».",en:"Higher emotions 'imply action, not passivity'."}},
        {sit:{it:"Ti arrabbi e pensi: «Chiunque si sarebbe arrabbiato al mio posto!»",en:"You get angry and think: 'Anyone would have got angry in my place!'"},correct:0,note:{it:"Giustificare l'emozione negativa le dà potere: la causa non può che essere al nostro interno.",en:"Justifying the negative emotion gives it power: the cause can only be within us."}},
        {sit:{it:"Hai provato gelosia e ti rimproveri duramente per averla provata.",en:"You felt jealousy and harshly scold yourself for feeling it."},correct:0,note:{it:"«Se è la nostra essenza a osservare, non c'è giudizio.»",en:"'If it is our essence that observes, there is no judgment.'"}},
        {sit:{it:"Ti dicono che un tale ha sparlato di te; rispondi: «Egli non conosceva gli altri miei difetti, altrimenti non avrebbe parlato solo di questo!»",en:"You're told someone spoke ill of you; you reply: 'He didn't know my other flaws, or he wouldn't have spoken only of this!'"},correct:1,note:{it:"Epitteto, Manuale, citato in «Officina Alkemica»: nessuna difesa, nessuna re-azione.",en:"Epictetus, Enchiridion, quoted in 'Officina Alkemica': no defence, no re-action."}},
        {sit:{it:"Sei bloccato in una lunga fila in banca e sfoghi la tua impazienza sull'impiegato.",en:"You're stuck in a long queue at the bank and vent your impatience on the clerk."},correct:0,note:{it:"«Resistete all'impulso di reagire. Non lasciatevi prendere dalla frustrazione o dall'impazienza.»",en:"'Resist the impulse to react. Don't give in to frustration or impatience.'"}},
        {sit:{it:"Il partner decide di andarsene e tu continui ad amarlo, senza disperazione.",en:"Your partner decides to leave and you keep loving them, without despair."},correct:1,note:{it:"Nell'emozione superiore non c'è aspettativa: è l'agápe, il vero Amore.",en:"In a higher emotion there is no expectation: it is agápe, true Love."}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"Le emozioni negative si chiamano 'negative' perché…",en:"Negative emotions are called 'negative' because…"},options:{it:["Sono l'altra faccia delle superiori, come numeri negativi","Sono sbagliate","Vanno represse","Non esistono"],en:["They are the other face of higher ones, like negative numbers","They are wrong","Must be repressed","Don't exist"]},correct:0,note:{it:"Sono il Piombo da trasmutare in Oro: preziose, non sbagliate.",en:"They are the Lead to transmute into Gold: precious, not wrong."}},
        {q:{it:"Il nucleo dell'Opera alchemica (Albedo) è…",en:"The core of the alchemical Work (Albedo) is…"},options:{it:["Trasmutare le emozioni negative in emozioni superiori","Accumulare conoscenze","Distruggere la personalità","Fuggire dalla materia"],en:["Transmuting negative emotions into higher emotions","Accumulating knowledge","Destroying the personality","Fleeing from matter"]},correct:0,note:{it:"Il Veleno diventa Farmaco: rabbia→beatitudine, paura→serenità.",en:"Poison becomes Remedy: anger→bliss, fear→serenity."}},
        {q:{it:"La vera 'Porta del Mago' è…",en:"The true 'Door of the Magus' is…"},options:{it:["La porta stretta del Cuore: perdono e non-giudizio","Un portale dimensionale","Un grimorio antico","Il corpo astrale"],en:["The narrow gate of the Heart: forgiveness and non-judgment","A dimensional portal","An ancient grimoire","The astral body"]},correct:0,note:{it:"Il ricordo di sé è solo propedeutico: la vera Porta è l'apertura del Cuore.",en:"Self-remembering is only preparatory: the true Door is the opening of the Heart."}},
        {q:{it:"Ogni emozione negativa è la manifestazione di…",en:"Every negative emotion is the manifestation of…"},options:{it:["Un giudizio che agisce nella mente","Un demone esterno","Una cattiva digestione","Un karma immutabile"],en:["A judgment acting in the mind","An external demon","Bad digestion","Immutable karma"]},correct:0,note:{it:"Il non-giudizio trasforma le emozioni negative in superiori: Piombo in Oro.",en:"Non-judgment transforms negative emotions into higher ones: Lead into Gold."}},
        {q:{it:"I Tre Segreti del Mago (Il bambino e il mago) sono…",en:"The Three Secrets (The child and the magus) are…"},options:{it:["Attrazione, Gratitudine, Amore","Forza, Coraggio, Saggezza","Fede, Speranza, Carità","Pensiero, Parola, Azione"],en:["Attraction, Gratitude, Love","Strength, Courage, Wisdom","Faith, Hope, Charity","Thought, Word, Action"]},correct:0,note:{it:"Attrazione: attiri ciò che sei. Gratitudine: magnete per il bene. Amore: unidirezionale dal Cuore.",en:"Attraction: you attract what you are. Gratitude: magnet for good. Love: unidirectional from the Heart."}},
        {q:{it:"Il corpo di gloria è costituito di…",en:"The body of glory is made of…"},options:{it:["Emozioni superiori","Emozioni negative","Pensieri razionali","Materia fisica"],en:["Higher emotions","Negative emotions","Rational thoughts","Physical matter"]},correct:0,note:{it:"Le emozioni superiori si sviluppano nutrendo il Bello e trasmutando le negative.",en:"Higher emotions develop by nourishing Beauty and transmuting the negative ones."}},
        {q:{it:"Il perdonare all'ottava alta significa…",en:"Forgiving at the high octave means…"},options:{it:["Realizzare che nessuno può fare del male alla nostra anima","Dimenticare in fretta","Aspettare le scuse","Fingere"],en:["Realising no one can harm our soul","Forgetting quickly","Waiting for an apology","Pretending"]},correct:0,note:{it:"All'ottava bassa: «Mi hai offeso, hai sbagliato, ma ci metto una pietra sopra». Non si è compreso che l'offesa in realtà non c'è mai stata.",en:"At the low octave: 'You offended me, you were wrong, but I'll let it go'. One hasn't understood that the offence never really occurred."}},
        {q:{it:"L'Amore, secondo 'Il bambino e il mago', è…",en:"Love, per 'The child and the magus', is…"},options:{it:["Unidirezionale: dal Cuore verso l'esterno, senza pretendere nulla","Un baratto equo","Solo per adulti","Qualcosa che si aspetta"],en:["Unidirectional: from Heart outward, expecting nothing","A fair barter","Only for adults","Something you expect"]},correct:0,note:{it:"«Fa' che l'Amore non sia un baratto, bensì un regalo.» Ama come ami un fiore: non pretendi che ricambi.",en:"'Let Love not be a barter, but a gift.' Love as you love a flower: you don't demand it loves you back."}},
        {q:{it:"«Cavalcare la Tigre» significa…",en:"'Riding the Tiger' means…"},options:{it:["Non manifestare le emozioni basse: tenerle dentro e osservarle col Cuore","Reprimere tutto","Sfogarsi","Ignorare"],en:["Not manifesting base emotions: keeping them inside and observing with the Heart","Repressing everything","Venting","Ignoring"]},correct:0,note:{it:"Non è repressione (involontaria) ma lavoro cosciente sulla trasmutazione.",en:"It is not repression (involuntary) but conscious work on transmutation."}},
        {q:{it:"Tutte le nostre sofferenze derivano da…",en:"All our suffering stems from…"},options:{it:["L'aridità del Cuore, la sua mancata apertura","Eventi esterni sfavorevoli","La cattiva sorte","L'azione degli altri"],en:["The dryness of the Heart, its failure to open","Unfavourable external events","Bad luck","Others' actions"]},correct:0,note:{it:"Nessuna difficoltà ha la sua fonte all'esterno: ogni problema origina dalla durezza del Cuore.",en:"No difficulty has its source outside: every problem originates from the hardness of the Heart."}},
        {q:{it:"Secondo «Officina Alkemica», si ha repressione quando…",en:"According to 'Officina Alkemica', repression occurs when…"},options:{it:["La non manifestazione dell'emozione è involontaria: l'ambiente lo impedisce o non ne siamo capaci","Scegliamo coscientemente di non manifestare l'emozione per osservarla","Trasmutiamo l'emozione nel Cuore","Accogliamo l'emozione senza giudicarla"],en:["Not expressing the emotion is involuntary: the environment prevents it or we are unable","We consciously choose not to express the emotion in order to observe it","We transmute the emotion in the Heart","We welcome the emotion without judging it"]},correct:0,note:{it:"Nel lavoro alchemico invece la non manifestazione è cosciente: si opera sulle emozioni negative dopo averne compreso la natura.",en:"In alchemical work, instead, non-expression is conscious: one works on negative emotions after understanding their nature."}},
        {q:{it:"Quando non perdoniamo, chi ci rimette?",en:"When we don't forgive, who pays the price?"},options:{it:["Noi stessi: il risentimento agisce come un acido sui nostri corpi sottili","Chi non viene perdonato","Nessuno","La società"],en:["We ourselves: resentment acts like an acid on our subtle bodies","The one who is not forgiven","No one","Society"]},correct:0,note:{it:"«Quando non perdoniamo ci rimettiamo noi, non coloro a cui non perdoniamo.»",en:"'When we don't forgive, we are the ones who lose, not those we fail to forgive.'"}},
        {q:{it:"Perdonare i propri nemici è la chiave per…",en:"Forgiving one's enemies is the key to…"},options:{it:["Lasciare il pianeta e non reincarnarsi più","Ottenere le loro scuse","Dimenticare l'offesa","Avere ragione"],en:["Leaving the planet and no longer reincarnating","Obtaining their apology","Forgetting the offence","Being right"]},correct:0,note:{it:"I nemici sono «tutti coloro che ci procurano un fastidio».",en:"Enemies are 'all those who cause us annoyance'."}},
        {q:{it:"Nella storiella ebrea citata da Brizzi, come si «vendica» il protagonista dei torti subiti?",en:"In the Jewish tale cited by Brizzi, how does the protagonist 'take revenge' for the wrongs suffered?"},options:{it:["Distribuendo intorno a sé tanto bene per quanto male aveva ricevuto","Restituendo il male ricevuto","Chiedendo giustizia a un giudice","Allontanandosi per sempre"],en:["By spreading as much good around him as the harm he had received","By returning the harm received","By asking a judge for justice","By going away forever"]},correct:0,note:{it:"«Questo comportamento lo porta in breve tempo all'illuminazione.»",en:"'This behaviour quickly leads him to enlightenment.'"}},
        {q:{it:"Le emozioni superiori sono «gratuite»: che cosa significa?",en:"Higher emotions are 'free': what does it mean?"},options:{it:["Che non vogliamo niente in cambio","Che arrivano senza alcun lavoro su di sé","Che non hanno valore","Che durano per sempre"],en:["That we want nothing in return","That they come without any inner work","That they have no value","That they last forever"]},correct:0,note:{it:"«Amiamo anche senza essere ricambiati, siamo amici anche di chi non è nostro amico.»",en:"'We love even without being loved back, we are friends even to those who are not our friends.'"}},
        {q:{it:"Qual è la «controindicazione obbligata» delle emozioni inferiori?",en:"What is the 'unavoidable side effect' of lower emotions?"},options:{it:["La sofferenza","La noia","La stanchezza fisica","Nessuna"],en:["Suffering","Boredom","Physical tiredness","None"]},correct:0,note:{it:"«Se amiamo aspettandoci qualcosa in cambio, prima o poi saremo costretti a soffrire.»",en:"'If we love expecting something in return, sooner or later we will be forced to suffer.'"}},
        {q:{it:"Perché, nel cammino evolutivo, sono esistite le emozioni negative?",en:"Why, in the course of evolution, have negative emotions existed?"},options:{it:["Per cominciare a percepire la sfera emotiva del pianeta","Per punirci","Per errore della natura","Per separarci dagli altri"],en:["To begin perceiving the emotional sphere of the planet","To punish us","By a mistake of nature","To separate us from others"]},correct:0,note:{it:"«Dobbiamo prima sentire pugni e schiaffi per poter un giorno percepire le carezze.»",en:"'We must first feel punches and slaps in order one day to perceive caresses.'"}},
        {q:{it:"Al bar i tifosi inveiscono contro l'arbitro e un signore comincia a inveire contro il Governo. Che cosa mostra l'esempio?",en:"At the bar, fans rail at the referee and a man starts railing at the Government. What does the example show?"},options:{it:["Che le emozioni negative non ci appartengono: la stessa vibrazione prende forme diverse","Che il signore ha ragione","Che la politica è più importante del calcio","Che le emozioni sono sempre personali"],en:["That negative emotions don't belong to us: the same vibration takes different forms","That the man is right","That politics matters more than football","That emotions are always personal"]},correct:0,note:{it:"La nostra anima non è influenzata dalle emozioni negative che sono nell'aria, la macchina biologica sì.",en:"Our soul is not affected by the negative emotions in the air; the biological machine is."}},
        {q:{it:"Secondo «La porta del mago», ogni nostra afflizione origina…",en:"According to 'La porta del mago', every affliction of ours originates…"},options:{it:["Dall'incapacità di perdonare una persona o una situazione","Dal destino","Da una colpa passata","Dal corpo fisico"],en:["From the inability to forgive a person or a situation","From destiny","From a past fault","From the physical body"]},correct:0,note:{it:"«Il perdono è la chiave con la quale aprire la serratura del Cuore.»",en:"'Forgiveness is the key that opens the lock of the Heart.'"}},
        {q:{it:"Secondo «Il lavoro alchemico», l'emozione superiore…",en:"According to 'Il lavoro alchemico', a higher emotion…"},options:{it:["Può solo essere attesa in raccoglimento e accolta quando giunge","Si provoca con lo sforzo di volontà","Si ottiene desiderandola intensamente","Si produce ripetendo una formula"],en:["Can only be awaited in inner recollection and welcomed when it comes","Is produced by effort of will","Is obtained by desiring it intensely","Is produced by repeating a formula"]},correct:0,note:{it:"«L'apertura del Cuore implica uno stato passivo, negativo e ricettivo.»",en:"'The opening of the Heart implies a passive, negative and receptive state.'"}},
        {q:{it:"Vista con lo sguardo dell'anima, l'aggressività diviene…",en:"Seen through the soul's eyes, aggressiveness becomes…"},options:{it:["Impeto guerriero","Indifferenza","Paura","Rassegnazione"],en:["Warrior impetus","Indifference","Fear","Resignation"]},correct:0,note:{it:"«Una stessa caratteristica vista con lo sguardo della personalità sembra un difetto, ma se è vista con lo sguardo dell'anima appare per ciò che è: una qualità.»",en:"'The same trait seen through the personality's eyes looks like a flaw, but seen through the soul's eyes it appears as what it is: a quality.'"}},
        {q:{it:"Viste dall'esterno, le emozioni superiori…",en:"Seen from outside, higher emotions…"},options:{it:["Somigliano a quelle inferiori: è difficile distinguerle","Sono sempre riconoscibili a colpo d'occhio","Non si manifestano mai","Sono identiche per tutti"],en:["Resemble lower ones: they are hard to tell apart","Are always recognisable at a glance","Never show","Are the same for everyone"]},correct:0,note:{it:"«Anche per chi prova l'emozione all'inizio è difficile distinguere fra le prime e le seconde.»",en:"'Even for the person feeling the emotion it is at first hard to tell the former from the latter.'"}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✶",
      items: [
        {a:{it:"Compassione",en:"Compassion"},b:{it:"Pietà",en:"Pity"}},
        {a:{it:"Innocuità",en:"Harmlessness"},b:{it:"Impotenza",en:"Impotence"}},
        {a:{it:"Solitudine",en:"Solitude"},b:{it:"Sentirsi soli",en:"Loneliness"}},
        {a:{it:"Devozione",en:"Devotion"},b:{it:"Servilismo",en:"Servility"}},
        {a:{it:"Autostima",en:"Self-esteem"},b:{it:"Orgoglio",en:"Pride"}},
        {a:{it:"Umiltà",en:"Humility"},b:{it:"Disistima",en:"Low self-esteem"}},
        {a:{it:"Neutralità",en:"Neutrality"},b:{it:"Menefreghismo",en:"Not caring"}},
        {a:{it:"Appartenenza",en:"Belonging"},b:{it:"Possesso",en:"Possession"}},
        {a:{it:"Regolarità, Ritmo",en:"Regularity, Rhythm"},b:{it:"Meccanicità, Abitudine",en:"Mechanicalness, Habit"}}
      ]
    }
  }
};
})();
