/* I MONDI INVISIBILI — data.js (from Mondi Spirituali + Risveglio + Porta del Mago) */
(function(){
"use strict";
window.GAME_DATA = {
  id: "mondi",
  modes: ["corpo","abitante","quiz","memoria"],
  rings: [
    {key:"adi",color:"#1a1326",ring:"#3a2f52",label:{it:"Adi",en:"Adi"}},
    {key:"mentale",color:"#10212a",ring:"#2f5d6b",label:{it:"Mentale",en:"Mental"}},
    {key:"astrale",color:"#2a1410",ring:"#7c3a2a",label:{it:"Astrale",en:"Astral"}},
    {key:"fisico",color:"#3a2c10",ring:"#c9973a",label:{it:"Fisico",en:"Physical"}}
  ],
  modeDefs: {
    corpo: { type:"scenario", roman:"I", glyph:"◐", optionKeys:[0,1,2],
      items: [
        {sit:{it:"Un corpo trasparente fatto di materia luminosa, dove non c'è notte né ombre.",en:"A transparent body made of luminous matter, where there is no night or shadows."},correct:1,note:{it:"Corpo astrale: sul piano astrale non c'è mai la notte, i corpi sono trasparenti e tutta la materia è luminosa.",en:"Astral body: on the astral plane there is never night, bodies are transparent and all matter is luminous."}},
        {sit:{it:"Un veicolo che si stacca nel sonno e vaga senza controllo, trascinato da desideri e paure.",en:"A vehicle that detaches in sleep and wanders without control, driven by desires and fears."},correct:1,note:{it:"Corpo astrale: tutti viaggiano così durante il sonno, ma mancando consapevolezza i viaggi sono confusi.",en:"Astral body: everyone travels this way in sleep, but lacking awareness the journeys are confused."}},
        {sit:{it:"Un doppio energetico che si estende pochi centimetri oltre la pelle e assicura la vitalità.",en:"An energetic double extending a few centimetres beyond the skin, ensuring vitality."},correct:0,note:{it:"Corpo eterico (fisico): il 'doppio eterico' è la controparte energetica del corpo denso.",en:"Etheric body (physical): the 'etheric double' is the energetic counterpart of the dense body."}},
        {sit:{it:"La sede dei pensieri e delle immagini mentali; si dissolve dopo la seconda morte.",en:"The seat of thoughts and mental images; it dissolves after the second death."},correct:2,note:{it:"Corpo mentale: dopo la 'seconda morte' (astrale), il corpo mentale si disgrega a sua volta.",en:"Mental body: after the 'second death' (astral), the mental body in turn disintegrates."}},
        {sit:{it:"Un campo di forza dove si percepiscono gli oggetti da tutti i lati contemporaneamente.",en:"A field of force where objects are perceived from all sides simultaneously."},correct:1,note:{it:"Corpo astrale: la vista astrale è quadridimensionale — ogni particella interna è visibile come l'esterno.",en:"Astral body: astral sight is four-dimensional — every inner particle is as visible as the outside."}},
        {sit:{it:"Il veicolo denso di carne e ossa che si abbandona alla prima morte.",en:"The dense vehicle of flesh and bone that is left at the first death."},correct:0,note:{it:"Corpo fisico: è il piano più grossolano, abbandonato al momento della morte.",en:"Physical body: the coarsest plane, left behind at the moment of death."}},
        {sit:{it:"Il corpo dove risiedono le forme-pensiero e i condizionamenti intellettuali.",en:"The body where thought-forms and intellectual conditioning reside."},correct:2,note:{it:"Corpo mentale: sede delle convinzioni e dei ragionamenti — l'alto e il basso della mente.",en:"Mental body: seat of beliefs and reasoning — the high and low of the mind."}},
        {sit:{it:"Un incessante gioco di colori che riflette ogni emozione provata in tempo reale.",en:"An incessant play of colours reflecting every emotion felt in real time."},correct:1,note:{it:"Corpo astrale/mercuriale: i colori dell'aura astrale cambiano istantaneamente con le emozioni.",en:"Astral/mercurial body: the colours of the astral aura change instantly with emotions."}},
        {sit:{it:"Il corpo che, una volta trasmutato, diventa il corpo Atmico: la resurrezione nella carne.",en:"The body that, once transmuted, becomes the Atmic body: the resurrection in the flesh."},correct:0,note:{it:"Corpo fisico trasmutato: la 'risurrezione nella carne' avviene quando il fisico sale di livello.",en:"Transmuted physical body: the 'resurrection in the flesh' occurs when the physical rises in level."}}
      ]
    },
    abitante: { type:"scenario", roman:"II", glyph:"◇", optionKeys:[0,1,2],
      items: [
        {sit:{it:"Massa informe che reagisce in una frazione di secondo a ogni pensiero umano, plasmandosi in un essere temporaneo.",en:"A formless mass reacting in a fraction of a second to every human thought, shaping itself into a temporary being."},correct:2,note:{it:"Essenza elementale: diffusa in tutto l'astrale, viene plasmata dai pensieri e dalle emozioni umane.",en:"Elemental essence: spread throughout the astral, it is shaped by human thoughts and emotions."}},
        {sit:{it:"Cadavere astrale che conserva l'apparenza e la memoria del defunto, ingannando i medium.",en:"An astral corpse keeping the appearance and memory of the deceased, deceiving mediums."},correct:1,note:{it:"Ombre: il cadavere astrale lasciato quando l'uomo muore sul piano astrale.",en:"Shades: the astral corpse left behind when one dies on the astral plane."}},
        {sit:{it:"Gnomi, ondine, silfidi, salamandre: amano il gioco e lo scherzo, rifuggono l'uomo.",en:"Gnomes, undines, sylphs, salamanders: they love play and pranks, they shun humankind."},correct:2,note:{it:"Spiriti di natura: gnomi (terra), ondine (acqua), silfidi (aria), salamandre (etere).",en:"Nature spirits: gnomes (earth), undines (water), sylphs (air), salamanders (ether)."}},
        {sit:{it:"Esseri potentissimi che si nutrono dei pensieri separativi e delle emozioni negative dell'umanità.",en:"Very powerful beings that feed on humanity's separative thoughts and negative emotions."},correct:2,note:{it:"Demoni: entità astrali che agiscono per egoismo. I più noti sono i 'rettiliani'.",en:"Demons: astral entities acting out of selfishness. The best known are the 'reptilians'."}},
        {sit:{it:"Persone comuni che ogni notte, durante il sonno, vagano in astrale senza consapevolezza.",en:"Ordinary people who every night, during sleep, wander the astral without awareness."},correct:0,note:{it:"Tutti viaggiano così durante il sonno: mancando controllo, tali viaggi sono confusi e poco utili.",en:"Everyone travels this way in sleep: lacking control, such journeys are confused and of little use."}},
        {sit:{it:"Individui trapassati in circostanze traumatiche che cercano di restare vicino al piano fisico.",en:"Individuals who died in traumatic circumstances, trying to stay near the physical plane."},correct:1,note:{it:"Suicidi e vittime di morte improvvisa: non accettano la nuova condizione.",en:"Suicides and victims of sudden death: they don't accept their new condition."}},
        {sit:{it:"Detti angeli o 'figli di Dio': appartengono a un'evoluzione superiore all'umanità.",en:"Called angels or 'sons of God': they belong to an evolution above humanity."},correct:2,note:{it:"Deva: tutto ciò che è cattivo è stato eliminato dal loro essere.",en:"Devas: all that is evil has been removed from their being."}},
        {sit:{it:"Maghi che usano il corpo astrale come primo veicolo di esplorazione cosciente.",en:"Magi who use the astral body as their first vehicle for conscious exploration."},correct:0,note:{it:"Maghi e loro allievi: ancora vivi nel corpo fisico, viaggiano coscientemente in astrale.",en:"Magi and their pupils: still alive in the physical body, they travel consciously in the astral."}},
        {sit:{it:"Entità che prolungano la propria esistenza assorbendo vitalità dagli esseri umani.",en:"Entities prolonging their existence by absorbing vitality from human beings."},correct:1,note:{it:"Vampiri: non più vivi nel corpo fisico, restano vicino alla materia terrestre.",en:"Vampires: no longer alive in the physical body, they stay near earthly matter."}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"Quanti sono i piani dell'universo manifesto?",en:"How many planes does the manifest universe have?"},options:{it:["Sette","Tre","Dodici","Quattro"],en:["Seven","Three","Twelve","Four"]},correct:0,note:{it:"Fisico, Astrale, Mentale, Buddhico, Atmico, Anupadaka, Adi.",en:"Physical, Astral, Mental, Buddhic, Atmic, Anupadaka, Adi."}},
        {q:{it:"In alchimia il corpo astrale è detto…",en:"In alchemy the astral body is called…"},options:{it:["Fluidico o Mercuriale","Atmico","Causale","Buddhico"],en:["Fluidic or Mercurial","Atmic","Causal","Buddhic"]},correct:0,note:{it:"Il corpo emotivo è detto Fluidico o Mercuriale per il gioco incessante dei colori.",en:"The emotional body is called Fluidic or Mercurial for the incessant play of colours."}},
        {q:{it:"Quante 'morti' descrivono gli scritti esoterici?",en:"How many 'deaths' do esoteric writings describe?"},options:{it:["Tre: una per ogni corpo","Una soltanto","Sette","Nessuna"],en:["Three: one for each body","Only one","Seven","None"]},correct:0,note:{it:"Una morte per ciascun corpo: fisico, emotivo e mentale.",en:"One death for each body: physical, emotional and mental."}},
        {q:{it:"Quando l'uomo sogna, si trova nel…",en:"When a person dreams, they are in the…"},options:{it:["Corpo astrale","Corpo causale","Corpo atmico","Nessun corpo"],en:["Astral body","Causal body","Atmic body","No body"]},correct:0,note:{it:"Nel sogno siamo nel corpo astrale: la lucidità dei sogni rivela quella che avremo da disincarnati.",en:"In dreams we are in the astral body: the lucidity of dreams reveals what we'll have once disincarnate."}},
        {q:{it:"L'esperienza dell''inferno' nel piano astrale serve a…",en:"The 'hell' experience on the astral plane serves to…"},options:{it:["Bruciare le emozioni inferiori e gli attaccamenti","Punire per l'eternità","Cancellare la memoria","Premiare i giusti"],en:["Burn lower emotions and attachments","Punish for eternity","Erase memory","Reward the righteous"]},correct:0,note:{it:"Non c'è punizione: è un processo di disgregazione dei condizionamenti emotivi.",en:"There is no punishment: it is a process of disintegrating emotional conditioning."}},
        {q:{it:"Cosa accade nel primo periodo dopo la morte?",en:"What happens in the first period after death?"},options:{it:["Si rivede tutta la vita 'all'indietro'","Si dimentica tutto","Si rinasce subito","Si incontra un giudice"],en:["One reviews all of life 'backwards'","One forgets everything","One is reborn at once","One meets a judge"]},correct:0,note:{it:"Rivedendo la vita al contrario si percepiscono le emozioni provocate negli altri.",en:"Reviewing life backwards one feels the emotions caused in others."}},
        {q:{it:"Gli spiriti della terra, acqua, aria ed etere sono…",en:"The spirits of earth, water, air and ether are…"},options:{it:["Gnomi, ondine, silfidi, salamandre","Deva, ombre, gusci, vampiri","Silfidi, gnomi, salamandre, ondine","Folletti, fate, elfi, troll"],en:["Gnomes, undines, sylphs, salamanders","Devas, shades, shells, vampires","Sylphs, gnomes, salamanders, undines","Goblins, fairies, elves, trolls"]},correct:0,note:{it:"Gnomi = terra, ondine = acqua, silfidi = aria, salamandre = etere.",en:"Gnomes = earth, undines = water, sylphs = air, salamanders = ether."}},
        {q:{it:"Una forma-pensiero di gelosia, se alimentata, può…",en:"A thought-form of jealousy, if fed, can…"},options:{it:["'Attaccarsi' a un uomo per tutta la vita","Dissolversi subito","Trasformarsi in un Deva","Diventare un corpo fisico"],en:["'Attach' itself to a person for life","Dissolve at once","Turn into a Deva","Become a physical body"]},correct:0,note:{it:"L'elementale cerca di sopravvivere e spinge a ripetere il pensiero che lo alimenta.",en:"The elemental seeks to survive and pushes one to repeat the thought that feeds it."}},
        {q:{it:"Il 'corpo di gloria' corrisponde a…",en:"The 'body of glory' corresponds to…"},options:{it:["I tre corpi superiori: causale, buddhico, atmico","Solo il corpo astrale","Solo il corpo mentale","Il corpo eterico"],en:["The three higher bodies: causal, buddhic, atmic","Only the astral body","Only the mental body","The etheric body"]},correct:0,note:{it:"Il percorso alchemico porta alla costruzione dei tre corpi superiori al contempo.",en:"The alchemical path leads to building the three higher bodies at once."}},
        {q:{it:"Il 'mago nero' cerca l'immortalità…",en:"The 'black magus' seeks immortality…"},options:{it:["Fissando e abitando il corpo astrale","Aprendo il Cuore","Dissolvendosi nell'Uno","Rinunciando a ogni potere"],en:["By fixing and inhabiting the astral body","By opening the Heart","By dissolving into the One","By renouncing all power"]},correct:0,note:{it:"Chi si separa dall'anima può solo sopravvivere in astrale: le Logge Nere cercano allievi disciplinati.",en:"One severed from the soul can only survive in the astral: Black Lodges seek disciplined pupils."}},
        {q:{it:"Hitler, secondo gli esoteristi, era…",en:"Hitler, according to esotericists, was…"},options:{it:["Un medium delle forze oscure, addestrato dalla Società Thule","Un mago bianco","Un illuminato","Un semplice politico"],en:["A medium of dark forces, trained by the Thule Society","A white magus","An enlightened one","A simple politician"]},correct:0,note:{it:"Dietrich Eckardt rese Hitler consapevole del suo compito e gli insegnò a comunicare con i 'Superiori Sconosciuti'.",en:"Dietrich Eckardt made Hitler aware of his task and taught him to communicate with the 'Unknown Superiors'."}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✶",
      items: [
        {a:{it:"Gnomi",en:"Gnomes"},b:{it:"Terra",en:"Earth"}},
        {a:{it:"Ondine",en:"Undines"},b:{it:"Acqua",en:"Water"}},
        {a:{it:"Silfidi",en:"Sylphs"},b:{it:"Aria",en:"Air"}},
        {a:{it:"Salamandre",en:"Salamanders"},b:{it:"Etere",en:"Ether"}},
        {a:{it:"Corpo astrale",en:"Astral body"},b:{it:"Mercuriale",en:"Mercurial"}},
        {a:{it:"Corpo di gloria",en:"Body of glory"},b:{it:"Causale + Buddhico\n+ Atmico",en:"Causal + Buddhic\n+ Atmic"}}
      ]
    }
  }
};
})();
