/* IL CORPO E L'ANIMA — data.js */
(function(){
"use strict";
window.GAME_DATA = {
  id: "corpo",
  modes: ["persona","immag","quiz","memoria"],
  rings: [
    {key:"piani",color:"#1a1326",ring:"#3a2f52",label:{it:"I Piani",en:"The Planes"}},
    {key:"corpi",color:"#10212a",ring:"#2f5d6b",label:{it:"I Corpi",en:"The Bodies"}},
    {key:"anima",color:"#2a1410",ring:"#7c3a2a",label:{it:"L'Anima",en:"The Soul"}},
    {key:"cuore",color:"#3a2c10",ring:"#c9973a",label:{it:"Il Cuore",en:"The Heart"}}
  ],
  modeDefs: {
    persona: { type:"classify", roman:"I", glyph:"◐", optionKeys:[0,1], count:10,
      items: [
        {item:{it:"La mente razionale",en:"The rational mind"},belongs:0,note:{it:"La personalità conosce per mezzo della mente, delle sensazioni e delle emozioni.",en:"The personality knows through the mind, the senses and the emotions."}},
        {item:{it:"Il Cuore",en:"The Heart"},belongs:1,note:{it:"Il Cuore è l'organo di conoscenza dell'anima.",en:"The Heart is the soul's organ of knowledge."}},
        {item:{it:"Le sensazioni fisiche",en:"Physical sensations"},belongs:0,note:{it:"Appartengono all'apparato psicofisico, la macchina biologica.",en:"They belong to the psychophysical apparatus, the biological machine."}},
        {item:{it:"La compassione e il senso del Bello",en:"Compassion and the sense of Beauty"},belongs:1,note:{it:"Sono emozioni superiori: il corpo dell'anima è costituito di esse.",en:"They are higher emotions: the body of the soul is made of them."}},
        {item:{it:"Il senso del possesso",en:"The sense of possession"},belongs:0,note:{it:"È uno schema mentale radicato nella personalità.",en:"It is a mental pattern rooted in the personality."}},
        {item:{it:"La «tuta spaziale»",en:"The 'spacesuit'"},belongs:0,note:{it:"La personalità è la tuta: ci consente di muoverci, ma in sé non conosce nulla.",en:"The personality is the suit: it lets us move, but in itself knows nothing."}},
        {item:{it:"L'«astronauta» dentro la tuta",en:"The 'astronaut' inside the suit"},belongs:1,note:{it:"L'anima è l'astronauta: solo a chi sta dentro è dato di conoscere.",en:"The soul is the astronaut: only the one inside can truly know."}},
        {item:{it:"Ciò che è immortale in noi",en:"What is immortal in us"},belongs:1,note:{it:"L'anima vive; la personalità soltanto sopravvive ed è mortale.",en:"The soul lives; the personality merely survives and is mortal."}},
        {item:{it:"Le emozioni negative",en:"Negative emotions"},belongs:0,note:{it:"La macchina biologica è prevalentemente costituita di emozioni negative.",en:"The biological machine is mostly made of negative emotions."}},
        {item:{it:"Essere trascinati dalle emozioni senza rendersene conto",en:"Being dragged by emotions without realising it"},belongs:0,note:{it:"Non si provano emozioni, si è da esse trascinati. Non si gestisce il corpo, si subisce.",en:"One doesn't feel emotions but is dragged by them. One doesn't manage the body, one undergoes it."}},
        {item:{it:"Lo sfondo immutabile pieno di Pace su cui accadono increspature superficiali",en:"The immutable background full of Peace on which surface ripples occur"},belongs:1,note:{it:"Diveniamo lo sfondo immutabile sul quale accadono increspature prive di reale importanza.",en:"We become the immutable background on which surface ripples devoid of real importance occur."}},
        {item:{it:"La competitività",en:"Competitiveness"},belongs:0,note:{it:"«La personalità è competitiva, l'anima è collaborativa.»",en:"'The personality is competitive, the soul is collaborative.'"}},
        {item:{it:"La collaborazione e la condivisione",en:"Collaboration and sharing"},belongs:1,note:{it:"«Una accumula, l'altra condivide.»",en:"'One accumulates, the other shares.'"}},
        {item:{it:"L'egoismo",en:"Selfishness"},belongs:0,note:{it:"È la caratteristica principe della personalità: chi deve sopravvivere pensa solo a sé.",en:"It is the personality's chief trait: whoever must survive thinks only of himself."}},
        {item:{it:"Aggressività e paura, cioè attacco e difesa",en:"Aggressiveness and fear, that is attack and defence"},belongs:0,note:{it:"Sono i due pilastri della sopravvivenza su cui è strutturata la macchina biologica.",en:"They are the two pillars of survival on which the biological machine is built."}},
        {item:{it:"Il sentirsi 'uno con l'intero Universo'",en:"Feeling 'one with the whole Universe'"},belongs:1,note:{it:"Da qui nascono le emozioni superiori dell'anima: gioia, amore, compassione.",en:"The soul's higher emotions arise from this: joy, love, compassion."}},
        {item:{it:"Il codice genetico",en:"The genetic code"},belongs:0,note:{it:"Nel DNA è scritto come deve essere costruito l'involucro di cui siamo ospiti, ma non dice chi siamo noi.",en:"DNA says how the casing we inhabit must be built, but it doesn't say who we are."}}
      ]
    },
    immag: { type:"classify", roman:"II", glyph:"◇", optionKeys:[0,1],
      items: [
        {item:{it:"Alla vigilia di un esame la mente costruisce scenari catastrofici non richiesti",en:"Before an exam the mind builds catastrophic scenarios unbidden"},belongs:0,note:{it:"Immaginazione negativa: ogni genere di immaginazione non voluta né controllata.",en:"Negative imagination: every kind of imagination neither willed nor controlled."}},
        {item:{it:"Un artista immagina coscientemente i mondi che poi rappresenterà",en:"An artist consciously imagines the worlds he will represent"},belongs:1,note:{it:"Visualizzazione: la capacità di immaginare in maniera voluta e cosciente.",en:"Visualisation: the ability to imagine in a willed and conscious manner."}},
        {item:{it:"Dopo un litigio, ripensare per ore a cosa avremmo detto",en:"After a quarrel, spending hours thinking about what we'd have said"},belongs:0,note:{it:"Fa riaffiorare un'emozione negativa a distanza di ore dall'evento.",en:"It makes a negative emotion resurface hours after the event."}},
        {item:{it:"Ricostruire il filo dei discorsi per trarne insegnamento, senza emozioni basse",en:"Reconstructing discussions to learn, without base emotions"},belongs:1,note:{it:"Ricostruire la scena è utile, ma senza replicare le stesse basse emozioni.",en:"Reconstructing the scene is useful, but without replicating the same base emotions."}},
        {item:{it:"Sognare a occhi aperti di vincere alla lotteria",en:"Daydreaming about winning the lottery"},belongs:0,note:{it:"I sogni a occhi aperti richiameranno una dose corrispondente di emozioni negative.",en:"Daydreams will attract a corresponding dose of negative emotions."}},
        {item:{it:"Immaginare un incontro importante in maniera controllata, senza ansia",en:"Imagining an important meeting in a controlled way, without anxiety"},belongs:1,note:{it:"Molto utile se fatto in maniera controllata.",en:"Very useful if done in a controlled manner."}},
        {item:{it:"Il partner è in vacanza e la mente immagina tradimenti e disgrazie",en:"Partner is on holiday and the mind imagines betrayals and disasters"},belongs:0,note:{it:"L'ipocondria è immaginazione negativa. Ogni pensiero ossessivo origina da essa.",en:"Hypochondria is negative imagination. Every obsessive thought originates from it."}},
        {item:{it:"Rappresentarsi mentalmente con precisione un obiettivo, restando focalizzati su di esso",en:"Picturing a goal precisely in the mind, staying focused on it"},belongs:1,note:{it:"Con la visualizzazione ci si rappresenta con precisione i propri obiettivi, restando focalizzati sopra un dato fine.",en:"Through visualisation one pictures one's goals precisely, staying focused on a given aim."}},
        {item:{it:"Prima di incontrare un parente antipatico, la mente costruisce dialoghi in cui si arriva agli insulti",en:"Before meeting a disliked relative, the mind builds dialogues that end in insults"},belongs:0,note:{it:"Queste immaginazioni fanno fremere la macchina come se la scena fosse reale.",en:"Such imaginings make the machine quiver as if the scene were real."}},
        {item:{it:"Ripensare per mesi al partner che ci ha lasciato, riprovando la stessa nostalgia",en:"Thinking for months about the partner who left us, feeling the same nostalgia again"},belongs:0,note:{it:"L'immaginazione negativa fa riaffiorare un'emozione anche a mesi di distanza dall'evento.",en:"Negative imagination revives an emotion even months after the event."}},
        {item:{it:"Costruire una visione meditata, secondo un metodo preciso",en:"Building a meditated vision, following a precise method"},belongs:1,note:{it:"Il vero mistico è attivo: costruisce le visioni. Il falso mistico le subisce.",en:"The true mystic is active: he builds visions. The false mystic undergoes them."}},
        {item:{it:"Subire visioni imprevedibili, senza alcun controllo su ciò che appare",en:"Undergoing unpredictable visions, with no control over what appears"},belongs:0,note:{it:"È la fantasia passiva: il falso mistico «fantastica».",en:"It is passive fantasy: the false mystic 'fantasises'."}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"L'organo di conoscenza dell'anima è…",en:"The soul's organ of knowledge is…"},options:{it:["Il Cuore","La mente","Gli occhi","Il cervello"],en:["The Heart","The mind","The eyes","The brain"]},correct:0,note:{it:"Col Cuore la coscienza si apre alla realtà oltre le apparenze.",en:"With the Heart consciousness opens to reality beyond appearances."}},
        {q:{it:"Le tre fasi dell'Opera, in ordine, sono…",en:"The three phases of the Work are…"},options:{it:["Nigredo, Albedo, Rubedo","Albedo, Rubedo, Nigredo","Rubedo, Nigredo, Albedo","Solve, Coagula, Ignis"],en:["Nigredo, Albedo, Rubedo","Albedo, Rubedo, Nigredo","Rubedo, Nigredo, Albedo","Solve, Coagula, Ignis"]},correct:0,note:{it:"Opera al Nero, al Bianco, al Rosso — pur sovrapponendosi nel cammino.",en:"Black, White and Red Work — though they overlap along the path."}},
        {q:{it:"La sequenza dei metalli è…",en:"The sequence of metals is…"},options:{it:["Piombo → Argento → Oro","Oro → Argento → Piombo","Ferro → Rame → Oro","Argento → Piombo → Oro"],en:["Lead → Silver → Gold","Gold → Silver → Lead","Iron → Copper → Gold","Silver → Lead → Gold"]},correct:0,note:{it:"Il Piombo diventa Argento con l'Albedo, e Argento diventa Oro con il Rubedo.",en:"Lead becomes Silver with the Albedo, and Silver becomes Gold with the Rubedo."}},
        {q:{it:"Nella Nigredo si costruisce…",en:"In the Nigredo one builds…"},options:{it:["Il 'Testimone'","Il corpo di gloria","L'Oro","Il senso del possesso"],en:["The 'Witness'","The body of glory","The Gold","The sense of possession"]},correct:0,note:{it:"La disidentificazione progressiva dalle reazioni emotive crea il Testimone.",en:"Gradual dis-identification from emotional reactions creates the Witness."}},
        {q:{it:"Cosa si reincarna?",en:"What reincarnates?"},options:{it:["L'anima, non la personalità","Il corpo fisico","La mente razionale","Le emozioni negative"],en:["The soul, not the personality","The physical body","The rational mind","Negative emotions"]},correct:0,note:{it:"La personalità è mortale; l'anima porta con sé l'essenza delle esperienze.",en:"The personality is mortal; the soul carries the essence of experiences."}},
        {q:{it:"Secondo Brizzi, ogni malattia ha…",en:"According to Brizzi, every illness has…"},options:{it:["Un significato esoterico, cioè simbolico, da comprendere","Solo cause meccaniche","Nessun significato: è un caso","Il valore di una punizione divina"],en:["An esoteric, that is symbolic, meaning to be understood","Only mechanical causes","No meaning: it's chance","The value of a divine punishment"]},correct:0,note:{it:"«Ogni malattia, incidente o incontro con una persona ha un significato esoterico, cioè simbolico.» La malattia è l'esteriorizzazione di un problema psicologico interno.",en:"'Every illness, accident or encounter with a person has an esoteric, that is symbolic, meaning.' Illness is the outward expression of an inner psychological problem."}},
        {q:{it:"L'Alchimia Superior (ars brevis) apre il Cuore tramite…",en:"Alchimia Superior (ars brevis) opens the Heart through…"},options:{it:["L'arte ('estasi estetica') e il servizio","La sofferenza","Rituali complicati","Lo studio intellettuale"],en:["Art ('aesthetic ecstasy') and service","Suffering","Complicated rituals","Intellectual study"]},correct:0,note:{it:"Apre il Cuore senza passare dalla sofferenza.",en:"Opens the Heart without passing through suffering."}},
        {q:{it:"Dopo la morte, la coscienza attraversa…",en:"After death, consciousness goes through…"},options:{it:["Una rivisitazione della vita all'indietro","Annullamento totale","Reincarnazione immediata","Sonno eterno"],en:["A review of life backwards","Total annihilation","Immediate reincarnation","Eternal sleep"]},correct:0,note:{it:"Si assiste come spettatori alla proiezione della propria esistenza, trasmessa all'indietro fino alla nascita: rivedendola al contrario si perde la connessione causa/effetto, e il comune giudizio sugli eventi viene sospeso.",en:"We watch, as spectators, the projection of our whole existence, played backwards to birth: seeing it in reverse we lose the cause/effect connection, and ordinary judgment of events is suspended."}},
        {q:{it:"Controllo e identificazione sono…",en:"Control and identification are…"},options:{it:["Inversamente proporzionali","Direttamente proporzionali","Uguali","Indipendenti"],en:["Inversely proportional","Directly proportional","Equal","Independent"]},correct:0,note:{it:"Meno siamo identificati con qualcosa, più ne abbiamo il controllo.",en:"The less identified we are, the more control we have."}},
        {q:{it:"Il 'crogiuolo' dove bruciare le emozioni negative è…",en:"The 'crucible' where negative emotions are burned is…"},options:{it:["Il Cuore in embrione","Il cervello razionale","Lo stomaco","Un rituale esterno"],en:["The embryonic Heart","The rational brain","The stomach","An external ritual"]},correct:0,note:{it:"Il crogiuolo è il nostro Cuore: una pietra magica capace di trasmutare.",en:"The crucible is our Heart: a magic stone able to transmute."}},
        {q:{it:"I due pilastri della sopravvivenza su cui è strutturata la macchina biologica sono…",en:"The two pillars of survival on which the biological machine is built are…"},options:{it:["Attacco e difesa: aggressività e paura","Amore e compassione","Pensiero e parola","Gioia e gratitudine"],en:["Attack and defence: aggressiveness and fear","Love and compassion","Thought and word","Joy and gratitude"]},correct:0,note:{it:"Il suo comportamento è quello di un animale che fugge o aggredisce.",en:"Its behaviour is that of an animal that flees or attacks."}},
        {q:{it:"La caratteristica principe della personalità è…",en:"The chief trait of the personality is…"},options:{it:["L'egoismo","La generosità","La saggezza","L'intuizione"],en:["Selfishness","Generosity","Wisdom","Intuition"]},correct:0,note:{it:"Chi deve sopravvivere pensa solo a sé o, al limite, alla sua famiglia e al suo 'branco'.",en:"Whoever must survive thinks only of himself or, at most, of his family and his 'pack'."}},
        {q:{it:"«La personalità è competitiva, l'anima è…»",en:"'The personality is competitive, the soul is…'"},options:{it:["Collaborativa","Indifferente","Passiva","Solitaria"],en:["Collaborative","Indifferent","Passive","Solitary"]},correct:0,note:{it:"«Una accumula, l'altra condivide.»",en:"'One accumulates, the other shares.'"}},
        {q:{it:"Con che cosa l'anima si costruisce la macchina biologica?",en:"What does the soul build the biological machine from?"},options:{it:["Con il cibo fisico, emotivo e mentale del luogo dove nasce","Solo con il DNA dei genitori","Con i ricordi delle vite precedenti","Con la propria volontà, senza influenze esterne"],en:["From the physical, emotional and mental food of the place where it is born","From the parents' DNA alone","From memories of previous lives","From its own will, without outside influence"]},correct:0,note:{it:"Niente di ciò che crediamo di essere è veramente nostro: era già pronto quando siamo arrivati.",en:"Nothing we believe we are is truly ours: it was already there when we arrived."}},
        {q:{it:"Secondo Brizzi, il codice genetico…",en:"According to Brizzi, the genetic code…"},options:{it:["Descrive l'involucro di cui siamo ospiti, ma non dice chi siamo","Contiene l'anima","Decide il nostro destino spirituale","Coincide con la coscienza"],en:["Describes the casing we inhabit, but doesn't say who we are","Contains the soul","Decides our spiritual destiny","Coincides with consciousness"]},correct:0,note:{it:"«Anche il codice genetico non siamo noi.»",en:"'Even the genetic code is not us.'"}},
        {q:{it:"Divenire immortali significa…",en:"Becoming immortal means…"},options:{it:["Identificarsi completamente con l'anima","Fermare la decadenza della personalità","Rendere immortale il corpo fisico","Non pensare alla morte"],en:["Identifying completely with the soul","Halting the decay of the personality","Making the physical body immortal","Not thinking about death"]},correct:0,note:{it:"«Non possiamo rendere immortale ciò che è mortale, ma possiamo identificarci con qualcosa che è già immortale.»",en:"'We cannot make immortal what is mortal, but we can identify with something that is already immortal.'"}},
        {q:{it:"Secondo Powell, il doppio eterico è composto…",en:"According to Powell, the etheric double is made of…"},options:{it:["Dei quattro stati più sottili di materia fisica","Di materia astrale","Di solidi, liquidi e gas","Di pura materia mentale"],en:["The four subtlest states of physical matter","Astral matter","Solids, liquids and gases","Pure mental matter"]},correct:0,note:{it:"Solidi, liquidi e gas formano invece il corpo denso.",en:"Solids, liquids and gases instead form the dense body."}},
        {q:{it:"Quale funzione ha il doppio eterico, secondo Powell?",en:"What is the function of the etheric double, according to Powell?"},options:{it:["Riceve e distribuisce la forza vitale emanata dal sole","È la sede dei pensieri astratti","È un veicolo di coscienza separato e autonomo","Conserva le emozioni superiori"],en:["It receives and distributes the vital force emanating from the sun","It is the seat of abstract thought","It is a separate, autonomous vehicle of consciousness","It stores the higher emotions"]},correct:0,note:{it:"Per questo è intimamente connesso con la salute fisica.",en:"That is why it is closely connected with physical health."}},
        {q:{it:"Con la morte, il livello di coscienza…",en:"At death, the level of consciousness…"},options:{it:["Non muta: «la morte non è una cura per l'ignoranza»","Si illumina all'improvviso","Si annulla","Raddoppia"],en:["Doesn't change: 'death is no cure for ignorance'","Suddenly becomes enlightened","Is annulled","Doubles"]},correct:0,note:{it:"«Un truffatore non diventa meno truffatore e un santo non diventa meno santo quando entrambi si cambiano d'abito.» (I mondi spirituali)",en:"'A swindler does not become less of a swindler and a saint does not become less of a saint when both change clothes.' (The Spiritual Worlds)"}},
        {q:{it:"Nel primo periodo dopo la morte, spesso…",en:"In the first period after death, often…"},options:{it:["Non ci accorgiamo di essere morti","Vediamo subito Dio","Dimentichiamo chi siamo","Ci reincarniamo all'istante"],en:["We don't realise we are dead","We immediately see God","We forget who we are","We reincarnate at once"]},correct:0,note:{it:"I desideri e le abitudini non mutano e continuiamo a pensare secondo le limitazioni terrene.",en:"Desires and habits don't change and we keep thinking within earthly limits."}},
        {q:{it:"Secondo Heindel, quando l'uomo rivive la sua vita nel Mondo del Desiderio…",en:"According to Heindel, when a man relives his life in the Desire World…"},options:{it:["Prova le stesse pene che ha causato agli altri","Non prova alcun sentimento","Rivede solo i momenti felici","Dimentica tutto"],en:["He feels the same pains he caused others","He feels nothing at all","He sees only the happy moments","He forgets everything"]},correct:0,note:{it:"Nel primo panorama, subito dopo la morte, osserva invece i quadri da spettatore, senza provare sentimenti.",en:"In the first panorama, right after death, he instead watches the pictures as a spectator, without feelings."}},
        {q:{it:"Nell'analogia di Brizzi, l'anima sta alla personalità come…",en:"In Brizzi's analogy, the soul is to the personality as…"},options:{it:["La personalità sta all'automobile","Il corpo sta all'anima","La mente sta al Cuore","Il figlio sta al padre"],en:["The personality is to the car","The body is to the soul","The mind is to the Heart","The son is to the father"]},correct:0,note:{it:"L'automobile rappresenta per analogia il nostro apparato psicofisico.",en:"By analogy the car stands for our psychophysical apparatus."}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✶",
      items: [
        {a:{it:"Corpo fisico",en:"Physical body"},b:{it:"Il piano denso\nvisibile",en:"The dense\nvisible plane"}},
        {a:{it:"Corpo eterico",en:"Etheric body"},b:{it:"Il 'doppio'\nenergetico",en:"The energetic\n'double'"}},
        {a:{it:"Corpo astrale",en:"Astral body"},b:{it:"La sede\ndelle emozioni",en:"The seat\nof emotions"}},
        {a:{it:"Corpo mentale",en:"Mental body"},b:{it:"La sede\ndei pensieri",en:"The seat\nof thoughts"}},
        {a:{it:"Personalità",en:"Personality"},b:{it:"Tuta spaziale",en:"Spacesuit"}},
        {a:{it:"Anima",en:"Soul"},b:{it:"Astronauta",en:"Astronaut"}},
        {a:{it:"Crogiuolo",en:"Crucible"},b:{it:"Il Cuore\nin embrione",en:"The embryonic\nHeart"}},
        {a:{it:"Alchimia\nSuperior",en:"Alchimia\nSuperior"},b:{it:"Estasi\nestetica",en:"Aesthetic\necstasy"}},
        {a:{it:"Nigredo",en:"Nigredo"},b:{it:"Il\n«testimone»",en:"The\n'witness'"}}
      ]
    }
  }
};
})();
