/* IL RISVEGLIO — data.js (pooled from 6 books) */
(function(){
"use strict";
window.GAME_DATA = {
  id: "risveglio",
  modes: ["sonno","attenzione","quiz","memoria"],
  rings: [
    {key:"tempo",color:"#1a1326",ring:"#3a2f52",label:{it:"Il Tempo",en:"Time"}},
    {key:"manipolazione",color:"#10212a",ring:"#2f5d6b",label:{it:"L'Incantesimo",en:"The Enchantment"}},
    {key:"presenza",color:"#2a1410",ring:"#7c3a2a",label:{it:"La Presenza",en:"Presence"}},
    {key:"risveglio",color:"#3a2c10",ring:"#c9973a",label:{it:"Il Risveglio",en:"Awakening"}}
  ],
  modeDefs: {
    sonno: { type:"classify", roman:"I", glyph:"◐", count:10,
      optionKeys:[0,1],
      items: [
        {item:{it:"Reagire meccanicamente a uno stimolo esterno",en:"Reacting mechanically to an external stimulus"},belongs:0,note:{it:"La personalità è una macchina biologica che re-agisce.",en:"The personality is a biological machine that re-acts."}},
        {item:{it:"Osservarsi nel qui-e-ora mentre si agisce: l'«attenzione divisa»",en:"Observing oneself in the here-and-now while acting: 'divided attention'"},belongs:1,note:{it:"Ricordarsi di sé: parte dell'attenzione su di sé, parte sull'azione.",en:"Self-remembering: part of the attention on oneself, part on the action."}},
        {item:{it:"Il «sonno verticale» scambiato per vera veglia",en:"'Vertical sleep' mistaken for true wakefulness"},belongs:0,note:{it:"Lo stato ordinario dell'uomo: sembra veglia ma è ancora sonno.",en:"Man's ordinary state: it looks like waking but is still sleep."}},
        {item:{it:"La «continuità di coscienza», vigili anche nel sonno",en:"'Continuity of consciousness', awake even in sleep"},belongs:1,note:{it:"Nel risveglio completo il Sé resta cosciente 24 ore su 24.",en:"In full awakening the Self stays conscious 24/7."}},
        {item:{it:"Credere di possedere libero arbitrio senza averlo verificato",en:"Believing one has free will without having verified it"},belongs:0,note:{it:"Se anche in una sola occasione le emozioni ci hanno tradito, non possediamo libero arbitrio.",en:"If even once our emotions betrayed us, we do not possess free will."}},
        {item:{it:"Creare un «centro di gravità permanente» dedicato al Lavoro",en:"Creating a 'permanent centre of gravity' dedicated to the Work"},belongs:1,note:{it:"Il passaggio da uomo 1-2-3 a uomo n. 4: la ferma decisione di lavorare su di sé.",en:"The passage from man 1-2-3 to man no. 4: the firm decision to work on oneself."}},
        {item:{it:"Vivere schiacciati tra il rimpianto del passato e l'ansia del futuro",en:"Living crushed between regret for the past and anxiety about the future"},belongs:0,note:{it:"Ogni sofferenza nasce dal tempo. Obiettivo: la sconfitta del tempo.",en:"All suffering is born of time. The aim: the defeat of time."}},
        {item:{it:"Restare nel Qui-e-Ora: «Io sono il figlio del Momento»",en:"Staying in the Here-and-Now: 'I am the son of the Moment'"},belongs:1,note:{it:"Un guerriero che vive nel Momento è un guerriero senza paure.",en:"A warrior who lives in the Moment is a warrior without fears."}},
        {item:{it:"Far dipendere la propria interpretazione della realtà dalla televisione",en:"Making one's interpretation of reality depend on television"},belongs:0,note:{it:"Lo schermo televisivo conduce in uno stato di ipnosi: la visione della realtà viene alterata.",en:"The TV screen leads into a state of hypnosis: the vision of reality is altered."}},
        {item:{it:"Sentire che nessuno può farmi sentire più libero di quanto già sono",en:"Feeling that no one can make me feel freer than I already am"},belongs:1,note:{it:"Nessuna decisione del governo può aggiungere libertà a quella che ho già. La libertà è interiore.",en:"No government decision can add freedom to what I already have. Freedom is inner."}},
        {item:{it:"Le parole escono dalla bocca come reazione meccanica",en:"Words leave the mouth as a mechanical reaction"},belongs:0,note:{it:"Il nostro parlare è sempre reazione meccanica perché la mente ci bypassa.",en:"Our speech is always a mechanical reaction because the mind bypasses us."}},
        {item:{it:"Pensare «Io sono» almeno una volta ogni ora, con inspirazione ed espirazione",en:"Thinking 'I am' at least once every hour, with inhalation and exhalation"},belongs:1,note:{it:"Serve a permeare di ricordo di sé l'intera giornata.",en:"It serves to permeate the entire day with self-remembering."}},
        {item:{it:"Un io prende decisioni e un altro io le dimentica",en:"One 'I' makes decisions and another 'I' forgets them"},belongs:0,note:{it:"Non siamo 'uno' ma 'tanti': ogni io crede di essere l'unico.",en:"We are not 'one' but 'many': each I believes it is the only one."}},
        {item:{it:"L'Osservatore silenzioso che non giudica ciò che osserva",en:"The silent Observer that doesn't judge what it observes"},belongs:1,note:{it:"L'Osservatore non ha mai nulla da dire: è lo sfondo immutabile su cui accade ogni pensare.",en:"The Observer never has anything to say: it is the immutable background on which all thinking happens."}},
        {item:{it:"Provare fastidio verso le proprie abitudini meccaniche",en:"Feeling annoyed at one's own mechanical habits"},belongs:0,note:{it:"Il fastidio verso le abitudini della macchina la tiene addormentata.",en:"Annoyance at the machine's habits keeps it asleep."}},
        {item:{it:"Osservare con amore il sonno della propria macchina",en:"Observing one's machine's sleep with love"},belongs:1,note:{it:"«Solo l'amore per il sonno della macchina la sveglia.»",en:"'Only love for the machine's sleep awakens it.'"}},
        {item:{it:"Lasciare qualche secondo fra ciò che si sente e la reazione",en:"Leaving a few seconds between what one feels and the reaction"},belongs:1,note:{it:"Il tempo di ricordarci di noi stessi ed entrare nel qui e ora.",en:"The time to remember ourselves and enter the here and now."}},
        {item:{it:"Vivere come uomo n. 1, 2 o 3",en:"Living as man no. 1, 2 or 3"},belongs:0,note:{it:"I primi tre sono meccanici e dormono in ugual misura.",en:"The first three are mechanical and sleep equally."}},
        {item:{it:"Continuare a sforzarsi di ricordarsi di sé anche quando non riesce",en:"Continuing to strive to remember oneself even when it doesn't work"},belongs:1,note:{it:"«Lo scopo è sforzarsi, tendere verso, non raggiungere il risultato voluto.»",en:"'The aim is to strive, to tend towards, not to reach the desired result.'"}}
      ]
    },
    attenzione: { type:"classify", roman:"II", glyph:"◇",
      optionKeys:[0,1],
      items: [
        {item:{it:"Passeggiare per strada persi in preoccupazioni sul lavoro di domani",en:"Walking down the street lost in worries about tomorrow's work"},belongs:0,note:{it:"Il mondo esterno ci distrae e ci seduce: tiene la coscienza addormentata.",en:"The outside world distracts and seduces us: it keeps consciousness asleep."}},
        {item:{it:"Osservare come si muovono le mani, l'espressione del volto, le posture del corpo",en:"Observing how the hands move, the facial expression, the body's postures"},belongs:1,note:{it:"Guidare l'Attenzione sulle attività dell'apparato psicofisico ci consente di conoscerlo.",en:"Guiding Attention to the activities of the psychophysical apparatus allows us to know it."}},
        {item:{it:"Costruire mentalmente dialoghi immaginari con chi ci ha fatto arrabbiare",en:"Mentally constructing imaginary dialogues with someone who angered us"},belongs:0,note:{it:"Immaginazione negativa: il mentale e l'emozionale ci trascinano tra passato e futuro.",en:"Negative imagination: the mental and emotional drag us between past and future."}},
        {item:{it:"Rilassare i muscoli del corpo nel mezzo di un'arrabbiatura, a cominciare dal viso",en:"Relaxing the body's muscles in the middle of anger, starting with the face"},belongs:1,note:{it:"Il corpo è sempre QUI e ORA, non mente. Questo vi costringe a essere presenti.",en:"The body is always HERE and NOW, it doesn't lie. This forces you to be present."}},
        {item:{it:"Fantasticare sul futuro o rivivere ricordi del passato durante una passeggiata",en:"Fantasising about the future or reliving past memories during a walk"},belongs:0,note:{it:"Passato e futuro mi riagganciano al lavorio della mente. L'Istante mi conduce in una dimensione superiore.",en:"Past and future hook me back to the mind's workings. The Instant leads me to a higher dimension."}},
        {item:{it:"Sentire i piedi che toccano il suolo, il respiro che entra ed esce",en:"Feeling the feet touching the ground, the breath entering and leaving"},belongs:1,note:{it:"Il corpo è il filo di Arianna fuori dal labirinto. Ciò che pensiamo è un sogno, il corpo è reale.",en:"The body is Ariadne's thread out of the labyrinth. What we think is a dream, the body is real."}},
        {item:{it:"La mente fantastica senza controllo: sogni a occhi aperti non richiesti",en:"The mind fantasises without control: unbidden daydreams"},belongs:0,note:{it:"Ogni genere di immaginazione che avviene nella macchina e non è da noi voluto né controllato.",en:"Every kind of imagination occurring in the machine that is neither willed nor controlled by us."}},
        {item:{it:"Un artista immagina coscientemente i mondi che poi rappresenterà nelle sue opere",en:"An artist consciously imagines the worlds he will then represent in his works"},belongs:1,note:{it:"Visualizzazione: la capacità di immaginare e costruire col pensiero in maniera voluta e cosciente.",en:"Visualisation: the ability to imagine and build with thought in a willed and conscious manner."}},
        {item:{it:"Una persona ci urta per strada e restiamo «fuori di noi» per ore",en:"Someone bumps into us in the street and we stay 'beside ourselves' for hours"},belongs:0,note:{it:"L'Attenzione è un fiore delicato: basta un fremito della pelle e vola via.",en:"Attention is a delicate flower: one quiver of the skin and it flies away."}},
        {item:{it:"Notare, durante un'emozione, il calore al plesso solare o l'oppressione al petto",en:"Noticing, during an emotion, heat in the solar plexus or pressure in the chest"},belongs:1,note:{it:"Portare l'Attenzione su ciò che la macchina fa mentre manifesta un'emozione.",en:"Bringing Attention to what the machine does while expressing an emotion."}},
        {item:{it:"Lavando i piatti, portare l'attenzione su di sé oltre che sui gesti",en:"While washing dishes, bringing attention to oneself as well as to the gestures"},belongs:1,note:{it:"È l'attenzione divisa applicata a un'azione quotidiana.",en:"It is divided attention applied to a daily action."}},
        {item:{it:"Al telefono, farsi assorbire completamente da ciò che dice l'altro",en:"On the phone, being completely absorbed by what the other says"},belongs:0,note:{it:"È identificazione: il ricordo di sé si perde.",en:"It is identification: self-remembering is lost."}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"Quanti sono gli stati di coscienza?",en:"How many states of consciousness are there?"},options:{it:["Quattro","Due","Tre","Sette"],en:["Four","Two","Three","Seven"]},correct:0,note:{it:"Sonno profondo, sogno, sonno verticale (falsa veglia) e veglia reale.",en:"Deep sleep, dream, vertical sleep (false waking) and real wakefulness."}},
        {q:{it:"Il ricordo di sé, nell'Alchimia, è chiamato…",en:"Self-remembering, in Alchemy, is called…"},options:{it:["Il «fuoco lento», l'«agente universale»","La pietra filosofale","L'acqua corrosiva","Il solve et coagula"],en:["The 'slow fire', the 'universal agent'","The philosopher's stone","The corrosive water","The solve et coagula"]},correct:0,note:{it:"Il 'regime' a cui la materia della personalità dev'essere sottoposta per la trasmutazione.",en:"The 'regime' to which the matter of the personality must be subjected for transmutation."}},
        {q:{it:"Il tempo fisico, secondo Draco Daatson…",en:"Physical time, per Draco Daatson…"},options:{it:["Non esiste: è una sensazione soggettiva nella coscienza","È oggettivo e misurabile","È uguale per tutti","È creato dall'orologio"],en:["Doesn't exist: it's a subjective sensation in consciousness","Is objective and measurable","Is the same for everyone","Is created by the clock"]},correct:0,note:{it:"L'orologio misura le oscillazioni, non 'quanto tempo è passato': questo è personale.",en:"The clock measures oscillations, not 'how much time has passed': that is personal."}},
        {q:{it:"L'ipnosi di massa funziona perché…",en:"Mass hypnosis works because…"},options:{it:["Gli esseri umani non gestiscono il piano mentale e sono passivi","Tutti sono stupidi","È impossibile resistervi","Funziona solo sui deboli"],en:["Human beings don't manage the mental plane and are passive","Everyone is stupid","It is impossible to resist","It only works on the weak"]},correct:0,note:{it:"Il soggetto ideale è un individuo in stato di coscienza addormentato, passivo e ricettivo.",en:"The ideal subject is an individual in a sleeping, passive and receptive state."}},
        {q:{it:"L'Io osservatore (il «testimone») NON deve…",en:"The observing I (the 'witness') must NOT…"},options:{it:["Giudicare ciò che osserva","Osservare la rabbia","Osservare la felicità","Restare presente"],en:["Judge what it observes","Observe anger","Observe happiness","Remain present"]},correct:0,note:{it:"Se giudichiamo, guardiamo con un 'io' della personalità: rischio di scissione.",en:"If we judge, we look with a personality 'I': risk of splitting."}},
        {q:{it:"La PRESENZA è l'unica soluzione perché…",en:"PRESENCE is the only solution because…"},options:{it:["Non reprime né lascia scorrere il fuoco emotivo nell'inconsapevolezza","È la tecnica più facile","Non richiede alcuno sforzo","Elimina tutte le emozioni"],en:["It neither represses nor lets emotional fire flow in unawareness","It is the easiest technique","It requires no effort","It eliminates all emotions"]},correct:0,note:{it:"L'unico approccio che non reprime e allo stesso tempo non lascia scorrere l'emozione meccanicamente.",en:"The only approach that neither represses nor lets emotion flow mechanically."}},
        {q:{it:"«Non ducor duco» significa…",en:"'Non ducor duco' means…"},options:{it:["Non vengo condotto, conduco","Non penso, agisco","Non parlo, ascolto","Non vedo, credo"],en:["I am not led, I lead","I don't think, I act","I don't speak, I listen","I don't see, I believe"]},correct:0,note:{it:"Il motto del Risveglio: chi si risveglia conduce la propria macchina.",en:"The motto of Awakening: whoever awakens leads their own machine."}},
        {q:{it:"Il 95% del nostro essere…",en:"95% of our being…"},options:{it:["Lavora in maniera inconscia, fuori dal controllo cosciente","È guidato dalla volontà razionale","Segue un destino già scritto","Dipende dalle azioni degli altri"],en:["Works unconsciously, outside conscious control","Is guided by rational will","Follows a fate already written","Depends on other people's actions"]},correct:0,note:{it:"«La nostra realtà quotidiana non viene creata dalla nostra sfera cosciente, bensì da tutto ciò che è subconscio.»",en:"'Our daily reality is not created by our conscious sphere, but by everything that is subconscious.'"}},
        {q:{it:"Il termine 'emergenza' indica in realtà…",en:"The term 'emergency' actually indicates…"},options:{it:["L'emergere in superficie di ciò che è sommerso","Solo qualcosa di negativo","Un errore del sistema","Un evento casuale"],en:["The emerging to the surface of what is submerged","Only something negative","A system error","A random event"]},correct:0,note:{it:"Non indica qualcosa di negativo, bensì l'EMERGERE di ciò che è sommerso.",en:"It doesn't indicate something negative, but the EMERGING of what is submerged."}},
        {q:{it:"La Pace è…",en:"Peace is…"},options:{it:["Uno stato di non-identificazione con l'attività della mente","L'assenza di guerra","Una tecnica di rilassamento","Un dono dall'esterno"],en:["A state of non-identification with the mind's activity","The absence of war","A relaxation technique","A gift from outside"]},correct:0,note:{it:"Non è assenza di guerra. È totale rilassamento, non-identificazione con la mente.",en:"It's not the absence of war. It's total relaxation, non-identification with the mind."}},
        {q:{it:"La crisi è, per chi vuole risvegliarsi…",en:"Crisis is, for those who want to awaken…"},options:{it:["Il momento più favorevole","Il momento peggiore","Irrilevante","Un ostacolo insuperabile"],en:["The most favourable moment","The worst moment","Irrelevant","An insurmountable obstacle"]},correct:0,note:{it:"Tempi di estrema tensione sociale: tempi favorevoli per chi vuole svegliarsi.",en:"Times of extreme social tension: favourable times for those who want to awaken."}},
        {q:{it:"Nella metafora della «casa senza padrone», i servi sono…",en:"In the 'house without a master' metaphor, the servants are…"},options:{it:["I diversi 'io' che agiscono senza coordinamento","I corpi sottili","Le emozioni superiori","I pianeti"],en:["The different 'I's that act without coordination","The subtle bodies","The higher emotions","The planets"]},correct:0,note:{it:"Ogni 'io' crede di essere l'unico e prende decisioni per la totalità.",en:"Each 'I' believes it is the only one and makes decisions for the whole."}},
        {q:{it:"Che cosa distingue l'«uomo numero 5»?",en:"What distinguishes 'man number 5'?"},options:{it:["Ha aperto il Cuore, il centro emozionale superiore","Ha deciso per la prima volta di lavorare su di sé","Ha studiato molti libri esoterici","Ha smesso di provare emozioni"],en:["He has opened the Heart, the higher emotional centre","He has decided for the first time to work on himself","He has studied many esoteric books","He has stopped feeling emotions"]},correct:0,note:{it:"Vive in un costante stato di innamoramento verso la vita perché vede la Bellezza onnipresente.",en:"He lives in a constant state of being in love with life because he sees omnipresent Beauty."}},
        {q:{it:"L'effettivo stato di ricordo di sé è…",en:"The actual state of self-remembering is…"},options:{it:["Uno stato emotivo superiore","Un fenomeno intellettuale","Un esercizio di memoria","Uno stato di trance"],en:["A higher emotional state","An intellectual phenomenon","A memory exercise","A trance state"]},correct:0,note:{it:"«L'effettivo stato di ricordo di sé è uno stato EMOTIVO SUPERIORE, non un fenomeno intellettuale.»",en:"'The actual state of self-remembering is a HIGHER EMOTIONAL state, not an intellectual phenomenon.'"}},
        {q:{it:"Quanto dura, all'inizio, la pratica di un singolo esercizio di ricordo di sé?",en:"At first, how long should a single self-remembering exercise be practised?"},options:{it:["Una settimana; sette settimane chiudono un ciclo","Un giorno solo","Un anno intero","Finché non riesce perfettamente"],en:["One week; seven weeks close a cycle","A single day","A whole year","Until it succeeds perfectly"]},correct:0,note:{it:"«Sette giorni è il periodo ideale. Dopo sette settimane si conclude un ciclo.»",en:"'Seven days is the ideal period. After seven weeks a cycle is complete.'"}},
        {q:{it:"Paradossalmente, un esercizio di ricordo di sé funziona…",en:"Paradoxically, a self-remembering exercise works…"},options:{it:["Solo finché non siamo in grado di farlo bene e ci sforziamo","Solo quando lo si esegue alla perfezione","Solo se guidati da un maestro","Solo la mattina presto"],en:["Only as long as we can't yet do it well and strive to","Only when performed perfectly","Only when guided by a master","Only early in the morning"]},correct:0,note:{it:"«Lo scopo è sforzarsi, tendere verso, non raggiungere il risultato voluto.»",en:"'The aim is to strive, to tend towards, not to reach the desired result.'"}},
        {q:{it:"Completa la frase di Robert Earl Burton: «Se non possiamo controllare la macchina…»",en:"Complete Robert Earl Burton's sentence: 'If we cannot control the machine…'"},options:{it:["…siamo la macchina»","…dobbiamo distruggerla»","…dobbiamo ignorarla»","…è colpa del mondo»"],en:["…we are the machine'","…we must destroy it'","…we must ignore it'","…the world is to blame'"]},correct:0,note:{it:"Citata da Brizzi in «Il lavoro alchemico», prima degli esercizi avanzati.",en:"Quoted by Brizzi in 'Il lavoro alchemico', before the advanced exercises."}},
        {q:{it:"Chi è un risvegliato?",en:"Who is an awakened person?"},options:{it:["Uno in cui il pensare e la coscienza di sé sono due fenomeni distinti","Uno che non pensa più","Uno che ha letto tutti i testi sacri","Uno che non prova più emozioni"],en:["One in whom thinking and self-awareness are two distinct phenomena","One who no longer thinks","One who has read all the sacred texts","One who no longer feels emotions"]},correct:0,note:{it:"Si è identificato con la coscienza di sé, l'anima, il puro ESSERCI.",en:"He has identified with self-awareness, the soul, pure BEING-THERE."}},
        {q:{it:"Che cosa sveglia davvero la macchina?",en:"What truly awakens the machine?"},options:{it:["L'amore per il suo sonno","Il fastidio verso le sue abitudini","Il rifiuto deciso del sonno","La punizione degli errori"],en:["Love for its sleep","Annoyance at its habits","A firm rejection of sleep","Punishing its mistakes"]},correct:0,note:{it:"«Il rifiuto del sonno non può che essere mentale, e ci ricaccia nel sonno stesso.»",en:"'Rejecting sleep can only be mental, and it throws us back into sleep itself.'"}},
        {q:{it:"Che cosa consigliò Victoria Ignis a Brizzi, quando sul lavoro provava malessere?",en:"What did Victoria Ignis advise Brizzi when he felt unease at work?"},options:{it:["Entrare nella presenza e sentire il calore del fuoco emotivo","Cambiare subito lavoro","Sfogarsi con un collega","Distrarsi con un'attività piacevole"],en:["Enter presence and feel the heat of the emotional fire","Change job immediately","Vent to a colleague","Distract himself with something pleasant"]},correct:0,note:{it:"«Quel calore, quel subbuglio interiore è il nostro biglietto aereo Inferno-Paradiso, diretto, senza scalo.»",en:"'That heat, that inner turmoil, is our Hell-to-Paradise plane ticket, direct, no stopover.'"}},
        {q:{it:"Per usare un disagio come occasione di risveglio, che cosa è indispensabile?",en:"To use unease as an opportunity for awakening, what is indispensable?"},options:{it:["Frapporre qualche secondo fra il sentire interiore e la reazione esterna","Reagire subito per scaricare la tensione","Reprimere l'emozione","Analizzarne le cause con la mente"],en:["Putting a few seconds between inner feeling and outer reaction","Reacting at once to release tension","Repressing the emotion","Analysing its causes with the mind"]},correct:0,note:{it:"Il tempo di ricordarci di noi stessi ed entrare nel qui e ora.",en:"The time to remember ourselves and enter the here and now."}},
        {q:{it:"Perché l'immaginazione negativa è pericolosa?",en:"Why is negative imagination dangerous?"},options:{it:["Genera la maggior parte delle emozioni negative e le fa riaffiorare anche a distanza di mesi","Perché consuma troppo tempo","Perché impedisce di sognare","Perché è sempre legata al passato"],en:["It generates most negative emotions and revives them even months later","Because it takes too much time","Because it prevents dreaming","Because it is always tied to the past"]},correct:0,note:{it:"È ogni immaginazione o «dialogo interno» che non è da noi né voluto né controllato.",en:"It is any imagination or 'inner dialogue' that is neither willed nor controlled by us."}},
        {q:{it:"Secondo «La porta del mago», quali muscoli sono sempre contratti e vanno rilassati almeno una volta ogni ora?",en:"According to 'La porta del mago', which muscles are always contracted and should be relaxed at least once an hour?"},options:{it:["I trapezi, fra il collo e le spalle","I polpacci","Gli addominali","I muscoli delle mani"],en:["The trapezius, between neck and shoulders","The calves","The abdominals","The hand muscles"]},correct:0,note:{it:"Serve a permeare di ricordo di sé l'intera giornata.",en:"It serves to permeate the whole day with self-remembering."}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✶",
      items: [
        {a:{it:"Ricordo di sé",en:"Self-remembering"},b:{it:"Essere presenti\nqui-e-ora",en:"Being present\nhere-and-now"}},
        {a:{it:"Sonno verticale",en:"Vertical sleep"},b:{it:"La falsa veglia\ndell'uomo",en:"Man's false\nwakefulness"}},
        {a:{it:"Il Momento",en:"The Moment"},b:{it:"L'unica realtà\nfuori dal tempo",en:"The only reality\noutside time"}},
        {a:{it:"L'Osservatore",en:"The Observer"},b:{it:"Pura presenza\ndistaccata",en:"Pure detached\npresence"}},
        {a:{it:"La macchina\nbiologica",en:"The biological\nmachine"},b:{it:"Bacchetta\nmagico-organica",en:"Magical-organic\nwand"}},
        {a:{it:"L'incantesimo",en:"The enchantment"},b:{it:"Manipolazione\nmentale di massa",en:"Mass mental\nmanipulation"}},
        {a:{it:"Fuoco lento",en:"Slow fire"},b:{it:"Il ricordo di sé\ndegli alchimisti",en:"The alchemists'\nself-remembering"}},
        {a:{it:"Uomo n. 4",en:"Man no. 4"},b:{it:"Centro di gravità\npermanente",en:"Permanent centre\nof gravity"}},
        {a:{it:"Attenzione divisa",en:"Divided attention"},b:{it:"Sull'azione e\nsu di sé insieme",en:"On the action and\non oneself at once"}}
      ]
    }
  }
};
})();
