/* IL RISVEGLIO — data.js (pooled from 6 books) */
(function(){
"use strict";
window.GAME_DATA = {
  id: "risveglio",
  modes: ["sonno","attenzione","quiz","memoria"],
  rings: [
    {key:"tempo",color:"#1a1326",ring:"#3a2f52",label:{it:"Il Tempo",en:"Time"}},
    {key:"manipolazione",color:"#10212a",ring:"#2f5d6b",label:{it:"L'Incantesimo",en:"The Enchantment"}},
    {key:"presenza",color:"#2a1410",ring:"#7c3a2a",label:{it:"La Presenza",en:"Presence"}},
    {key:"risveglio",color:"#3a2c10",ring:"#c9973a",label:{it:"Il Risveglio",en:"Awakening"}}
  ],
  modeDefs: {
    sonno: { type:"classify", roman:"I", glyph:"◐",
      optionKeys:[0,1],
      items: [
        {item:{it:"Reagire meccanicamente a uno stimolo esterno",en:"Reacting mechanically to an external stimulus"},belongs:0,note:{it:"La personalità è una macchina biologica che re-agisce.",en:"The personality is a biological machine that re-acts."}},
        {item:{it:"Osservarsi nel qui-e-ora mentre si agisce: l'«attenzione divisa»",en:"Observing oneself in the here-and-now while acting: 'divided attention'"},belongs:1,note:{it:"Ricordarsi di sé: parte dell'attenzione su di sé, parte sull'azione.",en:"Self-remembering: part of the attention on oneself, part on the action."}},
        {item:{it:"Il «sonno verticale» scambiato per vera veglia",en:"'Vertical sleep' mistaken for true wakefulness"},belongs:0,note:{it:"Lo stato ordinario dell'uomo: sembra veglia ma è ancora sonno.",en:"Man's ordinary state: it looks like waking but is still sleep."}},
        {item:{it:"La «continuità di coscienza», vigili anche nel sonno",en:"'Continuity of consciousness', awake even in sleep"},belongs:1,note:{it:"Nel risveglio completo il Sé resta cosciente 24 ore su 24.",en:"In full awakening the Self stays conscious 24/7."}},
        {item:{it:"Credere di possedere libero arbitrio senza averlo verificato",en:"Believing one has free will without having verified it"},belongs:0,note:{it:"Se anche in una sola occasione le emozioni ci hanno tradito, non possediamo libero arbitrio.",en:"If even once our emotions betrayed us, we do not possess free will."}},
        {item:{it:"Creare un «centro di gravità permanente» dedicato al Lavoro",en:"Creating a 'permanent centre of gravity' dedicated to the Work"},belongs:1,note:{it:"Il passaggio da uomo 1-2-3 a uomo n. 4: la ferma decisione di lavorare su di sé.",en:"The passage from man 1-2-3 to man no. 4: the firm decision to work on oneself."}},
        {item:{it:"Vivere schiacciati tra il rimpianto del passato e l'ansia del futuro",en:"Living crushed between regret for the past and anxiety about the future"},belongs:0,note:{it:"Ogni sofferenza nasce dal tempo. Obiettivo: la sconfitta del tempo.",en:"All suffering is born of time. The aim: the defeat of time."}},
        {item:{it:"Restare nel Qui-e-Ora: «Io sono il figlio del Momento»",en:"Staying in the Here-and-Now: 'I am the son of the Moment'"},belongs:1,note:{it:"Un guerriero che vive nel Momento è un guerriero senza paure.",en:"A warrior who lives in the Moment is a warrior without fears."}},
        {item:{it:"Far dipendere la propria interpretazione della realtà dalla televisione",en:"Making one's interpretation of reality depend on television"},belongs:0,note:{it:"Lo schermo televisivo conduce in uno stato di ipnosi: la visione della realtà viene alterata.",en:"The TV screen leads into a state of hypnosis: the vision of reality is altered."}},
        {item:{it:"Sentire che nessuno può farmi sentire più libero di quanto già sono",en:"Feeling that no one can make me feel freer than I already am"},belongs:1,note:{it:"Nessuna decisione del governo può aggiungere libertà a quella che ho già. La libertà è interiore.",en:"No government decision can add freedom to what I already have. Freedom is inner."}},
        {item:{it:"Le parole escono dalla bocca come reazione meccanica",en:"Words leave the mouth as a mechanical reaction"},belongs:0,note:{it:"Il nostro parlare è sempre reazione meccanica perché la mente ci bypassa.",en:"Our speech is always a mechanical reaction because the mind bypasses us."}},
        {item:{it:"Pensare «Io sono» almeno una volta ogni ora, con inspirazione ed espirazione",en:"Thinking 'I am' at least once every hour, with inhalation and exhalation"},belongs:1,note:{it:"Serve a permeare di ricordo di sé l'intera giornata.",en:"It serves to permeate the entire day with self-remembering."}},
        {item:{it:"Un io prende decisioni e un altro io le dimentica",en:"One 'I' makes decisions and another 'I' forgets them"},belongs:0,note:{it:"Non siamo 'uno' ma 'tanti': ogni io crede di essere l'unico.",en:"We are not 'one' but 'many': each I believes it is the only one."}},
        {item:{it:"L'Osservatore silenzioso che non giudica ciò che osserva",en:"The silent Observer that doesn't judge what it observes"},belongs:1,note:{it:"L'Osservatore non ha mai nulla da dire: è lo sfondo immutabile su cui accade ogni pensare.",en:"The Observer never has anything to say: it is the immutable background on which all thinking happens."}}
      ]
    },
    attenzione: { type:"classify", roman:"II", glyph:"◇",
      optionKeys:[0,1],
      items: [
        {item:{it:"Passeggiare per strada persi in preoccupazioni sul lavoro di domani",en:"Walking down the street lost in worries about tomorrow's work"},belongs:0,note:{it:"Il mondo esterno ci distrae e ci seduce: tiene la coscienza addormentata.",en:"The outside world distracts and seduces us: it keeps consciousness asleep."}},
        {item:{it:"Osservare come si muovono le mani, l'espressione del volto, le posture del corpo",en:"Observing how the hands move, the facial expression, the body's postures"},belongs:1,note:{it:"Guidare l'Attenzione sulle attività dell'apparato psicofisico ci consente di conoscerlo.",en:"Guiding Attention to the activities of the psychophysical apparatus allows us to know it."}},
        {item:{it:"Costruire mentalmente dialoghi immaginari con chi ci ha fatto arrabbiare",en:"Mentally constructing imaginary dialogues with someone who angered us"},belongs:0,note:{it:"Immaginazione negativa: il mentale e l'emozionale ci trascinano tra passato e futuro.",en:"Negative imagination: the mental and emotional drag us between past and future."}},
        {item:{it:"Rilassare i muscoli del corpo nel mezzo di un'arrabbiatura, a cominciare dal viso",en:"Relaxing the body's muscles in the middle of anger, starting with the face"},belongs:1,note:{it:"Il corpo è sempre QUI e ORA, non mente. Questo vi costringe a essere presenti.",en:"The body is always HERE and NOW, it doesn't lie. This forces you to be present."}},
        {item:{it:"Fantasticare sul futuro o rivivere ricordi del passato durante una passeggiata",en:"Fantasising about the future or reliving past memories during a walk"},belongs:0,note:{it:"Passato e futuro mi riagganciano al lavorio della mente. L'Istante mi conduce in una dimensione superiore.",en:"Past and future hook me back to the mind's workings. The Instant leads me to a higher dimension."}},
        {item:{it:"Sentire i piedi che toccano il suolo, il respiro che entra ed esce",en:"Feeling the feet touching the ground, the breath entering and leaving"},belongs:1,note:{it:"Il corpo è il filo di Arianna fuori dal labirinto. Ciò che pensiamo è un sogno, il corpo è reale.",en:"The body is Ariadne's thread out of the labyrinth. What we think is a dream, the body is real."}},
        {item:{it:"La mente fantastica senza controllo: sogni a occhi aperti non richiesti",en:"The mind fantasises without control: unbidden daydreams"},belongs:0,note:{it:"Ogni genere di immaginazione che avviene nella macchina e non è da noi voluto né controllato.",en:"Every kind of imagination occurring in the machine that is neither willed nor controlled by us."}},
        {item:{it:"Un artista immagina coscientemente i mondi che poi rappresenterà nelle sue opere",en:"An artist consciously imagines the worlds he will then represent in his works"},belongs:1,note:{it:"Visualizzazione: la capacità di immaginare e costruire col pensiero in maniera voluta e cosciente.",en:"Visualisation: the ability to imagine and build with thought in a willed and conscious manner."}}
      ]
    },
    quiz: { type:"quiz", roman:"III", glyph:"✦", count:10,
      items: [
        {q:{it:"Quanti sono gli stati di coscienza?",en:"How many states of consciousness are there?"},options:{it:["Quattro","Due","Tre","Sette"],en:["Four","Two","Three","Seven"]},correct:0,note:{it:"Sonno profondo, sogno, sonno verticale (falsa veglia) e veglia reale.",en:"Deep sleep, dream, vertical sleep (false waking) and real wakefulness."}},
        {q:{it:"Il ricordo di sé, nell'Alchimia, è chiamato…",en:"Self-remembering, in Alchemy, is called…"},options:{it:["Il «fuoco lento», l'«agente universale»","La pietra filosofale","L'acqua corrosiva","Il solve et coagula"],en:["The 'slow fire', the 'universal agent'","The philosopher's stone","The corrosive water","The solve et coagula"]},correct:0,note:{it:"Il 'regime' a cui la materia della personalità dev'essere sottoposta per la trasmutazione.",en:"The 'regime' to which the matter of the personality must be subjected for transmutation."}},
        {q:{it:"Il tempo fisico, secondo Draco Daatson…",en:"Physical time, per Draco Daatson…"},options:{it:["Non esiste: è una sensazione soggettiva nella coscienza","È oggettivo e misurabile","È uguale per tutti","È creato dall'orologio"],en:["Doesn't exist: it's a subjective sensation in consciousness","Is objective and measurable","Is the same for everyone","Is created by the clock"]},correct:0,note:{it:"L'orologio misura le oscillazioni, non 'quanto tempo è passato': questo è personale.",en:"The clock measures oscillations, not 'how much time has passed': that is personal."}},
        {q:{it:"L'ipnosi di massa funziona perché…",en:"Mass hypnosis works because…"},options:{it:["Gli esseri umani non gestiscono il piano mentale e sono passivi","Tutti sono stupidi","È impossibile resistervi","Funziona solo sui deboli"],en:["Human beings don't manage the mental plane and are passive","Everyone is stupid","It is impossible to resist","It only works on the weak"]},correct:0,note:{it:"Il soggetto ideale è un individuo in stato di coscienza addormentato, passivo e ricettivo.",en:"The ideal subject is an individual in a sleeping, passive and receptive state."}},
        {q:{it:"L'Io osservatore (il «testimone») NON deve…",en:"The observing I (the 'witness') must NOT…"},options:{it:["Giudicare ciò che osserva","Osservare la rabbia","Osservare la felicità","Restare presente"],en:["Judge what it observes","Observe anger","Observe happiness","Remain present"]},correct:0,note:{it:"Se giudichiamo, guardiamo con un 'io' della personalità: rischio di scissione.",en:"If we judge, we look with a personality 'I': risk of splitting."}},
        {q:{it:"La PRESENZA è l'unica soluzione perché…",en:"PRESENCE is the only solution because…"},options:{it:["Non reprime né lascia scorrere il fuoco emotivo nell'inconsapevolezza","È la tecnica più facile","Non richiede alcuno sforzo","Elimina tutte le emozioni"],en:["It neither represses nor lets emotional fire flow in unawareness","It is the easiest technique","It requires no effort","It eliminates all emotions"]},correct:0,note:{it:"L'unico approccio che non reprime e allo stesso tempo non lascia scorrere l'emozione meccanicamente.",en:"The only approach that neither represses nor lets emotion flow mechanically."}},
        {q:{it:"«Non ducor duco» significa…",en:"'Non ducor duco' means…"},options:{it:["Non vengo condotto, conduco","Non penso, agisco","Non parlo, ascolto","Non vedo, credo"],en:["I am not led, I lead","I don't think, I act","I don't speak, I listen","I don't see, I believe"]},correct:0,note:{it:"Il motto del Risveglio: non essere più condotti dalla macchina, ma condurla.",en:"The motto of Awakening: no longer being led by the machine, but leading it."}},
        {q:{it:"Il 95% della realtà è creato da…",en:"95% of reality is created by…"},options:{it:["Il subconscio, non dal pensiero cosciente","La volontà razionale","Il destino","Le azioni degli altri"],en:["The subconscious, not by conscious thought","Rational will","Destiny","Other people's actions"]},correct:0,note:{it:"La nostra realtà quotidiana non viene creata dalla sfera cosciente, bensì dal subconscio.",en:"Our daily reality is not created by our conscious sphere, but by the subconscious."}},
        {q:{it:"Il termine 'emergenza' indica in realtà…",en:"The term 'emergency' actually indicates…"},options:{it:["L'emergere in superficie di ciò che è sommerso","Solo qualcosa di negativo","Un errore del sistema","Un evento casuale"],en:["The emerging to the surface of what is submerged","Only something negative","A system error","A random event"]},correct:0,note:{it:"Non indica qualcosa di negativo, bensì l'EMERGERE di ciò che è sommerso.",en:"It doesn't indicate something negative, but the EMERGING of what is submerged."}},
        {q:{it:"La Pace è…",en:"Peace is…"},options:{it:["Uno stato di non-identificazione con l'attività della mente","L'assenza di guerra","Una tecnica di rilassamento","Un dono dall'esterno"],en:["A state of non-identification with the mind's activity","The absence of war","A relaxation technique","A gift from outside"]},correct:0,note:{it:"Non è assenza di guerra. È totale rilassamento, non-identificazione con la mente.",en:"It's not the absence of war. It's total relaxation, non-identification with the mind."}},
        {q:{it:"La crisi è, per chi vuole risvegliarsi…",en:"Crisis is, for those who want to awaken…"},options:{it:["Il momento più favorevole","Il momento peggiore","Irrilevante","Un ostacolo insuperabile"],en:["The most favourable moment","The worst moment","Irrelevant","An insurmountable obstacle"]},correct:0,note:{it:"Tempi di estrema tensione sociale: tempi favorevoli per chi vuole svegliarsi.",en:"Times of extreme social tension: favourable times for those who want to awaken."}},
        {q:{it:"Nella metafora della «casa senza padrone», i servi sono…",en:"In the 'house without a master' metaphor, the servants are…"},options:{it:["I diversi 'io' che agiscono senza coordinamento","I corpi sottili","Le emozioni superiori","I pianeti"],en:["The different 'I's that act without coordination","The subtle bodies","The higher emotions","The planets"]},correct:0,note:{it:"Ogni 'io' crede di essere l'unico e prende decisioni per la totalità.",en:"Each 'I' believes it is the only one and makes decisions for the whole."}}
      ]
    },
    memoria: { type:"memory", roman:"IV", glyph:"✶",
      items: [
        {a:{it:"Ricordo di sé",en:"Self-remembering"},b:{it:"Essere presenti\nqui-e-ora",en:"Being present\nhere-and-now"}},
        {a:{it:"Sonno verticale",en:"Vertical sleep"},b:{it:"La falsa veglia\ndell'uomo",en:"Man's false\nwakefulness"}},
        {a:{it:"Il Momento",en:"The Moment"},b:{it:"L'unica realtà\nfuori dal tempo",en:"The only reality\noutside time"}},
        {a:{it:"L'Osservatore",en:"The Observer"},b:{it:"Pura presenza\ndistaccata",en:"Pure detached\npresence"}},
        {a:{it:"La macchina\nbiologica",en:"The biological\nmachine"},b:{it:"Bacchetta\nmagico-organica",en:"Magical-organic\nwand"}},
        {a:{it:"L'incantesimo",en:"The enchantment"},b:{it:"Manipolazione\nmentale di massa",en:"Mass mental\nmanipulation"}}
      ]
    }
  }
};
})();
