/* ============================================================
   I MONDI SPIRITUALI — dati di gioco bilingue (IT / EN)
   Fonte: Salvatore Brizzi, "I Mondi Spirituali"
   (con riferimenti a A. E. Powell e C. W. Leadbeater)
   Ogni voce è { it, en }. Esposto come window.MS_DATA.
   ============================================================ */
(function () {
  "use strict";

  /* ---------- 1. I COLORI DELL'ANIMA (colore astrale ↔ stato) ----------
     Le tinte CSS sono evocazioni fedeli alle descrizioni del testo
     ("l'incessante gioco di colori del corpo mercuriale"). */
  const COLORS = [
    { css: "radial-gradient(circle at 40% 35%, #1c1c1f, #050505 70%)",
      name: { it: "Nero", en: "Black" },
      state: { it: "Odio e malizia", en: "Hatred and malice" } },
    { css: "radial-gradient(circle at 35% 30%, #5e0d0d, #120303 72%)",
      name: { it: "Lampi rosso scuro su fondo nero", en: "Dark-red flashes on black" },
      state: { it: "Collera", en: "Wrath" } },
    { css: "radial-gradient(circle at 38% 34%, #d24a2c, #7c1c10 80%)",
      name: { it: "Nube scarlatta", en: "Scarlet cloud" },
      state: { it: "Irritabilità", en: "Irritability" } },
    { css: "radial-gradient(circle at 38% 32%, #ff5036, #c01f12 78%)",
      name: { it: "Scarlatto vivo", en: "Vivid scarlet" },
      state: { it: "Nobile indignazione", en: "Noble indignation" } },
    { css: "radial-gradient(circle at 38% 34%, #8e1622, #3c0810 80%)",
      name: { it: "Rosso sangue e rosso cupo", en: "Blood-red and deep red" },
      state: { it: "Sensualità", en: "Sensuality" } },
    { css: "radial-gradient(circle at 40% 35%, #7a6753, #463a2c 82%)",
      name: { it: "Grigio-bruno", en: "Brownish-grey" },
      state: { it: "Egoismo", en: "Selfishness" } },
    { css: "radial-gradient(circle at 36% 32%, #5d6535, #2c3016 78%), radial-gradient(circle at 70% 70%, #b32a1e, transparent 40%)",
      name: { it: "Bruno-verdastro con lampi scarlatti", en: "Greenish-brown with scarlet flashes" },
      state: { it: "Gelosia", en: "Jealousy" } },
    { css: "radial-gradient(circle at 40% 35%, #8c8c94, #4f4f56 82%)",
      name: { it: "Grigio", en: "Grey" },
      state: { it: "Depressione", en: "Depression" } },
    { css: "radial-gradient(circle at 40% 35%, #aab0b6, #6c7176 82%)",
      name: { it: "Grigio livido", en: "Livid grey" },
      state: { it: "Paura", en: "Fear" } },
    { css: "radial-gradient(circle at 38% 32%, #ffb6cd, #e87aa0 80%)",
      name: { it: "Rosa", en: "Rose" },
      state: { it: "Amore non egoista", en: "Unselfish love" } },
    { css: "radial-gradient(circle at 38% 33%, #ffa24a, #d9651c 80%)",
      name: { it: "Arancio", en: "Orange" },
      state: { it: "Orgoglio o ambizione", en: "Pride or ambition" } },
    { css: "radial-gradient(circle at 40% 35%, #b9a52f, #6e6112 82%)",
      name: { it: "Giallo cupo", en: "Dull yellow" },
      state: { it: "Intelletto usato per fini egoistici", en: "Intellect used for selfish ends" } },
    { css: "radial-gradient(circle at 38% 33%, #f6e98a, #d7c24a 82%)",
      name: { it: "Giallo primula", en: "Primrose yellow" },
      state: { it: "Intelletto votato a scopi spirituali", en: "Intellect devoted to spiritual aims" } },
    { css: "radial-gradient(circle at 38% 32%, #ffe07a, #e7b321 80%)",
      name: { it: "Giallo oro", en: "Golden yellow" },
      state: { it: "Intelligenza pura (filosofia, matematica)", en: "Pure intelligence (philosophy, mathematics)" } },
    { css: "radial-gradient(circle at 40% 35%, #7c8a6b, #44503a 82%)",
      name: { it: "Verde-grigio", en: "Greyish-green" },
      state: { it: "Astuzia usata per ingannare", en: "Cunning used to deceive" } },
    { css: "radial-gradient(circle at 38% 32%, #1fc77e, #0c794a 80%)",
      name: { it: "Verde smeraldo", en: "Emerald green" },
      state: { it: "Versatilità, ingegnosità altruista", en: "Versatility, altruistic ingenuity" } },
    { css: "radial-gradient(circle at 38% 33%, #2f4f9e, #16244e 82%)",
      name: { it: "Blu cupo", en: "Deep blue" },
      state: { it: "Sentimento religioso", en: "Religious feeling" } },
    { css: "radial-gradient(circle at 38% 32%, #8fc2ee, #4a86c4 80%)",
      name: { it: "Blu chiaro", en: "Light blue" },
      state: { it: "Devozione a un nobile ideale spirituale", en: "Devotion to a noble spiritual ideal" } },
    { css: "radial-gradient(circle at 38% 32%, #b07ce6, #6a2fb0 80%)",
      name: { it: "Ultravioletto", en: "Ultraviolet" },
      state: { it: "Facoltà psichiche del Mago per fini elevati", en: "The Magus's psychic faculties for high ends" } },
    { css: "radial-gradient(circle at 38% 32%, #c01030, #4a0512 80%)",
      name: { it: "Infrarosso", en: "Infrared" },
      state: { it: "Basse facoltà psichiche del Mago Nero", en: "The Black Magus's lower psychic faculties" } }
  ];

  /* ---------- 2. GLI ABITANTI DEL PIANO ASTRALE ---------- */
  const ENTITIES = [
    { name: { it: "Essenza elementale", en: "Elemental essence" },
      group: { it: "Entità non umana", en: "Non-human entity" },
      clue: { it: "Massa informe diffusa in tutto l'astrale. Reagisce in una frazione di secondo a ogni pensiero umano, plasmandosi in un essere vivente temporaneo che svanisce appena cessa l'emozione che lo alimenta.",
        en: "A formless mass spread throughout the astral. It reacts in a fraction of a second to every human thought, shaping itself into a temporary living being that vanishes as soon as the feeding emotion ceases." } },
    { name: { it: "Ombre", en: "Shades" },
      group: { it: "Non più vive nel corpo fisico", en: "No longer alive in the physical body" },
      clue: { it: "Cadavere astrale lasciato dietro di sé quando l'uomo muore sul piano astrale. Conserva l'apparenza, la memoria e le vecchie abitudini, e può ingannare i medium delle sedute spiritiche.",
        en: "The astral corpse left behind when one dies on the astral plane. It keeps its appearance, memory and old habits, and can deceive the mediums of séances." } },
    { name: { it: "Gusci", en: "Shells" },
      group: { it: "Non più vive nel corpo fisico", en: "No longer alive in the physical body" },
      clue: { it: "Ombre all'ultimo stadio di disintegrazione prima di scomparire. Possono essere vitalizzate attraverso cerimonie di magia nera o riti Voodoo e Obeah.",
        en: "Shades at the last stage of disintegration before vanishing. They can be vitalised through black-magic ceremonies or Voodoo and Obeah rites." } },
    { name: { it: "Spiriti di natura", en: "Nature spirits" },
      group: { it: "Entità non umana", en: "Non-human entity" },
      clue: { it: "Gnomi (terra), ondine (acqua), silfidi (aria), salamandre (etere). Amano massimamente il gioco e lo scherzo; rifuggono l'uomo, ma talvolta gli fanno smarrire la strada in un bosco.",
        en: "Gnomes (earth), undines (water), sylphs (air), salamanders (ether). They love play and pranks above all; they shun humankind, yet sometimes make one lose the way in a wood." } },
    { name: { it: "Demoni", en: "Demons" },
      group: { it: "Entità non umana", en: "Non-human entity" },
      clue: { it: "Esseri astrali molto potenti che agiscono per egoismo e si nutrono dei pensieri separativi e delle emozioni negative degli uomini. I più noti sono i «rettiliani».",
        en: "Very powerful astral beings that act out of selfishness and feed on humans' separative thoughts and negative emotions. The best known are the 'reptilians'." } },
    { name: { it: "Deva", en: "Devas" },
      group: { it: "Entità non umana", en: "Non-human entity" },
      clue: { it: "Detti angeli o «figli di Dio». Appartengono a un'evoluzione superiore all'umanità e appaiono come esseri umani di misura gigantesca; tutto ciò che è cattivo è già stato eliminato dal loro essere.",
        en: "Called angels or 'sons of God'. They belong to an evolution above humanity and appear as humans of gigantic size; all that is evil has long been removed from their being." } },
    { name: { it: "Vampiri", en: "Vampires" },
      group: { it: "Non più vive nel corpo fisico", en: "No longer alive in the physical body" },
      clue: { it: "Entità che prolungano la propria esistenza vicino alla materia terrestre assorbendo vitalità dagli esseri umani che riescono a influenzare.",
        en: "Entities that prolong their existence near earthly matter by absorbing vitality from the humans they manage to influence." } },
    { name: { it: "Suicidi e vittime di morte improvvisa", en: "Suicides and victims of sudden death" },
      group: { it: "Non più vive nel corpo fisico", en: "No longer alive in the physical body" },
      clue: { it: "Individui trapassati in circostanze traumatiche che non si rassegnano alla nuova condizione e cercano di restare vicino al piano fisico assorbendo vitalità dai viventi.",
        en: "Individuals who died in traumatic circumstances, do not accept their new condition, and try to remain near the physical plane by drawing vitality from the living." } },
    { name: { it: "Maghi e loro allievi", en: "Magi and their pupils" },
      group: { it: "Ancora vive nel corpo fisico", en: "Still alive in the physical body" },
      clue: { it: "Di norma usano il corpo mentale, ma nelle fasi meno avanzate dell'istruzione il corpo astrale è il primo con cui l'apprendista prende confidenza una volta divenuto cosciente in esso.",
        en: "They normally use the mental body, but in the earlier stages of training the astral body is the first the apprentice grows familiar with, once fully conscious within it." } },
    { name: { it: "Maghi neri e loro allievi", en: "Black magi and their pupils" },
      group: { it: "Ancora vive nel corpo fisico", en: "Still alive in the physical body" },
      clue: { it: "Come i Maghi, ma lo sviluppo ha per scopo il male: i poteri vengono acquisiti per fini egoistici miranti a soggiogare l'umanità anziché favorirne l'evoluzione.",
        en: "Like the Magi, but their development aims at evil: powers are gained for selfish ends, to subjugate humanity rather than help it evolve." } },
    { name: { it: "Psichici", en: "Psychics" },
      group: { it: "Ancora vive nel corpo fisico", en: "Still alive in the physical body" },
      clue: { it: "Persone che hanno sviluppato i poteri psichici al punto di viaggiare coscientemente in astrale; se non istruite da un iniziato interpretano spesso in modo frammentario ed errato ciò che vedono.",
        en: "People who have developed psychic powers enough to travel consciously in the astral; if untrained by an initiate, they often misread what they see in a fragmentary, mistaken way." } },
    { name: { it: "Persone comuni (durante il sonno)", en: "Ordinary people (during sleep)" },
      group: { it: "Ancora vive nel corpo fisico", en: "Still alive in the physical body" },
      clue: { it: "Tutti viaggiano così durante il sonno: il corpo fisico dorme e si vaga nel corpo astrale. Mancando consapevolezza e controllo, tali viaggi sono involontari, confusi e poco utili.",
        en: "Everyone travels this way in sleep: the physical body sleeps while one wanders in the astral body. Lacking awareness and control, such journeys are involuntary, confused and of little use." } }
  ];

  /* ---------- 3. I SETTE SOTTOPIANI (viaggio: dal 7° al 1°) ---------- */
  const SUBPLANES = [
    { level: 7,
      title: { it: "Settimo sottopiano", en: "Seventh subplane" },
      desc: { it: "La materia più grossolana, che vibra con gli istinti meno nobili dell'uomo. Attraversarlo è come aprirsi il cammino in un fluido nero e vischioso.",
        en: "The coarsest matter, vibrating with man's least noble instincts. To pass through it is like forcing a way through a black, viscous fluid." },
      q: { it: "Chi dimora a lungo su questo sottopiano dopo la morte del corpo fisico?",
        en: "Who dwells at length on this subplane after the death of the physical body?" },
      options: { it: ["Assassini, pervertiti e schiavi dei propri vizi", "Religiosi egoisti", "Ricercatori materialisti", "Anime molto evolute"],
        en: ["Murderers, perverts and slaves to their vices", "Selfish religious souls", "Materialist researchers", "Highly evolved souls"] },
      correct: 0 },
    { level: 6,
      title: { it: "Sesto sottopiano", en: "Sixth subplane" },
      desc: { it: "Materia ancora densa, ma meno del settimo. Le anime restano fortemente legate alla Terra e alle sue attività, incapaci di distoglierne lo sguardo.",
        en: "Matter still dense, though less than the seventh. Souls remain strongly bound to the Earth and its activities, unable to look away from it." },
      q: { it: "In astrale, rispetto al piano fisico, l'ambiente che circonda il defunto è…",
        en: "On the astral plane, compared with the physical, the environment surrounding the deceased is…" },
      options: { it: ["Un fedele riflesso del suo stato emotivo", "Identico per tutte le anime", "Stabilito da un giudice", "Privo di forme"],
        en: ["A faithful reflection of his emotional state", "Identical for every soul", "Set by a judge", "Devoid of forms"] },
      correct: 0 },
    { level: 5,
      title: { it: "Quinto sottopiano", en: "Fifth subplane" },
      desc: { it: "Sul piano astrale non c'è mai la notte e non vi sono ombre, perché i corpi astrali sono trasparenti e tutta la materia è essa stessa luminosa. Non esiste il sonno.",
        en: "On the astral plane there is never night and there are no shadows, for astral bodies are transparent and all matter is itself luminous. Sleep does not exist." },
      q: { it: "Cosa accade quando due abitanti dell'astrale si «incontrano»?",
        en: "What happens when two astral inhabitants 'meet'?" },
      options: { it: ["Passano l'uno attraverso l'altro", "Si feriscono a vicenda", "Non possono vedersi", "Si fondono per sempre"],
        en: ["They pass through one another", "They wound each other", "They cannot see each other", "They merge forever"] },
      correct: 0 },
    { level: 4,
      title: { it: "Quarto sottopiano", en: "Fourth subplane" },
      desc: { it: "Il piano astrale ha le caratteristiche di un mondo a quattro dimensioni: con la vista astrale si percepiscono gli oggetti da tutti i lati contemporaneamente, e ogni particella interna è visibile come l'esterno.",
        en: "The astral plane has the features of a four-dimensional world: with astral sight one perceives objects from all sides at once, and every inner particle is as visible as the outside." },
      q: { it: "Guardando un libro chiuso con la vista astrale si vede…",
        en: "Looking at a closed book with astral sight, one sees…" },
      options: { it: ["Ogni pagina come se fosse la sola visibile", "Solo la copertina", "Le pagine sovrapposte e confuse", "Nulla, è opaco"],
        en: ["Each page as if it were the only one visible", "Only the cover", "The pages overlapped and confused", "Nothing, it is opaque"] },
      correct: 0 },
    { level: 3,
      title: { it: "Terzo sottopiano", en: "Third subplane" },
      desc: { it: "Qui i defunti perdono di vista la Terra. Profondamente assorbiti dai pensieri, creano il proprio ambiente: vivono in città immaginarie di loro creazione, scenari fantastici di notevole bellezza.",
        en: "Here the dead lose sight of the Earth. Deeply absorbed in thought, they create their own surroundings: they live in imaginary cities of their own making, fantastic scenes of remarkable beauty." },
      q: { it: "Quale rischio corre il viaggiatore spirituale neofita in questi paesaggi?",
        en: "What risk does the novice spiritual traveller run in these landscapes?" },
      options: { it: ["Perdersi, aggiungendo le proprie fantasie a quelle già presenti", "Restare congelato", "Essere giudicato", "Svanire all'istante"],
        en: ["Getting lost, adding his own fantasies to those already there", "Being frozen", "Being judged", "Vanishing at once"] },
      correct: 0 },
    { level: 2,
      title: { it: "Secondo sottopiano", en: "Second subplane" },
      desc: { it: "Abitato specialmente da religiosi egoisti e poco spirituali. Qui costruiscono templi immaginari e adorano una riproduzione della divinità che già adoravano nel mondo fisico.",
        en: "Specially inhabited by selfish, scarcely spiritual religious people. Here they build imaginary temples and worship a reproduction of the deity they already worshipped in the physical world." },
      q: { it: "Cosa costruiscono gli abitanti di questo sottopiano?",
        en: "What do the inhabitants of this subplane build?" },
      options: { it: ["Templi immaginari", "Biblioteche di scienza", "Officine", "Nulla"],
        en: ["Imaginary temples", "Libraries of science", "Workshops", "Nothing"] },
      correct: 0 },
    { level: 1,
      title: { it: "Primo sottopiano", en: "First subplane" },
      desc: { it: "Destinato a chi in vita si è consacrato a ricerche materiali per soddisfare ambizioni egoistiche, e non per servire i propri fratelli. Qui non si costruiscono ambienti immaginari come ai livelli inferiori.",
        en: "Reserved for those who in life devoted themselves to material research to satisfy selfish ambitions, not to serve their fellows. Here no imaginary environments are built as on the lower levels." },
      q: { it: "Cosa trattiene queste anime su questo sottopiano, talvolta per anni?",
        en: "What keeps these souls on this subplane, sometimes for years?" },
      options: { it: ["Le loro ricerche intellettuali", "Il sonno eterno", "La punizione divina", "L'oblio totale"],
        en: ["Their intellectual researches", "Eternal sleep", "Divine punishment", "Total oblivion"] },
      correct: 0 }
  ];

  /* ---------- 4. QUIZ DELL'INIZIATO (concetti chiave) ---------- */
  const QUIZ = [
    { q: { it: "Quanti sono i piani in cui è suddiviso l'universo manifesto?", en: "Into how many planes is the manifest universe divided?" },
      options: { it: ["Sette", "Tre", "Dodici", "Quattro"], en: ["Seven", "Three", "Twelve", "Four"] }, correct: 0,
      note: { it: "I sette piani, dal basso: Fisico, Astrale, Mentale, Buddhico, Atmico, Anupadaka, Adi.", en: "The seven planes, from the bottom: Physical, Astral, Mental, Buddhic, Atmic, Anupadaka, Adi." } },
    { q: { it: "In alchimia il corpo astrale è detto anche…", en: "In alchemy the astral body is also called…" },
      options: { it: ["Fluidico o Mercuriale", "Atmico", "Causale", "Buddhico"], en: ["Fluidic or Mercurial", "Atmic", "Causal", "Buddhic"] }, correct: 0,
      note: { it: "Il corpo emotivo (astrale) è detto in alchimia Fluidico o Mercuriale.", en: "The emotional (astral) body is called Fluidic or Mercurial in alchemy." } },
    { q: { it: "Quante «morti» descrivono gli scritti esoterici?", en: "How many 'deaths' do the esoteric writings describe?" },
      options: { it: ["Tre: una per ogni corpo da abbandonare", "Una soltanto", "Sette", "Nessuna"], en: ["Three: one for each body to be left behind", "Only one", "Seven", "None"] }, correct: 0,
      note: { it: "Una morte per ciascun corpo: fisico, emotivo e mentale.", en: "One death for each body: physical, emotional and mental." } },
    { q: { it: "Quando l'uomo sogna, in quale corpo si trova?", en: "When a person dreams, in which body are they?" },
      options: { it: ["Nel corpo astrale", "Nel corpo causale", "Nel corpo atmico", "In nessun corpo"], en: ["In the astral body", "In the causal body", "In the atmic body", "In no body"] }, correct: 0,
      note: { it: "Nel sogno siamo nel corpo astrale, proprio come lo saremo dopo la morte: la lucidità dei sogni rivela quella che avremo da disincarnati.", en: "In dreams we are in the astral body, just as we will be after death: the lucidity of dreams reveals the lucidity we will have once disincarnate." } },
    { q: { it: "Secondo il testo, la vera domanda non è «C'è coscienza dopo la morte?» ma…", en: "According to the text, the real question is not 'Is there consciousness after death?' but…" },
      options: { it: ["«C'è coscienza dopo la nascita?»", "«Esiste l'aldilà?»", "«Quanti sono gli angeli?»", "«Dove si trova il Paradiso?»"], en: ["'Is there consciousness after birth?'", "'Does the afterlife exist?'", "'How many angels are there?'", "'Where is Paradise?'"] }, correct: 0,
      note: { it: "Si è coscienti dopo la morte solo nella misura in cui lo si è già durante la vita. La morte non è una cura per l'ignoranza.", en: "One is conscious after death only insofar as one already is during life. Death is no cure for ignorance." } },
    { q: { it: "L'esperienza dell'«inferno» nel piano astrale serve a…", en: "The experience of 'hell' on the astral plane serves to…" },
      options: { it: ["Bruciare le emozioni inferiori e gli attaccamenti", "Punire i peccatori per l'eternità", "Cancellare la memoria", "Premiare i giusti"], en: ["Burn the lower emotions and attachments", "Punish sinners for eternity", "Erase memory", "Reward the righteous"] }, correct: 0,
      note: { it: "Non c'è punizione perché non c'è stato errore: è un processo energetico di disgregazione dei condizionamenti emotivi.", en: "There is no punishment because there was no error: it is an energetic process that disintegrates emotional conditioning." } },
    { q: { it: "Perché, secondo il testo, il suicidio è un atto privo di senso?", en: "Why, according to the text, is suicide a senseless act?" },
      options: { it: ["Il disagio si ritrova identico, senza più i mezzi fisici per risolverlo", "Perché è proibito dalla legge", "Perché cancella l'anima", "Perché impedisce di sognare"], en: ["The same distress returns, now without physical means to resolve it", "Because it is forbidden by law", "Because it erases the soul", "Because it prevents dreaming"] }, correct: 0,
      note: { it: "Il suicida ritrova nell'aldilà lo stesso problema esistenziale e dovrà riaffrontarlo in una nuova incarnazione.", en: "The suicide meets the same existential problem in the afterlife and must face it again in a new incarnation." } },
    { q: { it: "Cosa accade nel primo periodo dopo l'abbandono del corpo fisico?", en: "What happens in the first period after leaving the physical body?" },
      options: { it: ["Si rivede tutta la propria vita «all'indietro»", "Si dimentica tutto", "Si rinasce subito", "Si incontra un giudice"], en: ["One reviews one's whole life 'backwards'", "One forgets everything", "One is reborn at once", "One meets a judge"] }, correct: 0,
      note: { it: "Per la coscienza astrale, quadridimensionale, spazio e tempo scorrono diversamente: rivedendo la vita al contrario si sospende il giudizio causa/effetto.", en: "For four-dimensional astral consciousness, space and time flow differently: reviewing life backwards suspends cause/effect judgement." } },
    { q: { it: "I tre «corpi superiori» (causale, buddhico, atmico) sono riassunti nell'espressione…", en: "The three 'higher bodies' (causal, buddhic, atmic) are summed up in the phrase…" },
      options: { it: ["«Corpo di gloria» o «corpo dell'anima»", "«Corpo mercuriale»", "«Doppio eterico»", "«Macchina biologica»"], en: ["'Body of glory' or 'body of the soul'", "'Mercurial body'", "'Etheric double'", "'Biological machine'"] }, correct: 0,
      note: { it: "Il percorso alchemico porta alla costruzione dei tre corpi superiori al contempo.", en: "The alchemical path leads to building the three higher bodies at once." } },
    { q: { it: "L'identificazione con l'anima, nel linguaggio alchemico, è detta…", en: "Identification with the soul, in alchemical language, is called…" },
      options: { it: ["Albedo", "Rubedo", "Nigredo eterna", "Solve"], en: ["Albedo", "Rubedo", "Eternal Nigredo", "Solve"] }, correct: 0,
      note: { it: "L'Albedo è la realizzazione dell'identità animica; la Rubedo è l'identità divina.", en: "Albedo is the realisation of the soul-identity; Rubedo is the divine identity." } },
    { q: { it: "Gli spiriti della terra, dell'acqua, dell'aria e dell'etere sono detti rispettivamente…", en: "The spirits of earth, water, air and ether are called, respectively…" },
      options: { it: ["Gnomi, ondine, silfidi, salamandre", "Deva, ombre, gusci, vampiri", "Silfidi, gnomi, salamandre, ondine", "Folletti, fate, elfi, troll"], en: ["Gnomes, undines, sylphs, salamanders", "Devas, shades, shells, vampires", "Sylphs, gnomes, salamanders, undines", "Goblins, fairies, elves, trolls"] }, correct: 0,
      note: { it: "Gnomi = terra, ondine = acqua, silfidi = aria, salamandre = etere.", en: "Gnomes = earth, undines = water, sylphs = air, salamanders = ether." } },
    { q: { it: "L'essenza elementale del piano astrale…", en: "The elemental essence of the astral plane…" },
      options: { it: ["Reagisce istantaneamente a ogni pensiero umano", "È totalmente inerte", "Vive solo nel corpo fisico", "È visibile a tutti"], en: ["Reacts instantly to every human thought", "Is wholly inert", "Lives only in the physical body", "Is visible to everyone"] }, correct: 0,
      note: { it: "Ogni pensiero ed emozione la plasma in un essere temporaneo: il regno elementale è ciò che lo hanno reso i pensieri collettivi dell'umanità.", en: "Every thought and emotion shapes it into a temporary being: the elemental kingdom is what humanity's collective thoughts have made it." } },
    { q: { it: "Una forma-pensiero di gelosia o depressione, se continuamente alimentata, può…", en: "A thought-form of jealousy or depression, if continually fed, can…" },
      options: { it: ["«Attaccarsi» a un uomo per tutta la vita", "Dissolversi subito", "Trasformarsi in un Deva", "Diventare un corpo fisico"], en: ["'Attach' itself to a person for life", "Dissolve at once", "Turn into a Deva", "Become a physical body"] }, correct: 0,
      note: { it: "L'elementale cerca di sopravvivere e spinge l'individuo a ripetere il pensiero che lo alimenta.", en: "The elemental seeks to survive and pushes the person to repeat the thought that feeds it." } },
    { q: { it: "La «risurrezione nella carne» avviene quando l'uomo trasmuta il suo corpo…", en: "The 'resurrection in the flesh' occurs when one transmutes the body…" },
      options: { it: ["Fisico, che diviene corpo Atmico", "Mentale, che diviene Causale", "Emotivo, che diviene Buddhico", "Eterico soltanto"], en: ["Physical, which becomes the Atmic body", "Mental, which becomes Causal", "Emotional, which becomes Buddhic", "Etheric only"] }, correct: 0,
      note: { it: "Trasmutando il corpo fisico esso sale di livello e diviene il corpo Atmico: lo stesso corpo diventa immortale.", en: "By transmuting the physical body it rises and becomes the Atmic body: the very body becomes immortal." } },
    { q: { it: "Impegnarsi solo per la sopravvivenza o il viaggio astrale è considerato…", en: "Striving merely for astral survival or astral travel is regarded as…" },
      options: { it: ["Un comportamento infantile, da Bassa Magia", "La vetta dell'Opera", "L'Albedo", "L'unico vero scopo"], en: ["A childish attitude, of Low Magic", "The summit of the Work", "The Albedo", "The only true aim"] }, correct: 0,
      note: { it: "Il fine resta la realizzazione dell'identità animica e divina; la sopravvivenza astrale è solo un «effetto collaterale».", en: "The aim remains realising the soul- and divine-identity; astral survival is only a 'side effect'." } }
  ];

  /* ---------- 5. MEMORIA ASTRALE (coppie corrispondenza) ---------- */
  const MEMORY = [
    { a: { it: "Gnomi", en: "Gnomes" }, b: { it: "Terra", en: "Earth" } },
    { a: { it: "Ondine", en: "Undines" }, b: { it: "Acqua", en: "Water" } },
    { a: { it: "Silfidi", en: "Sylphs" }, b: { it: "Aria", en: "Air" } },
    { a: { it: "Salamandre", en: "Salamanders" }, b: { it: "Etere", en: "Ether" } },
    { a: { it: "Corpo astrale", en: "Astral body" }, b: { it: "Mercuriale", en: "Mercurial" } },
    { a: { it: "Corpo dell'anima", en: "Body of the soul" }, b: { it: "Corpo di gloria", en: "Body of glory" } }
  ];

  /* ---------- I SETTE PIANI (per il diagramma di apertura) ---------- */
  const PLANES = [
    { it: "Adi (Logos)", en: "Adi (Logos)" },
    { it: "Anupadaka (Monade)", en: "Anupadaka (Monad)" },
    { it: "Atmico", en: "Atmic" },
    { it: "Buddhico", en: "Buddhic" },
    { it: "Mentale / Causale", en: "Mental / Causal" },
    { it: "Astrale (Emotivo)", en: "Astral (Emotional)" },
    { it: "Fisico ed Eterico", en: "Physical & Etheric" }
  ];

  window.MS_DATA = { COLORS, ENTITIES, SUBPLANES, QUIZ, MEMORY, PLANES };
})();
